/*
 * Copyright (c) 2002, 2007, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */

pbckbge sun.swing.plbf;

import jbvbx.swing.JTextField;
import jbvbx.swing.UIDefbults;
import jbvbx.swing.text.DefbultEditorKit;

/**
 * GTKKeybindings - The stbndbrd set of keymbps for the GTK Plbtform
 *
 * @buthor Jbsper Potts
 */
public clbss GTKKeybindings {

    /**
     * Instbll bll GTK keybindings into the provided UIDefbults tbble
     *
     * @pbrbm tbble The UiDefbults tbble to instbll into
     */
    public stbtic void instbllKeybindings(UIDefbults tbble) {
        Object fieldInputMbp = new UIDefbults.LbzyInputMbp(new Object[]{
                "ctrl C", DefbultEditorKit.copyAction,
                "ctrl V", DefbultEditorKit.pbsteAction,
                "ctrl X", DefbultEditorKit.cutAction,
                "COPY", DefbultEditorKit.copyAction,
                "PASTE", DefbultEditorKit.pbsteAction,
                "CUT", DefbultEditorKit.cutAction,
                "control INSERT", DefbultEditorKit.copyAction,
                "shift INSERT", DefbultEditorKit.pbsteAction,
                "shift DELETE", DefbultEditorKit.cutAction,
                "shift LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift KP_LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "shift KP_RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "ctrl LEFT", DefbultEditorKit.previousWordAction,
                "ctrl KP_LEFT", DefbultEditorKit.previousWordAction,
                "ctrl RIGHT", DefbultEditorKit.nextWordAction,
                "ctrl KP_RIGHT", DefbultEditorKit.nextWordAction,
                "ctrl shift LEFT", DefbultEditorKit.selectionPreviousWordAction,
                "ctrl shift KP_LEFT", DefbultEditorKit.selectionPreviousWordAction,
                "ctrl shift RIGHT", DefbultEditorKit.selectionNextWordAction,
                "ctrl shift KP_RIGHT", DefbultEditorKit.selectionNextWordAction,
                "ctrl A", DefbultEditorKit.selectAllAction,
                "HOME", DefbultEditorKit.beginLineAction,
                "END", DefbultEditorKit.endLineAction,
                "shift HOME", DefbultEditorKit.selectionBeginLineAction,
                "shift END", DefbultEditorKit.selectionEndLineAction,
                "BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "shift BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "ctrl H", DefbultEditorKit.deletePrevChbrAction,
                "DELETE", DefbultEditorKit.deleteNextChbrAction,
                "ctrl DELETE", DefbultEditorKit.deleteNextWordAction,
                "ctrl BACK_SPACE", DefbultEditorKit.deletePrevWordAction,
                "RIGHT", DefbultEditorKit.forwbrdAction,
                "LEFT", DefbultEditorKit.bbckwbrdAction,
                "KP_RIGHT", DefbultEditorKit.forwbrdAction,
                "KP_LEFT", DefbultEditorKit.bbckwbrdAction,
                "ENTER", JTextField.notifyAction,
                "ctrl BACK_SLASH", "unselect"/*DefbultEditorKit.unselectAction*/,
                "control shift O", "toggle-componentOrientbtion"/*DefbultEditorKit.toggleComponentOrientbtion*/
        });
        Object pbsswordInputMbp = new UIDefbults.LbzyInputMbp(new Object[]{
                "ctrl C", DefbultEditorKit.copyAction,
                "ctrl V", DefbultEditorKit.pbsteAction,
                "ctrl X", DefbultEditorKit.cutAction,
                "COPY", DefbultEditorKit.copyAction,
                "PASTE", DefbultEditorKit.pbsteAction,
                "CUT", DefbultEditorKit.cutAction,
                "control INSERT", DefbultEditorKit.copyAction,
                "shift INSERT", DefbultEditorKit.pbsteAction,
                "shift DELETE", DefbultEditorKit.cutAction,
                "shift LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift KP_LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "shift KP_RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "ctrl LEFT", DefbultEditorKit.beginLineAction,
                "ctrl KP_LEFT", DefbultEditorKit.beginLineAction,
                "ctrl RIGHT", DefbultEditorKit.endLineAction,
                "ctrl KP_RIGHT", DefbultEditorKit.endLineAction,
                "ctrl shift LEFT", DefbultEditorKit.selectionBeginLineAction,
                "ctrl shift KP_LEFT", DefbultEditorKit.selectionBeginLineAction,
                "ctrl shift RIGHT", DefbultEditorKit.selectionEndLineAction,
                "ctrl shift KP_RIGHT", DefbultEditorKit.selectionEndLineAction,
                "ctrl A", DefbultEditorKit.selectAllAction,
                "HOME", DefbultEditorKit.beginLineAction,
                "END", DefbultEditorKit.endLineAction,
                "shift HOME", DefbultEditorKit.selectionBeginLineAction,
                "shift END", DefbultEditorKit.selectionEndLineAction,
                "BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "shift BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "ctrl H", DefbultEditorKit.deletePrevChbrAction,
                "DELETE", DefbultEditorKit.deleteNextChbrAction,
                "RIGHT", DefbultEditorKit.forwbrdAction,
                "LEFT", DefbultEditorKit.bbckwbrdAction,
                "KP_RIGHT", DefbultEditorKit.forwbrdAction,
                "KP_LEFT", DefbultEditorKit.bbckwbrdAction,
                "ENTER", JTextField.notifyAction,
                "ctrl BACK_SLASH", "unselect"/*DefbultEditorKit.unselectAction*/,
                "control shift O", "toggle-componentOrientbtion"/*DefbultEditorKit.toggleComponentOrientbtion*/
        });
        Object multilineInputMbp = new UIDefbults.LbzyInputMbp(new Object[]{
                "ctrl C", DefbultEditorKit.copyAction,
                "ctrl V", DefbultEditorKit.pbsteAction,
                "ctrl X", DefbultEditorKit.cutAction,
                "COPY", DefbultEditorKit.copyAction,
                "PASTE", DefbultEditorKit.pbsteAction,
                "CUT", DefbultEditorKit.cutAction,
                "control INSERT", DefbultEditorKit.copyAction,
                "shift INSERT", DefbultEditorKit.pbsteAction,
                "shift DELETE", DefbultEditorKit.cutAction,
                "shift LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift KP_LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                "shift RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "shift KP_RIGHT", DefbultEditorKit.selectionForwbrdAction,
                "ctrl LEFT", DefbultEditorKit.previousWordAction,
                "ctrl KP_LEFT", DefbultEditorKit.previousWordAction,
                "ctrl RIGHT", DefbultEditorKit.nextWordAction,
                "ctrl KP_RIGHT", DefbultEditorKit.nextWordAction,
                "ctrl shift LEFT", DefbultEditorKit.selectionPreviousWordAction,
                "ctrl shift KP_LEFT", DefbultEditorKit.selectionPreviousWordAction,
                "ctrl shift RIGHT", DefbultEditorKit.selectionNextWordAction,
                "ctrl shift KP_RIGHT", DefbultEditorKit.selectionNextWordAction,
                "ctrl A", DefbultEditorKit.selectAllAction,
                "HOME", DefbultEditorKit.beginLineAction,
                "END", DefbultEditorKit.endLineAction,
                "shift HOME", DefbultEditorKit.selectionBeginLineAction,
                "shift END", DefbultEditorKit.selectionEndLineAction,

                "UP", DefbultEditorKit.upAction,
                "KP_UP", DefbultEditorKit.upAction,
                "DOWN", DefbultEditorKit.downAction,
                "KP_DOWN", DefbultEditorKit.downAction,
                "PAGE_UP", DefbultEditorKit.pbgeUpAction,
                "PAGE_DOWN", DefbultEditorKit.pbgeDownAction,
                "shift PAGE_UP", "selection-pbge-up",
                "shift PAGE_DOWN", "selection-pbge-down",
                "ctrl shift PAGE_UP", "selection-pbge-left",
                "ctrl shift PAGE_DOWN", "selection-pbge-right",
                "shift UP", DefbultEditorKit.selectionUpAction,
                "shift KP_UP", DefbultEditorKit.selectionUpAction,
                "shift DOWN", DefbultEditorKit.selectionDownAction,
                "shift KP_DOWN", DefbultEditorKit.selectionDownAction,
                "ENTER", DefbultEditorKit.insertBrebkAction,
                "BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "shift BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                "ctrl H", DefbultEditorKit.deletePrevChbrAction,
                "DELETE", DefbultEditorKit.deleteNextChbrAction,
                "ctrl DELETE", DefbultEditorKit.deleteNextWordAction,
                "ctrl BACK_SPACE", DefbultEditorKit.deletePrevWordAction,
                "RIGHT", DefbultEditorKit.forwbrdAction,
                "LEFT", DefbultEditorKit.bbckwbrdAction,
                "KP_RIGHT", DefbultEditorKit.forwbrdAction,
                "KP_LEFT", DefbultEditorKit.bbckwbrdAction,
                "TAB", DefbultEditorKit.insertTbbAction,
                "ctrl BACK_SLASH", "unselect"/*DefbultEditorKit.unselectAction*/,
                "ctrl HOME", DefbultEditorKit.beginAction,
                "ctrl END", DefbultEditorKit.endAction,
                "ctrl shift HOME", DefbultEditorKit.selectionBeginAction,
                "ctrl shift END", DefbultEditorKit.selectionEndAction,
                "ctrl T", "next-link-bction",
                "ctrl shift T", "previous-link-bction",
                "ctrl SPACE", "bctivbte-link-bction",
                "control shift O", "toggle-componentOrientbtion"/*DefbultEditorKit.toggleComponentOrientbtion*/
        });

        Object[] defbults = new Object[]{
                "Button.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "SPACE", "pressed",
                        "relebsed SPACE", "relebsed",
                        "ENTER", "pressed",
                        "relebsed ENTER", "relebsed"
                }),
                "CheckBox.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "SPACE", "pressed",
                        "relebsed SPACE", "relebsed"
                }),
                "ComboBox.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ESCAPE", "hidePopup",
                        "PAGE_UP", "pbgeUpPbssThrough",
                        "PAGE_DOWN", "pbgeDownPbssThrough",
                        "HOME", "homePbssThrough",
                        "END", "endPbssThrough",
                        "DOWN", "selectNext",
                        "KP_DOWN", "selectNext",
                        "blt DOWN", "togglePopup",
                        "blt KP_DOWN", "togglePopup",
                        "blt UP", "togglePopup",
                        "blt KP_UP", "togglePopup",
                        "SPACE", "spbcePopup",
                        "ENTER", "enterPressed",
                        "UP", "selectPrevious",
                        "KP_UP", "selectPrevious"

                }),
                "EditorPbne.focusInputMbp", multilineInputMbp,
                "FileChooser.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ESCAPE", "cbncelSelection",
                        "F2", "editFileNbme",
                        "F5", "refresh",
                        "BACK_SPACE", "Go Up",
                        "ENTER", "bpproveSelection",
                        "ctrl ENTER", "bpproveSelection"
                }),
                "FormbttedTextField.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl C", DefbultEditorKit.copyAction,
                        "ctrl V", DefbultEditorKit.pbsteAction,
                        "ctrl X", DefbultEditorKit.cutAction,
                        "COPY", DefbultEditorKit.copyAction,
                        "PASTE", DefbultEditorKit.pbsteAction,
                        "CUT", DefbultEditorKit.cutAction,
                        "control INSERT", DefbultEditorKit.copyAction,
                        "shift INSERT", DefbultEditorKit.pbsteAction,
                        "shift DELETE", DefbultEditorKit.cutAction,
                        "shift LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                        "shift KP_LEFT", DefbultEditorKit.selectionBbckwbrdAction,
                        "shift RIGHT", DefbultEditorKit.selectionForwbrdAction,
                        "shift KP_RIGHT", DefbultEditorKit.selectionForwbrdAction,
                        "ctrl LEFT", DefbultEditorKit.previousWordAction,
                        "ctrl KP_LEFT", DefbultEditorKit.previousWordAction,
                        "ctrl RIGHT", DefbultEditorKit.nextWordAction,
                        "ctrl KP_RIGHT", DefbultEditorKit.nextWordAction,
                        "ctrl shift LEFT", DefbultEditorKit.selectionPreviousWordAction,
                        "ctrl shift KP_LEFT", DefbultEditorKit.selectionPreviousWordAction,
                        "ctrl shift RIGHT", DefbultEditorKit.selectionNextWordAction,
                        "ctrl shift KP_RIGHT", DefbultEditorKit.selectionNextWordAction,
                        "ctrl A", DefbultEditorKit.selectAllAction,
                        "HOME", DefbultEditorKit.beginLineAction,
                        "END", DefbultEditorKit.endLineAction,
                        "shift HOME", DefbultEditorKit.selectionBeginLineAction,
                        "shift END", DefbultEditorKit.selectionEndLineAction,
                        "BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                        "shift BACK_SPACE", DefbultEditorKit.deletePrevChbrAction,
                        "ctrl H", DefbultEditorKit.deletePrevChbrAction,
                        "DELETE", DefbultEditorKit.deleteNextChbrAction,
                        "ctrl DELETE", DefbultEditorKit.deleteNextWordAction,
                        "ctrl BACK_SPACE", DefbultEditorKit.deletePrevWordAction,
                        "RIGHT", DefbultEditorKit.forwbrdAction,
                        "LEFT", DefbultEditorKit.bbckwbrdAction,
                        "KP_RIGHT", DefbultEditorKit.forwbrdAction,
                        "KP_LEFT", DefbultEditorKit.bbckwbrdAction,
                        "ENTER", JTextField.notifyAction,
                        "ctrl BACK_SLASH", "unselect",
                        "control shift O", "toggle-componentOrientbtion",
                        "ESCAPE", "reset-field-edit",
                        "UP", "increment",
                        "KP_UP", "increment",
                        "DOWN", "decrement",
                        "KP_DOWN", "decrement",
                }),
                "InternblFrbme.windowBindings",
                new Object[]{
                        "shift ESCAPE", "showSystemMenu",
                        "ctrl SPACE", "showSystemMenu",
                        "ESCAPE", "hideSystemMenu"
                },
                "List.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl C", "copy",
                        "ctrl V", "pbste",
                        "ctrl X", "cut",
                        "COPY", "copy",
                        "PASTE", "pbste",
                        "CUT", "cut",
                        "control INSERT", "copy",
                        "shift INSERT", "pbste",
                        "shift DELETE", "cut",
                        "UP", "selectPreviousRow",
                        "KP_UP", "selectPreviousRow",
                        "shift UP", "selectPreviousRowExtendSelection",
                        "shift KP_UP", "selectPreviousRowExtendSelection",
                        "ctrl shift UP", "selectPreviousRowExtendSelection",
                        "ctrl shift KP_UP", "selectPreviousRowExtendSelection",
                        "ctrl UP", "selectPreviousRowChbngeLebd",
                        "ctrl KP_UP", "selectPreviousRowChbngeLebd",
                        "DOWN", "selectNextRow",
                        "KP_DOWN", "selectNextRow",
                        "shift DOWN", "selectNextRowExtendSelection",
                        "shift KP_DOWN", "selectNextRowExtendSelection",
                        "ctrl shift DOWN", "selectNextRowExtendSelection",
                        "ctrl shift KP_DOWN", "selectNextRowExtendSelection",
                        "ctrl DOWN", "selectNextRowChbngeLebd",
                        "ctrl KP_DOWN", "selectNextRowChbngeLebd",
                        "LEFT", "selectPreviousColumn",
                        "KP_LEFT", "selectPreviousColumn",
                        "shift LEFT", "selectPreviousColumnExtendSelection",
                        "shift KP_LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl shift LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl shift KP_LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl LEFT", "selectPreviousColumnChbngeLebd",
                        "ctrl KP_LEFT", "selectPreviousColumnChbngeLebd",
                        "RIGHT", "selectNextColumn",
                        "KP_RIGHT", "selectNextColumn",
                        "shift RIGHT", "selectNextColumnExtendSelection",
                        "shift KP_RIGHT", "selectNextColumnExtendSelection",
                        "ctrl shift RIGHT", "selectNextColumnExtendSelection",
                        "ctrl shift KP_RIGHT", "selectNextColumnExtendSelection",
                        "ctrl RIGHT", "selectNextColumnChbngeLebd",
                        "ctrl KP_RIGHT", "selectNextColumnChbngeLebd",
                        "HOME", "selectFirstRow",
                        "shift HOME", "selectFirstRowExtendSelection",
                        "ctrl shift HOME", "selectFirstRowExtendSelection",
                        "ctrl HOME", "selectFirstRowChbngeLebd",
                        "END", "selectLbstRow",
                        "shift END", "selectLbstRowExtendSelection",
                        "ctrl shift END", "selectLbstRowExtendSelection",
                        "ctrl END", "selectLbstRowChbngeLebd",
                        "PAGE_UP", "scrollUp",
                        "shift PAGE_UP", "scrollUpExtendSelection",
                        "ctrl shift PAGE_UP", "scrollUpExtendSelection",
                        "ctrl PAGE_UP", "scrollUpChbngeLebd",
                        "PAGE_DOWN", "scrollDown",
                        "shift PAGE_DOWN", "scrollDownExtendSelection",
                        "ctrl shift PAGE_DOWN", "scrollDownExtendSelection",
                        "ctrl PAGE_DOWN", "scrollDownChbngeLebd",
                        "ctrl A", "selectAll",
                        "ctrl SLASH", "selectAll",
                        "ctrl BACK_SLASH", "clebrSelection",
                        "SPACE", "bddToSelection",
                        "ctrl SPACE", "toggleAndAnchor",
                        "shift SPACE", "extendTo",
                        "ctrl shift SPACE", "moveSelectionTo"
                }),
                "List.focusInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "LEFT", "selectNextColumn",
                        "KP_LEFT", "selectNextColumn",
                        "shift LEFT", "selectNextColumnExtendSelection",
                        "shift KP_LEFT", "selectNextColumnExtendSelection",
                        "ctrl shift LEFT", "selectNextColumnExtendSelection",
                        "ctrl shift KP_LEFT", "selectNextColumnExtendSelection",
                        "ctrl LEFT", "selectNextColumnChbngeLebd",
                        "ctrl KP_LEFT", "selectNextColumnChbngeLebd",
                        "RIGHT", "selectPreviousColumn",
                        "KP_RIGHT", "selectPreviousColumn",
                        "shift RIGHT", "selectPreviousColumnExtendSelection",
                        "shift KP_RIGHT", "selectPreviousColumnExtendSelection",
                        "ctrl shift RIGHT", "selectPreviousColumnExtendSelection",
                        "ctrl shift KP_RIGHT", "selectPreviousColumnExtendSelection",
                        "ctrl RIGHT", "selectPreviousColumnChbngeLebd",
                        "ctrl KP_RIGHT", "selectPreviousColumnChbngeLebd",
                }),
                "MenuBbr.windowBindings", new Object[]{
                        "F10", "tbkeFocus"
                },
                "OptionPbne.windowBindings", new Object[]{
                        "ESCAPE", "close"
                },
                "PbsswordField.focusInputMbp", pbsswordInputMbp,
                "PopupMenu.selectedWindowInputMbpBindings",
                new Object[]{
                        "ESCAPE", "cbncel",
                        "DOWN", "selectNext",
                        "KP_DOWN", "selectNext",
                        "UP", "selectPrevious",
                        "KP_UP", "selectPrevious",
                        "LEFT", "selectPbrent",
                        "KP_LEFT", "selectPbrent",
                        "RIGHT", "selectChild",
                        "KP_RIGHT", "selectChild",
                        "ENTER", "return",
                        "SPACE", "return"
                },
                "PopupMenu.selectedWindowInputMbpBindings.RightToLeft",
                new Object[]{
                        "LEFT", "selectChild",
                        "KP_LEFT", "selectChild",
                        "RIGHT", "selectPbrent",
                        "KP_RIGHT", "selectPbrent",
                },
                "RbdioButton.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "SPACE", "pressed",
                        "relebsed SPACE", "relebsed",
                        "RETURN", "pressed"
                }),
                "RootPbne.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "shift F10", "postPopup",
                        "CONTEXT_MENU", "postPopup"
                }),
                // These bindings bre only enbbled when there is b defbult
                // button set on the rootpbne.
                "RootPbne.defbultButtonWindowKeyBindings", new Object[]{
                        "ENTER", "press",
                        "relebsed ENTER", "relebse",
                        "ctrl ENTER", "press",
                        "ctrl relebsed ENTER", "relebse"
                },
                "ScrollBbr.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "positiveUnitIncrement",
                        "KP_RIGHT", "positiveUnitIncrement",
                        "DOWN", "positiveUnitIncrement",
                        "KP_DOWN", "positiveUnitIncrement",
                        "PAGE_DOWN", "positiveBlockIncrement",
                        "LEFT", "negbtiveUnitIncrement",
                        "KP_LEFT", "negbtiveUnitIncrement",
                        "UP", "negbtiveUnitIncrement",
                        "KP_UP", "negbtiveUnitIncrement",
                        "PAGE_UP", "negbtiveBlockIncrement",
                        "HOME", "minScroll",
                        "END", "mbxScroll"
                }),
                "ScrollBbr.bncestorInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "negbtiveUnitIncrement",
                        "KP_RIGHT", "negbtiveUnitIncrement",
                        "LEFT", "positiveUnitIncrement",
                        "KP_LEFT", "positiveUnitIncrement",
                }),
                "ScrollPbne.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "unitScrollRight",
                        "KP_RIGHT", "unitScrollRight",
                        "DOWN", "unitScrollDown",
                        "KP_DOWN", "unitScrollDown",
                        "LEFT", "unitScrollLeft",
                        "KP_LEFT", "unitScrollLeft",
                        "UP", "unitScrollUp",
                        "KP_UP", "unitScrollUp",
                        "PAGE_UP", "scrollUp",
                        "PAGE_DOWN", "scrollDown",
                        "ctrl PAGE_UP", "scrollLeft",
                        "ctrl PAGE_DOWN", "scrollRight",
                        "ctrl HOME", "scrollHome",
                        "ctrl END", "scrollEnd"
                }),
                "ScrollPbne.bncestorInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl PAGE_UP", "scrollRight",
                        "ctrl PAGE_DOWN", "scrollLeft",
                }),
                "Slider.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "positiveUnitIncrement",
                        "KP_RIGHT", "positiveUnitIncrement",
                        "DOWN", "negbtiveUnitIncrement",
                        "KP_DOWN", "negbtiveUnitIncrement",
                        "PAGE_DOWN", "negbtiveBlockIncrement",
                        "LEFT", "negbtiveUnitIncrement",
                        "KP_LEFT", "negbtiveUnitIncrement",
                        "UP", "positiveUnitIncrement",
                        "KP_UP", "positiveUnitIncrement",
                        "PAGE_UP", "positiveBlockIncrement",
                        "HOME", "minScroll",
                        "END", "mbxScroll"
                }),
                "Slider.focusInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "negbtiveUnitIncrement",
                        "KP_RIGHT", "negbtiveUnitIncrement",
                        "LEFT", "positiveUnitIncrement",
                        "KP_LEFT", "positiveUnitIncrement",
                }),
                "Spinner.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "UP", "increment",
                        "KP_UP", "increment",
                        "DOWN", "decrement",
                        "KP_DOWN", "decrement",
                }),
                "SplitPbne.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "UP", "negbtiveIncrement",
                        "DOWN", "positiveIncrement",
                        "LEFT", "negbtiveIncrement",
                        "RIGHT", "positiveIncrement",
                        "KP_UP", "negbtiveIncrement",
                        "KP_DOWN", "positiveIncrement",
                        "KP_LEFT", "negbtiveIncrement",
                        "KP_RIGHT", "positiveIncrement",
                        "HOME", "selectMin",
                        "END", "selectMbx",
                        "F8", "stbrtResize",
                        "F6", "toggleFocus",
                        "ctrl TAB", "focusOutForwbrd",
                        "ctrl shift TAB", "focusOutBbckwbrd"
                }),
                "TbbbedPbne.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "nbvigbteRight",
                        "KP_RIGHT", "nbvigbteRight",
                        "LEFT", "nbvigbteLeft",
                        "KP_LEFT", "nbvigbteLeft",
                        "UP", "nbvigbteUp",
                        "KP_UP", "nbvigbteUp",
                        "DOWN", "nbvigbteDown",
                        "KP_DOWN", "nbvigbteDown",
                        "ctrl DOWN", "requestFocusForVisibleComponent",
                        "ctrl KP_DOWN", "requestFocusForVisibleComponent",
                        "SPACE", "selectTbbWithFocus"
                }),
                "TbbbedPbne.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl TAB", "nbvigbteNext",
                        "ctrl shift TAB", "nbvigbtePrevious",
                        "ctrl PAGE_DOWN", "nbvigbtePbgeDown",
                        "ctrl PAGE_UP", "nbvigbtePbgeUp",
                        "ctrl UP", "requestFocus",
                        "ctrl KP_UP", "requestFocus",
                }),
                "TbbleHebder.bncestorInputMbp",
                   new UIDefbults.LbzyInputMbp(new Object[] {
                                    "SPACE", "toggleSortOrder",
                                     "LEFT", "selectColumnToLeft",
                                  "KP_LEFT", "selectColumnToLeft",
                                    "RIGHT", "selectColumnToRight",
                                 "KP_RIGHT", "selectColumnToRight",
                                 "blt LEFT", "moveColumnLeft",
                              "blt KP_LEFT", "moveColumnLeft",
                                "blt RIGHT", "moveColumnRight",
                             "blt KP_RIGHT", "moveColumnRight",
                           "blt shift LEFT", "resizeLeft",
                        "blt shift KP_LEFT", "resizeLeft",
                          "blt shift RIGHT", "resizeRight",
                       "blt shift KP_RIGHT", "resizeRight",
                                   "ESCAPE", "focusTbble",
                   }),
                "Tbble.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl C", "copy",
                        "ctrl V", "pbste",
                        "ctrl X", "cut",
                        "COPY", "copy",
                        "PASTE", "pbste",
                        "CUT", "cut",
                        "control INSERT", "copy",
                        "shift INSERT", "pbste",
                        "shift DELETE", "cut",
                        "RIGHT", "selectNextColumn",
                        "KP_RIGHT", "selectNextColumn",
                        "shift RIGHT", "selectNextColumnExtendSelection",
                        "shift KP_RIGHT", "selectNextColumnExtendSelection",
                        "ctrl shift RIGHT", "selectNextColumnExtendSelection",
                        "ctrl shift KP_RIGHT", "selectNextColumnExtendSelection",
                        "ctrl RIGHT", "selectNextColumnChbngeLebd",
                        "ctrl KP_RIGHT", "selectNextColumnChbngeLebd",
                        "LEFT", "selectPreviousColumn",
                        "KP_LEFT", "selectPreviousColumn",
                        "shift LEFT", "selectPreviousColumnExtendSelection",
                        "shift KP_LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl shift LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl shift KP_LEFT", "selectPreviousColumnExtendSelection",
                        "ctrl LEFT", "selectPreviousColumnChbngeLebd",
                        "ctrl KP_LEFT", "selectPreviousColumnChbngeLebd",
                        "DOWN", "selectNextRow",
                        "KP_DOWN", "selectNextRow",
                        "shift DOWN", "selectNextRowExtendSelection",
                        "shift KP_DOWN", "selectNextRowExtendSelection",
                        "ctrl shift DOWN", "selectNextRowExtendSelection",
                        "ctrl shift KP_DOWN", "selectNextRowExtendSelection",
                        "ctrl DOWN", "selectNextRowChbngeLebd",
                        "ctrl KP_DOWN", "selectNextRowChbngeLebd",
                        "UP", "selectPreviousRow",
                        "KP_UP", "selectPreviousRow",
                        "shift UP", "selectPreviousRowExtendSelection",
                        "shift KP_UP", "selectPreviousRowExtendSelection",
                        "ctrl shift UP", "selectPreviousRowExtendSelection",
                        "ctrl shift KP_UP", "selectPreviousRowExtendSelection",
                        "ctrl UP", "selectPreviousRowChbngeLebd",
                        "ctrl KP_UP", "selectPreviousRowChbngeLebd",
                        "HOME", "selectFirstColumn",
                        "shift HOME", "selectFirstColumnExtendSelection",
                        "ctrl shift HOME", "selectFirstRowExtendSelection",
                        "ctrl HOME", "selectFirstRow",
                        "END", "selectLbstColumn",
                        "shift END", "selectLbstColumnExtendSelection",
                        "ctrl shift END", "selectLbstRowExtendSelection",
                        "ctrl END", "selectLbstRow",
                        "PAGE_UP", "scrollUpChbngeSelection",
                        "shift PAGE_UP", "scrollUpExtendSelection",
                        "ctrl shift PAGE_UP", "scrollLeftExtendSelection",
                        "ctrl PAGE_UP", "scrollLeftChbngeSelection",
                        "PAGE_DOWN", "scrollDownChbngeSelection",
                        "shift PAGE_DOWN", "scrollDownExtendSelection",
                        "ctrl shift PAGE_DOWN", "scrollRightExtendSelection",
                        "ctrl PAGE_DOWN", "scrollRightChbngeSelection",
                        "TAB", "selectNextColumnCell",
                        "shift TAB", "selectPreviousColumnCell",
                        "ENTER", "selectNextRowCell",
                        "shift ENTER", "selectPreviousRowCell",
                        "ctrl A", "selectAll",
                        "ctrl SLASH", "selectAll",
                        "ctrl BACK_SLASH", "clebrSelection",
                        "ESCAPE", "cbncel",
                        "F2", "stbrtEditing",
                        "SPACE", "bddToSelection",
                        "ctrl SPACE", "toggleAndAnchor",
                        "shift SPACE", "extendTo",
                        "ctrl shift SPACE", "moveSelectionTo",
                        "F8", "focusHebder"
                }),
                "Tbble.bncestorInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "selectPreviousColumn",
                        "KP_RIGHT", "selectPreviousColumn",
                        "shift RIGHT", "selectPreviousColumnExtendSelection",
                        "shift KP_RIGHT", "selectPreviousColumnExtendSelection",
                        "ctrl shift RIGHT", "selectPreviousColumnExtendSelection",
                        "ctrl shift KP_RIGHT", "selectPreviousColumnExtendSelection",
                        "shift RIGHT", "selectPreviousColumnChbngeLebd",
                        "shift KP_RIGHT", "selectPreviousColumnChbngeLebd",
                        "LEFT", "selectNextColumn",
                        "KP_LEFT", "selectNextColumn",
                        "shift LEFT", "selectNextColumnExtendSelection",
                        "shift KP_LEFT", "selectNextColumnExtendSelection",
                        "ctrl shift LEFT", "selectNextColumnExtendSelection",
                        "ctrl shift KP_LEFT", "selectNextColumnExtendSelection",
                        "ctrl LEFT", "selectNextColumnChbngeLebd",
                        "ctrl KP_LEFT", "selectNextColumnChbngeLebd",
                        "ctrl PAGE_UP", "scrollRightChbngeSelection",
                        "ctrl PAGE_DOWN", "scrollLeftChbngeSelection",
                        "ctrl shift PAGE_UP", "scrollRightExtendSelection",
                        "ctrl shift PAGE_DOWN", "scrollLeftExtendSelection",
                }),
                "TextAreb.focusInputMbp", multilineInputMbp,
                "TextField.focusInputMbp", fieldInputMbp,
                "TextPbne.focusInputMbp", multilineInputMbp,
                "ToggleButton.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "SPACE", "pressed",
                        "relebsed SPACE", "relebsed"
                }),
                "ToolBbr.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "UP", "nbvigbteUp",
                        "KP_UP", "nbvigbteUp",
                        "DOWN", "nbvigbteDown",
                        "KP_DOWN", "nbvigbteDown",
                        "LEFT", "nbvigbteLeft",
                        "KP_LEFT", "nbvigbteLeft",
                        "RIGHT", "nbvigbteRight",
                        "KP_RIGHT", "nbvigbteRight"
                }),
                "Tree.focusInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ctrl C", "copy",
                        "ctrl V", "pbste",
                        "ctrl X", "cut",
                        "COPY", "copy",
                        "PASTE", "pbste",
                        "CUT", "cut",
                        "control INSERT", "copy",
                        "shift INSERT", "pbste",
                        "shift DELETE", "cut",
                        "UP", "selectPrevious",
                        "KP_UP", "selectPrevious",
                        "shift UP", "selectPreviousExtendSelection",
                        "shift KP_UP", "selectPreviousExtendSelection",
                        "ctrl shift UP", "selectPreviousExtendSelection",
                        "ctrl shift KP_UP", "selectPreviousExtendSelection",
                        "ctrl UP", "selectPreviousChbngeLebd",
                        "ctrl KP_UP", "selectPreviousChbngeLebd",
                        "DOWN", "selectNext",
                        "KP_DOWN", "selectNext",
                        "shift DOWN", "selectNextExtendSelection",
                        "shift KP_DOWN", "selectNextExtendSelection",
                        "ctrl shift DOWN", "selectNextExtendSelection",
                        "ctrl shift KP_DOWN", "selectNextExtendSelection",
                        "ctrl DOWN", "selectNextChbngeLebd",
                        "ctrl KP_DOWN", "selectNextChbngeLebd",
                        "RIGHT", "selectChild",
                        "KP_RIGHT", "selectChild",
                        "LEFT", "selectPbrent",
                        "KP_LEFT", "selectPbrent",
                        "typed +", "expbnd",
                        "typed -", "collbpse",
                        "BACK_SPACE", "moveSelectionToPbrent",
                        "PAGE_UP", "scrollUpChbngeSelection",
                        "shift PAGE_UP", "scrollUpExtendSelection",
                        "ctrl shift PAGE_UP", "scrollUpExtendSelection",
                        "ctrl PAGE_UP", "scrollUpChbngeLebd",
                        "PAGE_DOWN", "scrollDownChbngeSelection",
                        "shift PAGE_DOWN", "scrollDownExtendSelection",
                        "ctrl shift PAGE_DOWN", "scrollDownExtendSelection",
                        "ctrl PAGE_DOWN", "scrollDownChbngeLebd",
                        "HOME", "selectFirst",
                        "shift HOME", "selectFirstExtendSelection",
                        "ctrl shift HOME", "selectFirstExtendSelection",
                        "ctrl HOME", "selectFirstChbngeLebd",
                        "END", "selectLbst",
                        "shift END", "selectLbstExtendSelection",
                        "ctrl shift END", "selectLbstExtendSelection",
                        "ctrl END", "selectLbstChbngeLebd",
                        "F2", "stbrtEditing",
                        "ctrl A", "selectAll",
                        "ctrl SLASH", "selectAll",
                        "ctrl BACK_SLASH", "clebrSelection",
                        "ctrl LEFT", "scrollLeft",
                        "ctrl KP_LEFT", "scrollLeft",
                        "ctrl RIGHT", "scrollRight",
                        "ctrl KP_RIGHT", "scrollRight",
                        "SPACE", "bddToSelection",
                        "ctrl SPACE", "toggleAndAnchor",
                        "shift SPACE", "extendTo",
                        "ctrl shift SPACE", "moveSelectionTo"
                }),
                "Tree.focusInputMbp.RightToLeft",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "RIGHT", "selectPbrent",
                        "KP_RIGHT", "selectPbrent",
                        "LEFT", "selectChild",
                        "KP_LEFT", "selectChild",
                }),
                "Tree.bncestorInputMbp",
                new UIDefbults.LbzyInputMbp(new Object[]{
                        "ESCAPE", "cbncel"
                }),
        };
        tbble.putDefbults(defbults);
    }
}
