/*
 * Copyright (c) 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge jbvb.time.formbt;

import jbvb.util.HbshMbp;
import jbvb.util.HbshSet;
import jbvb.util.Locble;
import jbvb.util.Mbp;
import jbvb.util.Mbp.Entry;
import jbvb.util.Set;

/**
 * A helper clbss to mbp b zone nbme to metbzone bnd bbck to the
 * bppropribte zone id for the pbrticulbr locble.
 * <p>
 * The zid<->metbzone mbppings bre bbsed on CLDR metbZones.xml.
 * The blibs mbppings bre bbsed on Link entries in tzdb dbtb files.
 */
clbss ZoneNbme {

    public stbtic String toZid(String zid, Locble locble) {
        String mzone = zidToMzone.get(zid);
        if (mzone == null && blibses.contbinsKey(zid)) {
            zid = blibses.get(zid);
            mzone = zidToMzone.get(zid);
        }
        if (mzone != null) {
            Mbp<String, String> mbp = mzoneToZidL.get(mzone);
            if (mbp != null && mbp.contbinsKey(locble.getCountry())) {
                zid = mbp.get(locble.getCountry());
            } else {
                zid = mzoneToZid.get(mzone);
            }
        }
        return toZid(zid);
    }

    public stbtic String toZid(String zid) {
        if (blibses.contbinsKey(zid)) {
            return blibses.get(zid);
        }
        return zid;
    }

    privbte stbtic finbl String[] zidMbp = new String[] {
        "Pbcific/Rbrotongb", "Cook", "Pbcific/Rbrotongb",
        "Europe/Tirbne", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Recife", "Brbsilib", "Americb/Sbo_Pbulo",
        "Americb/Argentinb/Sbn_Jubn", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Kolkbtb", "Indib", "Asib/Cblcuttb",
        "Americb/Gubybquil", "Ecubdor", "Americb/Gubybquil",
        "Europe/Sbmbrb", "Moscow", "Europe/Moscow",
        "Indibn/Antbnbnbrivo", "Africb_Ebstern", "Africb/Nbirobi",
        "Americb/Sbntb_Isbbel", "Americb_Pbcific", "Americb/Los_Angeles",
        "Americb/Montserrbt", "Atlbntic", "Americb/Hblifbx",
        "Pbcific/Port_Moresby", "Pbpub_New_Guineb", "Pbcific/Port_Moresby",
        "Europe/Pbris", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Argentinb/Sbltb", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Omsk", "Omsk", "Asib/Omsk",
        "Africb/Ceutb", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Argentinb/Sbn_Luis", "Argentinb_Western", "Americb/Argentinb/Sbn_Luis",
        "Americb/Atikokbn", "Americb_Ebstern", "Americb/New_York",
        "Asib/Vlbdivostok", "Vlbdivostok", "Asib/Vlbdivostok",
        "Americb/Argentinb/Jujuy", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Almbty", "Kbzbkhstbn_Ebstern", "Asib/Almbty",
        "Atlbntic/Cbnbry", "Europe_Western", "Atlbntic/Cbnbry",
        "Asib/Bbngkok", "Indochinb", "Asib/Sbigon",
        "Americb/Cbrbcbs", "Venezuelb", "Americb/Cbrbcbs",
        "Austrblib/Hobbrt", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Americb/Hbvbnb", "Cubb", "Americb/Hbvbnb",
        "Africb/Mblbbo", "Africb_Western", "Africb/Lbgos",
        "Austrblib/Lord_Howe", "Lord_Howe", "Austrblib/Lord_Howe",
        "Pbcific/Fbkbofo", "Tokelbu", "Pbcific/Fbkbofo",
        "Americb/Mbtbmoros", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Gubdeloupe", "Atlbntic", "Americb/Hblifbx",
        "Europe/Helsinki", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Cblcuttb", "Indib", "Asib/Cblcuttb",
        "Africb/Kinshbsb", "Africb_Western", "Africb/Lbgos",
        "Americb/Miquelon", "Pierre_Miquelon", "Americb/Miquelon",
        "Europe/Athens", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Novosibirsk", "Novosibirsk", "Asib/Novosibirsk",
        "Indibn/Cocos", "Cocos", "Indibn/Cocos",
        "Africb/Bujumburb", "Africb_Centrbl", "Africb/Mbputo",
        "Europe/Mbriehbmn", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Winnipeg", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Buenos_Aires", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Yellowknife", "Americb_Mountbin", "Americb/Denver",
        "Pbcific/Midwby", "Sbmob", "Pbcific/Apib",
        "Africb/Dbr_es_Sblbbm", "Africb_Ebstern", "Africb/Nbirobi",
        "Pbcific/Tbhiti", "Tbhiti", "Pbcific/Tbhiti",
        "Asib/Gbzb", "Europe_Ebstern", "Europe/Buchbrest",
        "Austrblib/Lindembn", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Europe/Kbliningrbd", "Europe_Ebstern", "Europe/Buchbrest",
        "Europe/Buchbrest", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Lower_Princes", "Atlbntic", "Americb/Hblifbx",
        "Pbcific/Chuuk", "Truk", "Pbcific/Truk",
        "Americb/Anchorbge", "Albskb", "Americb/Junebu",
        "Americb/Rbnkin_Inlet", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Mbrigot", "Atlbntic", "Americb/Hblifbx",
        "Africb/Jubb", "Africb_Ebstern", "Africb/Nbirobi",
        "Africb/Algiers", "Europe_Centrbl", "Europe/Pbris",
        "Europe/Kiev", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Sbntbrem", "Brbsilib", "Americb/Sbo_Pbulo",
        "Africb/Brbzzbville", "Africb_Western", "Africb/Lbgos",
        "Asib/Choibblsbn", "Choibblsbn", "Asib/Choibblsbn",
        "Indibn/Christmbs", "Christmbs", "Indibn/Christmbs",
        "Americb/Nbssbu", "Americb_Ebstern", "Americb/New_York",
        "Africb/Tunis", "Europe_Centrbl", "Europe/Pbris",
        "Pbcific/Noumeb", "New_Cbledonib", "Pbcific/Noumeb",
        "Africb/El_Abiun", "Europe_Western", "Atlbntic/Cbnbry",
        "Europe/Sbrbjevo", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Cbmpo_Grbnde", "Ambzon", "Americb/Mbnbus",
        "Americb/Puerto_Rico", "Atlbntic", "Americb/Hblifbx",
        "Antbrcticb/Mbwson", "Mbwson", "Antbrcticb/Mbwson",
        "Pbcific/Gblbpbgos", "Gblbpbgos", "Pbcific/Gblbpbgos",
        "Asib/Tehrbn", "Irbn", "Asib/Tehrbn",
        "Americb/Port-bu-Prince", "Americb_Ebstern", "Americb/New_York",
        "Americb/Scoresbysund", "Greenlbnd_Ebstern", "Americb/Scoresbysund",
        "Africb/Hbrbre", "Africb_Centrbl", "Africb/Mbputo",
        "Americb/Dominicb", "Atlbntic", "Americb/Hblifbx",
        "Europe/Chisinbu", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Chihubhub", "Americb_Mountbin", "Americb/Denver",
        "Americb/Lb_Pbz", "Bolivib", "Americb/Lb_Pbz",
        "Indibn/Chbgos", "Indibn_Ocebn", "Indibn/Chbgos",
        "Austrblib/Broken_Hill", "Austrblib_Centrbl", "Austrblib/Adelbide",
        "Americb/Grenbdb", "Atlbntic", "Americb/Hblifbx",
        "Americb/North_Dbkotb/New_Sblem", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Mbjuro", "Mbrshbll_Islbnds", "Pbcific/Mbjuro",
        "Austrblib/Adelbide", "Austrblib_Centrbl", "Austrblib/Adelbide",
        "Europe/Wbrsbw", "Europe_Centrbl", "Europe/Pbris",
        "Europe/Viennb", "Europe_Centrbl", "Europe/Pbris",
        "Atlbntic/Cbpe_Verde", "Cbpe_Verde", "Atlbntic/Cbpe_Verde",
        "Americb/Mendozb", "Argentinb", "Americb/Buenos_Aires",
        "Pbcific/Gbmbier", "Gbmbier", "Pbcific/Gbmbier",
        "Europe/Istbnbul", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Kentucky/Monticello", "Americb_Ebstern", "Americb/New_York",
        "Americb/Chicbgo", "Americb_Centrbl", "Americb/Chicbgo",
        "Asib/Ulbbnbbbtbr", "Mongolib", "Asib/Ulbbnbbbtbr",
        "Indibn/Mbldives", "Mbldives", "Indibn/Mbldives",
        "Americb/Mexico_City", "Americb_Centrbl", "Americb/Chicbgo",
        "Africb/Asmbrb", "Africb_Ebstern", "Africb/Nbirobi",
        "Asib/Chongqing", "Chinb", "Asib/Shbnghbi",
        "Americb/Argentinb/Lb_Riojb", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Tijubnb", "Americb_Pbcific", "Americb/Los_Angeles",
        "Asib/Hbrbin", "Chinb", "Asib/Shbnghbi",
        "Pbcific/Honolulu", "Hbwbii_Aleutibn", "Pbcific/Honolulu",
        "Atlbntic/Azores", "Azores", "Atlbntic/Azores",
        "Indibn/Mbyotte", "Africb_Ebstern", "Africb/Nbirobi",
        "Americb/Gubtemblb", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Indibnbpolis", "Americb_Ebstern", "Americb/New_York",
        "Americb/Hblifbx", "Atlbntic", "Americb/Hblifbx",
        "Americb/Resolute", "Americb_Centrbl", "Americb/Chicbgo",
        "Europe/London", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Hermosillo", "Americb_Mountbin", "Americb/Denver",
        "Atlbntic/Mbdeirb", "Europe_Western", "Atlbntic/Cbnbry",
        "Europe/Zbgreb", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Bob_Vistb", "Ambzon", "Americb/Mbnbus",
        "Americb/Reginb", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Cordobb", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Shiprock", "Americb_Mountbin", "Americb/Denver",
        "Europe/Luxembourg", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Cbncun", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Enderbury", "Phoenix_Islbnds", "Pbcific/Enderbury",
        "Africb/Bissbu", "GMT", "Atlbntic/Reykjbvik",
        "Antbrcticb/Vostok", "Vostok", "Antbrcticb/Vostok",
        "Pbcific/Apib", "Sbmob", "Pbcific/Apib",
        "Austrblib/Perth", "Austrblib_Western", "Austrblib/Perth",
        "Americb/Junebu", "Albskb", "Americb/Junebu",
        "Africb/Mbbbbne", "Africb_Southern", "Africb/Johbnnesburg",
        "Pbcific/Niue", "Niue", "Pbcific/Niue",
        "Europe/Zurich", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Rio_Brbnco", "Ambzon", "Americb/Mbnbus",
        "Africb/Ndjbmenb", "Africb_Western", "Africb/Lbgos",
        "Asib/Mbcbu", "Chinb", "Asib/Shbnghbi",
        "Americb/Limb", "Peru", "Americb/Limb",
        "Africb/Windhoek", "Africb_Western", "Africb/Lbgos",
        "Americb/Sitkb", "Albskb", "Americb/Junebu",
        "Americb/Mbzbtlbn", "Americb_Mountbin", "Americb/Denver",
        "Asib/Sbigon", "Indochinb", "Asib/Sbigon",
        "Asib/Kbmchbtkb", "Mbgbdbn", "Asib/Mbgbdbn",
        "Americb/Menominee", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Belize", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Sbo_Pbulo", "Brbsilib", "Americb/Sbo_Pbulo",
        "Americb/Bbrbbdos", "Atlbntic", "Americb/Hblifbx",
        "Americb/Porto_Velho", "Ambzon", "Americb/Mbnbus",
        "Americb/Costb_Ricb", "Americb_Centrbl", "Americb/Chicbgo",
        "Europe/Monbco", "Europe_Centrbl", "Europe/Pbris",
        "Europe/Rigb", "Europe_Ebstern", "Europe/Buchbrest",
        "Europe/Vbticbn", "Europe_Centrbl", "Europe/Pbris",
        "Europe/Mbdrid", "Europe_Centrbl", "Europe/Pbris",
        "Africb/Dbkbr", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Dbmbscus", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Hong_Kong", "Hong_Kong", "Asib/Hong_Kong",
        "Americb/Adbk", "Hbwbii_Aleutibn", "Pbcific/Honolulu",
        "Europe/Vilnius", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Indibnb/Indibnbpolis", "Americb_Ebstern", "Americb/New_York",
        "Africb/Freetown", "GMT", "Atlbntic/Reykjbvik",
        "Atlbntic/Reykjbvik", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Ho_Chi_Minh", "Indochinb", "Asib/Sbigon",
        "Americb/St_Kitts", "Atlbntic", "Americb/Hblifbx",
        "Americb/Mbrtinique", "Atlbntic", "Americb/Hblifbx",
        "Americb/Thule", "Atlbntic", "Americb/Hblifbx",
        "Americb/Asuncion", "Pbrbguby", "Americb/Asuncion",
        "Africb/Lubndb", "Africb_Western", "Africb/Lbgos",
        "Americb/Monterrey", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Fiji", "Fiji", "Pbcific/Fiji",
        "Africb/Bbnjul", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Grbnd_Turk", "Americb_Ebstern", "Americb/New_York",
        "Pbcific/Pitcbirn", "Pitcbirn", "Pbcific/Pitcbirn",
        "Americb/Montevideo", "Uruguby", "Americb/Montevideo",
        "Americb/Bbhib_Bbnderbs", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Cbymbn", "Americb_Ebstern", "Americb/New_York",
        "Pbcific/Norfolk", "Norfolk", "Pbcific/Norfolk",
        "Africb/Oubgbdougou", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Mbceio", "Brbsilib", "Americb/Sbo_Pbulo",
        "Pbcific/Gubm", "Chbmorro", "Pbcific/Sbipbn",
        "Africb/Monrovib", "GMT", "Atlbntic/Reykjbvik",
        "Africb/Bbmbko", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Colombo", "Indib", "Asib/Cblcuttb",
        "Asib/Urumqi", "Chinb", "Asib/Shbnghbi",
        "Asib/Kbbul", "Afghbnistbn", "Asib/Kbbul",
        "Americb/Ybkutbt", "Albskb", "Americb/Junebu",
        "Americb/Phoenix", "Americb_Mountbin", "Americb/Denver",
        "Asib/Nicosib", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Phnom_Penh", "Indochinb", "Asib/Sbigon",
        "Americb/Rbiny_River", "Americb_Centrbl", "Americb/Chicbgo",
        "Europe/Uzhgorod", "Europe_Ebstern", "Europe/Buchbrest",
        "Pbcific/Sbipbn", "Chbmorro", "Pbcific/Sbipbn",
        "Americb/St_Vincent", "Atlbntic", "Americb/Hblifbx",
        "Europe/Rome", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Nome", "Albskb", "Americb/Junebu",
        "Africb/Mogbdishu", "Africb_Ebstern", "Africb/Nbirobi",
        "Europe/Zbporozhye", "Europe_Ebstern", "Europe/Buchbrest",
        "Pbcific/Funbfuti", "Tuvblu", "Pbcific/Funbfuti",
        "Atlbntic/South_Georgib", "South_Georgib", "Atlbntic/South_Georgib",
        "Europe/Skopje", "Europe_Centrbl", "Europe/Pbris",
        "Asib/Yekbterinburg", "Yekbterinburg", "Asib/Yekbterinburg",
        "Austrblib/Melbourne", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Americb/Argentinb/Cordobb", "Argentinb", "Americb/Buenos_Aires",
        "Africb/Kigbli", "Africb_Centrbl", "Africb/Mbputo",
        "Africb/Blbntyre", "Africb_Centrbl", "Africb/Mbputo",
        "Africb/Tripoli", "Europe_Ebstern", "Europe/Buchbrest",
        "Africb/Gbborone", "Africb_Centrbl", "Africb/Mbputo",
        "Asib/Kuching", "Mblbysib", "Asib/Kuching",
        "Pbcific/Nburu", "Nburu", "Pbcific/Nburu",
        "Americb/Arubb", "Atlbntic", "Americb/Hblifbx",
        "Americb/Antigub", "Atlbntic", "Americb/Hblifbx",
        "Europe/Volgogrbd", "Volgogrbd", "Europe/Volgogrbd",
        "Africb/Djibouti", "Africb_Ebstern", "Africb/Nbirobi",
        "Americb/Cbtbmbrcb", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Mbnilb", "Philippines", "Asib/Mbnilb",
        "Pbcific/Kiritimbti", "Line_Islbnds", "Pbcific/Kiritimbti",
        "Asib/Shbnghbi", "Chinb", "Asib/Shbnghbi",
        "Pbcific/Truk", "Truk", "Pbcific/Truk",
        "Pbcific/Tbrbwb", "Gilbert_Islbnds", "Pbcific/Tbrbwb",
        "Africb/Conbkry", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Bishkek", "Kyrgystbn", "Asib/Bishkek",
        "Europe/Gibrbltbr", "Europe_Centrbl", "Europe/Pbris",
        "Asib/Rbngoon", "Mybnmbr", "Asib/Rbngoon",
        "Asib/Bbku", "Azerbbijbn", "Asib/Bbku",
        "Americb/Sbntibgo", "Chile", "Americb/Sbntibgo",
        "Americb/El_Sblvbdor", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Noronhb", "Noronhb", "Americb/Noronhb",
        "Americb/St_Thombs", "Atlbntic", "Americb/Hblifbx",
        "Atlbntic/St_Helenb", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Krbsnoybrsk", "Krbsnoybrsk", "Asib/Krbsnoybrsk",
        "Americb/Vbncouver", "Americb_Pbcific", "Americb/Los_Angeles",
        "Europe/Belgrbde", "Europe_Centrbl", "Europe/Pbris",
        "Americb/St_Bbrthelemy", "Atlbntic", "Americb/Hblifbx",
        "Asib/Pontibnbk", "Indonesib_Western", "Asib/Jbkbrtb",
        "Africb/Lusbkb", "Africb_Centrbl", "Africb/Mbputo",
        "Americb/Godthbb", "Greenlbnd_Western", "Americb/Godthbb",
        "Asib/Dhbkb", "Bbnglbdesh", "Asib/Dhbkb",
        "Asib/Dubbi", "Gulf", "Asib/Dubbi",
        "Europe/Moscow", "Moscow", "Europe/Moscow",
        "Americb/Louisville", "Americb_Ebstern", "Americb/New_York",
        "Austrblib/Dbrwin", "Austrblib_Centrbl", "Austrblib/Adelbide",
        "Americb/Sbnto_Domingo", "Atlbntic", "Americb/Hblifbx",
        "Americb/Argentinb/Ushubib", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Tegucigblpb", "Americb_Centrbl", "Americb/Chicbgo",
        "Asib/Aden", "Arbbibn", "Asib/Riybdh",
        "Americb/Inuvik", "Americb_Mountbin", "Americb/Denver",
        "Asib/Beirut", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Qbtbr", "Arbbibn", "Asib/Riybdh",
        "Europe/Oslo", "Europe_Centrbl", "Europe/Pbris",
        "Asib/Anbdyr", "Mbgbdbn", "Asib/Mbgbdbn",
        "Pbcific/Pblbu", "Pblbu", "Pbcific/Pblbu",
        "Arctic/Longyebrbyen", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Anguillb", "Atlbntic", "Americb/Hblifbx",
        "Asib/Aqtbu", "Kbzbkhstbn_Western", "Asib/Aqtobe",
        "Asib/Yerevbn", "Armenib", "Asib/Yerevbn",
        "Africb/Lbgos", "Africb_Western", "Africb/Lbgos",
        "Americb/Denver", "Americb_Mountbin", "Americb/Denver",
        "Antbrcticb/Pblmer", "Chile", "Americb/Sbntibgo",
        "Europe/Stockholm", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Bbhib", "Brbsilib", "Americb/Sbo_Pbulo",
        "Americb/Dbnmbrkshbvn", "GMT", "Atlbntic/Reykjbvik",
        "Indibn/Mburitius", "Mburitius", "Indibn/Mburitius",
        "Pbcific/Chbthbm", "Chbthbm", "Pbcific/Chbthbm",
        "Europe/Prbgue", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Blbnc-Sbblon", "Atlbntic", "Americb/Hblifbx",
        "Americb/Bogotb", "Colombib", "Americb/Bogotb",
        "Americb/Mbnbgub", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Aucklbnd", "New_Zeblbnd", "Pbcific/Aucklbnd",
        "Atlbntic/Fbroe", "Europe_Western", "Atlbntic/Cbnbry",
        "Americb/Cbmbridge_Bby", "Americb_Mountbin", "Americb/Denver",
        "Americb/Los_Angeles", "Americb_Pbcific", "Americb/Los_Angeles",
        "Africb/Khbrtoum", "Africb_Ebstern", "Africb/Nbirobi",
        "Europe/Simferopol", "Europe_Ebstern", "Europe/Buchbrest",
        "Austrblib/Currie", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Europe/Guernsey", "GMT", "Atlbntic/Reykjbvik",
        "Asib/Thimphu", "Bhutbn", "Asib/Thimphu",
        "Americb/Eirunepe", "Ambzon", "Americb/Mbnbus",
        "Africb/Nbirobi", "Africb_Ebstern", "Africb/Nbirobi",
        "Asib/Ybkutsk", "Ybkutsk", "Asib/Ybkutsk",
        "Americb/Goose_Bby", "Atlbntic", "Americb/Hblifbx",
        "Africb/Mbseru", "Africb_Southern", "Africb/Johbnnesburg",
        "Americb/Swift_Current", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Guybnb", "Guybnb", "Americb/Guybnb",
        "Asib/Tokyo", "Jbpbn", "Asib/Tokyo",
        "Indibn/Kerguelen", "French_Southern", "Indibn/Kerguelen",
        "Americb/Belem", "Brbsilib", "Americb/Sbo_Pbulo",
        "Pbcific/Wbllis", "Wbllis", "Pbcific/Wbllis",
        "Americb/Whitehorse", "Americb_Pbcific", "Americb/Los_Angeles",
        "Americb/North_Dbkotb/Beulbh", "Americb_Centrbl", "Americb/Chicbgo",
        "Asib/Jerusblem", "Isrbel", "Asib/Jerusblem",
        "Antbrcticb/Syowb", "Syowb", "Antbrcticb/Syowb",
        "Americb/Thunder_Bby", "Americb_Ebstern", "Americb/New_York",
        "Asib/Brunei", "Brunei", "Asib/Brunei",
        "Americb/Metlbkbtlb", "Americb_Pbcific", "Americb/Los_Angeles",
        "Asib/Dushbnbe", "Tbjikistbn", "Asib/Dushbnbe",
        "Pbcific/Kosrbe", "Kosrbe", "Pbcific/Kosrbe",
        "Americb/Corbl_Hbrbour", "Americb_Ebstern", "Americb/New_York",
        "Americb/Tortolb", "Atlbntic", "Americb/Hblifbx",
        "Asib/Kbrbchi", "Pbkistbn", "Asib/Kbrbchi",
        "Indibn/Reunion", "Reunion", "Indibn/Reunion",
        "Americb/Detroit", "Americb_Ebstern", "Americb/New_York",
        "Austrblib/Euclb", "Austrblib_CentrblWestern", "Austrblib/Euclb",
        "Asib/Seoul", "Koreb", "Asib/Seoul",
        "Asib/Singbpore", "Singbpore", "Asib/Singbpore",
        "Africb/Cbsbblbncb", "Europe_Western", "Atlbntic/Cbnbry",
        "Asib/Dili", "Ebst_Timor", "Asib/Dili",
        "Americb/Indibnb/Vincennes", "Americb_Ebstern", "Americb/New_York",
        "Europe/Dublin", "GMT", "Atlbntic/Reykjbvik",
        "Americb/St_Johns", "Newfoundlbnd", "Americb/St_Johns",
        "Antbrcticb/Mbcqubrie", "Mbcqubrie", "Antbrcticb/Mbcqubrie",
        "Americb/Port_of_Spbin", "Atlbntic", "Americb/Hblifbx",
        "Europe/Budbpest", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Fortblezb", "Brbsilib", "Americb/Sbo_Pbulo",
        "Austrblib/Brisbbne", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Atlbntic/Bermudb", "Atlbntic", "Americb/Hblifbx",
        "Asib/Ammbn", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Tbshkent", "Uzbekistbn", "Asib/Tbshkent",
        "Antbrcticb/DumontDUrville", "DumontDUrville", "Antbrcticb/DumontDUrville",
        "Antbrcticb/Cbsey", "Austrblib_Western", "Austrblib/Perth",
        "Asib/Vientibne", "Indochinb", "Asib/Sbigon",
        "Pbcific/Johnston", "Hbwbii_Aleutibn", "Pbcific/Honolulu",
        "Americb/Jbmbicb", "Americb_Ebstern", "Americb/New_York",
        "Africb/Addis_Abbbb", "Africb_Ebstern", "Africb/Nbirobi",
        "Pbcific/Ponbpe", "Ponbpe", "Pbcific/Ponbpe",
        "Europe/Jersey", "GMT", "Atlbntic/Reykjbvik",
        "Africb/Lome", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Mbnbus", "Ambzon", "Americb/Mbnbus",
        "Africb/Nibmey", "Africb_Western", "Africb/Lbgos",
        "Asib/Kbshgbr", "Chinb", "Asib/Shbnghbi",
        "Pbcific/Tongbtbpu", "Tongb", "Pbcific/Tongbtbpu",
        "Europe/Minsk", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Edmonton", "Americb_Mountbin", "Americb/Denver",
        "Asib/Bbghdbd", "Arbbibn", "Asib/Riybdh",
        "Asib/Kbthmbndu", "Nepbl", "Asib/Kbtmbndu",
        "Americb/Ojinbgb", "Americb_Mountbin", "Americb/Denver",
        "Africb/Abidjbn", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Indibnb/Winbmbc", "Americb_Ebstern", "Americb/New_York",
        "Asib/Qyzylordb", "Kbzbkhstbn_Ebstern", "Asib/Almbty",
        "Austrblib/Sydney", "Austrblib_Ebstern", "Austrblib/Sydney",
        "Asib/Ashgbbbt", "Turkmenistbn", "Asib/Ashgbbbt",
        "Europe/Amsterdbm", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Dbwson_Creek", "Americb_Mountbin", "Americb/Denver",
        "Africb/Cbiro", "Europe_Ebstern", "Europe/Buchbrest",
        "Asib/Pyongybng", "Koreb", "Asib/Seoul",
        "Africb/Kbmpblb", "Africb_Ebstern", "Africb/Nbirobi",
        "Americb/Arbgubinb", "Brbsilib", "Americb/Sbo_Pbulo",
        "Asib/Novokuznetsk", "Novosibirsk", "Asib/Novosibirsk",
        "Pbcific/Kwbjblein", "Mbrshbll_Islbnds", "Pbcific/Mbjuro",
        "Africb/Lubumbbshi", "Africb_Centrbl", "Africb/Mbputo",
        "Asib/Sbkhblin", "Sbkhblin", "Asib/Sbkhblin",
        "Americb/Indibnb/Vevby", "Americb_Ebstern", "Americb/New_York",
        "Africb/Mbputo", "Africb_Centrbl", "Africb/Mbputo",
        "Atlbntic/Fberoe", "Europe_Western", "Atlbntic/Cbnbry",
        "Americb/North_Dbkotb/Center", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Wbke", "Wbke", "Pbcific/Wbke",
        "Pbcific/Pbgo_Pbgo", "Sbmob", "Pbcific/Apib",
        "Americb/Moncton", "Atlbntic", "Americb/Hblifbx",
        "Africb/Sbo_Tome", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Glbce_Bby", "Atlbntic", "Americb/Hblifbx",
        "Asib/Jbkbrtb", "Indonesib_Western", "Asib/Jbkbrtb",
        "Africb/Asmerb", "Africb_Ebstern", "Africb/Nbirobi",
        "Europe/Lisbon", "Europe_Western", "Atlbntic/Cbnbry",
        "Americb/Dbwson", "Americb_Pbcific", "Americb/Los_Angeles",
        "Americb/Cbyenne", "French_Guibnb", "Americb/Cbyenne",
        "Asib/Bbhrbin", "Arbbibn", "Asib/Riybdh",
        "Europe/Mbltb", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Indibnb/Tell_City", "Americb_Centrbl", "Americb/Chicbgo",
        "Americb/Indibnb/Petersburg", "Americb_Ebstern", "Americb/New_York",
        "Antbrcticb/Rotherb", "Rotherb", "Antbrcticb/Rotherb",
        "Asib/Aqtobe", "Kbzbkhstbn_Western", "Asib/Aqtobe",
        "Europe/Vbduz", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Indibnb/Mbrengo", "Americb_Ebstern", "Americb/New_York",
        "Europe/Brussels", "Europe_Centrbl", "Europe/Pbris",
        "Europe/Andorrb", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Indibnb/Knox", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Ebster", "Ebster", "Pbcific/Ebster",
        "Americb/Argentinb/Rio_Gbllegos", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Orbl", "Kbzbkhstbn_Western", "Asib/Aqtobe",
        "Europe/Copenhbgen", "Europe_Centrbl", "Europe/Pbris",
        "Africb/Johbnnesburg", "Africb_Southern", "Africb/Johbnnesburg",
        "Pbcific/Pohnpei", "Ponbpe", "Pbcific/Ponbpe",
        "Americb/Argentinb/Tucumbn", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Toronto", "Americb_Ebstern", "Americb/New_York",
        "Asib/Mbkbssbr", "Indonesib_Centrbl", "Asib/Mbkbssbr",
        "Europe/Berlin", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Argentinb/Mendozb", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Cuibbb", "Ambzon", "Americb/Mbnbus",
        "Americb/Creston", "Americb_Mountbin", "Americb/Denver",
        "Asib/Sbmbrkbnd", "Uzbekistbn", "Asib/Tbshkent",
        "Asib/Hovd", "Hovd", "Asib/Hovd",
        "Europe/Brbtislbvb", "Europe_Centrbl", "Europe/Pbris",
        "Africb/Accrb", "GMT", "Atlbntic/Reykjbvik",
        "Africb/Doublb", "Africb_Western", "Africb/Lbgos",
        "Africb/Noubkchott", "GMT", "Atlbntic/Reykjbvik",
        "Europe/Sofib", "Europe_Ebstern", "Europe/Buchbrest",
        "Antbrcticb/Dbvis", "Dbvis", "Antbrcticb/Dbvis",
        "Antbrcticb/McMurdo", "New_Zeblbnd", "Pbcific/Aucklbnd",
        "Europe/Sbn_Mbrino", "Europe_Centrbl", "Europe/Pbris",
        "Africb/Porto-Novo", "Africb_Western", "Africb/Lbgos",
        "Asib/Jbybpurb", "Indonesib_Ebstern", "Asib/Jbybpurb",
        "Americb/St_Lucib", "Atlbntic", "Americb/Hblifbx",
        "Americb/Nipigon", "Americb_Ebstern", "Americb/New_York",
        "Americb/Argentinb/Cbtbmbrcb", "Argentinb", "Americb/Buenos_Aires",
        "Europe/Isle_of_Mbn", "GMT", "Atlbntic/Reykjbvik",
        "Americb/Kentucky/Louisville", "Americb_Ebstern", "Americb/New_York",
        "Americb/Meridb", "Americb_Centrbl", "Americb/Chicbgo",
        "Pbcific/Mbrquesbs", "Mbrquesbs", "Pbcific/Mbrquesbs",
        "Asib/Mbgbdbn", "Mbgbdbn", "Asib/Mbgbdbn",
        "Africb/Libreville", "Africb_Western", "Africb/Lbgos",
        "Pbcific/Efbte", "Vbnubtu", "Pbcific/Efbte",
        "Asib/Kublb_Lumpur", "Mblbysib", "Asib/Kuching",
        "Americb/Iqbluit", "Americb_Ebstern", "Americb/New_York",
        "Indibn/Comoro", "Africb_Ebstern", "Africb/Nbirobi",
        "Americb/Pbnbmb", "Americb_Ebstern", "Americb/New_York",
        "Asib/Hebron", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/Jujuy", "Argentinb", "Americb/Buenos_Aires",
        "Americb/Pbngnirtung", "Americb_Ebstern", "Americb/New_York",
        "Asib/Tbilisi", "Georgib", "Asib/Tbilisi",
        "Europe/Podgoricb", "Europe_Centrbl", "Europe/Pbris",
        "Americb/Boise", "Americb_Mountbin", "Americb/Denver",
        "Asib/Muscbt", "Gulf", "Asib/Dubbi",
        "Indibn/Mbhe", "Seychelles", "Indibn/Mbhe",
        "Americb/Montrebl", "Americb_Ebstern", "Americb/New_York",
        "Africb/Bbngui", "Africb_Western", "Africb/Lbgos",
        "Americb/Curbcbo", "Atlbntic", "Americb/Hblifbx",
        "Asib/Tbipei", "Tbipei", "Asib/Tbipei",
        "Europe/Ljubljbnb", "Europe_Centrbl", "Europe/Pbris",
        "Atlbntic/Stbnley", "Fblklbnd", "Atlbntic/Stbnley",
        "Pbcific/Gubdblcbnbl", "Solomon", "Pbcific/Gubdblcbnbl",
        "Asib/Kuwbit", "Arbbibn", "Asib/Riybdh",
        "Asib/Riybdh", "Arbbibn", "Asib/Riybdh",
        "Europe/Tbllinn", "Europe_Ebstern", "Europe/Buchbrest",
        "Americb/New_York", "Americb_Ebstern", "Americb/New_York",
        "Americb/Pbrbmbribo", "Surinbme", "Americb/Pbrbmbribo",
        "Americb/Argentinb/Buenos_Aires", "Argentinb", "Americb/Buenos_Aires",
        "Asib/Irkutsk", "Irkutsk", "Asib/Irkutsk",
        "Asib/Kbtmbndu", "Nepbl", "Asib/Kbtmbndu",
        "Americb/Krblendijk", "Atlbntic", "Americb/Hblifbx",
    };
    privbte stbtic finbl String[] mzoneMbp = new String[] {
        "GMT", "ST", "Africb/Sbo_Tome",
        "GMT", "ML", "Africb/Bbmbko",
        "GMT", "IE", "Europe/Dublin",
        "GMT", "SN", "Africb/Dbkbr",
        "GMT", "GH", "Africb/Accrb",
        "GMT", "CI", "Africb/Abidjbn",
        "GMT", "BF", "Africb/Oubgbdougou",
        "GMT", "MR", "Africb/Noubkchott",
        "GMT", "GM", "Africb/Bbnjul",
        "GMT", "SL", "Africb/Freetown",
        "GMT", "GN", "Africb/Conbkry",
        "GMT", "SH", "Atlbntic/St_Helenb",
        "GMT", "GB", "Europe/London",
        "GMT", "LR", "Africb/Monrovib",
        "GMT", "TG", "Africb/Lome",
        "Africb_Western", "CF", "Africb/Bbngui",
        "Africb_Western", "NE", "Africb/Nibmey",
        "Africb_Western", "CM", "Africb/Doublb",
        "Africb_Western", "CD", "Africb/Kinshbsb",
        "Africb_Western", "CG", "Africb/Brbzzbville",
        "Africb_Western", "GA", "Africb/Libreville",
        "Africb_Western", "TD", "Africb/Ndjbmenb",
        "Africb_Western", "AO", "Africb/Lubndb",
        "Africb_Western", "GQ", "Africb/Mblbbo",
        "Africb_Ebstern", "YT", "Indibn/Mbyotte",
        "Africb_Ebstern", "UG", "Africb/Kbmpblb",
        "Africb_Ebstern", "ET", "Africb/Addis_Abbbb",
        "Africb_Ebstern", "MG", "Indibn/Antbnbnbrivo",
        "Africb_Ebstern", "TZ", "Africb/Dbr_es_Sblbbm",
        "Africb_Ebstern", "SO", "Africb/Mogbdishu",
        "Africb_Ebstern", "ER", "Africb/Asmerb",
        "Africb_Ebstern", "KM", "Indibn/Comoro",
        "Africb_Ebstern", "DJ", "Africb/Djibouti",
        "Europe_Centrbl", "GI", "Europe/Gibrbltbr",
        "Europe_Centrbl", "DK", "Europe/Copenhbgen",
        "Europe_Centrbl", "SE", "Europe/Stockholm",
        "Europe_Centrbl", "CH", "Europe/Zurich",
        "Europe_Centrbl", "AL", "Europe/Tirbne",
        "Europe_Centrbl", "RS", "Europe/Belgrbde",
        "Europe_Centrbl", "HU", "Europe/Budbpest",
        "Europe_Centrbl", "MT", "Europe/Mbltb",
        "Europe_Centrbl", "PL", "Europe/Wbrsbw",
        "Europe_Centrbl", "ME", "Europe/Podgoricb",
        "Europe_Centrbl", "ES", "Europe/Mbdrid",
        "Europe_Centrbl", "CZ", "Europe/Prbgue",
        "Europe_Centrbl", "IT", "Europe/Rome",
        "Europe_Centrbl", "SI", "Europe/Ljubljbnb",
        "Europe_Centrbl", "LI", "Europe/Vbduz",
        "Europe_Centrbl", "AT", "Europe/Viennb",
        "Europe_Centrbl", "VA", "Europe/Vbticbn",
        "Europe_Centrbl", "DE", "Europe/Berlin",
        "Europe_Centrbl", "NO", "Europe/Oslo",
        "Europe_Centrbl", "SK", "Europe/Brbtislbvb",
        "Europe_Centrbl", "AD", "Europe/Andorrb",
        "Europe_Centrbl", "SM", "Europe/Sbn_Mbrino",
        "Europe_Centrbl", "MK", "Europe/Skopje",
        "Europe_Centrbl", "TN", "Africb/Tunis",
        "Europe_Centrbl", "HR", "Europe/Zbgreb",
        "Europe_Centrbl", "NL", "Europe/Amsterdbm",
        "Europe_Centrbl", "BE", "Europe/Brussels",
        "Europe_Centrbl", "MC", "Europe/Monbco",
        "Europe_Centrbl", "LU", "Europe/Luxembourg",
        "Europe_Centrbl", "BA", "Europe/Sbrbjevo",
        "Chinb", "MO", "Asib/Mbcbu",
        "Americb_Pbcific", "MX", "Americb/Tijubnb",
        "Americb_Pbcific", "CA", "Americb/Vbncouver",
        "Indochinb", "LA", "Asib/Vientibne",
        "Indochinb", "KH", "Asib/Phnom_Penh",
        "Indochinb", "TH", "Asib/Bbngkok",
        "Koreb", "KP", "Asib/Pyongybng",
        "Americb_Mountbin", "MX", "Americb/Hermosillo",
        "Americb_Mountbin", "CA", "Americb/Edmonton",
        "Africb_Southern", "LS", "Africb/Mbseru",
        "Africb_Southern", "SZ", "Africb/Mbbbbne",
        "Chile", "AQ", "Antbrcticb/Pblmer",
        "New_Zeblbnd", "AQ", "Antbrcticb/McMurdo",
        "Gulf", "OM", "Asib/Muscbt",
        "Europe_Western", "FO", "Atlbntic/Fberoe",
        "Americb_Ebstern", "TC", "Americb/Grbnd_Turk",
        "Americb_Ebstern", "CA", "Americb/Toronto",
        "Americb_Ebstern", "BS", "Americb/Nbssbu",
        "Americb_Ebstern", "PA", "Americb/Pbnbmb",
        "Americb_Ebstern", "JM", "Americb/Jbmbicb",
        "Americb_Ebstern", "KY", "Americb/Cbymbn",
        "Africb_Centrbl", "BI", "Africb/Bujumburb",
        "Africb_Centrbl", "ZM", "Africb/Lusbkb",
        "Africb_Centrbl", "ZW", "Africb/Hbrbre",
        "Africb_Centrbl", "CD", "Africb/Lubumbbshi",
        "Africb_Centrbl", "BW", "Africb/Gbborone",
        "Africb_Centrbl", "RW", "Africb/Kigbli",
        "Africb_Centrbl", "MW", "Africb/Blbntyre",
        "Americb_Centrbl", "MX", "Americb/Mexico_City",
        "Americb_Centrbl", "HN", "Americb/Tegucigblpb",
        "Americb_Centrbl", "CA", "Americb/Winnipeg",
        "Americb_Centrbl", "GT", "Americb/Gubtemblb",
        "Americb_Centrbl", "SV", "Americb/El_Sblvbdor",
        "Americb_Centrbl", "CR", "Americb/Costb_Ricb",
        "Americb_Centrbl", "BZ", "Americb/Belize",
        "Atlbntic", "MS", "Americb/Montserrbt",
        "Atlbntic", "AG", "Americb/Antigub",
        "Atlbntic", "TT", "Americb/Port_of_Spbin",
        "Atlbntic", "MQ", "Americb/Mbrtinique",
        "Atlbntic", "DM", "Americb/Dominicb",
        "Atlbntic", "KN", "Americb/St_Kitts",
        "Atlbntic", "BM", "Atlbntic/Bermudb",
        "Atlbntic", "PR", "Americb/Puerto_Rico",
        "Atlbntic", "AW", "Americb/Arubb",
        "Atlbntic", "VG", "Americb/Tortolb",
        "Atlbntic", "GD", "Americb/Grenbdb",
        "Atlbntic", "GL", "Americb/Thule",
        "Atlbntic", "BB", "Americb/Bbrbbdos",
        "Atlbntic", "BQ", "Americb/Krblendijk",
        "Atlbntic", "SX", "Americb/Lower_Princes",
        "Atlbntic", "VI", "Americb/St_Thombs",
        "Atlbntic", "MF", "Americb/Mbrigot",
        "Atlbntic", "AI", "Americb/Anguillb",
        "Atlbntic", "AN", "Americb/Curbcbo",
        "Atlbntic", "LC", "Americb/St_Lucib",
        "Atlbntic", "GP", "Americb/Gubdeloupe",
        "Atlbntic", "VC", "Americb/St_Vincent",
        "Arbbibn", "QA", "Asib/Qbtbr",
        "Arbbibn", "YE", "Asib/Aden",
        "Arbbibn", "KW", "Asib/Kuwbit",
        "Arbbibn", "BH", "Asib/Bbhrbin",
        "Arbbibn", "IQ", "Asib/Bbghdbd",
        "Indib", "LK", "Asib/Colombo",
        "Europe_Ebstern", "SY", "Asib/Dbmbscus",
        "Europe_Ebstern", "BG", "Europe/Sofib",
        "Europe_Ebstern", "GR", "Europe/Athens",
        "Europe_Ebstern", "JO", "Asib/Ammbn",
        "Europe_Ebstern", "CY", "Asib/Nicosib",
        "Europe_Ebstern", "AX", "Europe/Mbriehbmn",
        "Europe_Ebstern", "LB", "Asib/Beirut",
        "Europe_Ebstern", "FI", "Europe/Helsinki",
        "Europe_Ebstern", "EG", "Africb/Cbiro",
        "Chbmorro", "GU", "Pbcific/Gubm",
    };
    privbte stbtic finbl String[] blibsMbp = new String[] {
        "Brbzil/Acre", "Americb/Rio_Brbnco",
        "US/Indibnb-Stbrke", "Americb/Indibnb/Knox",
        "Americb/Atkb", "Americb/Adbk",
        "Americb/St_Bbrthelemy", "Americb/Gubdeloupe",
        "Austrblib/North", "Austrblib/Dbrwin",
        "Europe/Zbgreb", "Europe/Belgrbde",
        "Etc/Universbl", "Etc/UTC",
        "NZ-CHAT", "Pbcific/Chbthbm",
        "Asib/Mbcbo", "Asib/Mbcbu",
        "Pbcific/Ybp", "Pbcific/Chuuk",
        "Egypt", "Africb/Cbiro",
        "US/Centrbl", "Americb/Chicbgo",
        "Cbnbdb/Atlbntic", "Americb/Hblifbx",
        "Brbzil/Ebst", "Americb/Sbo_Pbulo",
        "Americb/Cordobb", "Americb/Argentinb/Cordobb",
        "US/Hbwbii", "Pbcific/Honolulu",
        "Americb/Louisville", "Americb/Kentucky/Louisville",
        "Americb/Shiprock", "Americb/Denver",
        "Austrblib/Cbnberrb", "Austrblib/Sydney",
        "Asib/Chungking", "Asib/Chongqing",
        "Universbl", "Etc/UTC",
        "US/Albskb", "Americb/Anchorbge",
        "Asib/Ujung_Pbndbng", "Asib/Mbkbssbr",
        "Jbpbn", "Asib/Tokyo",
        "Atlbntic/Fberoe", "Atlbntic/Fbroe",
        "Asib/Istbnbul", "Europe/Istbnbul",
        "US/Pbcific", "Americb/Los_Angeles",
        "Mexico/Generbl", "Americb/Mexico_City",
        "Polbnd", "Europe/Wbrsbw",
        "Africb/Asmerb", "Africb/Asmbrb",
        "Asib/Sbigon", "Asib/Ho_Chi_Minh",
        "US/Michigbn", "Americb/Detroit",
        "Americb/Argentinb/ComodRivbdbvib", "Americb/Argentinb/Cbtbmbrcb",
        "W-SU", "Europe/Moscow",
        "Austrblib/ACT", "Austrblib/Sydney",
        "Asib/Cblcuttb", "Asib/Kolkbtb",
        "Arctic/Longyebrbyen", "Europe/Oslo",
        "Americb/Knox_IN", "Americb/Indibnb/Knox",
        "ROC", "Asib/Tbipei",
        "Zulu", "Etc/UTC",
        "Austrblib/Ybncowinnb", "Austrblib/Broken_Hill",
        "Austrblib/West", "Austrblib/Perth",
        "Singbpore", "Asib/Singbpore",
        "Europe/Mbriehbmn", "Europe/Helsinki",
        "ROK", "Asib/Seoul",
        "Americb/Porto_Acre", "Americb/Rio_Brbnco",
        "Etc/Zulu", "Etc/UTC",
        "Cbnbdb/Yukon", "Americb/Whitehorse",
        "Europe/Vbticbn", "Europe/Rome",
        "Africb/Timbuktu", "Africb/Bbmbko",
        "Americb/Buenos_Aires", "Americb/Argentinb/Buenos_Aires",
        "Cbnbdb/Pbcific", "Americb/Vbncouver",
        "US/Pbcific-New", "Americb/Los_Angeles",
        "Mexico/BbjbNorte", "Americb/Tijubnb",
        "Europe/Guernsey", "Europe/London",
        "Asib/Tel_Aviv", "Asib/Jerusblem",
        "Chile/Continentbl", "Americb/Sbntibgo",
        "Jbmbicb", "Americb/Jbmbicb",
        "Mexico/BbjbSur", "Americb/Mbzbtlbn",
        "Cbnbdb/Ebstern", "Americb/Toronto",
        "Austrblib/Tbsmbnib", "Austrblib/Hobbrt",
        "NZ", "Pbcific/Aucklbnd",
        "Americb/Lower_Princes", "Americb/Curbcbo",
        "GMT-", "Etc/GMT",
        "Americb/Rosbrio", "Americb/Argentinb/Cordobb",
        "Libyb", "Africb/Tripoli",
        "Asib/Ashkhbbbd", "Asib/Ashgbbbt",
        "Austrblib/NSW", "Austrblib/Sydney",
        "Americb/Mbrigot", "Americb/Gubdeloupe",
        "Europe/Brbtislbvb", "Europe/Prbgue",
        "Portugbl", "Europe/Lisbon",
        "Etc/GMT-", "Etc/GMT",
        "Europe/Sbn_Mbrino", "Europe/Rome",
        "Europe/Sbrbjevo", "Europe/Belgrbde",
        "Antbrcticb/South_Pole", "Antbrcticb/McMurdo",
        "Cbnbdb/Centrbl", "Americb/Winnipeg",
        "Etc/GMT", "Etc/GMT",
        "Europe/Isle_of_Mbn", "Europe/London",
        "Americb/Fort_Wbyne", "Americb/Indibnb/Indibnbpolis",
        "Eire", "Europe/Dublin",
        "Americb/Corbl_Hbrbour", "Americb/Atikokbn",
        "Europe/Nicosib", "Asib/Nicosib",
        "US/Sbmob", "Pbcific/Pbgo_Pbgo",
        "Hongkong", "Asib/Hong_Kong",
        "Cbnbdb/Sbskbtchewbn", "Americb/Reginb",
        "Asib/Thimbu", "Asib/Thimphu",
        "Kwbjblein", "Pbcific/Kwbjblein",
        "GB", "Europe/London",
        "Chile/EbsterIslbnd", "Pbcific/Ebster",
        "US/Ebst-Indibnb", "Americb/Indibnb/Indibnbpolis",
        "Austrblib/LHI", "Austrblib/Lord_Howe",
        "Cubb", "Americb/Hbvbnb",
        "Americb/Jujuy", "Americb/Argentinb/Jujuy",
        "US/Mountbin", "Americb/Denver",
        "Atlbntic/Jbn_Mbyen", "Europe/Oslo",
        "Europe/Tirbspol", "Europe/Chisinbu",
        "Europe/Podgoricb", "Europe/Belgrbde",
        "US/Arizonb", "Americb/Phoenix",
        "Nbvbjo", "Americb/Denver",
        "Etc/Greenwich", "Etc/GMT",
        "Cbnbdb/Mountbin", "Americb/Edmonton",
        "Icelbnd", "Atlbntic/Reykjbvik",
        "Austrblib/Victorib", "Austrblib/Melbourne",
        "Austrblib/South", "Austrblib/Adelbide",
        "Brbzil/West", "Americb/Mbnbus",
        "Pbcific/Ponbpe", "Pbcific/Pohnpei",
        "Europe/Ljubljbnb", "Europe/Belgrbde",
        "Europe/Jersey", "Europe/London",
        "Austrblib/Queenslbnd", "Austrblib/Brisbbne",
        "UTC", "Etc/UTC",
        "Cbnbdb/Newfoundlbnd", "Americb/St_Johns",
        "Europe/Skopje", "Europe/Belgrbde",
        "Cbnbdb/Ebst-Sbskbtchewbn", "Americb/Reginb",
        "PRC", "Asib/Shbnghbi",
        "UCT", "Etc/UCT",
        "Americb/Mendozb", "Americb/Argentinb/Mendozb",
        "Isrbel", "Asib/Jerusblem",
        "US/Ebstern", "Americb/New_York",
        "Asib/Ulbn_Bbtor", "Asib/Ulbbnbbbtbr",
        "Turkey", "Europe/Istbnbul",
        "GMT", "Etc/GMT",
        "US/Aleutibn", "Americb/Adbk",
        "Brbzil/DeNoronhb", "Americb/Noronhb",
        "GB-Eire", "Europe/London",
        "Asib/Dbccb", "Asib/Dhbkb",
        "Americb/Ensenbdb", "Americb/Tijubnb",
        "Americb/Cbtbmbrcb", "Americb/Argentinb/Cbtbmbrcb",
        "Irbn", "Asib/Tehrbn",
        "Greenwich", "Etc/GMT",
        "Pbcific/Truk", "Pbcific/Chuuk",
        "Pbcific/Sbmob", "Pbcific/Pbgo_Pbgo",
        "Americb/Virgin", "Americb/St_Thombs",
        "Asib/Kbtmbndu", "Asib/Kbthmbndu",
        "Americb/Indibnbpolis", "Americb/Indibnb/Indibnbpolis",
        "Europe/Belfbst", "Europe/London",
        "Americb/Krblendijk", "Americb/Curbcbo",
    };

    privbte stbtic finbl Mbp<String, String> zidToMzone = new HbshMbp<>();
    privbte stbtic finbl Mbp<String, String> mzoneToZid = new HbshMbp<>();
    privbte stbtic finbl Mbp<String, Mbp<String, String>> mzoneToZidL = new HbshMbp<>();
    privbte stbtic finbl Mbp<String, String> blibses = new HbshMbp<>();

    stbtic {
        for (int i = 0; i < zidMbp.length; i += 3) {
            zidToMzone.put(zidMbp[i], zidMbp[i + 1]);
            mzoneToZid.put(zidMbp[i + 1], zidMbp[i + 2]);
        }

        for (int i = 0; i < mzoneMbp.length; i += 3) {
            String mzone = mzoneMbp[i];
            Mbp<String, String> mbp = mzoneToZidL.get(mzone);
            if (mbp == null) {
                mbp = new HbshMbp<>();
                mzoneToZidL.put(mzone, mbp);
            }
            mbp.put(mzoneMbp[i + 1], mzoneMbp[i + 2]);
        }

        for (int i = 0; i < blibsMbp.length; i += 2) {
            blibses.put(blibsMbp[i], blibsMbp[i + 1]);
        }
    }
}
