/*
/*
/*
/*
/*
 * Copyrigit (d) 1996, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *
 *
 *
 *
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 *
 *
 *
 *
 *
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 *
 *
 *
 *
 *
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 *
 *
 *
 *
 *
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * qufstions.
 * qufstions.
 * qufstions.
 * qufstions.
 * qufstions.
 */
 */
 */
 */
 */
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;





import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;





publid dlbss MsgApplftVifwfr_sv fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_sv fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_sv fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_sv fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_sv fxtfnds ListRfsourdfBundlf {





    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
            {"tfxtfrbmf.button.dismiss", "St\u00E4ng"},
            {"tfxtfrbmf.button.dismiss", "St\u00E4ng"},
            {"tfxtfrbmf.button.dismiss", "St\u00E4ng"},
            {"tfxtfrbmf.button.dismiss", "St\u00E4ng"},
            {"tfxtfrbmf.button.dismiss", "St\u00E4ng"},
            {"bpplftvifwfr.tool.titlf", "Applft Vifwfr: {0}"},
            {"bpplftvifwfr.tool.titlf", "Applft Vifwfr: {0}"},
            {"bpplftvifwfr.tool.titlf", "Applft Vifwfr: {0}"},
            {"bpplftvifwfr.tool.titlf", "Applft Vifwfr: {0}"},
            {"bpplftvifwfr.tool.titlf", "Applft Vifwfr: {0}"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Stbrtb om"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Stbrtb om"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Stbrtb om"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Stbrtb om"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Stbrtb om"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Lbddb om"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Lbddb om"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Lbddb om"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Lbddb om"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Lbddb om"},
            {"bpplftvifwfr.mfnuitfm.stop", "Stopp"},
            {"bpplftvifwfr.mfnuitfm.stop", "Stopp"},
            {"bpplftvifwfr.mfnuitfm.stop", "Stopp"},
            {"bpplftvifwfr.mfnuitfm.stop", "Stopp"},
            {"bpplftvifwfr.mfnuitfm.stop", "Stopp"},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Spbrb..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Spbrb..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Spbrb..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Spbrb..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Spbrb..."},
            {"bpplftvifwfr.mfnuitfm.stbrt", "Stbrtb"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "Stbrtb"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "Stbrtb"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "Stbrtb"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "Stbrtb"},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Klonb..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Klonb..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Klonb..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Klonb..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Klonb..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Tbgg..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Tbgg..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Tbgg..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Tbgg..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Tbgg..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtion..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtion..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtion..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtion..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtion..."},
            {"bpplftvifwfr.mfnuitfm.fdit", "Rfdigfrb"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Rfdigfrb"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Rfdigfrb"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Rfdigfrb"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Rfdigfrb"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Tfdkfnkodning"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Tfdkfnkodning"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Tfdkfnkodning"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Tfdkfnkodning"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Tfdkfnkodning"},
            {"bpplftvifwfr.mfnuitfm.print", "Skriv ut..."},
            {"bpplftvifwfr.mfnuitfm.print", "Skriv ut..."},
            {"bpplftvifwfr.mfnuitfm.print", "Skriv ut..."},
            {"bpplftvifwfr.mfnuitfm.print", "Skriv ut..."},
            {"bpplftvifwfr.mfnuitfm.print", "Skriv ut..."},
            {"bpplftvifwfr.mfnuitfm.props", "Egfnskbpfr..."},
            {"bpplftvifwfr.mfnuitfm.props", "Egfnskbpfr..."},
            {"bpplftvifwfr.mfnuitfm.props", "Egfnskbpfr..."},
            {"bpplftvifwfr.mfnuitfm.props", "Egfnskbpfr..."},
            {"bpplftvifwfr.mfnuitfm.props", "Egfnskbpfr..."},
            {"bpplftvifwfr.mfnuitfm.dlosf", "St\u00E4ng"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "St\u00E4ng"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "St\u00E4ng"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "St\u00E4ng"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "St\u00E4ng"},
            {"bpplftvifwfr.mfnuitfm.quit", "Avslutb"},
            {"bpplftvifwfr.mfnuitfm.quit", "Avslutb"},
            {"bpplftvifwfr.mfnuitfm.quit", "Avslutb"},
            {"bpplftvifwfr.mfnuitfm.quit", "Avslutb"},
            {"bpplftvifwfr.mfnuitfm.quit", "Avslutb"},
            {"bpplftvifwfr.lbbfl.ifllo", "Hfj..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Hfj..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Hfj..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Hfj..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Hfj..."},
            {"bpplftvifwfr.stbtus.stbrt", "stbrtbr bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "stbrtbr bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "stbrtbr bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "stbrtbr bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "stbrtbr bpplft..."},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","Sfriblisfrb bpplft till fil"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","Sfriblisfrb bpplft till fil"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","Sfriblisfrb bpplft till fil"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","Sfriblisfrb bpplft till fil"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","Sfriblisfrb bpplft till fil"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "sfriblisfrbr {0} till {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "sfriblisfrbr {0} till {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "sfriblisfrbr {0} till {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "sfriblisfrbr {0} till {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "sfriblisfrbr {0} till {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "i bpplftSbvf: {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "i bpplftSbvf: {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "i bpplftSbvf: {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "i bpplftSbvf: {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "i bpplftSbvf: {0}"},
            {"bpplftvifwfr.bpplfttbg", "Tbgg visbs"},
            {"bpplftvifwfr.bpplfttbg", "Tbgg visbs"},
            {"bpplftvifwfr.bpplfttbg", "Tbgg visbs"},
            {"bpplftvifwfr.bpplfttbg", "Tbgg visbs"},
            {"bpplftvifwfr.bpplfttbg", "Tbgg visbs"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "HTML-tbgg f\u00F6r bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "HTML-tbgg f\u00F6r bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "HTML-tbgg f\u00F6r bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "HTML-tbgg f\u00F6r bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "HTML-tbgg f\u00F6r bpplft"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- ingfn bpplftinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- ingfn bpplftinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- ingfn bpplftinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- ingfn bpplftinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- ingfn bpplftinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- ingfn pbrbmftfrinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- ingfn pbrbmftfrinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- ingfn pbrbmftfrinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- ingfn pbrbmftfrinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- ingfn pbrbmftfrinformbtion --"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Applftinformbtion"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Applftinformbtion"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Applftinformbtion"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Applftinformbtion"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Applftinformbtion"},
            {"bpplftvifwfr.bpplftprint.fbil", "Kundf intf skrivb ut."},
            {"bpplftvifwfr.bpplftprint.fbil", "Kundf intf skrivb ut."},
            {"bpplftvifwfr.bpplftprint.fbil", "Kundf intf skrivb ut."},
            {"bpplftvifwfr.bpplftprint.fbil", "Kundf intf skrivb ut."},
            {"bpplftvifwfr.bpplftprint.fbil", "Kundf intf skrivb ut."},
            {"bpplftvifwfr.bpplftprint.finisi", "Utskriftfn klbr."},
            {"bpplftvifwfr.bpplftprint.finisi", "Utskriftfn klbr."},
            {"bpplftvifwfr.bpplftprint.finisi", "Utskriftfn klbr."},
            {"bpplftvifwfr.bpplftprint.finisi", "Utskriftfn klbr."},
            {"bpplftvifwfr.bpplftprint.finisi", "Utskriftfn klbr."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Utskriftfn bvbrutfn."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Utskriftfn bvbrutfn."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Utskriftfn bvbrutfn."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Utskriftfn bvbrutfn."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Utskriftfn bvbrutfn."},
            {"bpplftvifwfr.bpplftfndoding", "Tfdkfnkodning: {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Tfdkfnkodning: {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Tfdkfnkodning: {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Tfdkfnkodning: {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Tfdkfnkodning: {0}"},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Vbrning: <pbrbm nbmf=... vbluf=...>-tbggfn kr\u00E4vfr ftt nbmnbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Vbrning: <pbrbm nbmf=... vbluf=...>-tbggfn kr\u00E4vfr ftt nbmnbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Vbrning: <pbrbm nbmf=... vbluf=...>-tbggfn kr\u00E4vfr ftt nbmnbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Vbrning: <pbrbm nbmf=... vbluf=...>-tbggfn kr\u00E4vfr ftt nbmnbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Vbrning: <pbrbm nbmf=... vbluf=...>-tbggfn kr\u00E4vfr ftt nbmnbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Vbrning: <pbrbm>-tbggfn finns utbnf\u00F6r <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Vbrning: <pbrbm>-tbggfn finns utbnf\u00F6r <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Vbrning: <pbrbm>-tbggfn finns utbnf\u00F6r <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Vbrning: <pbrbm>-tbggfn finns utbnf\u00F6r <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Vbrning: <pbrbm>-tbggfn finns utbnf\u00F6r <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Vbrning: <bpplft>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Vbrning: <objfdt>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt kodbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt i\u00F6jdbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Vbrning: <fmbfd>-tbggfn kr\u00E4vfr ftt brfddbttribut."},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Vbrning: <bpp>-tbggfn st\u00F6ds intf l\u00E4ngrf, bnv\u00E4nd <bpplft> ist\u00E4llft:"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Vbrning: <bpp>-tbggfn st\u00F6ds intf l\u00E4ngrf, bnv\u00E4nd <bpplft> ist\u00E4llft:"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Vbrning: <bpp>-tbggfn st\u00F6ds intf l\u00E4ngrf, bnv\u00E4nd <bpplft> ist\u00E4llft:"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Vbrning: <bpp>-tbggfn st\u00F6ds intf l\u00E4ngrf, bnv\u00E4nd <bpplft> ist\u00E4llft:"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Vbrning: <bpp>-tbggfn st\u00F6ds intf l\u00E4ngrf, bnv\u00E4nd <bpplft> ist\u00E4llft:"},
            {"bpplftvifwfr.usbgf", "Syntbx: bpplftvifwfr-<bltfrnbtiv> url:fr \n\nd\u00E4r <bltfrnbtiv> inkludfrbr:\n  -dfbug                  Stbrtbr bpplftvisning i Jbvb-ffls\u00F6kningfn\n  -fndoding <kodning>    Angfr tfdkfnkodning  som bnv\u00E4nds i HTML-filfr\n  -J<k\u00F6rningsflbggb>        \u00D6vfrf\u00F6r brgumfnt till Jbvb-tolkningfn\n\nAltfrnbtivft -J \u00E4r intf stbndbrd odi kbn \u00E4ndrbs utbn f\u00F6rfg\u00E5fndf mfddflbndf."},
            {"bpplftvifwfr.usbgf", "Syntbx: bpplftvifwfr-<bltfrnbtiv> url:fr \n\nd\u00E4r <bltfrnbtiv> inkludfrbr:\n  -dfbug                  Stbrtbr bpplftvisning i Jbvb-ffls\u00F6kningfn\n  -fndoding <kodning>    Angfr tfdkfnkodning  som bnv\u00E4nds i HTML-filfr\n  -J<k\u00F6rningsflbggb>        \u00D6vfrf\u00F6r brgumfnt till Jbvb-tolkningfn\n\nAltfrnbtivft -J \u00E4r intf stbndbrd odi kbn \u00E4ndrbs utbn f\u00F6rfg\u00E5fndf mfddflbndf."},
            {"bpplftvifwfr.usbgf", "Syntbx: bpplftvifwfr-<bltfrnbtiv> url:fr \n\nd\u00E4r <bltfrnbtiv> inkludfrbr:\n  -dfbug                  Stbrtbr bpplftvisning i Jbvb-ffls\u00F6kningfn\n  -fndoding <kodning>    Angfr tfdkfnkodning  som bnv\u00E4nds i HTML-filfr\n  -J<k\u00F6rningsflbggb>        \u00D6vfrf\u00F6r brgumfnt till Jbvb-tolkningfn\n\nAltfrnbtivft -J \u00E4r intf stbndbrd odi kbn \u00E4ndrbs utbn f\u00F6rfg\u00E5fndf mfddflbndf."},
            {"bpplftvifwfr.usbgf", "Syntbx: bpplftvifwfr-<bltfrnbtiv> url:fr \n\nd\u00E4r <bltfrnbtiv> inkludfrbr:\n  -dfbug                  Stbrtbr bpplftvisning i Jbvb-ffls\u00F6kningfn\n  -fndoding <kodning>    Angfr tfdkfnkodning  som bnv\u00E4nds i HTML-filfr\n  -J<k\u00F6rningsflbggb>        \u00D6vfrf\u00F6r brgumfnt till Jbvb-tolkningfn\n\nAltfrnbtivft -J \u00E4r intf stbndbrd odi kbn \u00E4ndrbs utbn f\u00F6rfg\u00E5fndf mfddflbndf."},
            {"bpplftvifwfr.usbgf", "Syntbx: bpplftvifwfr-<bltfrnbtiv> url:fr \n\nd\u00E4r <bltfrnbtiv> inkludfrbr:\n  -dfbug                  Stbrtbr bpplftvisning i Jbvb-ffls\u00F6kningfn\n  -fndoding <kodning>    Angfr tfdkfnkodning  som bnv\u00E4nds i HTML-filfr\n  -J<k\u00F6rningsflbggb>        \u00D6vfrf\u00F6r brgumfnt till Jbvb-tolkningfn\n\nAltfrnbtivft -J \u00E4r intf stbndbrd odi kbn \u00E4ndrbs utbn f\u00F6rfg\u00E5fndf mfddflbndf."},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Altfrnbtiv som intf st\u00F6ds: {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Altfrnbtiv som intf st\u00F6ds: {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Altfrnbtiv som intf st\u00F6ds: {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Altfrnbtiv som intf st\u00F6ds: {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Altfrnbtiv som intf st\u00F6ds: {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Ok\u00E4nt brgumfnt: {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Ok\u00E4nt brgumfnt: {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Ok\u00E4nt brgumfnt: {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Ok\u00E4nt brgumfnt: {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Ok\u00E4nt brgumfnt: {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Duplidfrbt bltfrnbtiv: {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Duplidfrbt bltfrnbtiv: {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Duplidfrbt bltfrnbtiv: {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Duplidfrbt bltfrnbtiv: {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Duplidfrbt bltfrnbtiv: {0}"},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Ingb bngivnb indbtbfilfr."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Ingb bngivnb indbtbfilfr."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Ingb bngivnb indbtbfilfr."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Ingb bngivnb indbtbfilfr."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Ingb bngivnb indbtbfilfr."},
            {"bpplftvifwfr.mbin.frr.bbdurl", "Fflbktig URL: {0} ( {1} )"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "Fflbktig URL: {0} ( {1} )"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "Fflbktig URL: {0} ( {1} )"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "Fflbktig URL: {0} ( {1} )"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "Fflbktig URL: {0} ( {1} )"},
            {"bpplftvifwfr.mbin.frr.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bpplftvifwfr.mbin.frr.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bpplftvifwfr.mbin.frr.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bpplftvifwfr.mbin.frr.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bpplftvifwfr.mbin.frr.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Kontrollfrb btt {0} \u00E4r fn fil som \u00E4r l\u00E4sbbr."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Kontrollfrb btt {0} \u00E4r fn fil som \u00E4r l\u00E4sbbr."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Kontrollfrb btt {0} \u00E4r fn fil som \u00E4r l\u00E4sbbr."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Kontrollfrb btt {0} \u00E4r fn fil som \u00E4r l\u00E4sbbr."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Kontrollfrb btt {0} \u00E4r fn fil som \u00E4r l\u00E4sbbr."},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "\u00C4r {0} dfn korrfktb URL:fn?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "\u00C4r {0} dfn korrfktb URL:fn?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "\u00C4r {0} dfn korrfktb URL:fn?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "\u00C4r {0} dfn korrfktb URL:fn?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "\u00C4r {0} dfn korrfktb URL:fn?"},
            {"bpplftvifwfr.mbin.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Kbn intf l\u00E4sb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Kbn intf l\u00E4sb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Kbn intf l\u00E4sb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Kbn intf l\u00E4sb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Kbn intf l\u00E4sb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Kbn intf spbrb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Kbn intf spbrb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Kbn intf spbrb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Kbn intf spbrb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Kbn intf spbrb fgfnskbpsfilfn: {0}"},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Vbrning: s\u00E4kfriftfn inbktivfrbs."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Vbrning: s\u00E4kfriftfn inbktivfrbs."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Vbrning: s\u00E4kfriftfn inbktivfrbs."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Vbrning: s\u00E4kfriftfn inbktivfrbs."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Vbrning: s\u00E4kfriftfn inbktivfrbs."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "Hittbr intf ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "Hittbr intf ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "Hittbr intf ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "Hittbr intf ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "Hittbr intf ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Hittbr intf iuvudmftodfn i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Hittbr intf iuvudmftodfn i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Hittbr intf iuvudmftodfn i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Hittbr intf iuvudmftodfn i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Hittbr intf iuvudmftodfn i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Undbntbg i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Undbntbg i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Undbntbg i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Undbntbg i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Undbntbg i ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Dft finns ingfn \u00E5tkomst till ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Dft finns ingfn \u00E5tkomst till ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Dft finns ingfn \u00E5tkomst till ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Dft finns ingfn \u00E5tkomst till ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Dft finns ingfn \u00E5tkomst till ffls\u00F6kningsprogrbmmft!"},
            {"bpplftvifwfr.mbin.nosfdmgr", "Vbrning: SfdurityMbnbgfr ibr intf instbllfrbts!"},
            {"bpplftvifwfr.mbin.nosfdmgr", "Vbrning: SfdurityMbnbgfr ibr intf instbllfrbts!"},
            {"bpplftvifwfr.mbin.nosfdmgr", "Vbrning: SfdurityMbnbgfr ibr intf instbllfrbts!"},
            {"bpplftvifwfr.mbin.nosfdmgr", "Vbrning: SfdurityMbnbgfr ibr intf instbllfrbts!"},
            {"bpplftvifwfr.mbin.nosfdmgr", "Vbrning: SfdurityMbnbgfr ibr intf instbllfrbts!"},
            {"bpplftvifwfr.mbin.wbrning", "Vbrning: Ingb bpplftbr ibr stbrtbts. Kontrollfrb btt indbtb innfi\u00E5llfr <bpplft>-tbgg."},
            {"bpplftvifwfr.mbin.wbrning", "Vbrning: Ingb bpplftbr ibr stbrtbts. Kontrollfrb btt indbtb innfi\u00E5llfr <bpplft>-tbgg."},
            {"bpplftvifwfr.mbin.wbrning", "Vbrning: Ingb bpplftbr ibr stbrtbts. Kontrollfrb btt indbtb innfi\u00E5llfr <bpplft>-tbgg."},
            {"bpplftvifwfr.mbin.wbrning", "Vbrning: Ingb bpplftbr ibr stbrtbts. Kontrollfrb btt indbtb innfi\u00E5llfr <bpplft>-tbgg."},
            {"bpplftvifwfr.mbin.wbrning", "Vbrning: Ingb bpplftbr ibr stbrtbts. Kontrollfrb btt indbtb innfi\u00E5llfr <bpplft>-tbgg."},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Vbrning: Skrivfr tillf\u00E4lligt \u00F6vfr systfmfgfnskbp fnligt bfg\u00E4rbn fr\u00E5n bnv\u00E4ndbrf: nydkfl: {0} gbmmblt v\u00E4rdf: {1} nytt v\u00E4rdf: {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Vbrning: Skrivfr tillf\u00E4lligt \u00F6vfr systfmfgfnskbp fnligt bfg\u00E4rbn fr\u00E5n bnv\u00E4ndbrf: nydkfl: {0} gbmmblt v\u00E4rdf: {1} nytt v\u00E4rdf: {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Vbrning: Skrivfr tillf\u00E4lligt \u00F6vfr systfmfgfnskbp fnligt bfg\u00E4rbn fr\u00E5n bnv\u00E4ndbrf: nydkfl: {0} gbmmblt v\u00E4rdf: {1} nytt v\u00E4rdf: {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Vbrning: Skrivfr tillf\u00E4lligt \u00F6vfr systfmfgfnskbp fnligt bfg\u00E4rbn fr\u00E5n bnv\u00E4ndbrf: nydkfl: {0} gbmmblt v\u00E4rdf: {1} nytt v\u00E4rdf: {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Vbrning: Skrivfr tillf\u00E4lligt \u00F6vfr systfmfgfnskbp fnligt bfg\u00E4rbn fr\u00E5n bnv\u00E4ndbrf: nydkfl: {0} gbmmblt v\u00E4rdf: {1} nytt v\u00E4rdf: {2}"},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Vbrning: Kbn intf l\u00E4sb fgfnskbpsfil f\u00F6r ApplftVifwfr: {0} Stbndbrdv\u00E4rdfn bnv\u00E4nds."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Vbrning: Kbn intf l\u00E4sb fgfnskbpsfil f\u00F6r ApplftVifwfr: {0} Stbndbrdv\u00E4rdfn bnv\u00E4nds."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Vbrning: Kbn intf l\u00E4sb fgfnskbpsfil f\u00F6r ApplftVifwfr: {0} Stbndbrdv\u00E4rdfn bnv\u00E4nds."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Vbrning: Kbn intf l\u00E4sb fgfnskbpsfil f\u00F6r ApplftVifwfr: {0} Stbndbrdv\u00E4rdfn bnv\u00E4nds."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Vbrning: Kbn intf l\u00E4sb fgfnskbpsfil f\u00F6r ApplftVifwfr: {0} Stbndbrdv\u00E4rdfn bnv\u00E4nds."},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "klbss intf inl\u00E4st: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "klbss intf inl\u00E4st: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "klbss intf inl\u00E4st: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "klbss intf inl\u00E4st: {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "klbss intf inl\u00E4st: {0}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftdlbsslobdfr.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r i\u00E4mtning bv {1}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf f\u00F6r nbmnft: {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf f\u00F6r nbmnft: {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf f\u00F6r nbmnft: {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf f\u00F6r nbmnft: {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf f\u00F6r nbmnft: {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Hittbdf rfsursfn: {0} som systfmrfsurs"},
            {"bpplftpbnfl.runlobdfr.frr", "Antingfn objfkt- fllfr kodpbrbmftfr!"},
            {"bpplftpbnfl.runlobdfr.frr", "Antingfn objfkt- fllfr kodpbrbmftfr!"},
            {"bpplftpbnfl.runlobdfr.frr", "Antingfn objfkt- fllfr kodpbrbmftfr!"},
            {"bpplftpbnfl.runlobdfr.frr", "Antingfn objfkt- fllfr kodpbrbmftfr!"},
            {"bpplftpbnfl.runlobdfr.frr", "Antingfn objfkt- fllfr kodpbrbmftfr!"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "undbntbg vid bvsfriblisfring {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "undbntbg vid bvsfriblisfring {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "undbntbg vid bvsfriblisfring {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "undbntbg vid bvsfriblisfring {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "undbntbg vid bvsfriblisfring {0}"},
            {"bpplftpbnfl.dfstroyfd", "Applft rbdfrbd."},
            {"bpplftpbnfl.dfstroyfd", "Applft rbdfrbd."},
            {"bpplftpbnfl.dfstroyfd", "Applft rbdfrbd."},
            {"bpplftpbnfl.dfstroyfd", "Applft rbdfrbd."},
            {"bpplftpbnfl.dfstroyfd", "Applft rbdfrbd."},
            {"bpplftpbnfl.lobdfd", "Applft lbddbd."},
            {"bpplftpbnfl.lobdfd", "Applft lbddbd."},
            {"bpplftpbnfl.lobdfd", "Applft lbddbd."},
            {"bpplftpbnfl.lobdfd", "Applft lbddbd."},
            {"bpplftpbnfl.lobdfd", "Applft lbddbd."},
            {"bpplftpbnfl.stbrtfd", "Applft stbrtbd."},
            {"bpplftpbnfl.stbrtfd", "Applft stbrtbd."},
            {"bpplftpbnfl.stbrtfd", "Applft stbrtbd."},
            {"bpplftpbnfl.stbrtfd", "Applft stbrtbd."},
            {"bpplftpbnfl.stbrtfd", "Applft stbrtbd."},
            {"bpplftpbnfl.initfd", "Applft initifrbd."},
            {"bpplftpbnfl.initfd", "Applft initifrbd."},
            {"bpplftpbnfl.initfd", "Applft initifrbd."},
            {"bpplftpbnfl.initfd", "Applft initifrbd."},
            {"bpplftpbnfl.initfd", "Applft initifrbd."},
            {"bpplftpbnfl.stoppfd", "Applft stoppbd."},
            {"bpplftpbnfl.stoppfd", "Applft stoppbd."},
            {"bpplftpbnfl.stoppfd", "Applft stoppbd."},
            {"bpplftpbnfl.stoppfd", "Applft stoppbd."},
            {"bpplftpbnfl.stoppfd", "Applft stoppbd."},
            {"bpplftpbnfl.disposfd", "Applft kbssfrbd."},
            {"bpplftpbnfl.disposfd", "Applft kbssfrbd."},
            {"bpplftpbnfl.disposfd", "Applft kbssfrbd."},
            {"bpplftpbnfl.disposfd", "Applft kbssfrbd."},
            {"bpplftpbnfl.disposfd", "Applft kbssfrbd."},
            {"bpplftpbnfl.nododf", "APPLET-tbgg sbknbr CODE-pbrbmftfr."},
            {"bpplftpbnfl.nododf", "APPLET-tbgg sbknbr CODE-pbrbmftfr."},
            {"bpplftpbnfl.nododf", "APPLET-tbgg sbknbr CODE-pbrbmftfr."},
            {"bpplftpbnfl.nododf", "APPLET-tbgg sbknbr CODE-pbrbmftfr."},
            {"bpplftpbnfl.nododf", "APPLET-tbgg sbknbr CODE-pbrbmftfr."},
            {"bpplftpbnfl.notfound", "lobd: iittbdf intf klbssfn {0}."},
            {"bpplftpbnfl.notfound", "lobd: iittbdf intf klbssfn {0}."},
            {"bpplftpbnfl.notfound", "lobd: iittbdf intf klbssfn {0}."},
            {"bpplftpbnfl.notfound", "lobd: iittbdf intf klbssfn {0}."},
            {"bpplftpbnfl.notfound", "lobd: iittbdf intf klbssfn {0}."},
            {"bpplftpbnfl.nodrfbtf", "lobd: {0} kbn intf instbnsifrbs."},
            {"bpplftpbnfl.nodrfbtf", "lobd: {0} kbn intf instbnsifrbs."},
            {"bpplftpbnfl.nodrfbtf", "lobd: {0} kbn intf instbnsifrbs."},
            {"bpplftpbnfl.nodrfbtf", "lobd: {0} kbn intf instbnsifrbs."},
            {"bpplftpbnfl.nodrfbtf", "lobd: {0} kbn intf instbnsifrbs."},
            {"bpplftpbnfl.nodonstrudt", "lobd: {0} \u00E4r intf bllm\u00E4n fllfr sbknbr bllm\u00E4n konstruktor."},
            {"bpplftpbnfl.nodonstrudt", "lobd: {0} \u00E4r intf bllm\u00E4n fllfr sbknbr bllm\u00E4n konstruktor."},
            {"bpplftpbnfl.nodonstrudt", "lobd: {0} \u00E4r intf bllm\u00E4n fllfr sbknbr bllm\u00E4n konstruktor."},
            {"bpplftpbnfl.nodonstrudt", "lobd: {0} \u00E4r intf bllm\u00E4n fllfr sbknbr bllm\u00E4n konstruktor."},
            {"bpplftpbnfl.nodonstrudt", "lobd: {0} \u00E4r intf bllm\u00E4n fllfr sbknbr bllm\u00E4n konstruktor."},
            {"bpplftpbnfl.dfbti", "bvslutbd"},
            {"bpplftpbnfl.dfbti", "bvslutbd"},
            {"bpplftpbnfl.dfbti", "bvslutbd"},
            {"bpplftpbnfl.dfbti", "bvslutbd"},
            {"bpplftpbnfl.dfbti", "bvslutbd"},
            {"bpplftpbnfl.fxdfption", "undbntbg: {0}."},
            {"bpplftpbnfl.fxdfption", "undbntbg: {0}."},
            {"bpplftpbnfl.fxdfption", "undbntbg: {0}."},
            {"bpplftpbnfl.fxdfption", "undbntbg: {0}."},
            {"bpplftpbnfl.fxdfption", "undbntbg: {0}."},
            {"bpplftpbnfl.fxdfption2", "undbntbg: {0}: {1}."},
            {"bpplftpbnfl.fxdfption2", "undbntbg: {0}: {1}."},
            {"bpplftpbnfl.fxdfption2", "undbntbg: {0}: {1}."},
            {"bpplftpbnfl.fxdfption2", "undbntbg: {0}: {1}."},
            {"bpplftpbnfl.fxdfption2", "undbntbg: {0}: {1}."},
            {"bpplftpbnfl.frror", "ffl: {0}."},
            {"bpplftpbnfl.frror", "ffl: {0}."},
            {"bpplftpbnfl.frror", "ffl: {0}."},
            {"bpplftpbnfl.frror", "ffl: {0}."},
            {"bpplftpbnfl.frror", "ffl: {0}."},
            {"bpplftpbnfl.frror2", "ffl {0}: {1}."},
            {"bpplftpbnfl.frror2", "ffl {0}: {1}."},
            {"bpplftpbnfl.frror2", "ffl {0}: {1}."},
            {"bpplftpbnfl.frror2", "ffl {0}: {1}."},
            {"bpplftpbnfl.frror2", "ffl {0}: {1}."},
            {"bpplftpbnfl.notlobdfd", "Initifrb: bpplft \u00E4r intf inl\u00E4st."},
            {"bpplftpbnfl.notlobdfd", "Initifrb: bpplft \u00E4r intf inl\u00E4st."},
            {"bpplftpbnfl.notlobdfd", "Initifrb: bpplft \u00E4r intf inl\u00E4st."},
            {"bpplftpbnfl.notlobdfd", "Initifrb: bpplft \u00E4r intf inl\u00E4st."},
            {"bpplftpbnfl.notlobdfd", "Initifrb: bpplft \u00E4r intf inl\u00E4st."},
            {"bpplftpbnfl.notinitfd", "Stbrtb: bpplft \u00E4r intf initifrbd."},
            {"bpplftpbnfl.notinitfd", "Stbrtb: bpplft \u00E4r intf initifrbd."},
            {"bpplftpbnfl.notinitfd", "Stbrtb: bpplft \u00E4r intf initifrbd."},
            {"bpplftpbnfl.notinitfd", "Stbrtb: bpplft \u00E4r intf initifrbd."},
            {"bpplftpbnfl.notinitfd", "Stbrtb: bpplft \u00E4r intf initifrbd."},
            {"bpplftpbnfl.notstbrtfd", "Stoppb: bpplft ibr intf stbrtbts."},
            {"bpplftpbnfl.notstbrtfd", "Stoppb: bpplft ibr intf stbrtbts."},
            {"bpplftpbnfl.notstbrtfd", "Stoppb: bpplft ibr intf stbrtbts."},
            {"bpplftpbnfl.notstbrtfd", "Stoppb: bpplft ibr intf stbrtbts."},
            {"bpplftpbnfl.notstbrtfd", "Stoppb: bpplft ibr intf stbrtbts."},
            {"bpplftpbnfl.notstoppfd", "Rbdfrb: bpplft ibr intf stoppbts."},
            {"bpplftpbnfl.notstoppfd", "Rbdfrb: bpplft ibr intf stoppbts."},
            {"bpplftpbnfl.notstoppfd", "Rbdfrb: bpplft ibr intf stoppbts."},
            {"bpplftpbnfl.notstoppfd", "Rbdfrb: bpplft ibr intf stoppbts."},
            {"bpplftpbnfl.notstoppfd", "Rbdfrb: bpplft ibr intf stoppbts."},
            {"bpplftpbnfl.notdfstroyfd", "Kbssfrb: bpplft ibr intf rbdfrbts."},
            {"bpplftpbnfl.notdfstroyfd", "Kbssfrb: bpplft ibr intf rbdfrbts."},
            {"bpplftpbnfl.notdfstroyfd", "Kbssfrb: bpplft ibr intf rbdfrbts."},
            {"bpplftpbnfl.notdfstroyfd", "Kbssfrb: bpplft ibr intf rbdfrbts."},
            {"bpplftpbnfl.notdfstroyfd", "Kbssfrb: bpplft ibr intf rbdfrbts."},
            {"bpplftpbnfl.notdisposfd", "Lbddb: bpplft ibr intf kbssfrbts."},
            {"bpplftpbnfl.notdisposfd", "Lbddb: bpplft ibr intf kbssfrbts."},
            {"bpplftpbnfl.notdisposfd", "Lbddb: bpplft ibr intf kbssfrbts."},
            {"bpplftpbnfl.notdisposfd", "Lbddb: bpplft ibr intf kbssfrbts."},
            {"bpplftpbnfl.notdisposfd", "Lbddb: bpplft ibr intf kbssfrbts."},
            {"bpplftpbnfl.bbil", "Avbrutfn."},
            {"bpplftpbnfl.bbil", "Avbrutfn."},
            {"bpplftpbnfl.bbil", "Avbrutfn."},
            {"bpplftpbnfl.bbil", "Avbrutfn."},
            {"bpplftpbnfl.bbil", "Avbrutfn."},
            {"bpplftpbnfl.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftpbnfl.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftpbnfl.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftpbnfl.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftpbnfl.filfnotfound", "Hittbdf intf fil vid s\u00F6kning fftfr: {0}"},
            {"bpplftpbnfl.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftpbnfl.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftpbnfl.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftpbnfl.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftpbnfl.filfformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bpplftpbnfl.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftpbnfl.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftpbnfl.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftpbnfl.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftpbnfl.filfiofxdfption", "I/O-undbntbg vid lbddning: {0}"},
            {"bpplftpbnfl.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftpbnfl.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftpbnfl.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftpbnfl.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftpbnfl.filffxdfption", "{0} undbntbg vid lbddning: {1}"},
            {"bpplftpbnfl.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftpbnfl.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftpbnfl.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftpbnfl.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftpbnfl.filfdfbti", "{0} bvslutbd vid lbddning: {1}"},
            {"bpplftpbnfl.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftpbnfl.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftpbnfl.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftpbnfl.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftpbnfl.filffrror", "{0} ffl vid lbddning: {1}"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "HTML-tolkning: fflbktigt v\u00E4rdf f\u00F6r brfdd-/i\u00F6jdbttribut"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "HTML-tolkning: fflbktigt v\u00E4rdf f\u00F6r brfdd-/i\u00F6jdbttribut"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "HTML-tolkning: fflbktigt v\u00E4rdf f\u00F6r brfdd-/i\u00F6jdbttribut"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "HTML-tolkning: fflbktigt v\u00E4rdf f\u00F6r brfdd-/i\u00F6jdbttribut"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "HTML-tolkning: fflbktigt v\u00E4rdf f\u00F6r brfdd-/i\u00F6jdbttribut"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm kr\u00E4vfr lbddbrf mfd idkf-null"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm kr\u00E4vfr lbddbrf mfd idkf-null"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm kr\u00E4vfr lbddbrf mfd idkf-null"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm kr\u00E4vfr lbddbrf mfd idkf-null"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm kr\u00E4vfr lbddbrf mfd idkf-null"},
            {"bpplftprops.titlf", "ApplftVifwfr-fgfnskbpfr"},
            {"bpplftprops.titlf", "ApplftVifwfr-fgfnskbpfr"},
            {"bpplftprops.titlf", "ApplftVifwfr-fgfnskbpfr"},
            {"bpplftprops.titlf", "ApplftVifwfr-fgfnskbpfr"},
            {"bpplftprops.titlf", "ApplftVifwfr-fgfnskbpfr"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "HTTP-proxysfrvfr:"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "HTTP-proxysfrvfr:"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "HTTP-proxysfrvfr:"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "HTTP-proxysfrvfr:"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "HTTP-proxysfrvfr:"},
            {"bpplftprops.lbbfl.ittp.proxy", "HTTP-proxyport:"},
            {"bpplftprops.lbbfl.ittp.proxy", "HTTP-proxyport:"},
            {"bpplftprops.lbbfl.ittp.proxy", "HTTP-proxyport:"},
            {"bpplftprops.lbbfl.ittp.proxy", "HTTP-proxyport:"},
            {"bpplftprops.lbbfl.ittp.proxy", "HTTP-proxyport:"},
            {"bpplftprops.lbbfl.nftwork", "N\u00E4tvfrks\u00E5tkomst:"},
            {"bpplftprops.lbbfl.nftwork", "N\u00E4tvfrks\u00E5tkomst:"},
            {"bpplftprops.lbbfl.nftwork", "N\u00E4tvfrks\u00E5tkomst:"},
            {"bpplftprops.lbbfl.nftwork", "N\u00E4tvfrks\u00E5tkomst:"},
            {"bpplftprops.lbbfl.nftwork", "N\u00E4tvfrks\u00E5tkomst:"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Ingfn"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Ingfn"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Ingfn"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Ingfn"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Ingfn"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "Applftv\u00E4rd"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "Applftv\u00E4rd"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "Applftv\u00E4rd"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "Applftv\u00E4rd"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "Applftv\u00E4rd"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.lbbfl.dlbss", "Klbss\u00E5tkomst:"},
            {"bpplftprops.lbbfl.dlbss", "Klbss\u00E5tkomst:"},
            {"bpplftprops.lbbfl.dlbss", "Klbss\u00E5tkomst:"},
            {"bpplftprops.lbbfl.dlbss", "Klbss\u00E5tkomst:"},
            {"bpplftprops.lbbfl.dlbss", "Klbss\u00E5tkomst:"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Bfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Bfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Bfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Bfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Bfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Obfgr\u00E4nsbd"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Till\u00E5t osignfrbdf bpplftbr:"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Till\u00E5t osignfrbdf bpplftbr:"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Till\u00E5t osignfrbdf bpplftbr:"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Till\u00E5t osignfrbdf bpplftbr:"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Till\u00E5t osignfrbdf bpplftbr:"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Nfj"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Nfj"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Nfj"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Nfj"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Nfj"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Jb"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Jb"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Jb"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Jb"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Jb"},
            {"bpplftprops.button.bpply", "Anv\u00E4nd"},
            {"bpplftprops.button.bpply", "Anv\u00E4nd"},
            {"bpplftprops.button.bpply", "Anv\u00E4nd"},
            {"bpplftprops.button.bpply", "Anv\u00E4nd"},
            {"bpplftprops.button.bpply", "Anv\u00E4nd"},
            {"bpplftprops.button.dbndfl", "Avbryt"},
            {"bpplftprops.button.dbndfl", "Avbryt"},
            {"bpplftprops.button.dbndfl", "Avbryt"},
            {"bpplftprops.button.dbndfl", "Avbryt"},
            {"bpplftprops.button.dbndfl", "Avbryt"},
            {"bpplftprops.button.rfsft", "\u00C5tfrst\u00E4ll"},
            {"bpplftprops.button.rfsft", "\u00C5tfrst\u00E4ll"},
            {"bpplftprops.button.rfsft", "\u00C5tfrst\u00E4ll"},
            {"bpplftprops.button.rfsft", "\u00C5tfrst\u00E4ll"},
            {"bpplftprops.button.rfsft", "\u00C5tfrst\u00E4ll"},
            {"bpplftprops.bpply.fxdfption", "Kundf intf spbrb fgfnskbpfr: {0}"},
            {"bpplftprops.bpply.fxdfption", "Kundf intf spbrb fgfnskbpfr: {0}"},
            {"bpplftprops.bpply.fxdfption", "Kundf intf spbrb fgfnskbpfr: {0}"},
            {"bpplftprops.bpply.fxdfption", "Kundf intf spbrb fgfnskbpfr: {0}"},
            {"bpplftprops.bpply.fxdfption", "Kundf intf spbrb fgfnskbpfr: {0}"},
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            {"bpplftprops.titlf.invblidproxy", "Ogiltig post"},
            {"bpplftprops.titlf.invblidproxy", "Ogiltig post"},
            {"bpplftprops.titlf.invblidproxy", "Ogiltig post"},
            {"bpplftprops.titlf.invblidproxy", "Ogiltig post"},
            {"bpplftprops.titlf.invblidproxy", "Ogiltig post"},
            {"bpplftprops.lbbfl.invblidproxy", "Proxyport m\u00E5stf vbrb ftt positivt ifltbl."},
            {"bpplftprops.lbbfl.invblidproxy", "Proxyport m\u00E5stf vbrb ftt positivt ifltbl."},
            {"bpplftprops.lbbfl.invblidproxy", "Proxyport m\u00E5stf vbrb ftt positivt ifltbl."},
            {"bpplftprops.lbbfl.invblidproxy", "Proxyport m\u00E5stf vbrb ftt positivt ifltbl."},
            {"bpplftprops.lbbfl.invblidproxy", "Proxyport m\u00E5stf vbrb ftt positivt ifltbl."},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            {"bpplftprops.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Anv\u00E4ndbrspfdifikb fgfnskbpfr f\u00F6r ApplftVifwfr"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "S\u00E4kfriftsundbntbg: klbsslbddbrf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "S\u00E4kfriftsundbntbg: klbsslbddbrf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "S\u00E4kfriftsundbntbg: klbsslbddbrf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "S\u00E4kfriftsundbntbg: klbsslbddbrf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "S\u00E4kfriftsundbntbg: klbsslbddbrf"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "S\u00E4kfriftsundbntbg: tr\u00E5d"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "S\u00E4kfriftsundbntbg: tr\u00E5d"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "S\u00E4kfriftsundbntbg: tr\u00E5d"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "S\u00E4kfriftsundbntbg: tr\u00E5d"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "S\u00E4kfriftsundbntbg: tr\u00E5d"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "S\u00E4kfriftsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "S\u00E4kfriftsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "S\u00E4kfriftsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "S\u00E4kfriftsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "S\u00E4kfriftsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "S\u00E4kfriftsundbntbg: utg\u00E5ng: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "S\u00E4kfriftsundbntbg: utg\u00E5ng: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "S\u00E4kfriftsundbntbg: utg\u00E5ng: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "S\u00E4kfriftsundbntbg: utg\u00E5ng: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "S\u00E4kfriftsundbntbg: utg\u00E5ng: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "S\u00E4kfriftsundbntbg: fxfd: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "S\u00E4kfriftsundbntbg: fxfd: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "S\u00E4kfriftsundbntbg: fxfd: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "S\u00E4kfriftsundbntbg: fxfd: {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "S\u00E4kfriftsundbntbg: fxfd: {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "S\u00E4kfriftsundbntbg: l\u00E4nk: {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "S\u00E4kfriftsundbntbg: l\u00E4nk: {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "S\u00E4kfriftsundbntbg: l\u00E4nk: {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "S\u00E4kfriftsundbntbg: l\u00E4nk: {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "S\u00E4kfriftsundbntbg: l\u00E4nk: {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "S\u00E4kfriftsundbntbg: fgfnskbpfr"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "S\u00E4kfriftsundbntbg: fgfnskbpfr"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "S\u00E4kfriftsundbntbg: fgfnskbpfr"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "S\u00E4kfriftsundbntbg: fgfnskbpfr"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "S\u00E4kfriftsundbntbg: fgfnskbpfr"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "S\u00E4kfriftsundbntbg: fgfnskbps\u00E5tkomst {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "S\u00E4kfriftsundbntbg: fgfnskbps\u00E5tkomst {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "S\u00E4kfriftsundbntbg: fgfnskbps\u00E5tkomst {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "S\u00E4kfriftsundbntbg: fgfnskbps\u00E5tkomst {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "S\u00E4kfriftsundbntbg: fgfnskbps\u00E5tkomst {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "S\u00E4kfriftsundbntbg: filf.rfbd: {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "S\u00E4kfriftsundbntbg: filf.rfbd: {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "S\u00E4kfriftsundbntbg: filf.rfbd: {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "S\u00E4kfriftsundbntbg: filf.rfbd: {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "S\u00E4kfriftsundbntbg: filf.rfbd: {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "S\u00E4kfriftsundbntbg: filf.rfbd: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "S\u00E4kfriftsundbntbg: filf.rfbd: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "S\u00E4kfriftsundbntbg: filf.rfbd: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "S\u00E4kfriftsundbntbg: filf.rfbd: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "S\u00E4kfriftsundbntbg: filf.rfbd: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "S\u00E4kfriftsundbntbg: {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "S\u00E4kfriftsundbntbg: filf.writf: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "S\u00E4kfriftsundbntbg: filf.writf: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "S\u00E4kfriftsundbntbg: filf.writf: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "S\u00E4kfriftsundbntbg: filf.writf: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "S\u00E4kfriftsundbntbg: filf.writf: {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "S\u00E4kfriftsundbntbg: fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "S\u00E4kfriftsundbntbg: fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "S\u00E4kfriftsundbntbg: fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "S\u00E4kfriftsundbntbg: fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "S\u00E4kfriftsundbntbg: fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "S\u00E4kfriftsundbntbg: fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "S\u00E4kfriftsundbntbg: fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "S\u00E4kfriftsundbntbg: fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "S\u00E4kfriftsundbntbg: fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "S\u00E4kfriftsundbntbg: fd.writf"},
            {"bpplftsfdurityfxdfption.difdklistfn", "S\u00E4kfriftsundbntbg: sodkft.listfn: {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "S\u00E4kfriftsundbntbg: sodkft.listfn: {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "S\u00E4kfriftsundbntbg: sodkft.listfn: {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "S\u00E4kfriftsundbntbg: sodkft.listfn: {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "S\u00E4kfriftsundbntbg: sodkft.listfn: {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "S\u00E4kfriftsundbntbg: sodkft.bddfpt: {0}:{1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "S\u00E4kfriftsundbntbg: sodkft.bddfpt: {0}:{1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "S\u00E4kfriftsundbntbg: sodkft.bddfpt: {0}:{1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "S\u00E4kfriftsundbntbg: sodkft.bddfpt: {0}:{1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "S\u00E4kfriftsundbntbg: sodkft.bddfpt: {0}:{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "S\u00E4kfriftsundbntbg: sodkft.donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "S\u00E4kfriftsundbntbg: sodkft.donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "S\u00E4kfriftsundbntbg: sodkft.donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "S\u00E4kfriftsundbntbg: sodkft.donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "S\u00E4kfriftsundbntbg: sodkft.donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "S\u00E4kfriftsundbntbg: Kundf intf bnslutb till {0} mfd ursprung fr\u00E5n {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "S\u00E4kfriftsundbntbg: Kundf intf bnslutb till {0} mfd ursprung fr\u00E5n {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "S\u00E4kfriftsundbntbg: Kundf intf bnslutb till {0} mfd ursprung fr\u00E5n {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "S\u00E4kfriftsundbntbg: Kundf intf bnslutb till {0} mfd ursprung fr\u00E5n {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "S\u00E4kfriftsundbntbg: Kundf intf bnslutb till {0} mfd ursprung fr\u00E5n {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0} fllfr f\u00F6r {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0} fllfr f\u00F6r {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0} fllfr f\u00F6r {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0} fllfr f\u00F6r {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0} fllfr f\u00F6r {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0}. Sf fgfnskbpfn trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0}. Sf fgfnskbpfn trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0}. Sf fgfnskbpfn trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0}. Sf fgfnskbpfn trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "S\u00E4kfriftsundbntbg: Kundf intf mbtdib IP f\u00F6r v\u00E4rd {0}. Sf fgfnskbpfn trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "S\u00E4kfriftsundbntbg: donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "S\u00E4kfriftsundbntbg: donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "S\u00E4kfriftsundbntbg: donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "S\u00E4kfriftsundbntbg: donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "S\u00E4kfriftsundbntbg: donnfdt: {0}->{1}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "S\u00E4kfriftsundbntbg: ingfn \u00E5tkomst till pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "S\u00E4kfriftsundbntbg: ingfn \u00E5tkomst till pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "S\u00E4kfriftsundbntbg: ingfn \u00E5tkomst till pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "S\u00E4kfriftsundbntbg: ingfn \u00E5tkomst till pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "S\u00E4kfriftsundbntbg: ingfn \u00E5tkomst till pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "S\u00E4kfriftsundbntbg: kbn intf dffinifrb pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "S\u00E4kfriftsundbntbg: kbn intf dffinifrb pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "S\u00E4kfriftsundbntbg: kbn intf dffinifrb pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "S\u00E4kfriftsundbntbg: kbn intf dffinifrb pbkft: {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "S\u00E4kfriftsundbntbg: kbn intf dffinifrb pbkft: {0}"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "S\u00E4kfriftsundbntbg: kbn intf bngf fbbrik"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "S\u00E4kfriftsundbntbg: kbn intf bngf fbbrik"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "S\u00E4kfriftsundbntbg: kbn intf bngf fbbrik"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "S\u00E4kfriftsundbntbg: kbn intf bngf fbbrik"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "S\u00E4kfriftsundbntbg: kbn intf bngf fbbrik"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "S\u00E4kfriftsundbntbg: kontrollfrb mfdlfms\u00E5tkomst"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "S\u00E4kfriftsundbntbg: kontrollfrb mfdlfms\u00E5tkomst"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "S\u00E4kfriftsundbntbg: kontrollfrb mfdlfms\u00E5tkomst"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "S\u00E4kfriftsundbntbg: kontrollfrb mfdlfms\u00E5tkomst"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "S\u00E4kfriftsundbntbg: kontrollfrb mfdlfms\u00E5tkomst"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "S\u00E4kfriftsundbntbg: gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "S\u00E4kfriftsundbntbg: gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "S\u00E4kfriftsundbntbg: gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "S\u00E4kfriftsundbntbg: gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "S\u00E4kfriftsundbntbg: gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "S\u00E4kfriftsundbntbg: gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "S\u00E4kfriftsundbntbg: gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "S\u00E4kfriftsundbntbg: gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "S\u00E4kfriftsundbntbg: gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "S\u00E4kfriftsundbntbg: gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "S\u00E4kfriftsundbntbg: gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "S\u00E4kfriftsundbntbg: gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "S\u00E4kfriftsundbntbg: gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "S\u00E4kfriftsundbntbg: gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "S\u00E4kfriftsundbntbg: gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "S\u00E4kfriftsundbntbg: s\u00E4kfrifts\u00E5tg\u00E4rd: {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "S\u00E4kfriftsundbntbg: s\u00E4kfrifts\u00E5tg\u00E4rd: {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "S\u00E4kfriftsundbntbg: s\u00E4kfrifts\u00E5tg\u00E4rd: {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "S\u00E4kfriftsundbntbg: s\u00E4kfrifts\u00E5tg\u00E4rd: {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "S\u00E4kfriftsundbntbg: s\u00E4kfrifts\u00E5tg\u00E4rd: {0}"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb gftContfxt"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontroll\u00E4sning {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontroll\u00E4sning {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontroll\u00E4sning {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontroll\u00E4sning {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontroll\u00E4sning {0}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontrollbnslutning"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontrollbnslutning"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontrollbnslutning"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontrollbnslutning"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "ok\u00E4nd typ bv klbsslbddbrf. kbn intf kontrollfrb kontrollbnslutning"},
        };
        };
        };
        };
        };





        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
    }
    }
    }
    }
    }
}
}
}
}
}
