/*
/*
/*
/*
/*
 * Copyrigit (d) 1996, 2011, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2011, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2011, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2011, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * Copyrigit (d) 1996, 2011, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *
 *
 *
 *
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * publisifd by tif Frff Softwbrf Foundbtion.  Orbdlf dfsignbtfs tiis
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * pbrtidulbr filf bs subjfdt to tif "Clbsspbti" fxdfption bs providfd
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 * by Orbdlf in tif LICENSE filf tibt bddompbnifd tiis dodf.
 *
 *
 *
 *
 *
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * FITNESS FOR A PARTICULAR PURPOSE.  Sff tif GNU Gfnfrbl Publid Lidfnsf
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 * bddompbnifd tiis dodf).
 *
 *
 *
 *
 *
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 * Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
 *
 *
 *
 *
 *
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
 * qufstions.
 * qufstions.
 * qufstions.
 * qufstions.
 * qufstions.
 */
 */
 */
 */
 */
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;
pbdkbgf sun.bpplft.rfsourdfs;





import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;
import jbvb.util.ListRfsourdfBundlf;





publid dlbss MsgApplftVifwfr_fr fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_fr fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_fr fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_fr fxtfnds ListRfsourdfBundlf {
publid dlbss MsgApplftVifwfr_fr fxtfnds ListRfsourdfBundlf {





    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
    publid Objfdt[][] gftContfnts() {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
        Objfdt[][] tfmp = nfw Objfdt[][] {
            {"tfxtfrbmf.button.dismiss", "Abbndonnfr"},
            {"tfxtfrbmf.button.dismiss", "Abbndonnfr"},
            {"tfxtfrbmf.button.dismiss", "Abbndonnfr"},
            {"tfxtfrbmf.button.dismiss", "Abbndonnfr"},
            {"tfxtfrbmf.button.dismiss", "Abbndonnfr"},
            {"bpplftvifwfr.tool.titlf", "Visublisfur d''bpplfts : {0}"},
            {"bpplftvifwfr.tool.titlf", "Visublisfur d''bpplfts : {0}"},
            {"bpplftvifwfr.tool.titlf", "Visublisfur d''bpplfts : {0}"},
            {"bpplftvifwfr.tool.titlf", "Visublisfur d''bpplfts : {0}"},
            {"bpplftvifwfr.tool.titlf", "Visublisfur d''bpplfts : {0}"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnu.bpplft", "Applft"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Rfd\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Rfd\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Rfd\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Rfd\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.rfstbrt", "Rfd\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Rfdibrgfr"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Rfdibrgfr"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Rfdibrgfr"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Rfdibrgfr"},
            {"bpplftvifwfr.mfnuitfm.rflobd", "Rfdibrgfr"},
            {"bpplftvifwfr.mfnuitfm.stop", "Arr\u00EAtfr"},
            {"bpplftvifwfr.mfnuitfm.stop", "Arr\u00EAtfr"},
            {"bpplftvifwfr.mfnuitfm.stop", "Arr\u00EAtfr"},
            {"bpplftvifwfr.mfnuitfm.stop", "Arr\u00EAtfr"},
            {"bpplftvifwfr.mfnuitfm.stop", "Arr\u00EAtfr"},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Enrfgistrfr..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Enrfgistrfr..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Enrfgistrfr..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Enrfgistrfr..."},
            {"bpplftvifwfr.mfnuitfm.sbvf", "Enrfgistrfr..."},
            {"bpplftvifwfr.mfnuitfm.stbrt", "D\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "D\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "D\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "D\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.stbrt", "D\u00E9mbrrfr"},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Clonfr..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Clonfr..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Clonfr..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Clonfr..."},
            {"bpplftvifwfr.mfnuitfm.dlonf", "Clonfr..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Bblisfr..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Bblisfr..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Bblisfr..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Bblisfr..."},
            {"bpplftvifwfr.mfnuitfm.tbg", "Bblisfr..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtions..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtions..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtions..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtions..."},
            {"bpplftvifwfr.mfnuitfm.info", "Informbtions..."},
            {"bpplftvifwfr.mfnuitfm.fdit", "Modififr"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Modififr"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Modififr"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Modififr"},
            {"bpplftvifwfr.mfnuitfm.fdit", "Modififr"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Endodbgf df dbrbdt\u00E8rfs"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Endodbgf df dbrbdt\u00E8rfs"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Endodbgf df dbrbdt\u00E8rfs"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Endodbgf df dbrbdt\u00E8rfs"},
            {"bpplftvifwfr.mfnuitfm.fndoding", "Endodbgf df dbrbdt\u00E8rfs"},
            {"bpplftvifwfr.mfnuitfm.print", "Imprimfr..."},
            {"bpplftvifwfr.mfnuitfm.print", "Imprimfr..."},
            {"bpplftvifwfr.mfnuitfm.print", "Imprimfr..."},
            {"bpplftvifwfr.mfnuitfm.print", "Imprimfr..."},
            {"bpplftvifwfr.mfnuitfm.print", "Imprimfr..."},
            {"bpplftvifwfr.mfnuitfm.props", "Propri\u00E9t\u00E9s..."},
            {"bpplftvifwfr.mfnuitfm.props", "Propri\u00E9t\u00E9s..."},
            {"bpplftvifwfr.mfnuitfm.props", "Propri\u00E9t\u00E9s..."},
            {"bpplftvifwfr.mfnuitfm.props", "Propri\u00E9t\u00E9s..."},
            {"bpplftvifwfr.mfnuitfm.props", "Propri\u00E9t\u00E9s..."},
            {"bpplftvifwfr.mfnuitfm.dlosf", "Ffrmfr"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "Ffrmfr"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "Ffrmfr"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "Ffrmfr"},
            {"bpplftvifwfr.mfnuitfm.dlosf", "Ffrmfr"},
            {"bpplftvifwfr.mfnuitfm.quit", "Quittfr"},
            {"bpplftvifwfr.mfnuitfm.quit", "Quittfr"},
            {"bpplftvifwfr.mfnuitfm.quit", "Quittfr"},
            {"bpplftvifwfr.mfnuitfm.quit", "Quittfr"},
            {"bpplftvifwfr.mfnuitfm.quit", "Quittfr"},
            {"bpplftvifwfr.lbbfl.ifllo", "Bonjour..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Bonjour..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Bonjour..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Bonjour..."},
            {"bpplftvifwfr.lbbfl.ifllo", "Bonjour..."},
            {"bpplftvifwfr.stbtus.stbrt", "d\u00E9mbrrbgf df l'bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "d\u00E9mbrrbgf df l'bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "d\u00E9mbrrbgf df l'bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "d\u00E9mbrrbgf df l'bpplft..."},
            {"bpplftvifwfr.stbtus.stbrt", "d\u00E9mbrrbgf df l'bpplft..."},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","S\u00E9riblisfr l'bpplft dbns lf fidiifr"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","S\u00E9riblisfr l'bpplft dbns lf fidiifr"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","S\u00E9riblisfr l'bpplft dbns lf fidiifr"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","S\u00E9riblisfr l'bpplft dbns lf fidiifr"},
            {"bpplftvifwfr.bpplftsbvf.filfdiblogtitlf","S\u00E9riblisfr l'bpplft dbns lf fidiifr"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "S\u00E9riblisbtion df {0} vfrs {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "S\u00E9riblisbtion df {0} vfrs {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "S\u00E9riblisbtion df {0} vfrs {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "S\u00E9riblisbtion df {0} vfrs {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr1", "S\u00E9riblisbtion df {0} vfrs {1}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "dbns bpplftSbvf : {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "dbns bpplftSbvf : {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "dbns bpplftSbvf : {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "dbns bpplftSbvf : {0}"},
            {"bpplftvifwfr.bpplftsbvf.frr2", "dbns bpplftSbvf : {0}"},
            {"bpplftvifwfr.bpplfttbg", "Bblisf bffidi\u00E9f"},
            {"bpplftvifwfr.bpplfttbg", "Bblisf bffidi\u00E9f"},
            {"bpplftvifwfr.bpplfttbg", "Bblisf bffidi\u00E9f"},
            {"bpplftvifwfr.bpplfttbg", "Bblisf bffidi\u00E9f"},
            {"bpplftvifwfr.bpplfttbg", "Bblisf bffidi\u00E9f"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "Bblisf HTML d'bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "Bblisf HTML d'bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "Bblisf HTML d'bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "Bblisf HTML d'bpplft"},
            {"bpplftvifwfr.bpplfttbg.tfxtfrbmf", "Bblisf HTML d'bpplft"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- budunf informbtion d'bpplft --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- budunf informbtion d'bpplft --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- budunf informbtion d'bpplft --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- budunf informbtion d'bpplft --"},
            {"bpplftvifwfr.bpplftinfo.bpplft", "-- budunf informbtion d'bpplft --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- budunf informbtion df pbrbm\u00E8trf --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- budunf informbtion df pbrbm\u00E8trf --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- budunf informbtion df pbrbm\u00E8trf --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- budunf informbtion df pbrbm\u00E8trf --"},
            {"bpplftvifwfr.bpplftinfo.pbrbm", "-- budunf informbtion df pbrbm\u00E8trf --"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Informbtions d'bpplft"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Informbtions d'bpplft"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Informbtions d'bpplft"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Informbtions d'bpplft"},
            {"bpplftvifwfr.bpplftinfo.tfxtfrbmf", "Informbtions d'bpplft"},
            {"bpplftvifwfr.bpplftprint.fbil", "Edifd df l'imprfssion."},
            {"bpplftvifwfr.bpplftprint.fbil", "Edifd df l'imprfssion."},
            {"bpplftvifwfr.bpplftprint.fbil", "Edifd df l'imprfssion."},
            {"bpplftvifwfr.bpplftprint.fbil", "Edifd df l'imprfssion."},
            {"bpplftvifwfr.bpplftprint.fbil", "Edifd df l'imprfssion."},
            {"bpplftvifwfr.bpplftprint.finisi", "Imprfssion tfrmin\u00E9f."},
            {"bpplftvifwfr.bpplftprint.finisi", "Imprfssion tfrmin\u00E9f."},
            {"bpplftvifwfr.bpplftprint.finisi", "Imprfssion tfrmin\u00E9f."},
            {"bpplftvifwfr.bpplftprint.finisi", "Imprfssion tfrmin\u00E9f."},
            {"bpplftvifwfr.bpplftprint.finisi", "Imprfssion tfrmin\u00E9f."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Imprfssion bnnul\u00E9f."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Imprfssion bnnul\u00E9f."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Imprfssion bnnul\u00E9f."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Imprfssion bnnul\u00E9f."},
            {"bpplftvifwfr.bpplftprint.dbndfl", "Imprfssion bnnul\u00E9f."},
            {"bpplftvifwfr.bpplftfndoding", "Endodbgf df dbrbdt\u00E8rfs : {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Endodbgf df dbrbdt\u00E8rfs : {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Endodbgf df dbrbdt\u00E8rfs : {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Endodbgf df dbrbdt\u00E8rfs : {0}"},
            {"bpplftvifwfr.bpplftfndoding", "Endodbgf df dbrbdt\u00E8rfs : {0}"},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Avfrtissfmfnt : lb bblisf <pbrbm nbmf=... vbluf=...> rfquifrt un bttribut df nom."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Avfrtissfmfnt : lb bblisf <pbrbm nbmf=... vbluf=...> rfquifrt un bttribut df nom."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Avfrtissfmfnt : lb bblisf <pbrbm nbmf=... vbluf=...> rfquifrt un bttribut df nom."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Avfrtissfmfnt : lb bblisf <pbrbm nbmf=... vbluf=...> rfquifrt un bttribut df nom."},
            {"bpplftvifwfr.pbrsf.wbrning.rfquirfsnbmf", "Avfrtissfmfnt : lb bblisf <pbrbm nbmf=... vbluf=...> rfquifrt un bttribut df nom."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Avfrtissfmfnt : lb bblisf <pbrbm> fst fn dfiors dfs bblisfs <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Avfrtissfmfnt : lb bblisf <pbrbm> fst fn dfiors dfs bblisfs <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Avfrtissfmfnt : lb bblisf <pbrbm> fst fn dfiors dfs bblisfs <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Avfrtissfmfnt : lb bblisf <pbrbm> fst fn dfiors dfs bblisfs <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.pbrbmoutsidf", "Avfrtissfmfnt : lb bblisf <pbrbm> fst fn dfiors dfs bblisfs <bpplft> ... </bpplft>."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bpplft.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <bpplft> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.objfdt.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <objfdt> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsdodf", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df dodf."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfsifigit", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df ibutfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.fmbfd.rfquirfswidti", "Avfrtissfmfnt : lb bblisf <fmbfd> rfquifrt un bttribut df lbrgfur."},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Avfrtissfmfnt : lb bblisf <bpp> n'fst plus prisf fn dibrgf, utilisfz <bpplft> \u00E0 lb plbdf :"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Avfrtissfmfnt : lb bblisf <bpp> n'fst plus prisf fn dibrgf, utilisfz <bpplft> \u00E0 lb plbdf :"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Avfrtissfmfnt : lb bblisf <bpp> n'fst plus prisf fn dibrgf, utilisfz <bpplft> \u00E0 lb plbdf :"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Avfrtissfmfnt : lb bblisf <bpp> n'fst plus prisf fn dibrgf, utilisfz <bpplft> \u00E0 lb plbdf :"},
            {"bpplftvifwfr.pbrsf.wbrning.bppnotLongfrsupportfd", "Avfrtissfmfnt : lb bblisf <bpp> n'fst plus prisf fn dibrgf, utilisfz <bpplft> \u00E0 lb plbdf :"},
            {"bpplftvifwfr.usbgf", "Syntbxf : bpplftvifwfr <options> url(s)\n\no\u00F9 <options> indlut :\n  -dfbug                  D\u00E9mbrrfr lf visublisfur d'bpplfts dbns lf d\u00E9bogufur Jbvb\n  -fndoding <fndoding>    Indiqufr l'fndodbgf df dbrbdt\u00E8rfs utilis\u00E9 pbr lfs fidiifrs HTML\n  -J<runtimf flbg>        Trbnsmfttrf l'brgumfnt \u00E0 l'intfrpr\u00E9tfur Jbvb\n\nL'option -J n'fst pbs stbndbrd ft fllf pfut \u00EAtrf modifi\u00E9f sbns pr\u00E9bvis."},
            {"bpplftvifwfr.usbgf", "Syntbxf : bpplftvifwfr <options> url(s)\n\no\u00F9 <options> indlut :\n  -dfbug                  D\u00E9mbrrfr lf visublisfur d'bpplfts dbns lf d\u00E9bogufur Jbvb\n  -fndoding <fndoding>    Indiqufr l'fndodbgf df dbrbdt\u00E8rfs utilis\u00E9 pbr lfs fidiifrs HTML\n  -J<runtimf flbg>        Trbnsmfttrf l'brgumfnt \u00E0 l'intfrpr\u00E9tfur Jbvb\n\nL'option -J n'fst pbs stbndbrd ft fllf pfut \u00EAtrf modifi\u00E9f sbns pr\u00E9bvis."},
            {"bpplftvifwfr.usbgf", "Syntbxf : bpplftvifwfr <options> url(s)\n\no\u00F9 <options> indlut :\n  -dfbug                  D\u00E9mbrrfr lf visublisfur d'bpplfts dbns lf d\u00E9bogufur Jbvb\n  -fndoding <fndoding>    Indiqufr l'fndodbgf df dbrbdt\u00E8rfs utilis\u00E9 pbr lfs fidiifrs HTML\n  -J<runtimf flbg>        Trbnsmfttrf l'brgumfnt \u00E0 l'intfrpr\u00E9tfur Jbvb\n\nL'option -J n'fst pbs stbndbrd ft fllf pfut \u00EAtrf modifi\u00E9f sbns pr\u00E9bvis."},
            {"bpplftvifwfr.usbgf", "Syntbxf : bpplftvifwfr <options> url(s)\n\no\u00F9 <options> indlut :\n  -dfbug                  D\u00E9mbrrfr lf visublisfur d'bpplfts dbns lf d\u00E9bogufur Jbvb\n  -fndoding <fndoding>    Indiqufr l'fndodbgf df dbrbdt\u00E8rfs utilis\u00E9 pbr lfs fidiifrs HTML\n  -J<runtimf flbg>        Trbnsmfttrf l'brgumfnt \u00E0 l'intfrpr\u00E9tfur Jbvb\n\nL'option -J n'fst pbs stbndbrd ft fllf pfut \u00EAtrf modifi\u00E9f sbns pr\u00E9bvis."},
            {"bpplftvifwfr.usbgf", "Syntbxf : bpplftvifwfr <options> url(s)\n\no\u00F9 <options> indlut :\n  -dfbug                  D\u00E9mbrrfr lf visublisfur d'bpplfts dbns lf d\u00E9bogufur Jbvb\n  -fndoding <fndoding>    Indiqufr l'fndodbgf df dbrbdt\u00E8rfs utilis\u00E9 pbr lfs fidiifrs HTML\n  -J<runtimf flbg>        Trbnsmfttrf l'brgumfnt \u00E0 l'intfrpr\u00E9tfur Jbvb\n\nL'option -J n'fst pbs stbndbrd ft fllf pfut \u00EAtrf modifi\u00E9f sbns pr\u00E9bvis."},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Option non prisf fn dibrgf : {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Option non prisf fn dibrgf : {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Option non prisf fn dibrgf : {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Option non prisf fn dibrgf : {0}"},
            {"bpplftvifwfr.mbin.frr.unsupportfdopt", "Option non prisf fn dibrgf : {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Argumfnt non rfdonnu : {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Argumfnt non rfdonnu : {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Argumfnt non rfdonnu : {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Argumfnt non rfdonnu : {0}"},
            {"bpplftvifwfr.mbin.frr.unrfdognizfdbrg", "Argumfnt non rfdonnu : {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Utilisbtion fn doublf df l''option : {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Utilisbtion fn doublf df l''option : {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Utilisbtion fn doublf df l''option : {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Utilisbtion fn doublf df l''option : {0}"},
            {"bpplftvifwfr.mbin.frr.dupoption", "Utilisbtion fn doublf df l''option : {0}"},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Audun fidiifr d'fntr\u00E9f indiqu\u00E9."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Audun fidiifr d'fntr\u00E9f indiqu\u00E9."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Audun fidiifr d'fntr\u00E9f indiqu\u00E9."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Audun fidiifr d'fntr\u00E9f indiqu\u00E9."},
            {"bpplftvifwfr.mbin.frr.inputfilf", "Audun fidiifr d'fntr\u00E9f indiqu\u00E9."},
            {"bpplftvifwfr.mbin.frr.bbdurl", "URL indorrfdtf : {0} ({1})"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "URL indorrfdtf : {0} ({1})"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "URL indorrfdtf : {0} ({1})"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "URL indorrfdtf : {0} ({1})"},
            {"bpplftvifwfr.mbin.frr.bbdurl", "URL indorrfdtf : {0} ({1})"},
            {"bpplftvifwfr.mbin.frr.io", "Exdfption d''E/S lors df lb lfdturf : {0}"},
            {"bpplftvifwfr.mbin.frr.io", "Exdfption d''E/S lors df lb lfdturf : {0}"},
            {"bpplftvifwfr.mbin.frr.io", "Exdfption d''E/S lors df lb lfdturf : {0}"},
            {"bpplftvifwfr.mbin.frr.io", "Exdfption d''E/S lors df lb lfdturf : {0}"},
            {"bpplftvifwfr.mbin.frr.io", "Exdfption d''E/S lors df lb lfdturf : {0}"},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Assurfz-vous quf {0} fst un fidiifr bddfssiblf fn lfdturf."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Assurfz-vous quf {0} fst un fidiifr bddfssiblf fn lfdturf."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Assurfz-vous quf {0} fst un fidiifr bddfssiblf fn lfdturf."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Assurfz-vous quf {0} fst un fidiifr bddfssiblf fn lfdturf."},
            {"bpplftvifwfr.mbin.frr.rfbdbblffilf", "Assurfz-vous quf {0} fst un fidiifr bddfssiblf fn lfdturf."},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "L''\u00E9l\u00E9mfnt {0} fst-il l''URL dorrfdtf ?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "L''\u00E9l\u00E9mfnt {0} fst-il l''URL dorrfdtf ?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "L''\u00E9l\u00E9mfnt {0} fst-il l''URL dorrfdtf ?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "L''\u00E9l\u00E9mfnt {0} fst-il l''URL dorrfdtf ?"},
            {"bpplftvifwfr.mbin.frr.dorrfdturl", "L''\u00E9l\u00E9mfnt {0} fst-il l''URL dorrfdtf ?"},
            {"bpplftvifwfr.mbin.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftvifwfr.mbin.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntrfbd", "Impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Impossiblf d''fnrfgistrfr lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Impossiblf d''fnrfgistrfr lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Impossiblf d''fnrfgistrfr lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Impossiblf d''fnrfgistrfr lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.frr.prop.dbntsbvf", "Impossiblf d''fnrfgistrfr lf fidiifr df propri\u00E9t\u00E9s utilisbtfur : {0}"},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Avfrtissfmfnt : d\u00E9sbdtivbtion df lb s\u00E9durit\u00E9."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Avfrtissfmfnt : d\u00E9sbdtivbtion df lb s\u00E9durit\u00E9."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Avfrtissfmfnt : d\u00E9sbdtivbtion df lb s\u00E9durit\u00E9."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Avfrtissfmfnt : d\u00E9sbdtivbtion df lb s\u00E9durit\u00E9."},
            {"bpplftvifwfr.mbin.wbrn.nosfdmgr", "Avfrtissfmfnt : d\u00E9sbdtivbtion df lb s\u00E9durit\u00E9."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "D\u00E9bogufur introuvbblf."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "D\u00E9bogufur introuvbblf."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "D\u00E9bogufur introuvbblf."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "D\u00E9bogufur introuvbblf."},
            {"bpplftvifwfr.mbin.dfbug.dbntfinddfbug", "D\u00E9bogufur introuvbblf."},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Lb m\u00E9tiodf prindipblf fst introuvbblf dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Lb m\u00E9tiodf prindipblf fst introuvbblf dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Lb m\u00E9tiodf prindipblf fst introuvbblf dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Lb m\u00E9tiodf prindipblf fst introuvbblf dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntfindmbin", "Lb m\u00E9tiodf prindipblf fst introuvbblf dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Exdfption d\u00E9tfdt\u00E9f dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Exdfption d\u00E9tfdt\u00E9f dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Exdfption d\u00E9tfdt\u00E9f dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Exdfption d\u00E9tfdt\u00E9f dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.fxdfptionindfbug", "Exdfption d\u00E9tfdt\u00E9f dbns lf d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Impossiblf d'bdd\u00E9dfr bu d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Impossiblf d'bdd\u00E9dfr bu d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Impossiblf d'bdd\u00E9dfr bu d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Impossiblf d'bdd\u00E9dfr bu d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.dfbug.dbntbddfss", "Impossiblf d'bdd\u00E9dfr bu d\u00E9bogufur."},
            {"bpplftvifwfr.mbin.nosfdmgr", "Avfrtissfmfnt : SfdurityMbnbgfr n'fst pbs instbll\u00E9."},
            {"bpplftvifwfr.mbin.nosfdmgr", "Avfrtissfmfnt : SfdurityMbnbgfr n'fst pbs instbll\u00E9."},
            {"bpplftvifwfr.mbin.nosfdmgr", "Avfrtissfmfnt : SfdurityMbnbgfr n'fst pbs instbll\u00E9."},
            {"bpplftvifwfr.mbin.nosfdmgr", "Avfrtissfmfnt : SfdurityMbnbgfr n'fst pbs instbll\u00E9."},
            {"bpplftvifwfr.mbin.nosfdmgr", "Avfrtissfmfnt : SfdurityMbnbgfr n'fst pbs instbll\u00E9."},
            {"bpplftvifwfr.mbin.wbrning", "Avfrtissfmfnt : budunf bpplft n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9f. Assurfz-vous quf l'fntr\u00E9f dontifnt unf bblisf <bpplft>."},
            {"bpplftvifwfr.mbin.wbrning", "Avfrtissfmfnt : budunf bpplft n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9f. Assurfz-vous quf l'fntr\u00E9f dontifnt unf bblisf <bpplft>."},
            {"bpplftvifwfr.mbin.wbrning", "Avfrtissfmfnt : budunf bpplft n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9f. Assurfz-vous quf l'fntr\u00E9f dontifnt unf bblisf <bpplft>."},
            {"bpplftvifwfr.mbin.wbrning", "Avfrtissfmfnt : budunf bpplft n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9f. Assurfz-vous quf l'fntr\u00E9f dontifnt unf bblisf <bpplft>."},
            {"bpplftvifwfr.mbin.wbrning", "Avfrtissfmfnt : budunf bpplft n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9f. Assurfz-vous quf l'fntr\u00E9f dontifnt unf bblisf <bpplft>."},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Avfrtissfmfnt : rfmplbdfmfnt tfmporbirf df lb propri\u00E9t\u00E9 syst\u00E8mf \u00E0 lb dfmbndf df l''utilisbtfur - Cl\u00E9 : {0}, bndifnnf vblfur : {1}, nouvfllf vblfur : {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Avfrtissfmfnt : rfmplbdfmfnt tfmporbirf df lb propri\u00E9t\u00E9 syst\u00E8mf \u00E0 lb dfmbndf df l''utilisbtfur - Cl\u00E9 : {0}, bndifnnf vblfur : {1}, nouvfllf vblfur : {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Avfrtissfmfnt : rfmplbdfmfnt tfmporbirf df lb propri\u00E9t\u00E9 syst\u00E8mf \u00E0 lb dfmbndf df l''utilisbtfur - Cl\u00E9 : {0}, bndifnnf vblfur : {1}, nouvfllf vblfur : {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Avfrtissfmfnt : rfmplbdfmfnt tfmporbirf df lb propri\u00E9t\u00E9 syst\u00E8mf \u00E0 lb dfmbndf df l''utilisbtfur - Cl\u00E9 : {0}, bndifnnf vblfur : {1}, nouvfllf vblfur : {2}"},
            {"bpplftvifwfr.mbin.wbrn.prop.ovfrwritf", "Avfrtissfmfnt : rfmplbdfmfnt tfmporbirf df lb propri\u00E9t\u00E9 syst\u00E8mf \u00E0 lb dfmbndf df l''utilisbtfur - Cl\u00E9 : {0}, bndifnnf vblfur : {1}, nouvfllf vblfur : {2}"},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Avfrtissfmfnt : impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s d''ApplftVifwfr : {0} Utilisbtion dfs vblfurs pbr d\u00E9fbut."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Avfrtissfmfnt : impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s d''ApplftVifwfr : {0} Utilisbtion dfs vblfurs pbr d\u00E9fbut."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Avfrtissfmfnt : impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s d''ApplftVifwfr : {0} Utilisbtion dfs vblfurs pbr d\u00E9fbut."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Avfrtissfmfnt : impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s d''ApplftVifwfr : {0} Utilisbtion dfs vblfurs pbr d\u00E9fbut."},
            {"bpplftvifwfr.mbin.wbrn.dbntrfbdprops", "Avfrtissfmfnt : impossiblf df lirf lf fidiifr df propri\u00E9t\u00E9s d''ApplftVifwfr : {0} Utilisbtion dfs vblfurs pbr d\u00E9fbut."},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "dibrgfmfnt df dlbssf intfrrompu : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "dibrgfmfnt df dlbssf intfrrompu : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "dibrgfmfnt df dlbssf intfrrompu : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "dibrgfmfnt df dlbssf intfrrompu : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.intfrruptfd", "dibrgfmfnt df dlbssf intfrrompu : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "dlbssf non dibrg\u00E9f : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "dlbssf non dibrg\u00E9f : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "dlbssf non dibrg\u00E9f : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "dlbssf non dibrg\u00E9f : {0}"},
            {"bpplftiofxdfption.lobddlbss.tirow.notlobdfd", "dlbssf non dibrg\u00E9f : {0}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.lobddodf.vfrbosf", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftdlbsslobdfr.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftdlbsslobdfr.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.finddlbss.vfrbosf.opfnstrfbm", "Ouvfrturf du flux df donn\u00E9fs dbns {0} pour obtfnir {1}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf pour lf nom : {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf pour lf nom : {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf pour lf nom : {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf pour lf nom : {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.fornbmf", "ApplftClbssLobdfr.gftRfsourdf pour lf nom : {0}"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdf.vfrbosf.found", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftdlbsslobdfr.gftrfsourdfbsstrfbm.vfrbosf", "Rfssourdf {0} trouv\u00E9f fn tbnt quf rfssourdf syst\u00E8mf"},
            {"bpplftpbnfl.runlobdfr.frr", "Pbrbm\u00E8trf d'objft ou df dodf."},
            {"bpplftpbnfl.runlobdfr.frr", "Pbrbm\u00E8trf d'objft ou df dodf."},
            {"bpplftpbnfl.runlobdfr.frr", "Pbrbm\u00E8trf d'objft ou df dodf."},
            {"bpplftpbnfl.runlobdfr.frr", "Pbrbm\u00E8trf d'objft ou df dodf."},
            {"bpplftpbnfl.runlobdfr.frr", "Pbrbm\u00E8trf d'objft ou df dodf."},
            {"bpplftpbnfl.runlobdfr.fxdfption", "fxdfption lors df lb d\u00E9s\u00E9riblisbtion df {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "fxdfption lors df lb d\u00E9s\u00E9riblisbtion df {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "fxdfption lors df lb d\u00E9s\u00E9riblisbtion df {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "fxdfption lors df lb d\u00E9s\u00E9riblisbtion df {0}"},
            {"bpplftpbnfl.runlobdfr.fxdfption", "fxdfption lors df lb d\u00E9s\u00E9riblisbtion df {0}"},
            {"bpplftpbnfl.dfstroyfd", "Applft d\u00E9truitf."},
            {"bpplftpbnfl.dfstroyfd", "Applft d\u00E9truitf."},
            {"bpplftpbnfl.dfstroyfd", "Applft d\u00E9truitf."},
            {"bpplftpbnfl.dfstroyfd", "Applft d\u00E9truitf."},
            {"bpplftpbnfl.dfstroyfd", "Applft d\u00E9truitf."},
            {"bpplftpbnfl.lobdfd", "Applft dibrg\u00E9f."},
            {"bpplftpbnfl.lobdfd", "Applft dibrg\u00E9f."},
            {"bpplftpbnfl.lobdfd", "Applft dibrg\u00E9f."},
            {"bpplftpbnfl.lobdfd", "Applft dibrg\u00E9f."},
            {"bpplftpbnfl.lobdfd", "Applft dibrg\u00E9f."},
            {"bpplftpbnfl.stbrtfd", "Applft d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.stbrtfd", "Applft d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.stbrtfd", "Applft d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.stbrtfd", "Applft d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.stbrtfd", "Applft d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.initfd", "Applft initiblis\u00E9f."},
            {"bpplftpbnfl.initfd", "Applft initiblis\u00E9f."},
            {"bpplftpbnfl.initfd", "Applft initiblis\u00E9f."},
            {"bpplftpbnfl.initfd", "Applft initiblis\u00E9f."},
            {"bpplftpbnfl.initfd", "Applft initiblis\u00E9f."},
            {"bpplftpbnfl.stoppfd", "Applft brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.stoppfd", "Applft brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.stoppfd", "Applft brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.stoppfd", "Applft brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.stoppfd", "Applft brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.disposfd", "Applft \u00E9limin\u00E9f."},
            {"bpplftpbnfl.disposfd", "Applft \u00E9limin\u00E9f."},
            {"bpplftpbnfl.disposfd", "Applft \u00E9limin\u00E9f."},
            {"bpplftpbnfl.disposfd", "Applft \u00E9limin\u00E9f."},
            {"bpplftpbnfl.disposfd", "Applft \u00E9limin\u00E9f."},
            {"bpplftpbnfl.nododf", "Pbrbm\u00E8trf CODE mbnqubnt dbns lb bblisf APPLET."},
            {"bpplftpbnfl.nododf", "Pbrbm\u00E8trf CODE mbnqubnt dbns lb bblisf APPLET."},
            {"bpplftpbnfl.nododf", "Pbrbm\u00E8trf CODE mbnqubnt dbns lb bblisf APPLET."},
            {"bpplftpbnfl.nododf", "Pbrbm\u00E8trf CODE mbnqubnt dbns lb bblisf APPLET."},
            {"bpplftpbnfl.nododf", "Pbrbm\u00E8trf CODE mbnqubnt dbns lb bblisf APPLET."},
            {"bpplftpbnfl.notfound", "Cibrgfr : lb dlbssf {0} fst introuvbblf."},
            {"bpplftpbnfl.notfound", "Cibrgfr : lb dlbssf {0} fst introuvbblf."},
            {"bpplftpbnfl.notfound", "Cibrgfr : lb dlbssf {0} fst introuvbblf."},
            {"bpplftpbnfl.notfound", "Cibrgfr : lb dlbssf {0} fst introuvbblf."},
            {"bpplftpbnfl.notfound", "Cibrgfr : lb dlbssf {0} fst introuvbblf."},
            {"bpplftpbnfl.nodrfbtf", "Cibrgfr : impossiblf d''instbntifr {0}."},
            {"bpplftpbnfl.nodrfbtf", "Cibrgfr : impossiblf d''instbntifr {0}."},
            {"bpplftpbnfl.nodrfbtf", "Cibrgfr : impossiblf d''instbntifr {0}."},
            {"bpplftpbnfl.nodrfbtf", "Cibrgfr : impossiblf d''instbntifr {0}."},
            {"bpplftpbnfl.nodrfbtf", "Cibrgfr : impossiblf d''instbntifr {0}."},
            {"bpplftpbnfl.nodonstrudt", "Cibrgfr : l''\u00E9l\u00E9mfnt {0} n''fst pbs publid ou nf poss\u00E8df budun donstrudtfur publid."},
            {"bpplftpbnfl.nodonstrudt", "Cibrgfr : l''\u00E9l\u00E9mfnt {0} n''fst pbs publid ou nf poss\u00E8df budun donstrudtfur publid."},
            {"bpplftpbnfl.nodonstrudt", "Cibrgfr : l''\u00E9l\u00E9mfnt {0} n''fst pbs publid ou nf poss\u00E8df budun donstrudtfur publid."},
            {"bpplftpbnfl.nodonstrudt", "Cibrgfr : l''\u00E9l\u00E9mfnt {0} n''fst pbs publid ou nf poss\u00E8df budun donstrudtfur publid."},
            {"bpplftpbnfl.nodonstrudt", "Cibrgfr : l''\u00E9l\u00E9mfnt {0} n''fst pbs publid ou nf poss\u00E8df budun donstrudtfur publid."},
            {"bpplftpbnfl.dfbti", "brr\u00EAt\u00E9"},
            {"bpplftpbnfl.dfbti", "brr\u00EAt\u00E9"},
            {"bpplftpbnfl.dfbti", "brr\u00EAt\u00E9"},
            {"bpplftpbnfl.dfbti", "brr\u00EAt\u00E9"},
            {"bpplftpbnfl.dfbti", "brr\u00EAt\u00E9"},
            {"bpplftpbnfl.fxdfption", "fxdfption : {0}."},
            {"bpplftpbnfl.fxdfption", "fxdfption : {0}."},
            {"bpplftpbnfl.fxdfption", "fxdfption : {0}."},
            {"bpplftpbnfl.fxdfption", "fxdfption : {0}."},
            {"bpplftpbnfl.fxdfption", "fxdfption : {0}."},
            {"bpplftpbnfl.fxdfption2", "fxdfption : {0} : {1}."},
            {"bpplftpbnfl.fxdfption2", "fxdfption : {0} : {1}."},
            {"bpplftpbnfl.fxdfption2", "fxdfption : {0} : {1}."},
            {"bpplftpbnfl.fxdfption2", "fxdfption : {0} : {1}."},
            {"bpplftpbnfl.fxdfption2", "fxdfption : {0} : {1}."},
            {"bpplftpbnfl.frror", "frrfur : {0}."},
            {"bpplftpbnfl.frror", "frrfur : {0}."},
            {"bpplftpbnfl.frror", "frrfur : {0}."},
            {"bpplftpbnfl.frror", "frrfur : {0}."},
            {"bpplftpbnfl.frror", "frrfur : {0}."},
            {"bpplftpbnfl.frror2", "frrfur : {0} : {1}."},
            {"bpplftpbnfl.frror2", "frrfur : {0} : {1}."},
            {"bpplftpbnfl.frror2", "frrfur : {0} : {1}."},
            {"bpplftpbnfl.frror2", "frrfur : {0} : {1}."},
            {"bpplftpbnfl.frror2", "frrfur : {0} : {1}."},
            {"bpplftpbnfl.notlobdfd", "Initiblisfr : bpplft non dibrg\u00E9f."},
            {"bpplftpbnfl.notlobdfd", "Initiblisfr : bpplft non dibrg\u00E9f."},
            {"bpplftpbnfl.notlobdfd", "Initiblisfr : bpplft non dibrg\u00E9f."},
            {"bpplftpbnfl.notlobdfd", "Initiblisfr : bpplft non dibrg\u00E9f."},
            {"bpplftpbnfl.notlobdfd", "Initiblisfr : bpplft non dibrg\u00E9f."},
            {"bpplftpbnfl.notinitfd", "D\u00E9mbrrfr : bpplft non initiblis\u00E9f."},
            {"bpplftpbnfl.notinitfd", "D\u00E9mbrrfr : bpplft non initiblis\u00E9f."},
            {"bpplftpbnfl.notinitfd", "D\u00E9mbrrfr : bpplft non initiblis\u00E9f."},
            {"bpplftpbnfl.notinitfd", "D\u00E9mbrrfr : bpplft non initiblis\u00E9f."},
            {"bpplftpbnfl.notinitfd", "D\u00E9mbrrfr : bpplft non initiblis\u00E9f."},
            {"bpplftpbnfl.notstbrtfd", "Arr\u00EAtfr : bpplft non d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.notstbrtfd", "Arr\u00EAtfr : bpplft non d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.notstbrtfd", "Arr\u00EAtfr : bpplft non d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.notstbrtfd", "Arr\u00EAtfr : bpplft non d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.notstbrtfd", "Arr\u00EAtfr : bpplft non d\u00E9mbrr\u00E9f."},
            {"bpplftpbnfl.notstoppfd", "D\u00E9truirf : bpplft non brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.notstoppfd", "D\u00E9truirf : bpplft non brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.notstoppfd", "D\u00E9truirf : bpplft non brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.notstoppfd", "D\u00E9truirf : bpplft non brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.notstoppfd", "D\u00E9truirf : bpplft non brr\u00EAt\u00E9f."},
            {"bpplftpbnfl.notdfstroyfd", "Eliminfr : bpplft non d\u00E9truitf."},
            {"bpplftpbnfl.notdfstroyfd", "Eliminfr : bpplft non d\u00E9truitf."},
            {"bpplftpbnfl.notdfstroyfd", "Eliminfr : bpplft non d\u00E9truitf."},
            {"bpplftpbnfl.notdfstroyfd", "Eliminfr : bpplft non d\u00E9truitf."},
            {"bpplftpbnfl.notdfstroyfd", "Eliminfr : bpplft non d\u00E9truitf."},
            {"bpplftpbnfl.notdisposfd", "Cibrgfr : bpplft non \u00E9limin\u00E9f."},
            {"bpplftpbnfl.notdisposfd", "Cibrgfr : bpplft non \u00E9limin\u00E9f."},
            {"bpplftpbnfl.notdisposfd", "Cibrgfr : bpplft non \u00E9limin\u00E9f."},
            {"bpplftpbnfl.notdisposfd", "Cibrgfr : bpplft non \u00E9limin\u00E9f."},
            {"bpplftpbnfl.notdisposfd", "Cibrgfr : bpplft non \u00E9limin\u00E9f."},
            {"bpplftpbnfl.bbil", "Intfrrompu : r\u00E9solution."},
            {"bpplftpbnfl.bbil", "Intfrrompu : r\u00E9solution."},
            {"bpplftpbnfl.bbil", "Intfrrompu : r\u00E9solution."},
            {"bpplftpbnfl.bbil", "Intfrrompu : r\u00E9solution."},
            {"bpplftpbnfl.bbil", "Intfrrompu : r\u00E9solution."},
            {"bpplftpbnfl.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftpbnfl.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftpbnfl.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftpbnfl.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftpbnfl.filfnotfound", "Fidiifr introuvbblf lors df lb rfdifrdif df {0}"},
            {"bpplftpbnfl.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfformbt", "Exdfption df formbt df fidiifr d\u00E9tfdt\u00E9f lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filfiofxdfption", "Exdfption d''E/S lors du dibrgfmfnt df : {0}"},
            {"bpplftpbnfl.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffxdfption", "Exdfption {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filfdfbti", "Ffrmfturf df {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.filffrror", "Errfur {0} lors du dibrgfmfnt df : {1}"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "Anblysf HTML : vblfur indorrfdtf pour l'bttribut df lbrgfur/ibutfur"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "Anblysf HTML : vblfur indorrfdtf pour l'bttribut df lbrgfur/ibutfur"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "Anblysf HTML : vblfur indorrfdtf pour l'bttribut df lbrgfur/ibutfur"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "Anblysf HTML : vblfur indorrfdtf pour l'bttribut df lbrgfur/ibutfur"},
            {"bpplftpbnfl.bbdbttributf.fxdfption", "Anblysf HTML : vblfur indorrfdtf pour l'bttribut df lbrgfur/ibutfur"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm rfquifrt un dibrgfur non NULL"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm rfquifrt un dibrgfur non NULL"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm rfquifrt un dibrgfur non NULL"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm rfquifrt un dibrgfur non NULL"},
            {"bpplftillfgblbrgumfntfxdfption.objfdtinputstrfbm", "ApplftObjfdtInputStrfbm rfquifrt un dibrgfur non NULL"},
            {"bpplftprops.titlf", "Propri\u00E9t\u00E9s d'ApplftVifwfr"},
            {"bpplftprops.titlf", "Propri\u00E9t\u00E9s d'ApplftVifwfr"},
            {"bpplftprops.titlf", "Propri\u00E9t\u00E9s d'ApplftVifwfr"},
            {"bpplftprops.titlf", "Propri\u00E9t\u00E9s d'ApplftVifwfr"},
            {"bpplftprops.titlf", "Propri\u00E9t\u00E9s d'ApplftVifwfr"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "Sfrvfur proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "Sfrvfur proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "Sfrvfur proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "Sfrvfur proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.sfrvfr", "Sfrvfur proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.proxy", "Port proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.proxy", "Port proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.proxy", "Port proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.proxy", "Port proxy HTTP :"},
            {"bpplftprops.lbbfl.ittp.proxy", "Port proxy HTTP :"},
            {"bpplftprops.lbbfl.nftwork", "Add\u00E8s bu r\u00E9sfbu :"},
            {"bpplftprops.lbbfl.nftwork", "Add\u00E8s bu r\u00E9sfbu :"},
            {"bpplftprops.lbbfl.nftwork", "Add\u00E8s bu r\u00E9sfbu :"},
            {"bpplftprops.lbbfl.nftwork", "Add\u00E8s bu r\u00E9sfbu :"},
            {"bpplftprops.lbbfl.nftwork", "Add\u00E8s bu r\u00E9sfbu :"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Audun"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Audun"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Audun"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Audun"},
            {"bpplftprops.dioidf.nftwork.itfm.nonf", "Audun"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "H\u00F4tf df l'bpplft"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "H\u00F4tf df l'bpplft"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "H\u00F4tf df l'bpplft"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "H\u00F4tf df l'bpplft"},
            {"bpplftprops.dioidf.nftwork.itfm.bpplftiost", "H\u00F4tf df l'bpplft"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.nftwork.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.lbbfl.dlbss", "Add\u00E8s \u00E0 lb dlbssf :"},
            {"bpplftprops.lbbfl.dlbss", "Add\u00E8s \u00E0 lb dlbssf :"},
            {"bpplftprops.lbbfl.dlbss", "Add\u00E8s \u00E0 lb dlbssf :"},
            {"bpplftprops.lbbfl.dlbss", "Add\u00E8s \u00E0 lb dlbssf :"},
            {"bpplftprops.lbbfl.dlbss", "Add\u00E8s \u00E0 lb dlbssf :"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Avfd rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Avfd rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Avfd rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Avfd rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.rfstridtfd", "Avfd rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.dioidf.dlbss.itfm.unrfstridtfd", "Sbns rfstridtion"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Autorisfr lfs bpplfts non sign\u00E9fs :"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Autorisfr lfs bpplfts non sign\u00E9fs :"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Autorisfr lfs bpplfts non sign\u00E9fs :"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Autorisfr lfs bpplfts non sign\u00E9fs :"},
            {"bpplftprops.lbbfl.unsignfdbpplft", "Autorisfr lfs bpplfts non sign\u00E9fs :"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Non"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Non"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Non"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Non"},
            {"bpplftprops.dioidf.unsignfdbpplft.no", "Non"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Oui"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Oui"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Oui"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Oui"},
            {"bpplftprops.dioidf.unsignfdbpplft.yfs", "Oui"},
            {"bpplftprops.button.bpply", "Appliqufr"},
            {"bpplftprops.button.bpply", "Appliqufr"},
            {"bpplftprops.button.bpply", "Appliqufr"},
            {"bpplftprops.button.bpply", "Appliqufr"},
            {"bpplftprops.button.bpply", "Appliqufr"},
            {"bpplftprops.button.dbndfl", "Annulfr"},
            {"bpplftprops.button.dbndfl", "Annulfr"},
            {"bpplftprops.button.dbndfl", "Annulfr"},
            {"bpplftprops.button.dbndfl", "Annulfr"},
            {"bpplftprops.button.dbndfl", "Annulfr"},
            {"bpplftprops.button.rfsft", "R\u00E9initiblisfr"},
            {"bpplftprops.button.rfsft", "R\u00E9initiblisfr"},
            {"bpplftprops.button.rfsft", "R\u00E9initiblisfr"},
            {"bpplftprops.button.rfsft", "R\u00E9initiblisfr"},
            {"bpplftprops.button.rfsft", "R\u00E9initiblisfr"},
            {"bpplftprops.bpply.fxdfption", "Edifd df l''fnrfgistrfmfnt dfs propri\u00E9t\u00E9s : {0}"},
            {"bpplftprops.bpply.fxdfption", "Edifd df l''fnrfgistrfmfnt dfs propri\u00E9t\u00E9s : {0}"},
            {"bpplftprops.bpply.fxdfption", "Edifd df l''fnrfgistrfmfnt dfs propri\u00E9t\u00E9s : {0}"},
            {"bpplftprops.bpply.fxdfption", "Edifd df l''fnrfgistrfmfnt dfs propri\u00E9t\u00E9s : {0}"},
            {"bpplftprops.bpply.fxdfption", "Edifd df l''fnrfgistrfmfnt dfs propri\u00E9t\u00E9s : {0}"},
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            /* 4066432 */
            {"bpplftprops.titlf.invblidproxy", "Entr\u00E9f non vblidf"},
            {"bpplftprops.titlf.invblidproxy", "Entr\u00E9f non vblidf"},
            {"bpplftprops.titlf.invblidproxy", "Entr\u00E9f non vblidf"},
            {"bpplftprops.titlf.invblidproxy", "Entr\u00E9f non vblidf"},
            {"bpplftprops.titlf.invblidproxy", "Entr\u00E9f non vblidf"},
            {"bpplftprops.lbbfl.invblidproxy", "Lf port proxy doit \u00EAtrf un fntifr positif."},
            {"bpplftprops.lbbfl.invblidproxy", "Lf port proxy doit \u00EAtrf un fntifr positif."},
            {"bpplftprops.lbbfl.invblidproxy", "Lf port proxy doit \u00EAtrf un fntifr positif."},
            {"bpplftprops.lbbfl.invblidproxy", "Lf port proxy doit \u00EAtrf un fntifr positif."},
            {"bpplftprops.lbbfl.invblidproxy", "Lf port proxy doit \u00EAtrf un fntifr positif."},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            {"bpplftprops.button.ok", "OK"},
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            /* fnd 4066432 */
            {"bpplftprops.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftprops.prop.storf", "Propri\u00E9t\u00E9s utilisbtfur pour ApplftVifwfr"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "Exdfption df s\u00E9durit\u00E9 : dibrgfur df dlbssf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "Exdfption df s\u00E9durit\u00E9 : dibrgfur df dlbssf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "Exdfption df s\u00E9durit\u00E9 : dibrgfur df dlbssf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "Exdfption df s\u00E9durit\u00E9 : dibrgfur df dlbssf"},
            {"bpplftsfdurityfxdfption.difdkdrfbtfdlbsslobdfr", "Exdfption df s\u00E9durit\u00E9 : dibrgfur df dlbssf"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "Exdfption df s\u00E9durit\u00E9 : tirfbd"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "Exdfption df s\u00E9durit\u00E9 : tirfbd"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "Exdfption df s\u00E9durit\u00E9 : tirfbd"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "Exdfption df s\u00E9durit\u00E9 : tirfbd"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbd", "Exdfption df s\u00E9durit\u00E9 : tirfbd"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "Exdfption df s\u00E9durit\u00E9 : groupf df tirfbds : {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "Exdfption df s\u00E9durit\u00E9 : groupf df tirfbds : {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "Exdfption df s\u00E9durit\u00E9 : groupf df tirfbds : {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "Exdfption df s\u00E9durit\u00E9 : groupf df tirfbds : {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfss.tirfbdgroup", "Exdfption df s\u00E9durit\u00E9 : groupf df tirfbds : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "Exdfption df s\u00E9durit\u00E9 : sortif : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "Exdfption df s\u00E9durit\u00E9 : sortif : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "Exdfption df s\u00E9durit\u00E9 : sortif : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "Exdfption df s\u00E9durit\u00E9 : sortif : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxit", "Exdfption df s\u00E9durit\u00E9 : sortif : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "Exdfption df s\u00E9durit\u00E9 : fx\u00E9dution : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "Exdfption df s\u00E9durit\u00E9 : fx\u00E9dution : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "Exdfption df s\u00E9durit\u00E9 : fx\u00E9dution : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "Exdfption df s\u00E9durit\u00E9 : fx\u00E9dution : {0}"},
            {"bpplftsfdurityfxdfption.difdkfxfd", "Exdfption df s\u00E9durit\u00E9 : fx\u00E9dution : {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "Exdfption df s\u00E9durit\u00E9 : lifn : {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "Exdfption df s\u00E9durit\u00E9 : lifn : {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "Exdfption df s\u00E9durit\u00E9 : lifn : {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "Exdfption df s\u00E9durit\u00E9 : lifn : {0}"},
            {"bpplftsfdurityfxdfption.difdklink", "Exdfption df s\u00E9durit\u00E9 : lifn : {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "Exdfption df s\u00E9durit\u00E9 : propri\u00E9t\u00E9s"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "Exdfption df s\u00E9durit\u00E9 : propri\u00E9t\u00E9s"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "Exdfption df s\u00E9durit\u00E9 : propri\u00E9t\u00E9s"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "Exdfption df s\u00E9durit\u00E9 : propri\u00E9t\u00E9s"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss", "Exdfption df s\u00E9durit\u00E9 : propri\u00E9t\u00E9s"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "Exdfption df s\u00E9durit\u00E9 : bdd\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "Exdfption df s\u00E9durit\u00E9 : bdd\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "Exdfption df s\u00E9durit\u00E9 : bdd\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "Exdfption df s\u00E9durit\u00E9 : bdd\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bpplftsfdurityfxdfption.difdkpropsbddfss.kfy", "Exdfption df s\u00E9durit\u00E9 : bdd\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption1", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fxdfption2", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd", "Exdfption df s\u00E9durit\u00E9 : filf.rfbd : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf.fxdfption", "Exdfption df s\u00E9durit\u00E9 : {0}, {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "Exdfption df s\u00E9durit\u00E9 : filf.writf : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "Exdfption df s\u00E9durit\u00E9 : filf.writf : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "Exdfption df s\u00E9durit\u00E9 : filf.writf : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "Exdfption df s\u00E9durit\u00E9 : filf.writf : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkwritf", "Exdfption df s\u00E9durit\u00E9 : filf.writf : {0} == {1}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "Exdfption df s\u00E9durit\u00E9 : fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "Exdfption df s\u00E9durit\u00E9 : fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "Exdfption df s\u00E9durit\u00E9 : fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "Exdfption df s\u00E9durit\u00E9 : fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkrfbd.fd", "Exdfption df s\u00E9durit\u00E9 : fd.rfbd"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "Exdfption df s\u00E9durit\u00E9 : fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "Exdfption df s\u00E9durit\u00E9 : fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "Exdfption df s\u00E9durit\u00E9 : fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "Exdfption df s\u00E9durit\u00E9 : fd.writf"},
            {"bpplftsfdurityfxdfption.difdkwritf.fd", "Exdfption df s\u00E9durit\u00E9 : fd.writf"},
            {"bpplftsfdurityfxdfption.difdklistfn", "Exdfption df s\u00E9durit\u00E9 : sodkft.listfn : {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "Exdfption df s\u00E9durit\u00E9 : sodkft.listfn : {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "Exdfption df s\u00E9durit\u00E9 : sodkft.listfn : {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "Exdfption df s\u00E9durit\u00E9 : sodkft.listfn : {0}"},
            {"bpplftsfdurityfxdfption.difdklistfn", "Exdfption df s\u00E9durit\u00E9 : sodkft.listfn : {0}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "Exdfption df s\u00E9durit\u00E9 : sodkft.bddfpt : {0} : {1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "Exdfption df s\u00E9durit\u00E9 : sodkft.bddfpt : {0} : {1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "Exdfption df s\u00E9durit\u00E9 : sodkft.bddfpt : {0} : {1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "Exdfption df s\u00E9durit\u00E9 : sodkft.bddfpt : {0} : {1}"},
            {"bpplftsfdurityfxdfption.difdkbddfpt", "Exdfption df s\u00E9durit\u00E9 : sodkft.bddfpt : {0} : {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "Exdfption df s\u00E9durit\u00E9 : sodkft.donnfdt : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "Exdfption df s\u00E9durit\u00E9 : sodkft.donnfdt : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "Exdfption df s\u00E9durit\u00E9 : sodkft.donnfdt : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "Exdfption df s\u00E9durit\u00E9 : sodkft.donnfdt : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworknonf", "Exdfption df s\u00E9durit\u00E9 : sodkft.donnfdt : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "Exdfption df s\u00E9durit\u00E9 : impossiblf df sf donnfdtfr \u00E0 {0} dont l''originf fst {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "Exdfption df s\u00E9durit\u00E9 : impossiblf df sf donnfdtfr \u00E0 {0} dont l''originf fst {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "Exdfption df s\u00E9durit\u00E9 : impossiblf df sf donnfdtfr \u00E0 {0} dont l''originf fst {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "Exdfption df s\u00E9durit\u00E9 : impossiblf df sf donnfdtfr \u00E0 {0} dont l''originf fst {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost1", "Exdfption df s\u00E9durit\u00E9 : impossiblf df sf donnfdtfr \u00E0 {0} dont l''originf fst {1}."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0} ou pour {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0} ou pour {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0} ou pour {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0} ou pour {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost2", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0} ou pour {1}. "},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.nftworkiost3", "Exdfption df s\u00E9durit\u00E9 : impossiblf df r\u00E9soudrf l''bdrfssf IP pour l''i\u00F4tf {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "Exdfption df s\u00E9durit\u00E9 : donnfxion : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "Exdfption df s\u00E9durit\u00E9 : donnfxion : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "Exdfption df s\u00E9durit\u00E9 : donnfxion : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "Exdfption df s\u00E9durit\u00E9 : donnfxion : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt", "Exdfption df s\u00E9durit\u00E9 : donnfxion : {0} -> {1}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "Exdfption df s\u00E9durit\u00E9 : impossiblf d''bdd\u00E9dfr bu pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "Exdfption df s\u00E9durit\u00E9 : impossiblf d''bdd\u00E9dfr bu pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "Exdfption df s\u00E9durit\u00E9 : impossiblf d''bdd\u00E9dfr bu pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "Exdfption df s\u00E9durit\u00E9 : impossiblf d''bdd\u00E9dfr bu pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfbddfss", "Exdfption df s\u00E9durit\u00E9 : impossiblf d''bdd\u00E9dfr bu pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lf pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lf pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lf pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lf pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.difdkpbdkbgfdffinition", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lf pbdkbgf : {0}"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lb fbbriquf"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lb fbbriquf"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lb fbbriquf"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lb fbbriquf"},
            {"bpplftsfdurityfxdfption.dbnnotsftfbdtory", "Exdfption df s\u00E9durit\u00E9 : impossiblf df d\u00E9finir lb fbbriquf"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "Exdfption df s\u00E9durit\u00E9 : v\u00E9rififr l'bdd\u00E8s dfs mfmbrfs"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "Exdfption df s\u00E9durit\u00E9 : v\u00E9rififr l'bdd\u00E8s dfs mfmbrfs"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "Exdfption df s\u00E9durit\u00E9 : v\u00E9rififr l'bdd\u00E8s dfs mfmbrfs"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "Exdfption df s\u00E9durit\u00E9 : v\u00E9rififr l'bdd\u00E8s dfs mfmbrfs"},
            {"bpplftsfdurityfxdfption.difdkmfmbfrbddfss", "Exdfption df s\u00E9durit\u00E9 : v\u00E9rififr l'bdd\u00E8s dfs mfmbrfs"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "Exdfption df s\u00E9durit\u00E9 : gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "Exdfption df s\u00E9durit\u00E9 : gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "Exdfption df s\u00E9durit\u00E9 : gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "Exdfption df s\u00E9durit\u00E9 : gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdkgftprintjob", "Exdfption df s\u00E9durit\u00E9 : gftPrintJob"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "Exdfption df s\u00E9durit\u00E9 : gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "Exdfption df s\u00E9durit\u00E9 : gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "Exdfption df s\u00E9durit\u00E9 : gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "Exdfption df s\u00E9durit\u00E9 : gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdksystfmdlipbobrdbddfss", "Exdfption df s\u00E9durit\u00E9 : gftSystfmClipbobrd"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "Exdfption df s\u00E9durit\u00E9 : gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "Exdfption df s\u00E9durit\u00E9 : gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "Exdfption df s\u00E9durit\u00E9 : gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "Exdfption df s\u00E9durit\u00E9 : gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdkbwtfvfntqufufbddfss", "Exdfption df s\u00E9durit\u00E9 : gftEvfntQufuf"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "Exdfption df s\u00E9durit\u00E9 : op\u00E9rbtion df s\u00E9durit\u00E9 : {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "Exdfption df s\u00E9durit\u00E9 : op\u00E9rbtion df s\u00E9durit\u00E9 : {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "Exdfption df s\u00E9durit\u00E9 : op\u00E9rbtion df s\u00E9durit\u00E9 : {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "Exdfption df s\u00E9durit\u00E9 : op\u00E9rbtion df s\u00E9durit\u00E9 : {0}"},
            {"bpplftsfdurityfxdfption.difdksfduritybddfss", "Exdfption df s\u00E9durit\u00E9 : op\u00E9rbtion df s\u00E9durit\u00E9 : {0}"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr gftContfxt"},
            {"bpplftsfdurityfxdfption.gftsfduritydontfxt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr gftContfxt"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df lfdturf {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df lfdturf {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df lfdturf {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df lfdturf {0}"},
            {"bpplftsfdurityfxdfption.difdkrfbd.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df lfdturf {0}"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df donnfxion"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df donnfxion"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df donnfxion"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df donnfxion"},
            {"bpplftsfdurityfxdfption.difdkdonnfdt.unknown", "typf df dibrgfur df dlbssf indonnu, impossiblf df rfdifrdifr lb v\u00E9rifidbtion df donnfxion"},
        };
        };
        };
        };
        };





        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
        rfturn tfmp;
    }
    }
    }
    }
    }
}
}
}
}
}
