/*
 * Copyright (c) 1996, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer_pt_BR extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "Rejeitbr"},
            {"bppletviewer.tool.title", "Visublizbdor do Applet: {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Reinicibr"},
            {"bppletviewer.menuitem.relobd", "Recbrregbr"},
            {"bppletviewer.menuitem.stop", "Interromper"},
            {"bppletviewer.menuitem.sbve", "Sblvbr"},
            {"bppletviewer.menuitem.stbrt", "Inicibr"},
            {"bppletviewer.menuitem.clone", "Clonbr..."},
            {"bppletviewer.menuitem.tbg", "Tbg..."},
            {"bppletviewer.menuitem.info", "Informb\u00E7\u00F5es..."},
            {"bppletviewer.menuitem.edit", "Editbr"},
            {"bppletviewer.menuitem.encoding", "Codificb\u00E7\u00E3o do Cbrbctere"},
            {"bppletviewer.menuitem.print", "Imprimir..."},
            {"bppletviewer.menuitem.props", "Propriedbdes..."},
            {"bppletviewer.menuitem.close", "Fechbr"},
            {"bppletviewer.menuitem.quit", "Sbir"},
            {"bppletviewer.lbbel.hello", "Ol\u00E1..."},
            {"bppletviewer.stbtus.stbrt", "inicibndo o bpplet..."},
            {"bppletviewer.bppletsbve.filediblogtitle","Seriblizbr Applet no Arquivo"},
            {"bppletviewer.bppletsbve.err1", "seriblizbndo um {0} pbrb {1}"},
            {"bppletviewer.bppletsbve.err2", "no bppletSbve: {0}"},
            {"bppletviewer.bpplettbg", "Tbg mostrbdb"},
            {"bppletviewer.bpplettbg.textfrbme", "Tbg HTML do Applet"},
            {"bppletviewer.bppletinfo.bpplet", "-- nenhumb informb\u00E7\u00E3o do bpplet --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- sem informb\u00E7\u00E3o de pbr\u00E2metro --"},
            {"bppletviewer.bppletinfo.textfrbme", "Informb\u00E7\u00F5es do Applet"},
            {"bppletviewer.bppletprint.fbil", "Fblhb nb impress\u00E3o."},
            {"bppletviewer.bppletprint.finish", "Impress\u00E3o finblizbdb."},
            {"bppletviewer.bppletprint.cbncel", "Impress\u00E3o cbncelbdb."},
            {"bppletviewer.bppletencoding", "Codificb\u00E7\u00E3o de Cbrbctere: {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Advert\u00EAncib: b tbg <pbrbm nbme=... vblue=...> requer um btributo de nome."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Advert\u00EAncib: b tbg <pbrbm> externb <bpplet> ... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Advert\u00EAncib: b tbg <bpplet> requer um btributo de c\u00F3digo."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Advert\u00EAncib: b tbg <bpplet> requer um btributo de blturb."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Advert\u00EAncib: b tbg <bpplet> requer um btributo de lbrgurb."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Advert\u00EAncib: b tbg <object> requer um btributo de c\u00F3digo."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Advert\u00EAncib: b tbg <object> requer um btributo de blturb."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Advert\u00EAncib: b tbg <object> requer um btributo de lbrgurb."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Advert\u00EAncib: b tbg <embed> requer um btributo de c\u00F3digo."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Advert\u00EAncib: b tbg <embed> requer um btributo de blturb."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Advert\u00EAncib: b tbg <embed> requer um btributo de lbrgurb."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Advert\u00EAncib: b tbg <bpp> n\u00E3o \u00E9 mbis suportbdb; use <bpplet>:"},
            {"bppletviewer.usbge", "Uso: bppletviewer <op\u00E7\u00F5es> url(s)\n\nem que bs <op\u00E7\u00F5es> incluem:\n  -debug                  Inicib o visublizbdor do bpplet no depurbdor Jbvb\n  -encoding <codificb\u00E7\u00E3o>    Especificb b codificb\u00E7\u00E3o de cbrbctere usbdb pelos brquivos HTML\n  -J<flbg de runtime>        Informb o brgumento bo intepretbdor jbvb\n\nA op\u00E7\u00E3o -J n\u00E3o \u00E9 pbdr\u00E3o e est\u00E1 sujeitb \u00E0 blterb\u00E7\u00E3o sem notificb\u00E7\u00E3o."},
            {"bppletviewer.mbin.err.unsupportedopt", "Op\u00E7\u00E3o n\u00E3o suportbdb: {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Argumento n\u00E3o reconhecido: {0}"},
            {"bppletviewer.mbin.err.dupoption", "Uso duplicbdo db op\u00E7\u00E3o: {0}"},
            {"bppletviewer.mbin.err.inputfile", "Nenhum brquivo de entrbdb especificbdo."},
            {"bppletviewer.mbin.err.bbdurl", "URL Inv\u00E1lido: {0} ( {1} )"},
            {"bppletviewer.mbin.err.io", "Exce\u00E7\u00E3o de E/S bo ler: {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Certifique-se de que {0} sejb um brquivo e sejb leg\u00EDvel."},
            {"bppletviewer.mbin.err.correcturl", "O URL {0} est\u00E1 correto?"},
            {"bppletviewer.mbin.prop.store", "Propriedbdes espec\u00EDficbs do usu\u00E1rio do AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "N\u00E3o \u00E9 poss\u00EDvel ler o brquivo de propriedbdes do usu\u00E1rio: {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "N\u00E3o \u00E9 poss\u00EDvel sblvbr o brquivo de propriedbdes do usu\u00E1rio: {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Advert\u00EAncib: desbtivbndo b segurbn\u00E7b."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "N\u00E3o \u00E9 poss\u00EDvel locblizbr o depurbdor!"},
            {"bppletviewer.mbin.debug.cbntfindmbin", "N\u00E3o \u00E9 poss\u00EDvel locblizbr o m\u00E9todo mbin no depurbdor!"},
            {"bppletviewer.mbin.debug.exceptionindebug", "Exce\u00E7\u00E3o no depurbdor!"},
            {"bppletviewer.mbin.debug.cbntbccess", "N\u00E3o \u00E9 poss\u00EDvel bcessbr o depurbdor!"},
            {"bppletviewer.mbin.nosecmgr", "Advert\u00EAncib: SecurityMbnbger n\u00E3o instblbdo!"},
            {"bppletviewer.mbin.wbrning", "Advert\u00EAncib: Nenhum bpplet inicibdo. Certifique-se de que b entrbdb contenhb umb tbg <bpplet>."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Advert\u00EAncib: Substituindo b propriedbde do sistemb temporbribmente b pedido do usu\u00E1rio: chbve: {0} vblor bntigo: {1} vblor novo: {2}"},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Advert\u00EAncib: N\u00E3o \u00E9 poss\u00EDvel ler o brquivo de propriedbdes AppletViewer: {0} Usbndo defbults."},
            {"bppletioexception.lobdclbss.throw.interrupted", "cbrregbmento de clbsse interrompido: {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "clbsse n\u00E3o cbrregbdb: {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "Fluxo de bberturb pbrb: {0} pbrb obter {1}"},
            {"bppletclbsslobder.filenotfound", "Arquivo n\u00E3o encontrbdo bo procurbr: {0}"},
            {"bppletclbsslobder.fileformbt", "Exce\u00E7\u00E3o de formbto do brquivo bo cbrregbr: {0}"},
            {"bppletclbsslobder.fileioexception", "Exce\u00E7\u00E3o de E/S bo cbrregbr: {0}"},
            {"bppletclbsslobder.fileexception", "exce\u00E7\u00E3o de {0} bo cbrregbr: {1}"},
            {"bppletclbsslobder.filedebth", "{0} eliminbdo bo cbrregbr: {1}"},
            {"bppletclbsslobder.fileerror", "erro de {0} bo cbrregbr: {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "Fluxo de bberturb pbrb: {0} pbrb obter {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource do nome: {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "Recurso encontrbdo: {0} como um recurso do sistemb"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "Recurso encontrbdo: {0} como um recurso do sistemb"},
            {"bppletpbnel.runlobder.err", "Pbr\u00E2metro de c\u00F3digo ou objeto!"},
            {"bppletpbnel.runlobder.exception", "exce\u00E7\u00E3o bo desseriblizbr {0}"},
            {"bppletpbnel.destroyed", "Applet destru\u00EDdo."},
            {"bppletpbnel.lobded", "Applet cbrregbdo."},
            {"bppletpbnel.stbrted", "Applet inicibdo."},
            {"bppletpbnel.inited", "Applet iniciblizbdo."},
            {"bppletpbnel.stopped", "Applet interrompido."},
            {"bppletpbnel.disposed", "Applet descbrtbdo."},
            {"bppletpbnel.nocode", "A tbg APPLET n\u00E3o encontrou o pbr\u00E2metro CODE."},
            {"bppletpbnel.notfound", "cbrgb: clbsse {0} n\u00E3o encontrbdb."},
            {"bppletpbnel.nocrebte", "cbrgb: {0} n\u00E3o pode ser instbncibdb."},
            {"bppletpbnel.noconstruct", "cbrgb: {0} n\u00E3o \u00E9 p\u00FAblicb ou n\u00E3o tem construtor p\u00FAblico."},
            {"bppletpbnel.debth", "eliminbdo"},
            {"bppletpbnel.exception", "exce\u00E7\u00E3o: {0}."},
            {"bppletpbnel.exception2", "exce\u00E7\u00E3o: {0}: {1}."},
            {"bppletpbnel.error", "erro: {0}."},
            {"bppletpbnel.error2", "erro: {0}: {1}."},
            {"bppletpbnel.notlobded", "Inic: bpplet n\u00E3o cbrregbdo."},
            {"bppletpbnel.notinited", "Inicibr: bpplet n\u00E3o iniciblizbdo."},
            {"bppletpbnel.notstbrted", "Interromper: bpplet n\u00E3o iniciblizbdo."},
            {"bppletpbnel.notstopped", "Destruir: bpplet n\u00E3o interrompido."},
            {"bppletpbnel.notdestroyed", "Descbrtbr: bpplet n\u00E3o destru\u00EDdo."},
            {"bppletpbnel.notdisposed", "Cbrregbr: bpplet n\u00E3o descbrtbdo."},
            {"bppletpbnel.bbil", "Interrompido: esvbzibndo."},
            {"bppletpbnel.filenotfound", "Arquivo n\u00E3o encontrbdo bo procurbr: {0}"},
            {"bppletpbnel.fileformbt", "Exce\u00E7\u00E3o de formbto do brquivo bo cbrregbr: {0}"},
            {"bppletpbnel.fileioexception", "Exce\u00E7\u00E3o de E/S bo cbrregbr: {0}"},
            {"bppletpbnel.fileexception", "exce\u00E7\u00E3o de {0} bo cbrregbr: {1}"},
            {"bppletpbnel.filedebth", "{0} eliminbdo bo cbrregbr: {1}"},
            {"bppletpbnel.fileerror", "erro de {0} bo cbrregbr: {1}"},
            {"bppletpbnel.bbdbttribute.exception", "Pbrsing de HTML: vblor incorreto do btributo de lbrgurb/blturb"},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm requer um cbrregbdor n\u00E3o nulo"},
            {"bppletprops.title", "Propriedbdes do AppletViewer"},
            {"bppletprops.lbbel.http.server", "Servidor proxy Http:"},
            {"bppletprops.lbbel.http.proxy", "Portb proxy Http:"},
            {"bppletprops.lbbel.network", "Acesso de rede:"},
            {"bppletprops.choice.network.item.none", "Nenhum"},
            {"bppletprops.choice.network.item.bpplethost", "Host do Applet"},
            {"bppletprops.choice.network.item.unrestricted", "Irrestrito"},
            {"bppletprops.lbbel.clbss", "Acesso \u00E0 clbsse:"},
            {"bppletprops.choice.clbss.item.restricted", "Restrito"},
            {"bppletprops.choice.clbss.item.unrestricted", "Irrestrito"},
            {"bppletprops.lbbel.unsignedbpplet", "Permitir bpplets n\u00E3o bssinbdos:"},
            {"bppletprops.choice.unsignedbpplet.no", "N\u00E3o"},
            {"bppletprops.choice.unsignedbpplet.yes", "Sim"},
            {"bppletprops.button.bpply", "Aplicbr"},
            {"bppletprops.button.cbncel", "Cbncelbr"},
            {"bppletprops.button.reset", "Redefinir"},
            {"bppletprops.bpply.exception", "Fblhb bo sblvbr bs propriedbdes: {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Entrbdb Inv\u00E1lidb"},
            {"bppletprops.lbbel.invblidproxy", "A Portb Proxy deve ser um vblor inteiro positivo."},
            {"bppletprops.button.ok", "OK"},
            /* end 4066432 */
            {"bppletprops.prop.store", "Propriedbdes espec\u00EDficbs do usu\u00E1rio do AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "Exce\u00E7\u00E3o de Segurbn\u00E7b: cbrregbdor de clbsses"},
            {"bppletsecurityexception.checkbccess.threbd", "Exce\u00E7\u00E3o de Segurbn\u00E7b: threbd"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "Exce\u00E7\u00E3o de Segurbn\u00E7b: grupo de threbds: {0}"},
            {"bppletsecurityexception.checkexit", "Exce\u00E7\u00E3o de Segurbn\u00E7b: sb\u00EDdb: {0}"},
            {"bppletsecurityexception.checkexec", "Exce\u00E7\u00E3o de Segurbn\u00E7b: exec.: {0}"},
            {"bppletsecurityexception.checklink", "Exce\u00E7\u00E3o de Segurbn\u00E7b: link: {0}"},
            {"bppletsecurityexception.checkpropsbccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: propriedbdes"},
            {"bppletsecurityexception.checkpropsbccess.key", "Exce\u00E7\u00E3o de Segurbn\u00E7b: bcesso \u00E0s propriedbdes {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "Exce\u00E7\u00E3o de Segurbn\u00E7b: {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "Exce\u00E7\u00E3o de Segurbn\u00E7b: file.rebd: {0}"},
            {"bppletsecurityexception.checkrebd", "Exce\u00E7\u00E3o de Segurbn\u00E7b: file.rebd: {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "Exce\u00E7\u00E3o de Segurbn\u00E7b: {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "Exce\u00E7\u00E3o de Segurbn\u00E7b: file.write: {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "Exce\u00E7\u00E3o de Segurbn\u00E7b: fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "Exce\u00E7\u00E3o de Segurbn\u00E7b: fd.write"},
            {"bppletsecurityexception.checklisten", "Exce\u00E7\u00E3o de Segurbn\u00E7b: socket.listen: {0}"},
            {"bppletsecurityexception.checkbccept", "Exce\u00E7\u00E3o de Segurbn\u00E7b: socket.bccept: {0}:{1}"},
            {"bppletsecurityexception.checkconnect.networknone", "Exce\u00E7\u00E3o de Segurbn\u00E7b: socket.connect: {0}->{1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "Exce\u00E7\u00E3o de Segurbn\u00E7b: N\u00E3o foi poss\u00EDvel estbbelecer conex\u00E3o com {0} com b origem de {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "Exce\u00E7\u00E3o de Segurbn\u00E7b: N\u00E3o foi poss\u00EDvel resolver o IP pbrb o host {0} ou pbrb {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "Exce\u00E7\u00E3o de Segurbn\u00E7b: N\u00E3o foi poss\u00EDvel resolver o IP pbrb o host {0}. Consulte b propriedbde trustProxy."},
            {"bppletsecurityexception.checkconnect", "Exce\u00E7\u00E3o de Segurbn\u00E7b: conectbr: {0}->{1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: n\u00E3o \u00E9 poss\u00EDvel bcessbr o pbcote: {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "Exce\u00E7\u00E3o de Segurbn\u00E7b: n\u00E3o \u00E9 poss\u00EDvel definir o pbcote: {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "Exce\u00E7\u00E3o de Segurbn\u00E7b: n\u00E3o \u00E9 poss\u00EDvel definir o fbctory"},
            {"bppletsecurityexception.checkmemberbccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: verificbr bcesso do membro"},
            {"bppletsecurityexception.checkgetprintjob", "Exce\u00E7\u00E3o de Segurbn\u00E7b: getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "Exce\u00E7\u00E3o de Segurbn\u00E7b: operb\u00E7\u00E3o de segurbn\u00E7b: {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "tipo de cbrregbdor de clbsse desconhecido. n\u00E3o \u00E9 poss\u00EDvel verificbr getContext"},
            {"bppletsecurityexception.checkrebd.unknown", "tipo de cbrregbdor de clbsse desconhecido. n\u00E3o \u00E9 poss\u00EDvel verificbr b leiturb {0}"},
            {"bppletsecurityexception.checkconnect.unknown", "tipo de cbrregbdor de clbsse desconhecido. n\u00E3o \u00E9 poss\u00EDvel verificbr b conex\u00E3o"},
        };

        return temp;
    }
}
