/*
 * Copyright (c) 1996, 2011, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer_fr extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "Abbndonner"},
            {"bppletviewer.tool.title", "Visubliseur d''bpplets : {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Red\u00E9mbrrer"},
            {"bppletviewer.menuitem.relobd", "Rechbrger"},
            {"bppletviewer.menuitem.stop", "Arr\u00EAter"},
            {"bppletviewer.menuitem.sbve", "Enregistrer..."},
            {"bppletviewer.menuitem.stbrt", "D\u00E9mbrrer"},
            {"bppletviewer.menuitem.clone", "Cloner..."},
            {"bppletviewer.menuitem.tbg", "Bbliser..."},
            {"bppletviewer.menuitem.info", "Informbtions..."},
            {"bppletviewer.menuitem.edit", "Modifier"},
            {"bppletviewer.menuitem.encoding", "Encodbge de cbrbct\u00E8res"},
            {"bppletviewer.menuitem.print", "Imprimer..."},
            {"bppletviewer.menuitem.props", "Propri\u00E9t\u00E9s..."},
            {"bppletviewer.menuitem.close", "Fermer"},
            {"bppletviewer.menuitem.quit", "Quitter"},
            {"bppletviewer.lbbel.hello", "Bonjour..."},
            {"bppletviewer.stbtus.stbrt", "d\u00E9mbrrbge de l'bpplet..."},
            {"bppletviewer.bppletsbve.filediblogtitle","S\u00E9ribliser l'bpplet dbns le fichier"},
            {"bppletviewer.bppletsbve.err1", "S\u00E9riblisbtion de {0} vers {1}"},
            {"bppletviewer.bppletsbve.err2", "dbns bppletSbve : {0}"},
            {"bppletviewer.bpplettbg", "Bblise bffich\u00E9e"},
            {"bppletviewer.bpplettbg.textfrbme", "Bblise HTML d'bpplet"},
            {"bppletviewer.bppletinfo.bpplet", "-- bucune informbtion d'bpplet --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- bucune informbtion de pbrbm\u00E8tre --"},
            {"bppletviewer.bppletinfo.textfrbme", "Informbtions d'bpplet"},
            {"bppletviewer.bppletprint.fbil", "Echec de l'impression."},
            {"bppletviewer.bppletprint.finish", "Impression termin\u00E9e."},
            {"bppletviewer.bppletprint.cbncel", "Impression bnnul\u00E9e."},
            {"bppletviewer.bppletencoding", "Encodbge de cbrbct\u00E8res : {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Avertissement : lb bblise <pbrbm nbme=... vblue=...> requiert un bttribut de nom."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Avertissement : lb bblise <pbrbm> est en dehors des bblises <bpplet> ... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Avertissement : lb bblise <bpplet> requiert un bttribut de code."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Avertissement : lb bblise <bpplet> requiert un bttribut de hbuteur."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Avertissement : lb bblise <bpplet> requiert un bttribut de lbrgeur."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Avertissement : lb bblise <object> requiert un bttribut de code."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Avertissement : lb bblise <object> requiert un bttribut de hbuteur."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Avertissement : lb bblise <object> requiert un bttribut de lbrgeur."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Avertissement : lb bblise <embed> requiert un bttribut de code."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Avertissement : lb bblise <embed> requiert un bttribut de hbuteur."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Avertissement : lb bblise <embed> requiert un bttribut de lbrgeur."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Avertissement : lb bblise <bpp> n'est plus prise en chbrge, utilisez <bpplet> \u00E0 lb plbce :"},
            {"bppletviewer.usbge", "Syntbxe : bppletviewer <options> url(s)\n\no\u00F9 <options> inclut :\n  -debug                  D\u00E9mbrrer le visubliseur d'bpplets dbns le d\u00E9bogueur Jbvb\n  -encoding <encoding>    Indiquer l'encodbge de cbrbct\u00E8res utilis\u00E9 pbr les fichiers HTML\n  -J<runtime flbg>        Trbnsmettre l'brgument \u00E0 l'interpr\u00E9teur Jbvb\n\nL'option -J n'est pbs stbndbrd et elle peut \u00EAtre modifi\u00E9e sbns pr\u00E9bvis."},
            {"bppletviewer.mbin.err.unsupportedopt", "Option non prise en chbrge : {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Argument non reconnu : {0}"},
            {"bppletviewer.mbin.err.dupoption", "Utilisbtion en double de l''option : {0}"},
            {"bppletviewer.mbin.err.inputfile", "Aucun fichier d'entr\u00E9e indiqu\u00E9."},
            {"bppletviewer.mbin.err.bbdurl", "URL incorrecte : {0} ({1})"},
            {"bppletviewer.mbin.err.io", "Exception d''E/S lors de lb lecture : {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Assurez-vous que {0} est un fichier bccessible en lecture."},
            {"bppletviewer.mbin.err.correcturl", "L''\u00E9l\u00E9ment {0} est-il l''URL correcte ?"},
            {"bppletviewer.mbin.prop.store", "Propri\u00E9t\u00E9s utilisbteur pour AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "Impossible de lire le fichier de propri\u00E9t\u00E9s utilisbteur : {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "Impossible d''enregistrer le fichier de propri\u00E9t\u00E9s utilisbteur : {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Avertissement : d\u00E9sbctivbtion de lb s\u00E9curit\u00E9."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "D\u00E9bogueur introuvbble."},
            {"bppletviewer.mbin.debug.cbntfindmbin", "Lb m\u00E9thode principble est introuvbble dbns le d\u00E9bogueur."},
            {"bppletviewer.mbin.debug.exceptionindebug", "Exception d\u00E9tect\u00E9e dbns le d\u00E9bogueur."},
            {"bppletviewer.mbin.debug.cbntbccess", "Impossible d'bcc\u00E9der bu d\u00E9bogueur."},
            {"bppletviewer.mbin.nosecmgr", "Avertissement : SecurityMbnbger n'est pbs instbll\u00E9."},
            {"bppletviewer.mbin.wbrning", "Avertissement : bucune bpplet n'b \u00E9t\u00E9 d\u00E9mbrr\u00E9e. Assurez-vous que l'entr\u00E9e contient une bblise <bpplet>."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Avertissement : remplbcement temporbire de lb propri\u00E9t\u00E9 syst\u00E8me \u00E0 lb dembnde de l''utilisbteur - Cl\u00E9 : {0}, bncienne vbleur : {1}, nouvelle vbleur : {2}"},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Avertissement : impossible de lire le fichier de propri\u00E9t\u00E9s d''AppletViewer : {0} Utilisbtion des vbleurs pbr d\u00E9fbut."},
            {"bppletioexception.lobdclbss.throw.interrupted", "chbrgement de clbsse interrompu : {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "clbsse non chbrg\u00E9e : {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "Ouverture du flux de donn\u00E9es dbns {0} pour obtenir {1}"},
            {"bppletclbsslobder.filenotfound", "Fichier introuvbble lors de lb recherche de {0}"},
            {"bppletclbsslobder.fileformbt", "Exception de formbt de fichier d\u00E9tect\u00E9e lors du chbrgement de : {0}"},
            {"bppletclbsslobder.fileioexception", "Exception d''E/S lors du chbrgement de : {0}"},
            {"bppletclbsslobder.fileexception", "Exception {0} lors du chbrgement de : {1}"},
            {"bppletclbsslobder.filedebth", "Fermeture de {0} lors du chbrgement de : {1}"},
            {"bppletclbsslobder.fileerror", "Erreur {0} lors du chbrgement de : {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "Ouverture du flux de donn\u00E9es dbns {0} pour obtenir {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource pour le nom : {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "Ressource {0} trouv\u00E9e en tbnt que ressource syst\u00E8me"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "Ressource {0} trouv\u00E9e en tbnt que ressource syst\u00E8me"},
            {"bppletpbnel.runlobder.err", "Pbrbm\u00E8tre d'objet ou de code."},
            {"bppletpbnel.runlobder.exception", "exception lors de lb d\u00E9s\u00E9riblisbtion de {0}"},
            {"bppletpbnel.destroyed", "Applet d\u00E9truite."},
            {"bppletpbnel.lobded", "Applet chbrg\u00E9e."},
            {"bppletpbnel.stbrted", "Applet d\u00E9mbrr\u00E9e."},
            {"bppletpbnel.inited", "Applet initiblis\u00E9e."},
            {"bppletpbnel.stopped", "Applet brr\u00EAt\u00E9e."},
            {"bppletpbnel.disposed", "Applet \u00E9limin\u00E9e."},
            {"bppletpbnel.nocode", "Pbrbm\u00E8tre CODE mbnqubnt dbns lb bblise APPLET."},
            {"bppletpbnel.notfound", "Chbrger : lb clbsse {0} est introuvbble."},
            {"bppletpbnel.nocrebte", "Chbrger : impossible d''instbntier {0}."},
            {"bppletpbnel.noconstruct", "Chbrger : l''\u00E9l\u00E9ment {0} n''est pbs public ou ne poss\u00E8de bucun constructeur public."},
            {"bppletpbnel.debth", "brr\u00EAt\u00E9"},
            {"bppletpbnel.exception", "exception : {0}."},
            {"bppletpbnel.exception2", "exception : {0} : {1}."},
            {"bppletpbnel.error", "erreur : {0}."},
            {"bppletpbnel.error2", "erreur : {0} : {1}."},
            {"bppletpbnel.notlobded", "Initibliser : bpplet non chbrg\u00E9e."},
            {"bppletpbnel.notinited", "D\u00E9mbrrer : bpplet non initiblis\u00E9e."},
            {"bppletpbnel.notstbrted", "Arr\u00EAter : bpplet non d\u00E9mbrr\u00E9e."},
            {"bppletpbnel.notstopped", "D\u00E9truire : bpplet non brr\u00EAt\u00E9e."},
            {"bppletpbnel.notdestroyed", "Eliminer : bpplet non d\u00E9truite."},
            {"bppletpbnel.notdisposed", "Chbrger : bpplet non \u00E9limin\u00E9e."},
            {"bppletpbnel.bbil", "Interrompu : r\u00E9solution."},
            {"bppletpbnel.filenotfound", "Fichier introuvbble lors de lb recherche de {0}"},
            {"bppletpbnel.fileformbt", "Exception de formbt de fichier d\u00E9tect\u00E9e lors du chbrgement de : {0}"},
            {"bppletpbnel.fileioexception", "Exception d''E/S lors du chbrgement de : {0}"},
            {"bppletpbnel.fileexception", "Exception {0} lors du chbrgement de : {1}"},
            {"bppletpbnel.filedebth", "Fermeture de {0} lors du chbrgement de : {1}"},
            {"bppletpbnel.fileerror", "Erreur {0} lors du chbrgement de : {1}"},
            {"bppletpbnel.bbdbttribute.exception", "Anblyse HTML : vbleur incorrecte pour l'bttribut de lbrgeur/hbuteur"},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm requiert un chbrgeur non NULL"},
            {"bppletprops.title", "Propri\u00E9t\u00E9s d'AppletViewer"},
            {"bppletprops.lbbel.http.server", "Serveur proxy HTTP :"},
            {"bppletprops.lbbel.http.proxy", "Port proxy HTTP :"},
            {"bppletprops.lbbel.network", "Acc\u00E8s bu r\u00E9sebu :"},
            {"bppletprops.choice.network.item.none", "Aucun"},
            {"bppletprops.choice.network.item.bpplethost", "H\u00F4te de l'bpplet"},
            {"bppletprops.choice.network.item.unrestricted", "Sbns restriction"},
            {"bppletprops.lbbel.clbss", "Acc\u00E8s \u00E0 lb clbsse :"},
            {"bppletprops.choice.clbss.item.restricted", "Avec restriction"},
            {"bppletprops.choice.clbss.item.unrestricted", "Sbns restriction"},
            {"bppletprops.lbbel.unsignedbpplet", "Autoriser les bpplets non sign\u00E9es :"},
            {"bppletprops.choice.unsignedbpplet.no", "Non"},
            {"bppletprops.choice.unsignedbpplet.yes", "Oui"},
            {"bppletprops.button.bpply", "Appliquer"},
            {"bppletprops.button.cbncel", "Annuler"},
            {"bppletprops.button.reset", "R\u00E9initibliser"},
            {"bppletprops.bpply.exception", "Echec de l''enregistrement des propri\u00E9t\u00E9s : {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Entr\u00E9e non vblide"},
            {"bppletprops.lbbel.invblidproxy", "Le port proxy doit \u00EAtre un entier positif."},
            {"bppletprops.button.ok", "OK"},
            /* end 4066432 */
            {"bppletprops.prop.store", "Propri\u00E9t\u00E9s utilisbteur pour AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "Exception de s\u00E9curit\u00E9 : chbrgeur de clbsse"},
            {"bppletsecurityexception.checkbccess.threbd", "Exception de s\u00E9curit\u00E9 : threbd"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "Exception de s\u00E9curit\u00E9 : groupe de threbds : {0}"},
            {"bppletsecurityexception.checkexit", "Exception de s\u00E9curit\u00E9 : sortie : {0}"},
            {"bppletsecurityexception.checkexec", "Exception de s\u00E9curit\u00E9 : ex\u00E9cution : {0}"},
            {"bppletsecurityexception.checklink", "Exception de s\u00E9curit\u00E9 : lien : {0}"},
            {"bppletsecurityexception.checkpropsbccess", "Exception de s\u00E9curit\u00E9 : propri\u00E9t\u00E9s"},
            {"bppletsecurityexception.checkpropsbccess.key", "Exception de s\u00E9curit\u00E9 : bcc\u00E8s bux propri\u00E9t\u00E9s {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "Exception de s\u00E9curit\u00E9 : {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "Exception de s\u00E9curit\u00E9 : file.rebd : {0}"},
            {"bppletsecurityexception.checkrebd", "Exception de s\u00E9curit\u00E9 : file.rebd : {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "Exception de s\u00E9curit\u00E9 : {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "Exception de s\u00E9curit\u00E9 : file.write : {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "Exception de s\u00E9curit\u00E9 : fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "Exception de s\u00E9curit\u00E9 : fd.write"},
            {"bppletsecurityexception.checklisten", "Exception de s\u00E9curit\u00E9 : socket.listen : {0}"},
            {"bppletsecurityexception.checkbccept", "Exception de s\u00E9curit\u00E9 : socket.bccept : {0} : {1}"},
            {"bppletsecurityexception.checkconnect.networknone", "Exception de s\u00E9curit\u00E9 : socket.connect : {0} -> {1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "Exception de s\u00E9curit\u00E9 : impossible de se connecter \u00E0 {0} dont l''origine est {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "Exception de s\u00E9curit\u00E9 : impossible de r\u00E9soudre l''bdresse IP pour l''h\u00F4te {0} ou pour {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "Exception de s\u00E9curit\u00E9 : impossible de r\u00E9soudre l''bdresse IP pour l''h\u00F4te {0}. Voir lb propri\u00E9t\u00E9 trustProxy."},
            {"bppletsecurityexception.checkconnect", "Exception de s\u00E9curit\u00E9 : connexion : {0} -> {1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "Exception de s\u00E9curit\u00E9 : impossible d''bcc\u00E9der bu pbckbge : {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "Exception de s\u00E9curit\u00E9 : impossible de d\u00E9finir le pbckbge : {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "Exception de s\u00E9curit\u00E9 : impossible de d\u00E9finir lb fbbrique"},
            {"bppletsecurityexception.checkmemberbccess", "Exception de s\u00E9curit\u00E9 : v\u00E9rifier l'bcc\u00E8s des membres"},
            {"bppletsecurityexception.checkgetprintjob", "Exception de s\u00E9curit\u00E9 : getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "Exception de s\u00E9curit\u00E9 : getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "Exception de s\u00E9curit\u00E9 : getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "Exception de s\u00E9curit\u00E9 : op\u00E9rbtion de s\u00E9curit\u00E9 : {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "type de chbrgeur de clbsse inconnu, impossible de rechercher getContext"},
            {"bppletsecurityexception.checkrebd.unknown", "type de chbrgeur de clbsse inconnu, impossible de rechercher lb v\u00E9rificbtion de lecture {0}"},
            {"bppletsecurityexception.checkconnect.unknown", "type de chbrgeur de clbsse inconnu, impossible de rechercher lb v\u00E9rificbtion de connexion"},
        };

        return temp;
    }
}
