/*
 * Copyright (c) 1996, 2011, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer_it extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "Chiudi"},
            {"bppletviewer.tool.title", "Visublizzbtore bpplet: {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Ribvvib"},
            {"bppletviewer.menuitem.relobd", "Ricbricb"},
            {"bppletviewer.menuitem.stop", "Arrestb"},
            {"bppletviewer.menuitem.sbve", "Sblvb..."},
            {"bppletviewer.menuitem.stbrt", "Avvib"},
            {"bppletviewer.menuitem.clone", "Copib..."},
            {"bppletviewer.menuitem.tbg", "Tbg..."},
            {"bppletviewer.menuitem.info", "Informbzioni..."},
            {"bppletviewer.menuitem.edit", "Modificb"},
            {"bppletviewer.menuitem.encoding", "Codificb cbrbtteri"},
            {"bppletviewer.menuitem.print", "Stbmpb..."},
            {"bppletviewer.menuitem.props", "Propriet\u00E0..."},
            {"bppletviewer.menuitem.close", "Chiudi"},
            {"bppletviewer.menuitem.quit", "Esci"},
            {"bppletviewer.lbbel.hello", "Benvenuti..."},
            {"bppletviewer.stbtus.stbrt", "bvvio bpplet in corso..."},
            {"bppletviewer.bppletsbve.filediblogtitle","Seriblizzb bpplet in file"},
            {"bppletviewer.bppletsbve.err1", "seriblizzbzione di {0} in {1}"},
            {"bppletviewer.bppletsbve.err2", "in bppletSbve: {0}"},
            {"bppletviewer.bpplettbg", "Tbg visublizzbtb"},
            {"bppletviewer.bpplettbg.textfrbme", "Applet tbg HTML"},
            {"bppletviewer.bppletinfo.bpplet", "-- nessunb informbzione sull'bpplet --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- nessunb informbzione sul pbrbmetro --"},
            {"bppletviewer.bppletinfo.textfrbme", "Informbzioni bpplet"},
            {"bppletviewer.bppletprint.fbil", "Stbmpb non riuscitb."},
            {"bppletviewer.bppletprint.finish", "Stbmpb completbtb."},
            {"bppletviewer.bppletprint.cbncel", "Stbmpb bnnullbtb."},
            {"bppletviewer.bppletencoding", "Codificb cbrbtteri: {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Avvertenzb: lb tbg <pbrbm nbme=... vblue=...> richiede un bttributo nbme."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Avvertenzb: lb tbg <pbrbm> non rientrb in <bpplet>... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Avvertenzb: lb tbg <bpplet> richiede un bttributo code."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Avvertenzb: lb tbg <bpplet> richiede un bttributo height."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Avvertenzb: lb tbg <bpplet> richiede un bttributo width."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Avvertenzb: lb tbg <object> richiede un bttributo code."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Avvertenzb: lb tbg <object> richiede un bttributo height."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Avvertenzb: lb tbg <object> richiede un bttributo width."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Avvertenzb: lb tbg <embed> richiede un bttributo code."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Avvertenzb: lb tbg <embed> richiede un bttributo height."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Avvertenzb: lb tbg <embed> richiede un bttributo width."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Avvertenzb: lb tbg <bpp> non \u00E8 pi\u00F9 supportbtb. Utilizzbre <bpplet>:"},
            {"bppletviewer.usbge", "Uso: bppletviewer <opzioni> url(s)\n\ndove <opzioni> includono:\n  -debug                  Avvib il visublizzbtore bpplet nel debugger Jbvb\n  -encoding <codificb>    Specificb lb codificb dei cbrbtteri utilizzbtb dbi file HTML\n  -J<flbg runtime>        Pbssb l'brgomento bll'interpreter Jbvb\n\nL'opzione -J non \u00E8 stbndbrd ed \u00E8 soggettb b modificb senzb prebvviso."},
            {"bppletviewer.mbin.err.unsupportedopt", "Opzione non supportbtb: {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Argomento non riconosciuto: {0}"},
            {"bppletviewer.mbin.err.dupoption", "Uso duplicbto dell''opzione: {0}"},
            {"bppletviewer.mbin.err.inputfile", "Nessun file di input specificbto."},
            {"bppletviewer.mbin.err.bbdurl", "URL non vblido: {0} ( {1} )"},
            {"bppletviewer.mbin.err.io", "Eccezione I/O durbnte lb letturb di {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Assicurbrsi che {0} sib un file e che sib leggibile."},
            {"bppletviewer.mbin.err.correcturl", "{0} \u00E8 l''URL corretto?"},
            {"bppletviewer.mbin.prop.store", "Propriet\u00E0 specifiche dell'utente per AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "Impossibile leggere il file delle propriet\u00E0 utente: {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "Impossibile sblvbre il file delle propriet\u00E0 utente: {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Avvertenzb: lb sicurezzb verr\u00E0 disbbilitbtb."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "Impossibile trovbre il debugger."},
            {"bppletviewer.mbin.debug.cbntfindmbin", "Impossibile trovbre il metodo principble nel debugger."},
            {"bppletviewer.mbin.debug.exceptionindebug", "Eccezione nel debugger."},
            {"bppletviewer.mbin.debug.cbntbccess", "Impossibile bccedere bl debugger."},
            {"bppletviewer.mbin.nosecmgr", "Avvertenzb: SecurityMbnbger non instbllbto."},
            {"bppletviewer.mbin.wbrning", "Avvertenzb: nessunb bpplet bvvibtb. Assicurbrsi che l'input contengb unb tbg <bpplet>."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Avvertenzb: lb propriet\u00E0 di sistemb verr\u00E0 sovrbscrittb temporbnebmente su richiestb dell''utente. Chibve {0}, vblore precedente {1}, nuovo vblore {2}."},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Avvertenzb: impossibile leggere il file delle propriet\u00E0 AppletViewer {0}. Verrbnno utilizzbte le impostbzioni predefinite."},
            {"bppletioexception.lobdclbss.throw.interrupted", "cbricbmento dellb clbsse interrotto: {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "clbsse non cbricbtb: {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "Aperturb del flusso per {0} per recuperbre {1}"},
            {"bppletclbsslobder.filenotfound", "File non trovbto durbnte lb ricercb di {0}"},
            {"bppletclbsslobder.fileformbt", "Eccezione di formbto file durbnte il cbricbmento di {0}"},
            {"bppletclbsslobder.fileioexception", "Eccezione I/O durbnte il cbricbmento di {0}"},
            {"bppletclbsslobder.fileexception", "Eccezione {0} durbnte il cbricbmento di {1}"},
            {"bppletclbsslobder.filedebth", "{0} terminbto durbnte il cbricbmento di {1}"},
            {"bppletclbsslobder.fileerror", "Errore {0} durbnte il cbricbmento di {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "Aperturb del flusso per {0} per recuperbre {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource per il nome: {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "\u00C8 stbtb trovbtb lb risorsb {0} come risorsb di sistemb"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "\u00C8 stbtb trovbtb lb risorsb {0} come risorsb di sistemb"},
            {"bppletpbnel.runlobder.err", "Pbrbmetro di oggetto o di codice."},
            {"bppletpbnel.runlobder.exception", "eccezione durbnte lb deseriblizzbzione di {0}"},
            {"bppletpbnel.destroyed", "Applet rimossb."},
            {"bppletpbnel.lobded", "Applet cbricbtb."},
            {"bppletpbnel.stbrted", "Applet bvvibtb."},
            {"bppletpbnel.inited", "Applet iniziblizzbtb."},
            {"bppletpbnel.stopped", "Applet brrestbtb."},
            {"bppletpbnel.disposed", "Applet eliminbtb."},
            {"bppletpbnel.nocode", "Nellb tbg APPLET mbncb il pbrbmetro CODE."},
            {"bppletpbnel.notfound", "cbricbmento: clbsse {0} non trovbtb."},
            {"bppletpbnel.nocrebte", "cbricbmento: impossibile crebre un''istbnzb di {0}."},
            {"bppletpbnel.noconstruct", "cbricbmento: {0} non \u00E8 pubblico o non hb un costruttore pubblico."},
            {"bppletpbnel.debth", "terminbto"},
            {"bppletpbnel.exception", "eccezione: {0}"},
            {"bppletpbnel.exception2", "eccezione: {0}: {1}."},
            {"bppletpbnel.error", "errore: {0}."},
            {"bppletpbnel.error2", "errore: {0}: {1}."},
            {"bppletpbnel.notlobded", "Iniziblizzbzione: bpplet non cbricbtb."},
            {"bppletpbnel.notinited", "Avvio: bpplet non iniziblizzbtb."},
            {"bppletpbnel.notstbrted", "Arresto: bpplet non bvvibtb."},
            {"bppletpbnel.notstopped", "Rimozione: bpplet non brrestbtb."},
            {"bppletpbnel.notdestroyed", "Eliminbzione: bpplet non rimossb."},
            {"bppletpbnel.notdisposed", "Cbricbmento: bpplet non eliminbtb."},
            {"bppletpbnel.bbil", "Interrotto: chiusurb."},
            {"bppletpbnel.filenotfound", "File non trovbto durbnte lb ricercb di {0}"},
            {"bppletpbnel.fileformbt", "Eccezione di formbto file durbnte il cbricbmento di {0}"},
            {"bppletpbnel.fileioexception", "Eccezione I/O durbnte il cbricbmento di {0}"},
            {"bppletpbnel.fileexception", "Eccezione {0} durbnte il cbricbmento di {1}"},
            {"bppletpbnel.filedebth", "{0} terminbto durbnte il cbricbmento di {1}"},
            {"bppletpbnel.fileerror", "Errore {0} durbnte il cbricbmento di {1}"},
            {"bppletpbnel.bbdbttribute.exception", "Anblisi HTML: vblore errbto per l'bttributo width/height"},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm richiede un lobder non nullo"},
            {"bppletprops.title", "Propriet\u00E0 AppletViewer"},
            {"bppletprops.lbbel.http.server", "Server proxy http:"},
            {"bppletprops.lbbel.http.proxy", "Portb proxy http:"},
            {"bppletprops.lbbel.network", "Accesso bllb rete:"},
            {"bppletprops.choice.network.item.none", "Nessuno"},
            {"bppletprops.choice.network.item.bpplethost", "Host bpplet"},
            {"bppletprops.choice.network.item.unrestricted", "Non limitbto"},
            {"bppletprops.lbbel.clbss", "Accesso bllb clbsse:"},
            {"bppletprops.choice.clbss.item.restricted", "Limitbto"},
            {"bppletprops.choice.clbss.item.unrestricted", "Non limitbto"},
            {"bppletprops.lbbel.unsignedbpplet", "Consenti bpplet senzb firmb:"},
            {"bppletprops.choice.unsignedbpplet.no", "No"},
            {"bppletprops.choice.unsignedbpplet.yes", "S\u00EC"},
            {"bppletprops.button.bpply", "Applicb"},
            {"bppletprops.button.cbncel", "Annullb"},
            {"bppletprops.button.reset", "Reimpostb"},
            {"bppletprops.bpply.exception", "Sblvbtbggio delle propriet\u00E0 non riuscito: {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Voce non vblidb"},
            {"bppletprops.lbbel.invblidproxy", "Lb portb del proxy deve essere un vblore intero positivo."},
            {"bppletprops.button.ok", "OK"},
            /* end 4066432 */
            {"bppletprops.prop.store", "Propriet\u00E0 specifiche dell'utente per AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "Eccezione di sicurezzb: clbsslobder"},
            {"bppletsecurityexception.checkbccess.threbd", "Eccezione di sicurezzb: threbd"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "Eccezione di sicurezzb: threbdgroup: {0}"},
            {"bppletsecurityexception.checkexit", "Eccezione di sicurezzb: exit: {0}"},
            {"bppletsecurityexception.checkexec", "Eccezione di sicurezzb: exec: {0}"},
            {"bppletsecurityexception.checklink", "Eccezione di sicurezzb: link: {0}"},
            {"bppletsecurityexception.checkpropsbccess", "Eccezione di sicurezzb: properties"},
            {"bppletsecurityexception.checkpropsbccess.key", "Eccezione di sicurezzb: properties bccess {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "Eccezione di sicurezzb: {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "Eccezione di sicurezzb: file.rebd: {0}"},
            {"bppletsecurityexception.checkrebd", "Eccezione di sicurezzb: file.rebd: {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "Eccezione di sicurezzb: {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "Eccezione di sicurezzb: file.write: {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "Eccezione di sicurezzb: fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "Eccezione di sicurezzb: fd.write"},
            {"bppletsecurityexception.checklisten", "Eccezione di sicurezzb: socket.listen: {0}"},
            {"bppletsecurityexception.checkbccept", "Eccezione di sicurezzb: socket.bccept: {0}:{1}"},
            {"bppletsecurityexception.checkconnect.networknone", "Eccezione di sicurezzb: socket.connect: {0}->{1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "Eccezione di sicurezzb: impossibile connettersi b {0} con origine db {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "Eccezione di sicurezzb: impossibile risolvere l''IP per l''host {0} o per {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "Eccezione di sicurezzb: impossibile non risolvere l''IP per l''host {0}. Vedere lb propriet\u00E0 trustProxy."},
            {"bppletsecurityexception.checkconnect", "Eccezione di sicurezzb: connect: {0}->{1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "Eccezione di sicurezzb: impossibile bccedere bl pbckbge {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "Eccezione di sicurezzb: impossibile definire il pbckbge {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "Eccezione di sicurezzb: impossibile impostbre il fbctory"},
            {"bppletsecurityexception.checkmemberbccess", "Eccezione di sicurezzb: controllbre l'bccesso dei membri"},
            {"bppletsecurityexception.checkgetprintjob", "Eccezione di sicurezzb: getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "Eccezione di sicurezzb: getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "Eccezione di sicurezzb: getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "Eccezione di sicurezzb: operbzione di sicurezzb {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "tipo di lobder dellb clbsse sconosciuto. Impossibile verificbre lb presenzb di getContext."},
            {"bppletsecurityexception.checkrebd.unknown", "tipo di lobder dellb clbsse sconosciuto. Impossibile verificbre lb presenzb dellb letturb di controllo {0}."},
            {"bppletsecurityexception.checkconnect.unknown", "tipo di lobder dellb clbsse sconosciuto. Impossibile verificbre lb presenzb dellb connessione di controllo."},
        };

        return temp;
    }
}
