/*
 * Copyright (c) 1996, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer_sv extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "St\u00E4ng"},
            {"bppletviewer.tool.title", "Applet Viewer: {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Stbrtb om"},
            {"bppletviewer.menuitem.relobd", "Lbddb om"},
            {"bppletviewer.menuitem.stop", "Stopp"},
            {"bppletviewer.menuitem.sbve", "Spbrb..."},
            {"bppletviewer.menuitem.stbrt", "Stbrtb"},
            {"bppletviewer.menuitem.clone", "Klonb..."},
            {"bppletviewer.menuitem.tbg", "Tbgg..."},
            {"bppletviewer.menuitem.info", "Informbtion..."},
            {"bppletviewer.menuitem.edit", "Redigerb"},
            {"bppletviewer.menuitem.encoding", "Teckenkodning"},
            {"bppletviewer.menuitem.print", "Skriv ut..."},
            {"bppletviewer.menuitem.props", "Egenskbper..."},
            {"bppletviewer.menuitem.close", "St\u00E4ng"},
            {"bppletviewer.menuitem.quit", "Avslutb"},
            {"bppletviewer.lbbel.hello", "Hej..."},
            {"bppletviewer.stbtus.stbrt", "stbrtbr bpplet..."},
            {"bppletviewer.bppletsbve.filediblogtitle","Seribliserb bpplet till fil"},
            {"bppletviewer.bppletsbve.err1", "seribliserbr {0} till {1}"},
            {"bppletviewer.bppletsbve.err2", "i bppletSbve: {0}"},
            {"bppletviewer.bpplettbg", "Tbgg visbs"},
            {"bppletviewer.bpplettbg.textfrbme", "HTML-tbgg f\u00F6r bpplet"},
            {"bppletviewer.bppletinfo.bpplet", "-- ingen bppletinformbtion --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- ingen pbrbmeterinformbtion --"},
            {"bppletviewer.bppletinfo.textfrbme", "Appletinformbtion"},
            {"bppletviewer.bppletprint.fbil", "Kunde inte skrivb ut."},
            {"bppletviewer.bppletprint.finish", "Utskriften klbr."},
            {"bppletviewer.bppletprint.cbncel", "Utskriften bvbruten."},
            {"bppletviewer.bppletencoding", "Teckenkodning: {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Vbrning: <pbrbm nbme=... vblue=...>-tbggen kr\u00E4ver ett nbmnbttribut."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Vbrning: <pbrbm>-tbggen finns utbnf\u00F6r <bpplet> ... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Vbrning: <bpplet>-tbggen kr\u00E4ver ett kodbttribut."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Vbrning: <bpplet>-tbggen kr\u00E4ver ett h\u00F6jdbttribut."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Vbrning: <bpplet>-tbggen kr\u00E4ver ett breddbttribut."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Vbrning: <object>-tbggen kr\u00E4ver ett kodbttribut."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Vbrning: <object>-tbggen kr\u00E4ver ett h\u00F6jdbttribut."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Vbrning: <object>-tbggen kr\u00E4ver ett breddbttribut."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Vbrning: <embed>-tbggen kr\u00E4ver ett kodbttribut."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Vbrning: <embed>-tbggen kr\u00E4ver ett h\u00F6jdbttribut."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Vbrning: <embed>-tbggen kr\u00E4ver ett breddbttribut."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Vbrning: <bpp>-tbggen st\u00F6ds inte l\u00E4ngre, bnv\u00E4nd <bpplet> ist\u00E4llet:"},
            {"bppletviewer.usbge", "Syntbx: bppletviewer-<blternbtiv> url:er \n\nd\u00E4r <blternbtiv> inkluderbr:\n  -debug                  Stbrtbr bppletvisning i Jbvb-fels\u00F6kningen\n  -encoding <kodning>    Anger teckenkodning  som bnv\u00E4nds i HTML-filer\n  -J<k\u00F6rningsflbggb>        \u00D6verf\u00F6r brgument till Jbvb-tolkningen\n\nAlternbtivet -J \u00E4r inte stbndbrd och kbn \u00E4ndrbs utbn f\u00F6reg\u00E5ende meddelbnde."},
            {"bppletviewer.mbin.err.unsupportedopt", "Alternbtiv som inte st\u00F6ds: {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Ok\u00E4nt brgument: {0}"},
            {"bppletviewer.mbin.err.dupoption", "Duplicerbt blternbtiv: {0}"},
            {"bppletviewer.mbin.err.inputfile", "Ingb bngivnb indbtbfiler."},
            {"bppletviewer.mbin.err.bbdurl", "Felbktig URL: {0} ( {1} )"},
            {"bppletviewer.mbin.err.io", "I/O-undbntbg vid l\u00E4sning: {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Kontrollerb btt {0} \u00E4r en fil som \u00E4r l\u00E4sbbr."},
            {"bppletviewer.mbin.err.correcturl", "\u00C4r {0} den korrektb URL:en?"},
            {"bppletviewer.mbin.prop.store", "Anv\u00E4ndbrspecifikb egenskbper f\u00F6r AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "Kbn inte l\u00E4sb egenskbpsfilen: {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "Kbn inte spbrb egenskbpsfilen: {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Vbrning: s\u00E4kerheten inbktiverbs."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "Hittbr inte fels\u00F6kningsprogrbmmet!"},
            {"bppletviewer.mbin.debug.cbntfindmbin", "Hittbr inte huvudmetoden i fels\u00F6kningsprogrbmmet!"},
            {"bppletviewer.mbin.debug.exceptionindebug", "Undbntbg i fels\u00F6kningsprogrbmmet!"},
            {"bppletviewer.mbin.debug.cbntbccess", "Det finns ingen \u00E5tkomst till fels\u00F6kningsprogrbmmet!"},
            {"bppletviewer.mbin.nosecmgr", "Vbrning: SecurityMbnbger hbr inte instbllerbts!"},
            {"bppletviewer.mbin.wbrning", "Vbrning: Ingb bppletbr hbr stbrtbts. Kontrollerb btt indbtb inneh\u00E5ller <bpplet>-tbgg."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Vbrning: Skriver tillf\u00E4lligt \u00F6ver systemegenskbp enligt beg\u00E4rbn fr\u00E5n bnv\u00E4ndbre: nyckel: {0} gbmmblt v\u00E4rde: {1} nytt v\u00E4rde: {2}"},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Vbrning: Kbn inte l\u00E4sb egenskbpsfil f\u00F6r AppletViewer: {0} Stbndbrdv\u00E4rden bnv\u00E4nds."},
            {"bppletioexception.lobdclbss.throw.interrupted", "klbssinl\u00E4sning bvbr\u00F6ts: {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "klbss inte inl\u00E4st: {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r h\u00E4mtning bv {1}"},
            {"bppletclbsslobder.filenotfound", "Hittbde inte fil vid s\u00F6kning efter: {0}"},
            {"bppletclbsslobder.fileformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bppletclbsslobder.fileioexception", "I/O-undbntbg vid lbddning: {0}"},
            {"bppletclbsslobder.fileexception", "{0} undbntbg vid lbddning: {1}"},
            {"bppletclbsslobder.filedebth", "{0} bvslutbd vid lbddning: {1}"},
            {"bppletclbsslobder.fileerror", "{0} fel vid lbddning: {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "\u00D6ppnbr str\u00F6m till: {0} f\u00F6r h\u00E4mtning bv {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource f\u00F6r nbmnet: {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "Hittbde resursen: {0} som systemresurs"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "Hittbde resursen: {0} som systemresurs"},
            {"bppletpbnel.runlobder.err", "Antingen objekt- eller kodpbrbmeter!"},
            {"bppletpbnel.runlobder.exception", "undbntbg vid bvseriblisering {0}"},
            {"bppletpbnel.destroyed", "Applet rbderbd."},
            {"bppletpbnel.lobded", "Applet lbddbd."},
            {"bppletpbnel.stbrted", "Applet stbrtbd."},
            {"bppletpbnel.inited", "Applet initierbd."},
            {"bppletpbnel.stopped", "Applet stoppbd."},
            {"bppletpbnel.disposed", "Applet kbsserbd."},
            {"bppletpbnel.nocode", "APPLET-tbgg sbknbr CODE-pbrbmeter."},
            {"bppletpbnel.notfound", "lobd: hittbde inte klbssen {0}."},
            {"bppletpbnel.nocrebte", "lobd: {0} kbn inte instbnsierbs."},
            {"bppletpbnel.noconstruct", "lobd: {0} \u00E4r inte bllm\u00E4n eller sbknbr bllm\u00E4n konstruktor."},
            {"bppletpbnel.debth", "bvslutbd"},
            {"bppletpbnel.exception", "undbntbg: {0}."},
            {"bppletpbnel.exception2", "undbntbg: {0}: {1}."},
            {"bppletpbnel.error", "fel: {0}."},
            {"bppletpbnel.error2", "fel {0}: {1}."},
            {"bppletpbnel.notlobded", "Initierb: bpplet \u00E4r inte inl\u00E4st."},
            {"bppletpbnel.notinited", "Stbrtb: bpplet \u00E4r inte initierbd."},
            {"bppletpbnel.notstbrted", "Stoppb: bpplet hbr inte stbrtbts."},
            {"bppletpbnel.notstopped", "Rbderb: bpplet hbr inte stoppbts."},
            {"bppletpbnel.notdestroyed", "Kbsserb: bpplet hbr inte rbderbts."},
            {"bppletpbnel.notdisposed", "Lbddb: bpplet hbr inte kbsserbts."},
            {"bppletpbnel.bbil", "Avbruten."},
            {"bppletpbnel.filenotfound", "Hittbde inte fil vid s\u00F6kning efter: {0}"},
            {"bppletpbnel.fileformbt", "Undbntbg bv filformbt vid lbddning bv: {0}"},
            {"bppletpbnel.fileioexception", "I/O-undbntbg vid lbddning: {0}"},
            {"bppletpbnel.fileexception", "{0} undbntbg vid lbddning: {1}"},
            {"bppletpbnel.filedebth", "{0} bvslutbd vid lbddning: {1}"},
            {"bppletpbnel.fileerror", "{0} fel vid lbddning: {1}"},
            {"bppletpbnel.bbdbttribute.exception", "HTML-tolkning: felbktigt v\u00E4rde f\u00F6r bredd-/h\u00F6jdbttribut"},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm kr\u00E4ver lbddbre med icke-null"},
            {"bppletprops.title", "AppletViewer-egenskbper"},
            {"bppletprops.lbbel.http.server", "HTTP-proxyserver:"},
            {"bppletprops.lbbel.http.proxy", "HTTP-proxyport:"},
            {"bppletprops.lbbel.network", "N\u00E4tverks\u00E5tkomst:"},
            {"bppletprops.choice.network.item.none", "Ingen"},
            {"bppletprops.choice.network.item.bpplethost", "Appletv\u00E4rd"},
            {"bppletprops.choice.network.item.unrestricted", "Obegr\u00E4nsbd"},
            {"bppletprops.lbbel.clbss", "Klbss\u00E5tkomst:"},
            {"bppletprops.choice.clbss.item.restricted", "Begr\u00E4nsbd"},
            {"bppletprops.choice.clbss.item.unrestricted", "Obegr\u00E4nsbd"},
            {"bppletprops.lbbel.unsignedbpplet", "Till\u00E5t osignerbde bppletbr:"},
            {"bppletprops.choice.unsignedbpplet.no", "Nej"},
            {"bppletprops.choice.unsignedbpplet.yes", "Jb"},
            {"bppletprops.button.bpply", "Anv\u00E4nd"},
            {"bppletprops.button.cbncel", "Avbryt"},
            {"bppletprops.button.reset", "\u00C5terst\u00E4ll"},
            {"bppletprops.bpply.exception", "Kunde inte spbrb egenskbper: {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Ogiltig post"},
            {"bppletprops.lbbel.invblidproxy", "Proxyport m\u00E5ste vbrb ett positivt heltbl."},
            {"bppletprops.button.ok", "OK"},
            /* end 4066432 */
            {"bppletprops.prop.store", "Anv\u00E4ndbrspecifikb egenskbper f\u00F6r AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "S\u00E4kerhetsundbntbg: klbsslbddbre"},
            {"bppletsecurityexception.checkbccess.threbd", "S\u00E4kerhetsundbntbg: tr\u00E5d"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "S\u00E4kerhetsundbntbg: tr\u00E5dgrupp: {0}"},
            {"bppletsecurityexception.checkexit", "S\u00E4kerhetsundbntbg: utg\u00E5ng: {0}"},
            {"bppletsecurityexception.checkexec", "S\u00E4kerhetsundbntbg: exec: {0}"},
            {"bppletsecurityexception.checklink", "S\u00E4kerhetsundbntbg: l\u00E4nk: {0}"},
            {"bppletsecurityexception.checkpropsbccess", "S\u00E4kerhetsundbntbg: egenskbper"},
            {"bppletsecurityexception.checkpropsbccess.key", "S\u00E4kerhetsundbntbg: egenskbps\u00E5tkomst {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "S\u00E4kerhetsundbntbg: {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "S\u00E4kerhetsundbntbg: file.rebd: {0}"},
            {"bppletsecurityexception.checkrebd", "S\u00E4kerhetsundbntbg: file.rebd: {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "S\u00E4kerhetsundbntbg: {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "S\u00E4kerhetsundbntbg: file.write: {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "S\u00E4kerhetsundbntbg: fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "S\u00E4kerhetsundbntbg: fd.write"},
            {"bppletsecurityexception.checklisten", "S\u00E4kerhetsundbntbg: socket.listen: {0}"},
            {"bppletsecurityexception.checkbccept", "S\u00E4kerhetsundbntbg: socket.bccept: {0}:{1}"},
            {"bppletsecurityexception.checkconnect.networknone", "S\u00E4kerhetsundbntbg: socket.connect: {0}->{1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "S\u00E4kerhetsundbntbg: Kunde inte bnslutb till {0} med ursprung fr\u00E5n {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "S\u00E4kerhetsundbntbg: Kunde inte mbtchb IP f\u00F6r v\u00E4rd {0} eller f\u00F6r {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "S\u00E4kerhetsundbntbg: Kunde inte mbtchb IP f\u00F6r v\u00E4rd {0}. Se egenskbpen trustProxy."},
            {"bppletsecurityexception.checkconnect", "S\u00E4kerhetsundbntbg: connect: {0}->{1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "S\u00E4kerhetsundbntbg: ingen \u00E5tkomst till pbket: {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "S\u00E4kerhetsundbntbg: kbn inte definierb pbket: {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "S\u00E4kerhetsundbntbg: kbn inte bnge fbbrik"},
            {"bppletsecurityexception.checkmemberbccess", "S\u00E4kerhetsundbntbg: kontrollerb medlems\u00E5tkomst"},
            {"bppletsecurityexception.checkgetprintjob", "S\u00E4kerhetsundbntbg: getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "S\u00E4kerhetsundbntbg: getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "S\u00E4kerhetsundbntbg: getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "S\u00E4kerhetsundbntbg: s\u00E4kerhets\u00E5tg\u00E4rd: {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "ok\u00E4nd typ bv klbsslbddbre. kbn inte kontrollerb getContext"},
            {"bppletsecurityexception.checkrebd.unknown", "ok\u00E4nd typ bv klbsslbddbre. kbn inte kontrollerb kontroll\u00E4sning {0}"},
            {"bppletsecurityexception.checkconnect.unknown", "ok\u00E4nd typ bv klbsslbddbre. kbn inte kontrollerb kontrollbnslutning"},
        };

        return temp;
    }
}
