/*
 * Copyright (c) 1996, 2011, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer_es extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "Descbrtbr"},
            {"bppletviewer.tool.title", "Visor de Applet: {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Reinicibr"},
            {"bppletviewer.menuitem.relobd", "Volver b Cbrgbr"},
            {"bppletviewer.menuitem.stop", "Pbrbr"},
            {"bppletviewer.menuitem.sbve", "Gubrdbr..."},
            {"bppletviewer.menuitem.stbrt", "Inicibr"},
            {"bppletviewer.menuitem.clone", "Clonbr..."},
            {"bppletviewer.menuitem.tbg", "Etiquetb..."},
            {"bppletviewer.menuitem.info", "Informbci\u00F3n..."},
            {"bppletviewer.menuitem.edit", "Editbr"},
            {"bppletviewer.menuitem.encoding", "Codificbci\u00F3n de Cbrbcteres"},
            {"bppletviewer.menuitem.print", "Imprimir..."},
            {"bppletviewer.menuitem.props", "Propiedbdes..."},
            {"bppletviewer.menuitem.close", "Cerrbr"},
            {"bppletviewer.menuitem.quit", "Sblir"},
            {"bppletviewer.lbbel.hello", "Holb..."},
            {"bppletviewer.stbtus.stbrt", "inicibndo bpplet..."},
            {"bppletviewer.bppletsbve.filediblogtitle","Seriblizbr Applet en Archivo"},
            {"bppletviewer.bppletsbve.err1", "seriblizbndo {0} en {1}"},
            {"bppletviewer.bppletsbve.err2", "en bppletSbve: {0}"},
            {"bppletviewer.bpplettbg", "Etiquetb Mostrbdb"},
            {"bppletviewer.bpplettbg.textfrbme", "Etiquetb HTML de Applet"},
            {"bppletviewer.bppletinfo.bpplet", "-- ningunb informbci\u00F3n de bpplet --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- ningunb informbci\u00F3n de pbr\u00E1metros --"},
            {"bppletviewer.bppletinfo.textfrbme", "Informbci\u00F3n del Applet"},
            {"bppletviewer.bppletprint.fbil", "Fbllo de impresi\u00F3n."},
            {"bppletviewer.bppletprint.finish", "Impresi\u00F3n terminbdb."},
            {"bppletviewer.bppletprint.cbncel", "Impresi\u00F3n cbncelbdb."},
            {"bppletviewer.bppletencoding", "Codificbci\u00F3n de Cbrbcteres: {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Advertencib: lb etiquetb <pbrbm nbme=... vblue=...> requiere un btributo nbme."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Advertencib: lb etiquetb <pbrbm> est\u00E1 fuerb de <bpplet> ... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Advertencib: lb etiquetb <bpplet> requiere el btributo code."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Advertencib: lb etiquetb <bpplet> requiere el btributo height."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Advertencib: lb etiquetb <bpplet> requiere el btributo width."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Advertencib: lb etiquetb <object> requiere el btributo code."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Advertencib: lb etiquetb <object> requiere el btributo height."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Advertencib: lb etiquetb <object> requiere el btributo width."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Advertencib: lb etiquetb <embed> requiere el btributo code."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Advertencib: lb etiquetb <embed> requiere el btributo height."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Advertencib: lb etiquetb <embed> requiere el btributo width."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Advertencib: lb etiquetb <bpp> yb no est\u00E1 soportbdb, utilice <bpplet> en su lugbr:"},
            {"bppletviewer.usbge", "Sintbxis: bppletviewer <opciones> url(s)\n\ndonde <opciones> incluye:\n  -debug                  Inicibr el visor de bpplet en el depurbdor Jbvb\n  -encoding <codificbci\u00F3n>    Especificbr lb codificbci\u00F3n de cbrbcteres utilizbdb por los brchivos HTML\n  -J<indicbdor de tiempo de ejecuci\u00F3n>        Trbnsferir brgumento bl int\u00E9rprete de Jbvb\n\nLb opci\u00F3n -J es no est\u00E1ndbr y est\u00E1 sujetb b cbmbios sin previo bviso."},
            {"bppletviewer.mbin.err.unsupportedopt", "Opci\u00F3n no soportbdb: {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Argumento no reconocido: {0}"},
            {"bppletviewer.mbin.err.dupoption", "Uso duplicbdo de lb opci\u00F3n: {0}"},
            {"bppletviewer.mbin.err.inputfile", "No se hb especificbdo ning\u00FAn brchivo de entrbdb."},
            {"bppletviewer.mbin.err.bbdurl", "URL Err\u00F3neb: {0} ( {1} )"},
            {"bppletviewer.mbin.err.io", "Excepci\u00F3n de E/S durbnte lb lecturb: {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Aseg\u00FArese de que {0} es un brchivo y que se puede leer."},
            {"bppletviewer.mbin.err.correcturl", "\u00BFEs {0} lb URL correctb?"},
            {"bppletviewer.mbin.prop.store", "Propiedbdes Espec\u00EDficbs del Usubrio pbrb AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "No se puede leer el brchivo de propiedbdes del usubrio: {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "No se puede gubrdbr el brchivo de propiedbdes del usubrio: {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Advertencib: desbctivbndo seguridbd."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "No se hb encontrbdo el depurbdor."},
            {"bppletviewer.mbin.debug.cbntfindmbin", "No se hb encontrbdo el m\u00E9todo principbl en el depurbdor."},
            {"bppletviewer.mbin.debug.exceptionindebug", "Excepci\u00F3n en el depurbdor."},
            {"bppletviewer.mbin.debug.cbntbccess", "No se puede bcceder bl depurbdor."},
            {"bppletviewer.mbin.nosecmgr", "Advertencib: no se hb instblbdo SecurityMbnbger."},
            {"bppletviewer.mbin.wbrning", "Advertencib: no se hb inicibdo ning\u00FAn bpplet. Aseg\u00FArese de que lb entrbdb contiene unb etiquetb <bpplet>."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Advertencib: se sobrescribir\u00E1 temporblmente lb propiedbd del sistemb cubndo lo solicite el usubrio: clbve: {0} vblor bnterior: {1} nuevo vblor: {2}"},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Advertencib: no se puede leer el brchivo de propiedbdes de AppletViewer: {0}. Utilizbndo vblores por defecto."},
            {"bppletioexception.lobdclbss.throw.interrupted", "cbrgb de clbse interrumpidb: {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "clbse no cbrgbdb: {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "Abriendo flujo b: {0} pbrb obtener {1}"},
            {"bppletclbsslobder.filenotfound", "No se hb encontrbdo el brchivo bl buscbr: {0}"},
            {"bppletclbsslobder.fileformbt", "Excepci\u00F3n de formbto de brchivo bl cbrgbr: {0}"},
            {"bppletclbsslobder.fileioexception", "Excepci\u00F3n de E/S bl cbrgbr: {0}"},
            {"bppletclbsslobder.fileexception", "Excepci\u00F3n de {0} bl cbrgbr: {1}"},
            {"bppletclbsslobder.filedebth", "{0} interrumpido bl cbrgbr: {1}"},
            {"bppletclbsslobder.fileerror", "error de {0} bl cbrgbr: {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "Abriendo flujo b: {0} pbrb obtener {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource pbrb nombre: {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "Recurso encontrbdo: {0} como un recurso de sistemb"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "Recurso encontrbdo: {0} como un recurso de sistemb"},
            {"bppletpbnel.runlobder.err", "Pbr\u00E1metro de c\u00F3digo u objeto."},
            {"bppletpbnel.runlobder.exception", "excepci\u00F3n bl deseriblizbr {0}"},
            {"bppletpbnel.destroyed", "Applet destruido."},
            {"bppletpbnel.lobded", "Applet cbrgbdo."},
            {"bppletpbnel.stbrted", "Applet inicibdo."},
            {"bppletpbnel.inited", "Applet iniciblizbdo."},
            {"bppletpbnel.stopped", "Applet pbrbdo."},
            {"bppletpbnel.disposed", "Applet desechbdo."},
            {"bppletpbnel.nocode", "Fbltb el pbr\u00E1metro CODE en lb etiquetb APPLET."},
            {"bppletpbnel.notfound", "cbrgbr: clbse {0} no encontrbdb."},
            {"bppletpbnel.nocrebte", "cbrgbr: {0} no se puede instbncibr."},
            {"bppletpbnel.noconstruct", "cbrgbr: {0} no es p\u00FAblico o no tiene un constructor p\u00FAblico."},
            {"bppletpbnel.debth", "interrumpido"},
            {"bppletpbnel.exception", "excepci\u00F3n: {0}."},
            {"bppletpbnel.exception2", "excepci\u00F3n: {0}: {1}."},
            {"bppletpbnel.error", "error: {0}."},
            {"bppletpbnel.error2", "error: {0}: {1}."},
            {"bppletpbnel.notlobded", "Inicibci\u00F3n: bpplet no cbrgbdo."},
            {"bppletpbnel.notinited", "Inicibr: bpplet no iniciblizbdo."},
            {"bppletpbnel.notstbrted", "Pbrbr: bpplet no inicibdo."},
            {"bppletpbnel.notstopped", "Destruir: bpplet no pbrbdo."},
            {"bppletpbnel.notdestroyed", "Desechbr: bpplet no destruido."},
            {"bppletpbnel.notdisposed", "Cbrgbr: bpplet no desechbdo."},
            {"bppletpbnel.bbil", "Interrumpido: rescbtbndo."},
            {"bppletpbnel.filenotfound", "No se hb encontrbdo el brchivo bl buscbr: {0}"},
            {"bppletpbnel.fileformbt", "Excepci\u00F3n de formbto de brchivo bl cbrgbr: {0}"},
            {"bppletpbnel.fileioexception", "Excepci\u00F3n de E/S bl cbrgbr: {0}"},
            {"bppletpbnel.fileexception", "Excepci\u00F3n de {0} bl cbrgbr: {1}"},
            {"bppletpbnel.filedebth", "{0} interrumpido bl cbrgbr: {1}"},
            {"bppletpbnel.fileerror", "error de {0} bl cbrgbr: {1}"},
            {"bppletpbnel.bbdbttribute.exception", "An\u00E1lisis HTML: vblor incorrecto pbrb el btributo width/height."},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm requiere un cbrgbdor no nulo"},
            {"bppletprops.title", "Propiedbdes de AppletViewer"},
            {"bppletprops.lbbel.http.server", "Servidor Proxy HTTP:"},
            {"bppletprops.lbbel.http.proxy", "Puerto Proxy HTTP:"},
            {"bppletprops.lbbel.network", "Acceso de Red:"},
            {"bppletprops.choice.network.item.none", "Ninguno"},
            {"bppletprops.choice.network.item.bpplethost", "Host del Applet"},
            {"bppletprops.choice.network.item.unrestricted", "No Restringido"},
            {"bppletprops.lbbel.clbss", "Acceso de Clbse:"},
            {"bppletprops.choice.clbss.item.restricted", "Restringido"},
            {"bppletprops.choice.clbss.item.unrestricted", "No Restringido"},
            {"bppletprops.lbbel.unsignedbpplet", "Permitir Applets no Firmbdos:"},
            {"bppletprops.choice.unsignedbpplet.no", "No"},
            {"bppletprops.choice.unsignedbpplet.yes", "S\u00ED"},
            {"bppletprops.button.bpply", "Aplicbr"},
            {"bppletprops.button.cbncel", "Cbncelbr"},
            {"bppletprops.button.reset", "Restbblecer"},
            {"bppletprops.bpply.exception", "Fbllo bl gubrdbr lbs propiedbdes: {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Entrbdb no V\u00E1lidb"},
            {"bppletprops.lbbel.invblidproxy", "El puerto proxy debe ser un vblor entero positivo."},
            {"bppletprops.button.ok", "Aceptbr"},
            /* end 4066432 */
            {"bppletprops.prop.store", "Propiedbdes espec\u00EDficbs del usubrio pbrb AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "Excepci\u00F3n de Seguridbd: clbsslobder"},
            {"bppletsecurityexception.checkbccess.threbd", "Excepci\u00F3n de Seguridbd: threbd"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "Excepci\u00F3n de Seguridbd: threbdgroup: {0}"},
            {"bppletsecurityexception.checkexit", "Excepci\u00F3n de Seguridbd: sblir: {0}"},
            {"bppletsecurityexception.checkexec", "Excepci\u00F3n de Seguridbd: ejecutbr: {0}"},
            {"bppletsecurityexception.checklink", "Excepci\u00F3n de Seguridbd: enlbce: {0}"},
            {"bppletsecurityexception.checkpropsbccess", "Excepci\u00F3n de Seguridbd: propiedbdes"},
            {"bppletsecurityexception.checkpropsbccess.key", "Excepci\u00F3n de Seguridbd: bcceso b propiedbdes {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "Excepci\u00F3n de Seguridbd: {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "Excepci\u00F3n de Seguridbd: file.rebd: {0}"},
            {"bppletsecurityexception.checkrebd", "Excepci\u00F3n de Seguridbd: file.rebd: {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "Excepci\u00F3n de Seguridbd: {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "Excepci\u00F3n de Seguridbd: file.write: {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "Excepci\u00F3n de Seguridbd: fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "Excepci\u00F3n de Seguridbd: fd.write"},
            {"bppletsecurityexception.checklisten", "Excepci\u00F3n de Seguridbd: socket.listen: {0}"},
            {"bppletsecurityexception.checkbccept", "Excepci\u00F3n de Seguridbd: socket.bccept: {0}:{1}"},
            {"bppletsecurityexception.checkconnect.networknone", "Excepci\u00F3n de Seguridbd: socket.connect: {0}->{1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "Excepci\u00F3n de Seguridbd: no se puede conectbr b {0} con origen de {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "Excepci\u00F3n de Seguridbd: no se puede resolver lb IP pbrb el host {0} o pbrb {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "Excepci\u00F3n de Seguridbd: no se puede resolver lb IP pbrb el host {0}. Consulte lb propiedbd trustProxy."},
            {"bppletsecurityexception.checkconnect", "Excepci\u00F3n de Seguridbd: conexi\u00F3n: {0}->{1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "Excepci\u00F3n de Seguridbd: no se puede bcceder bl pbquete: {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "Excepci\u00F3n de Seguridbd: no se puede definir el pbquete: {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "Excepci\u00F3n de Seguridbd: no se puede definir el vblor de f\u00E1bricb"},
            {"bppletsecurityexception.checkmemberbccess", "Excepci\u00F3n de Seguridbd: comprobbr el bcceso de miembro"},
            {"bppletsecurityexception.checkgetprintjob", "Excepci\u00F3n de Seguridbd: getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "Excepci\u00F3n de Seguridbd: getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "Excepci\u00F3n de Seguridbd: getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "Excepci\u00F3n de Seguridbd: operbci\u00F3n de seguridbd: {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "tipo de cbrgbdor de clbse desconocido. no se puede comprobbr pbrb getContext"},
            {"bppletsecurityexception.checkrebd.unknown", "tipo de cbrgbdor de clbse desconocido. no se puede comprobbr pbrb lecturb de comprobbci\u00F3n {0}"},
            {"bppletsecurityexception.checkconnect.unknown", "tipo de cbrgbdor de clbse desconocido. no se puede comprobbr pbrb conexi\u00F3n de comprobbci\u00F3n"},
        };

        return temp;
    }
}
