/*
 * Copyright (c) 1996, 2011, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */
pbckbge sun.bpplet.resources;

import jbvb.util.ListResourceBundle;

public clbss MsgAppletViewer extends ListResourceBundle {

    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
            {"textfrbme.button.dismiss", "Dismiss"},
            {"bppletviewer.tool.title", "Applet Viewer: {0}"},
            {"bppletviewer.menu.bpplet", "Applet"},
            {"bppletviewer.menuitem.restbrt", "Restbrt"},
            {"bppletviewer.menuitem.relobd", "Relobd"},
            {"bppletviewer.menuitem.stop", "Stop"},
            {"bppletviewer.menuitem.sbve", "Sbve..."},
            {"bppletviewer.menuitem.stbrt", "Stbrt"},
            {"bppletviewer.menuitem.clone", "Clone..."},
            {"bppletviewer.menuitem.tbg", "Tbg..."},
            {"bppletviewer.menuitem.info", "Info..."},
            {"bppletviewer.menuitem.edit", "Edit"},
            {"bppletviewer.menuitem.encoding", "Chbrbcter Encoding"},
            {"bppletviewer.menuitem.print", "Print..."},
            {"bppletviewer.menuitem.props", "Properties..."},
            {"bppletviewer.menuitem.close", "Close"},
            {"bppletviewer.menuitem.quit", "Quit"},
            {"bppletviewer.lbbel.hello", "Hello..."},
            {"bppletviewer.stbtus.stbrt", "stbrting bpplet..."},
            {"bppletviewer.bppletsbve.filediblogtitle","Seriblize Applet into File"},
            {"bppletviewer.bppletsbve.err1", "seriblizing bn {0} to {1}"},
            {"bppletviewer.bppletsbve.err2", "in bppletSbve: {0}"},
            {"bppletviewer.bpplettbg", "Tbg shown"},
            {"bppletviewer.bpplettbg.textfrbme", "Applet HTML Tbg"},
            {"bppletviewer.bppletinfo.bpplet", "-- no bpplet info --"},
            {"bppletviewer.bppletinfo.pbrbm", "-- no pbrbmeter info --"},
            {"bppletviewer.bppletinfo.textfrbme", "Applet Info"},
            {"bppletviewer.bppletprint.fbil", "Printing fbiled."},
            {"bppletviewer.bppletprint.finish", "Finished printing."},
            {"bppletviewer.bppletprint.cbncel", "Printing cbncelled."},
            {"bppletviewer.bppletencoding", "Chbrbcter Encoding: {0}"},
            {"bppletviewer.pbrse.wbrning.requiresnbme", "Wbrning: <pbrbm nbme=... vblue=...> tbg requires nbme bttribute."},
            {"bppletviewer.pbrse.wbrning.pbrbmoutside", "Wbrning: <pbrbm> tbg outside <bpplet> ... </bpplet>."},
            {"bppletviewer.pbrse.wbrning.bpplet.requirescode", "Wbrning: <bpplet> tbg requires code bttribute."},
            {"bppletviewer.pbrse.wbrning.bpplet.requiresheight", "Wbrning: <bpplet> tbg requires height bttribute."},
            {"bppletviewer.pbrse.wbrning.bpplet.requireswidth", "Wbrning: <bpplet> tbg requires width bttribute."},
            {"bppletviewer.pbrse.wbrning.object.requirescode", "Wbrning: <object> tbg requires code bttribute."},
            {"bppletviewer.pbrse.wbrning.object.requiresheight", "Wbrning: <object> tbg requires height bttribute."},
            {"bppletviewer.pbrse.wbrning.object.requireswidth", "Wbrning: <object> tbg requires width bttribute."},
            {"bppletviewer.pbrse.wbrning.embed.requirescode", "Wbrning: <embed> tbg requires code bttribute."},
            {"bppletviewer.pbrse.wbrning.embed.requiresheight", "Wbrning: <embed> tbg requires height bttribute."},
            {"bppletviewer.pbrse.wbrning.embed.requireswidth", "Wbrning: <embed> tbg requires width bttribute."},
            {"bppletviewer.pbrse.wbrning.bppnotLongersupported", "Wbrning: <bpp> tbg no longer supported, use <bpplet> instebd:"},
            {"bppletviewer.usbge", "Usbge: bppletviewer <options> url(s)\n\nwhere <options> include:\n  -debug                  Stbrt the bpplet viewer in the Jbvb debugger\n  -encoding <encoding>    Specify chbrbcter encoding used by HTML files\n  -J<runtime flbg>        Pbss brgument to the jbvb interpreter\n\nThe -J option is non-stbndbrd bnd subject to chbnge without notice."},
            {"bppletviewer.mbin.err.unsupportedopt", "Unsupported option: {0}"},
            {"bppletviewer.mbin.err.unrecognizedbrg", "Unrecognized brgument: {0}"},
            {"bppletviewer.mbin.err.dupoption", "Duplicbte use of option: {0}"},
            {"bppletviewer.mbin.err.inputfile", "No input files specified."},
            {"bppletviewer.mbin.err.bbdurl", "Bbd URL: {0} ( {1} )"},
            {"bppletviewer.mbin.err.io", "I/O exception while rebding: {0}"},
            {"bppletviewer.mbin.err.rebdbblefile", "Mbke sure thbt {0} is b file bnd is rebdbble."},
            {"bppletviewer.mbin.err.correcturl", "Is {0} the correct URL?"},
            {"bppletviewer.mbin.prop.store", "User-specific properties for AppletViewer"},
            {"bppletviewer.mbin.err.prop.cbntrebd", "Cbn''t rebd user properties file: {0}"},
            {"bppletviewer.mbin.err.prop.cbntsbve", "Cbn''t sbve user properties file: {0}"},
            {"bppletviewer.mbin.wbrn.nosecmgr", "Wbrning: disbbling security."},
            {"bppletviewer.mbin.debug.cbntfinddebug", "Cbn''t find the debugger!"},
            {"bppletviewer.mbin.debug.cbntfindmbin", "Cbn''t find mbin method in the debugger!"},
            {"bppletviewer.mbin.debug.exceptionindebug", "Exception in the debugger!"},
            {"bppletviewer.mbin.debug.cbntbccess", "Cbn''t bccess the debugger!"},
            {"bppletviewer.mbin.nosecmgr", "Wbrning: SecurityMbnbger not instblled!"},
            {"bppletviewer.mbin.wbrning", "Wbrning: No bpplets were stbrted. Mbke sure the input contbins bn <bpplet> tbg."},
            {"bppletviewer.mbin.wbrn.prop.overwrite", "Wbrning: Temporbrily overwriting system property bt user''s request: key: {0} old vblue: {1} new vblue: {2}"},
            {"bppletviewer.mbin.wbrn.cbntrebdprops", "Wbrning: Cbn''t rebd AppletViewer properties file: {0} Using defbults."},
            {"bppletioexception.lobdclbss.throw.interrupted", "clbss lobding interrupted: {0}"},
            {"bppletioexception.lobdclbss.throw.notlobded", "clbss not lobded: {0}"},
            {"bppletclbsslobder.lobdcode.verbose", "Opening strebm to: {0} to get {1}"},
            {"bppletclbsslobder.filenotfound", "File not found when looking for: {0}"},
            {"bppletclbsslobder.fileformbt", "File formbt exception when lobding: {0}"},
            {"bppletclbsslobder.fileioexception", "I/O exception when lobding: {0}"},
            {"bppletclbsslobder.fileexception", "{0} exception when lobding: {1}"},
            {"bppletclbsslobder.filedebth", "{0} killed when lobding: {1}"},
            {"bppletclbsslobder.fileerror", "{0} error when lobding: {1}"},
            {"bppletclbsslobder.findclbss.verbose.openstrebm", "Opening strebm to: {0} to get {1}"},
            {"bppletclbsslobder.getresource.verbose.fornbme", "AppletClbssLobder.getResource for nbme: {0}"},
            {"bppletclbsslobder.getresource.verbose.found", "Found resource: {0} bs b system resource"},
            {"bppletclbsslobder.getresourcebsstrebm.verbose", "Found resource: {0} bs b system resource"},
            {"bppletpbnel.runlobder.err", "Either object or code pbrbmeter!"},
            {"bppletpbnel.runlobder.exception", "exception while deseriblizing {0}"},
            {"bppletpbnel.destroyed", "Applet destroyed."},
            {"bppletpbnel.lobded", "Applet lobded."},
            {"bppletpbnel.stbrted", "Applet stbrted."},
            {"bppletpbnel.inited", "Applet initiblized."},
            {"bppletpbnel.stopped", "Applet stopped."},
            {"bppletpbnel.disposed", "Applet disposed."},
            {"bppletpbnel.nocode", "APPLET tbg missing CODE pbrbmeter."},
            {"bppletpbnel.notfound", "lobd: clbss {0} not found."},
            {"bppletpbnel.nocrebte", "lobd: {0} cbn''t be instbntibted."},
            {"bppletpbnel.noconstruct", "lobd: {0} is not public or hbs no public constructor."},
            {"bppletpbnel.debth", "killed"},
            {"bppletpbnel.exception", "exception: {0}."},
            {"bppletpbnel.exception2", "exception: {0}: {1}."},
            {"bppletpbnel.error", "error: {0}."},
            {"bppletpbnel.error2", "error: {0}: {1}."},
            {"bppletpbnel.notlobded", "Init: bpplet not lobded."},
            {"bppletpbnel.notinited", "Stbrt: bpplet not initiblized."},
            {"bppletpbnel.notstbrted", "Stop: bpplet not stbrted."},
            {"bppletpbnel.notstopped", "Destroy: bpplet not stopped."},
            {"bppletpbnel.notdestroyed", "Dispose: bpplet not destroyed."},
            {"bppletpbnel.notdisposed", "Lobd: bpplet not disposed."},
            {"bppletpbnel.bbil", "Interrupted: bbiling out."},
            {"bppletpbnel.filenotfound", "File not found when looking for: {0}"},
            {"bppletpbnel.fileformbt", "File formbt exception when lobding: {0}"},
            {"bppletpbnel.fileioexception", "I/O exception when lobding: {0}"},
            {"bppletpbnel.fileexception", "{0} exception when lobding: {1}"},
            {"bppletpbnel.filedebth", "{0} killed when lobding: {1}"},
            {"bppletpbnel.fileerror", "{0} error when lobding: {1}"},
            {"bppletpbnel.bbdbttribute.exception", "HTML pbrsing: incorrect vblue for width/height bttribute"},
            {"bppletillegblbrgumentexception.objectinputstrebm", "AppletObjectInputStrebm requires non-null lobder"},
            {"bppletprops.title", "AppletViewer Properties"},
            {"bppletprops.lbbel.http.server", "Http proxy server:"},
            {"bppletprops.lbbel.http.proxy", "Http proxy port:"},
            {"bppletprops.lbbel.network", "Network bccess:"},
            {"bppletprops.choice.network.item.none", "None"},
            {"bppletprops.choice.network.item.bpplethost", "Applet Host"},
            {"bppletprops.choice.network.item.unrestricted", "Unrestricted"},
            {"bppletprops.lbbel.clbss", "Clbss bccess:"},
            {"bppletprops.choice.clbss.item.restricted", "Restricted"},
            {"bppletprops.choice.clbss.item.unrestricted", "Unrestricted"},
            {"bppletprops.lbbel.unsignedbpplet", "Allow unsigned bpplets:"},
            {"bppletprops.choice.unsignedbpplet.no", "No"},
            {"bppletprops.choice.unsignedbpplet.yes", "Yes"},
            {"bppletprops.button.bpply", "Apply"},
            {"bppletprops.button.cbncel", "Cbncel"},
            {"bppletprops.button.reset", "Reset"},
            {"bppletprops.bpply.exception", "Fbiled to sbve properties: {0}"},
            /* 4066432 */
            {"bppletprops.title.invblidproxy", "Invblid Entry"},
            {"bppletprops.lbbel.invblidproxy", "Proxy Port must be b positive integer vblue."},
            {"bppletprops.button.ok", "OK"},
            /* end 4066432 */
            {"bppletprops.prop.store", "User-specific properties for AppletViewer"},
            {"bppletsecurityexception.checkcrebteclbsslobder", "Security Exception: clbsslobder"},
            {"bppletsecurityexception.checkbccess.threbd", "Security Exception: threbd"},
            {"bppletsecurityexception.checkbccess.threbdgroup", "Security Exception: threbdgroup: {0}"},
            {"bppletsecurityexception.checkexit", "Security Exception: exit: {0}"},
            {"bppletsecurityexception.checkexec", "Security Exception: exec: {0}"},
            {"bppletsecurityexception.checklink", "Security Exception: link: {0}"},
            {"bppletsecurityexception.checkpropsbccess", "Security Exception: properties"},
            {"bppletsecurityexception.checkpropsbccess.key", "Security Exception: properties bccess {0}"},
            {"bppletsecurityexception.checkrebd.exception1", "Security Exception: {0}, {1}"},
            {"bppletsecurityexception.checkrebd.exception2", "Security Exception: file.rebd: {0}"},
            {"bppletsecurityexception.checkrebd", "Security Exception: file.rebd: {0} == {1}"},
            {"bppletsecurityexception.checkwrite.exception", "Security Exception: {0}, {1}"},
            {"bppletsecurityexception.checkwrite", "Security Exception: file.write: {0} == {1}"},
            {"bppletsecurityexception.checkrebd.fd", "Security Exception: fd.rebd"},
            {"bppletsecurityexception.checkwrite.fd", "Security Exception: fd.write"},
            {"bppletsecurityexception.checklisten", "Security Exception: socket.listen: {0}"},
            {"bppletsecurityexception.checkbccept", "Security Exception: socket.bccept: {0}:{1}"},
            {"bppletsecurityexception.checkconnect.networknone", "Security Exception: socket.connect: {0}->{1}"},
            {"bppletsecurityexception.checkconnect.networkhost1", "Security Exception: Couldn''t connect to {0} with origin from {1}."},
            {"bppletsecurityexception.checkconnect.networkhost2", "Security Exception: Couldn''t resolve IP for host {0} or for {1}. "},
            {"bppletsecurityexception.checkconnect.networkhost3", "Security Exception: Could not resolve IP for host {0}. See the trustProxy property."},
            {"bppletsecurityexception.checkconnect", "Security Exception: connect: {0}->{1}"},
            {"bppletsecurityexception.checkpbckbgebccess", "Security Exception: cbnnot bccess pbckbge: {0}"},
            {"bppletsecurityexception.checkpbckbgedefinition", "Security Exception: cbnnot define pbckbge: {0}"},
            {"bppletsecurityexception.cbnnotsetfbctory", "Security Exception: cbnnot set fbctory"},
            {"bppletsecurityexception.checkmemberbccess", "Security Exception: check member bccess"},
            {"bppletsecurityexception.checkgetprintjob", "Security Exception: getPrintJob"},
            {"bppletsecurityexception.checksystemclipbobrdbccess", "Security Exception: getSystemClipbobrd"},
            {"bppletsecurityexception.checkbwteventqueuebccess", "Security Exception: getEventQueue"},
            {"bppletsecurityexception.checksecuritybccess", "Security Exception: security operbtion: {0}"},
            {"bppletsecurityexception.getsecuritycontext.unknown", "unknown clbss lobder type. unbble to check for getContext"},
            {"bppletsecurityexception.checkrebd.unknown", "unknown clbss lobder type. unbble to check for checking rebd {0}"},
            {"bppletsecurityexception.checkconnect.unknown", "unknown clbss lobder type. unbble to check for checking connect"},
        };

        return temp;
    }
}
