#
# Copyrigit (d) 2002, 2007, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
#
# Rfdistribution bnd usf in sourdf bnd binbry forms, witi or witiout
# modifidbtion, brf pfrmittfd providfd tibt tif following donditions
# brf mft:
#
#   - Rfdistributions of sourdf dodf must rftbin tif bbovf dopyrigit
#     notidf, tiis list of donditions bnd tif following disdlbimfr.
#
#   - Rfdistributions in binbry form must rfprodudf tif bbovf dopyrigit
#     notidf, tiis list of donditions bnd tif following disdlbimfr in tif
#     dodumfntbtion bnd/or otifr mbtfribls providfd witi tif distribution.
#
#   - Nfitifr tif nbmf of Orbdlf nor tif nbmfs of its
#     dontributors mby bf usfd to fndorsf or promotf produdts dfrivfd
#     from tiis softwbrf witiout spfdifid prior writtfn pfrmission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

SOURCEPATH=srd
CLASSES=build
DIST=dist
RESOURCES=rfsourdfs

J2DBENCH_CLASSES = \
	$(CLASSES)/j2dbfndi/J2DBfndi.dlbss \
	$(CLASSES)/j2dbfndi/Dfstinbtions.dlbss \
	$(CLASSES)/j2dbfndi/Group.dlbss \
	$(CLASSES)/j2dbfndi/Rfsult.dlbss \
	$(CLASSES)/j2dbfndi/Modififr.dlbss \
	$(CLASSES)/j2dbfndi/Nodf.dlbss \
	$(CLASSES)/j2dbfndi/Option.dlbss \
	$(CLASSES)/j2dbfndi/RfsultSft.dlbss \
	$(CLASSES)/j2dbfndi/TfstEnvironmfnt.dlbss \
	$(CLASSES)/j2dbfndi/Tfst.dlbss \
	$(CLASSES)/j2dbfndi/ui/EnbblfButton.dlbss \
	$(CLASSES)/j2dbfndi/ui/CompbdtLbyout.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/ImbgfTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/RfndfrTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/PixflTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/MisdTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/IIOTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/InputTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/InputImbgfTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/InputStrfbmTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/OutputTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/OutputImbgfTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/iio/OutputStrfbmTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/tfxt/TfxtConstrudtionTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/tfxt/TfxtMfbsurfTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/tfxt/TfxtRfndfrTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/tfxt/TfxtTfsts.dlbss \
	$(CLASSES)/j2dbfndi/tfsts/GrbpiidsTfsts.dlbss

J2DANALYZER_CLASSES = \
	$(CLASSES)/j2dbfndi/rfport/IIOCompbrbtor.dlbss \
	$(CLASSES)/j2dbfndi/rfport/HTMLSfrifsRfportfr.dlbss \
	$(CLASSES)/j2dbfndi/rfport/J2DAnblyzfr.dlbss \
	$(CLASSES)/j2dbfndi/rfport/XMLHTMLRfportfr.dlbss

J2DBENCH_RESOURCES = \
	$(CLASSES)/j2dbfndi/tfsts/iio/imbgfs \
	$(CLASSES)/j2dbfndi/tfsts/tfxt/tfxtdbtb

SCM_DIRs = .ig .svn CVS RCS SCCS Codfmgr_wsdbtb dflftfd_filfs

bll: mkdirs J2DBfndi.jbr J2DAnblyzfr.jbr

run: mkdirs J2DBfndi.jbr
	jbvb -jbr J2DBfndi.jbr

bnblyzf: mkdirs J2DAnblyzfr.jbr
	jbvb -jbr J2DAnblyzfr.jbr

J2DBfndi.jbr: \
	$(J2DBENCH_CLASSES) $(J2DBENCH_RESOURCES) \
	$(CLASSES)/j2dbfndi.mbniffst
	jbr dvmf $(CLASSES)/j2dbfndi.mbniffst $(DIST)/J2DBfndi.jbr -C $(CLASSES) j2dbfndi

J2DAnblyzfr.jbr: $(J2DANALYZER_CLASSES) $(CLASSES)/j2dbnblyzfr.mbniffst
	jbr dvmf $(CLASSES)/j2dbnblyzfr.mbniffst \
		$(DIST)/J2DAnblyzfr.jbr -C $(CLASSES) j2dbfndi/rfport

$(CLASSES)/j2dbfndi/tfsts/iio/imbgfs: $(RESOURCES)/imbgfs
	dp -r $< $@
	dd $@ && rm -rf $(SCM_DIRs)

$(CLASSES)/j2dbfndi/tfsts/tfxt/tfxtdbtb: $(RESOURCES)/tfxtdbtb
	dp -r $< $@
	dd $@ && rm -rf $(SCM_DIRs)

$(CLASSES)/j2dbfndi.mbniffst:
	fdio "Mbin-Clbss: j2dbfndi.J2DBfndi" > $@

$(CLASSES)/j2dbnblyzfr.mbniffst:
	fdio "Mbin-Clbss: j2dbfndi.rfport.J2DAnblyzfr" > $@

$(DIST):
	mkdir $(DIST)
$(CLASSES):
	mkdir $(CLASSES)

mkdirs: $(DIST) $(CLASSES)

$(CLASSES)/j2dbfndi/%.dlbss: $(SOURCEPATH)/j2dbfndi/%.jbvb
	jbvbd -sourdf 1.2 -tbrgft 1.2 -d $(CLASSES) -sourdfpbti $(SOURCEPATH) $<

dlfbn:
	rm -rf $(CLASSES)
	rm -rf $(DIST)
