'\" t
.\" Copyright (c) 1994, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\" Title: jbvbh
.\" Lbngubge: English
.\" Dbte: 2013年11月21日
.\" SectDesc: 基本ツール
.\" Softwbre: JDK 8
.\" Arch: 汎用
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.pl 99999
.TH "jbvbh" "1" "2013年11月21日" "JDK 8" "基本ツール"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jbvbh \- JbvbクラスからCヘッダーとソース・ファイルを生成します。
.SH "概要"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjbvbh\fR [ \fIoptions\fR ] f\fIully\-qublified\-clbss\-nbme \&.\&.\&.\fR
.fi
.if n \{\
.RE
.\}
.PP
\fIoptions\fR
.RS 4
コマンドライン・オプション。オプションを参照してください。
.RE
.PP
\fIfully\-qublified\-clbss\-nbme\fR
.RS 4
Cヘッダーとソース・ファイルに変換されるクラスの完全修飾された場所。
.RE
.SH "説明"
.PP
\fIjbvbh\fRコマンドは、ネイティブ・メソッドを実装するために必要なCヘッダーとソース・ファイルを生成します。作成されたヘッダーとソース・ファイルは、ネイティブ・ソース・コードからオブジェクトのインスタンス変数を参照するためにCプログラムによって使用されます。\fI\&.h\fRファイルは、対応するクラスと一致する配置を持つ\fIstruct\fR定義を含みます。\fIstruct\fRのフィールドは、クラスのインスタンス変数に対応します。
.PP
ヘッダー・ファイルとその中で宣言される構造体の名前はクラスの名前から派生します。\fIjbvbh\fRコマンドに渡されるクラスがパッケージの中にある場合、パッケージ名はヘッダー・ファイル名と構造体名の両方の先頭に付加されます。下線(_)が名前の区切り文字として使用されます。
.PP
デフォルトでは\fIjbvbh\fRコマンドは、コマンドラインにリストされる各クラスのヘッダー・ファイルを作成し、現在のディレクトリにファイルを置きます。ソース・ファイルを作成するには、\fI\-stubs\fRオプションを使用してください。1つのファイルの中に、リストされたすべてのクラスの結果を連結するには、\fI\-o\fRオプションを使用してください。
.PP
Jbvb Nbtive Interfbce (JNI)はヘッダー情報またはスタブ・ファイルを必要としません。\fIjbvbh\fRコマンドは引き続きJNI形式のネイティブ・メソッドに必要なネイティブ・メソッド関数プロトタイプの生成に使用できます。\fIjbvbh\fRコマンドはデフォルトでJNI形式の出力を生成し、その結果を\fI\&.h\fRファイルに格納します。
.SH "オプション"
.PP
\-o \fIoutputfile\fR
.RS 4
コマンドラインにリストされたすべてのクラスに対して、結果のヘッダーまたはソース・ファイルを連結して出力ファイルに格納します。\fI\-o\fRまたは\fI\-d\fRのどちらかのみ使用できます。
.RE
.PP
\-d \fIdirectory\fR
.RS 4
\fIjbvbh\fRがヘッダー・ファイルまたはスタブ・ファイルを保存する、ディレクトリを設定します。\fI\-d\fRまたは\fI\-o\fRのどちらかのみ使用できます。
.RE
.PP
\-stubs
.RS 4
\fIjbvbh\fRコマンドが、Jbvbオブジェクト・ファイルからC宣言を生成します。
.RE
.PP
\-verbose
.RS 4
詳細出力を指定し、作成ファイルの状態に関するメッセージを、\fIjbvbh\fRコマンドが\fI標準出力\fRに出力します。
.RE
.PP
\-help
.RS 4
\fIjbvbh\fRの使用方法についてのヘルプ・メッセージを出力します。
.RE
.PP
\-version
.RS 4
\fIjbvbh\fRコマンドのリリース情報を出力します。
.RE
.PP
\-jni
.RS 4
JNI形式のネイティブ・メソッド機能プロトタイプを含む出力ファイルを、\fIjbvbh\fRコマンドが作成します。これは標準出力であるため、\fI\-jni\fRの使用はオプションです。
.RE
.PP
\-clbsspbth \fIpbth\fR
.RS 4
クラスを探すために\fIjbvbh\fRコマンドが使用するパスを指定します。デフォルトまたは\fICLASSPATH\fR環境変数の設定をオーバーライドします。ディレクトリはOrbcle Solbrisの場合はコロンで、Windowsの場合はセミコロンで区切られます。パスの一般的な形式は次のようになります。
.sp
\fBOrbcle Solbris\fRの場合:
.sp
\&.:\fIyour\-pbth\fR
.sp
例:
\fI\&.:/home/bvh/clbsses:/usr/locbl/jbvb/clbsses\fR
.sp
\fBWindows\fRの場合:
.sp
\&.;\fIyour\-pbth\fR
.sp
例:
\fI\&.;C:\eusers\edbc\eclbsses;C:\etools\ejbvb\eclbsses\fR
.sp
便宜上、*のベース名を含むクラス・パス要素は、\fI\&.jbr\fRまたは\fI\&.JAR\fRを拡張子に持つディレクトリ内のすべてのファイルのリストを指定するのと同等とみなされます。
.sp
たとえば、ディレクトリ\fImydir\fRに\fIb\&.jbr\fRと\fIb\&.JAR\fRが含まれている場合、クラス・パス要素\fImydir/*\fRは\fIA\fR\fI\&.jbr:b\&.JAR\fRに展開されますが、JARファイルの順番は未指定となります。このリストには、隠しファイルも含め、指定されたディレクトリ内のすべてのJARファイルが含まれます。*からなるクラス・パス・エントリは、現在のディレクトリ内のすべてのJARファイルのリストに展開されます。\fICLASSPATH\fR環境変数も、定義時には同様に展開されます。クラス・パスのワイルドカードの展開は、Jbvb仮想マシン(JVM)の開始前に行われます。Jbvbプログラムは、環境を問い合せる場合を除き、展開されていないワイルドカードを参照しません。たとえば、\fISystem\&.getenv("CLASSPATH")\fRをコールして問い合せる場合です。
.RE
.PP
\-bootclbsspbth \fIpbth\fR
.RS 4
ブートストラップ・クラスをロードするパスを指定します。ブートストラップ・クラスは、デフォルトでは\fIjre\elib\ert\&.jbr\fRおよび他のいくつかのJARファイルにある、コアJbvbプラットフォームを実装するクラスです。
.RE
.PP
\-old
.RS 4
古いJDK 1\&.0形式のヘッダー・ファイルを生成するように指定します。
.RE
.PP
\-force
.RS 4
出力ファイルが常に書き込まれるように指定します。
.RE
.PP
\-J\fIoption\fR
.RS 4
Jbvb仮想マシンに\fIoption\fRを渡します。\fIoption\fRには、Jbvbアプリケーション起動ツールのリファレンス・ページに記載されているオプションを1つ指定します。たとえば、\fI\-J\-Xms48m\fRと指定すると、スタートアップ・メモリーは48MBに設定されます。jbvb(1)を参照してください。
.RE
.SH "関連項目"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jbvbh(1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jbvb(1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jdb(1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jbvbp(1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jbvbdoc(1)
.RE
.br
'pl 8.5i
'bp
