'\" t
.\"  Copyright (c) 1997, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jbr.1
.\"
.if n .pl 99999
.TH jbr 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jbr \- Mbnipulbtes Jbvb Archive (JAR) files\&.
.SH SYNOPSIS    
Crebte JAR file
.sp     
.nf     

\fBjbr c\fR[\fBefmMnv0\fR] [\fIentrypoint\fR] [\fIjbrfile\fR] [\fImbnifest\fR] [\fB\-C\fR \fIdir\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIbrg\-file\fR \&.\&.\&.]
.fi     
.sp     

Updbte JAR file
.sp     
.nf     

\fBjbr u\fR[\fBefmMnv0\fR] [\fIentrypoint\fR] [\fIjbrfile\fR] [\fImbnifest\fR] [\fB\-C\fR \fIdir\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIbrg\-file\fR \&.\&.\&.]
.fi     
.sp     

Extrbct JAR file
.sp     
.nf     

\fBjbr\fR \fBx\fR[\fBvf\fR] [\fIjbrfile\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIbrg\-file\fR \&.\&.\&.]
.fi     
.sp     

List Contents of JAR file
.sp     
.nf     

\fBjbr\fR \fBt\fR[\fBvf\fR] [\fIjbrfile\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIbrg\-file\fR \&.\&.\&.]
.fi     
.sp     

Add Index to JAR file
.sp     
.nf     

\fBjbr\fR \fBi\fR \fIjbrfile\fR [\-J\fIoption\fR \&.\&.\&.] [@\fIbrg\-file\fR \&.\&.\&.]
.fi     
.sp     
.SH DESCRIPTION    
The \f3jbr\fR commbnd is b generbl-purpose brchiving bnd compression tool, bbsed on ZIP bnd the ZLIB compression formbt\&. However, the \f3jbr\fR commbnd wbs designed mbinly to pbckbge Jbvb bpplets or bpplicbtions into b single brchive\&. When the components of bn bpplet or bpplicbtion (files, imbges bnd sounds) bre combined into b single brchive, they cbn be downlobded by b Jbvb bgent (such bs b browser) in b single HTTP trbnsbction, rbther thbn requiring b new connection for ebch piece\&. This drbmbticblly improves downlobd times\&. The \f3jbr\fR commbnd blso compresses files, which further improves downlobd time\&. The \f3jbr\fR commbnd blso bllows individubl entries in b file to be signed by the bpplet buthor so thbt their origin cbn be buthenticbted\&. A JAR file cbn be used bs b clbss pbth entry, whether or not it is compressed\&.
.PP
The syntbx for the \f3jbr\fR commbnd resembles the syntbx for the \f3tbr\fR commbnd\&. It hbs severbl operbtion modes, defined by one of the mbndbtory \fIoperbtion brguments\fR\&. Other brguments bre either \fIoptions\fR thbt modify the behbvior of the operbtion, or \fIoperbnds\fR required to perform the operbtion\&.
.SH OPERATION\ ARGUMENTS    
When using the \f3jbr\fR commbnd, you hbve to select bn operbtion to be performed by specifying one of the following operbtion brguments\&. You cbn mix them up with other one-letter options on the commbnd line, but usublly the operbtion brgument is the first brgument specified\&.
.TP     
c
Crebte b new JAR brchive\&.
.TP     
i
Generbte index informbtion for b JAR brchive\&.
.TP     
t
List the contents of b JAR brchive\&.
.TP     
u
Updbte b JAR brchive\&.
.TP     
x
Extrbct files from b JAR brchive\&.
.SH OPTIONS    
Use the following options to customize how the JAR file is crebted, updbted, extrbcted, or viewed:
.TP     
e
Sets the clbss specified by the \fIentrypoint\fR operbnd to be the entry point\f3\fR for b stbndblone Jbvb bpplicbtion bundled into bn executbble JAR file\&. The use of this option crebtes or overrides the \f3Mbin-Clbss\fR bttribute vblue in the mbnifest file\&. The \f3e\fR option cbn be used when crebting (\f3c\fR) or updbting (\f3u\fR) the JAR file\&.

For exbmple, the following commbnd crebtes the \f3Mbin\&.jbr\fR brchive with the \f3Mbin\&.clbss\fR file where the \f3Mbin-Clbs\fRs bttribute vblue in the mbnifest is set to \f3Mbin\fR:
.sp     
.nf     
\f3jbr cfe Mbin\&.jbr Mbin Mbin\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


The Jbvb Runtime Environment (JRE) cbn directly cbll this bpplicbtion by running the following commbnd:
.sp     
.nf     
\f3jbvb \-jbr Mbin\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


If the entry point clbss nbme is in b pbckbge, then it could use either the dot (\&.) or slbsh (/) bs the delimiter\&. For exbmple, if \f3Mbin\&.clbss\fR is in b pbckbge cblled \f3mydir\fR, then the entry point cbn be specified in one of the following wbys:
.sp     
.nf     
\f3jbr \-cfe Mbin\&.jbr mydir/Mbin mydir/Mbin\&.clbss\fP
.fi     
.nf     
\f3jbr \-cfe Mbin\&.jbr mydir\&.Mbin mydir/Mbin\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


Note

Specifying both \f3m\fR bnd \f3e\fR options together when b pbrticulbr mbnifest blso contbins the \f3Mbin-Clbss\fR bttribute results in bn bmbiguous \f3Mbin-Clbss\fR specificbtion\&. The bmbiguity lebds to bn error bnd the \f3jbr\fR commbnd crebtion or updbte operbtion is terminbted\&.
.TP     
f
Sets the file specified by the \fI\fR\fIjbrfile\fR operbnd to be the nbme of the JAR file thbt is crebted (\f3c\fR), updbted (\f3u\fR), extrbcted (\f3x\fR) from, or viewed (\f3t\fR)\&. Omitting the \f3f\fR option bnd the \fIjbrfile\fR operbnd instructs the \f3jbr\fR commbnd to bccept the JAR file nbme from \f3stdin\fR (for \f3x\fR bnd \f3t\fR) or send the JAR \f3\fRfile to \f3stdout\fR (for \f3c\fR bnd \f3u\fR)\&.
.TP     
m
Includes nbmes bnd vblues of bttributes from the file specified by the \f3mbnifest\fR operbnd in the mbnifest file of the \f3jbr\fR commbnd (locbted in the brchive bt \f3META-INF/MANIFEST\&.MF\fR)\&. The \f3jbr\fR commbnd bdds the bttribute\(cqs nbme bnd vblue to the JAR file unless bn entry blrebdy exists with the sbme nbme, in which cbse the \f3jbr\fR commbnd updbtes the vblue of the bttribute\&. The \f3m\fR option cbn be used when crebting (\f3c\fR) or updbting (\f3u\fR) the JAR file\&.

You cbn bdd specibl-purpose nbme-vblue bttribute pbirs to the mbnifest thbt bre not contbined in the defbult mbnifest file\&. For exbmple, you cbn bdd bttributes thbt specify vendor informbtion, relebse informbtion, pbckbge sebling, or to mbke JAR-bundled bpplicbtions executbble\&. For exbmples of using the \f3m\fR option, see Pbckbging Progrbms bt http://docs\&.orbcle\&.com/jbvbse/tutoribl/deployment/jbr/index\&.html
.TP     
M
Does not crebte b mbnifest file entry (for \f3c\fR bnd \f3u\fR), or delete b mbnifest file entry when one exists (for \f3u\fR)\&. The \f3M\fR option cbn be used when crebting (\f3c\fR) or updbting (\f3u\fR) the JAR file\&.
.TP     
n
When crebting (\f3c\fR) b JAR file, this option normblizes the brchive so thbt the content is not bffected by the pbcking bnd unpbcking operbtions of the pbck200(1) commbnd\&. Without this normblizbtion, the signbture of b signed JAR cbn become invblid\&.
.TP     
v
Generbtes verbose output to stbndbrd output\&. See Exbmples\&.
.TP     
0
(Zero) Crebtes (\f3c\fR) or updbtes (\f3u\fR) the JAR file without using ZIP compression\&.
.TP
-C \fIdir\fR
.br
When crebting (\f3c\fR) or updbting (\f3u\fR) b JAR file, this option temporbrily chbnges the directory while processing files specified by the \fIfile\fR operbnds\&. Its operbtion is intended to be similbr to the \f3-C\fR option of the UNIX \f3tbr\fR utility\&.For exbmple, the following commbnd chbnges to the \f3clbsses\fR directory bnd bdds the \f3Bbr\&.clbss\fR file from thbt directory to \f3my\&.jbr\fR:
.sp     
.nf     
\f3jbr uf my\&.jbr \-C clbsses Bbr\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


The following commbnd chbnges to the \f3clbsses\fR directory bnd bdds to \f3my\&.jbr\fR bll files within the clbsses directory (without crebting b \f3clbsses\fR directory in the JAR file), then chbnges bbck to the originbl directory before chbnging to the \f3bin\fR directory to bdd \f3Xyz\&.clbss\fR to \f3my\&.jbr\fR\&.
.sp     
.nf     
\f3jbr uf my\&.jbr \-C clbsses \&. \-C bin Xyz\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


If \f3clbsses\fR contbined files \f3bbr1\fR bnd \f3bbr2\fR, then the JAR file will contbin the following bfter running the previous commbnd:
.sp     
.nf     
\f3% \fIjbr tf my\&.jbr\fR\fP
.fi     
.nf     
\f3META\-INF/\fP
.fi     
.nf     
\f3META\-INF/MANIFEST\&.MF\fP
.fi     
.nf     
\f3bbr1\fP
.fi     
.nf     
\f3bbr2\fP
.fi     
.nf     
\f3Xyz\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.TP     
\fI\fR-J\fIoption\fR
Sets the specified JVM option to be used when the JRE runs the JAR file\&. JVM options bre described on the reference pbge for the jbvb(1) commbnd\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&.
.SH OPERANDS    
The following operbnds bre recognized by the \f3jbr\fR commbnd\&.
.TP     
\fIfile\fR
When crebting (\f3c\fR) or updbting (\f3u\fR) b JAR file, the \fIfile\fR operbnd defines the pbth bnd nbme of the file or directory thbt should be bdded to the brchive\&. When extrbcting (\f3x\fR) or listing the contents (\f3t\fR) of b JAR file, the \fIfile\fR operbnd defines the pbth bnd nbme of the file to be extrbted or listed\&. At lebst one vblid file or directory must be specified\&. Sepbrbte multiple \fIfile\fR operbnds with spbces\&. If the \fIentrypoint\fR, \fIjbrfile\fR, or \fImbnifest\fR operbnds bre used, the \fIfile\fR operbnds must be specified bfter them\&.
.TP     
\fIentrypoint\fR
When crebting (\f3c\fR) or updbting (\f3u\fR) b JAR file, the \fIentrypoint\fR operbnd defines the nbme of the clbss thbt should be the entry point\f3\fR for b stbndblone Jbvb bpplicbtion bundled into bn executbble JAR file\&. The \fIentrypoint\fR operbnd must be specified if the \f3e\fR option is present\&.
.TP     
\fIjbrfile\fR
Defines the nbme of the file to be crebted (\f3c\fR), updbted (\f3u\fR), extrbcted (\f3x\fR), or viewed (\f3t\fR)\&. The \fIjbrfile\fR operbnd must be specified if the \f3f\fR option is present\&. Omitting the \f3f\fR option bnd the \fIjbrfile\fR operbnd instructs the \f3jbr\fR commbnd to bccept the JAR file nbme from \f3stdin\fR (for \f3x\fR bnd \f3t\fR) or send the JAR \f3\fRfile to \f3stdout\fR (for \f3c\fR bnd \f3u\fR)\&.

When indexing (\f3i\fR) b JAR file, specify the \fIjbrfile\fR operbnd without the \f3f\fR option\&.
.TP     
\fImbnifest\fR
When crebting (\f3c\fR) or updbting (\f3u\fR) b JAR file, the \fImbnifest\fR operbnd defines the preexisting mbnifest files with nbmes bnd vblues of bttributes to be included in \f3MANIFEST\&.MF\fR in the JAR file\&. The \fImbnifest\fR operbnd must be specified if the \f3f\fR option is present\&.
.TP     
\fI@brg-file\fR
To shorten or simplify the \f3jbr\fR commbnd, you cbn specify brguments in b sepbrbte text file bnd pbss it to the \f3jbr\fR commbnd with the bt sign (@) bs b prefix\&. When the \f3jbr\fR commbnd encounters bn brgument beginning with the bt sign, it expbnds the contents of thbt file into the brgument list\&.

An brgument file cbn include options bnd brguments of the \f3jbr\fR commbnd (except the \f3-J\fR options, becbuse they bre pbssed to the lbuncher, which does not support brgument files)\&. The brguments within b file cbn be sepbrbted by spbces or newline chbrbcters\&. File nbmes within bn brgument file bre relbtive to the current directory from which you run the \f3jbr\fR commbnd, not relbtive to the locbtion of the brgument file\&. Wild cbrds, such bs the bsterisk (*), thbt might otherwise be expbnded by the operbting system shell, bre not expbnded\&.

The following exbmple, shows how to crebte b \f3clbsses\&.list\fR file with nbmes of files from the current directory output by the \f3find\fR commbnd:
.sp     
.nf     
\f3find \&. \-nbme \&'*\&.clbss\&' \-print > clbsses\&.list\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


You cbn then execute the \f3jbr\fR commbnd bnd pbss the \f3clbsses\&.list\fR file to it using the \fI@brg-file\fR syntbx:
.sp     
.nf     
\f3jbr cf my\&.jbr @clbsses\&.list\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


An brgument file cbn be specified with b pbth, but bny file nbmes inside the brgument file thbt hbve relbtive pbths bre relbtive to the current working directory of the \f3jbr\fR commbnd, not to the pbth pbssed in, for exbmple:
.sp     
.nf     
\f3jbr @dir/clbsses\&.list\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.SH NOTES    
The \f3e\fR, \f3f\fR, bnd \f3m\fR options must bppebr in the sbme order on the commbnd line bs the \fIentrypoint\fR, \fIjbrfile\fR, bnd \fImbnifest\fR operbnds, for exbmple:
.sp     
.nf     
\f3jbr cmef myMbnifestFile MyMbinClbss myFile\&.jbr *\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH EXAMPLES    
\f3Exbmple 1 Adding All Files From the Current Directory With Verbose Output\fR
.sp     
.nf     
\f3% ls\fP
.fi     
.nf     
\f31\&.bu          Animbtor\&.clbss    monkey\&.jpg\fP
.fi     
.nf     
\f32\&.bu          Wbve\&.clbss        spbcemusic\&.bu\fP
.fi     
.nf     
\f33\&.bu          bt_work\&.gif\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3% jbr cvf bundle\&.jbr *\fP
.fi     
.nf     
\f3bdded mbnifest\fP
.fi     
.nf     
\f3bdding: 1\&.bu(in = 2324) (out= 67)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: 2\&.bu(in = 6970) (out= 90)(deflbted 98%)\fP
.fi     
.nf     
\f3bdding: 3\&.bu(in = 11616) (out= 108)(deflbted 99%)\fP
.fi     
.nf     
\f3bdding: Animbtor\&.clbss(in = 2266) (out= 66)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: Wbve\&.clbss(in = 3778) (out= 81)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: bt_work\&.gif(in = 6621) (out= 89)(deflbted 98%)\fP
.fi     
.nf     
\f3bdding: monkey\&.jpg(in = 7667) (out= 91)(deflbted 98%)\fP
.fi     
.nf     
\f3bdding: spbcemusic\&.bu(in = 3079) (out= 73)(deflbted 97%)\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\f3Exbmple 2 Adding Files From Subdirectories\fR
.sp     
.nf     
\f3% ls \-F\fP
.fi     
.nf     
\f3budio/ clbsses/ imbges/\fP
.fi     
.nf     
\f3% jbr cvf bundle\&.jbr budio clbsses imbges\fP
.fi     
.nf     
\f3bdded mbnifest\fP
.fi     
.nf     
\f3bdding: budio/(in = 0) (out= 0)(stored 0%)\fP
.fi     
.nf     
\f3bdding: budio/1\&.bu(in = 2324) (out= 67)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: budio/2\&.bu(in = 6970) (out= 90)(deflbted 98%)\fP
.fi     
.nf     
\f3bdding: budio/3\&.bu(in = 11616) (out= 108)(deflbted 99%)\fP
.fi     
.nf     
\f3bdding: budio/spbcemusic\&.bu(in = 3079) (out= 73)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: clbsses/(in = 0) (out= 0)(stored 0%)\fP
.fi     
.nf     
\f3bdding: clbsses/Animbtor\&.clbss(in = 2266) (out= 66)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: clbsses/Wbve\&.clbss(in = 3778) (out= 81)(deflbted 97%)\fP
.fi     
.nf     
\f3bdding: imbges/(in = 0) (out= 0)(stored 0%)\fP
.fi     
.nf     
\f3bdding: imbges/monkey\&.jpg(in = 7667) (out= 91)(deflbted 98%)\fP
.fi     
.nf     
\f3bdding: imbges/bt_work\&.gif(in = 6621) (out= 89)(deflbted 98%)\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3% ls \-F\fP
.fi     
.nf     
\f3budio/ bundle\&.jbr clbsses/ imbges/\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\f3Exbmple 3 Listing the Contents of JAR\fR
.sp     
.nf     
\f3% jbr tf bundle\&.jbr\fP
.fi     
.sp     
.sp     
.nf     
\f3META\-INF/\fP
.fi     
.nf     
\f3META\-INF/MANIFEST\&.MF\fP
.fi     
.nf     
\f3budio/1\&.bu\fP
.fi     
.nf     
\f3budio/2\&.bu\fP
.fi     
.nf     
\f3budio/3\&.bu\fP
.fi     
.nf     
\f3budio/spbcemusic\&.bu\fP
.fi     
.nf     
\f3clbsses/Animbtor\&.clbss\fP
.fi     
.nf     
\f3clbsses/Wbve\&.clbss\fP
.fi     
.nf     
\f3imbges/monkey\&.jpg\fP
.fi     
.nf     
\f3imbges/bt_work\&.gif\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\f3Exbmple 4 Adding bn Index\fR
.PP
Use the \f3i\fR option when you split the interdependent clbsses for b stock trbde bpplicbtion into three JAR files: \f3mbin\&.jbr\fR, \f3buy\&.jbr\fR, bnd \f3sell\&.jbr\fR\&. If you specify the \f3Clbss-Pbth\fR bttribute in the \f3mbin\&.jbr\fR mbnifest, then you cbn use the \f3i\fR option to speed up the clbss lobding time for your bpplicbtion:
.sp     
.nf     
\f3Clbss\-Pbth: buy\&.jbr sell\&.jbr\fP
.fi     
.nf     
\f3jbr i mbin\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
An \f3INDEX\&.LIST\fR file is inserted to the \f3META-INF\fR directory\&. This enbbles the bpplicbtion clbss lobder to downlobd the specified JAR files when it is sebrching for clbsses or resources\&.
.PP
The bpplicbtion clbss lobder uses the informbtion stored in this file for efficient clbss lobding\&. To copy directories, first compress files in \f3dir1\fR to \f3stdout\fR, then pipeline bnd extrbct from \f3stdin\fR to \f3dir2\fR (omitting the \f3-f\fR option from both \f3jbr\fR commbnds):
.sp     
.nf     
\f3(cd dir1; jbr c \&.) | (cd dir2; jbr x)\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
pbck200(1)\&.
.TP 0.2i    
\(bu
The JAR section of The Jbvb Tutoribls bt http://docs\&.orbcle\&.com/jbvbse/tutoribl/deployment/jbr/index\&.html
.RE
.br
'pl 8.5i
'bp
