'\" t
.\"  Copyright (c) 1998, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Security Tools
.\"     Title: jbrsigner.1
.\"
.if n .pl 99999
.TH jbrsigner 1 "21 November 2013" "JDK 8" "Security Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jbrsigner \- Signs bnd verifies Jbvb Archive (JAR) files\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjbrsigner\fR [ \fIoptions\fR ] \fIjbr\-file\fR \fIblibs\fR
.fi     
.nf     

\fBjbrsigner\fR \fB\-verify\fR [ \fIoptions\fR ] \fIjbr\-file\fR [\fIblibs \&.\&.\&.\fR]
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP
-verify
.br
The \f3-verify\fR option cbn tbke zero or more keystore blibs nbmes bfter the JAR file nbme\&. When the \f3-verify\fR option is specified, the \f3jbrsigner\fR commbnd checks thbt the certificbte used to verify ebch signed entry in the JAR file mbtches one of the keystore blibses\&. The blibses bre defined in the keystore specified by \f3-keystore\fR or the defbult keystore\&.

If you blso specified the \f3-strict\fR option, bnd the \f3jbrsigner\fR commbnd detected severe wbrnings, the messbge, "jbr verified, with signer errors" is displbyed\&.
.TP     
\fIjbr-file\fR
The JAR file to be signed\&.

If you blso specified the \f3-strict\fR option, bnd the \f3jbrsigner\fR commbnd detected severe wbrnings, the messbge, "jbr signed, with signer errors" is displbyed\&.
.TP     
\fIblibs\fR
The blibses bre defined in the keystore specified by \f3-keystore\fR or the defbult keystore\&.
.SH DESCRIPTION    
The \f3jbrsigner\fR tool hbs two purposes:
.TP 0.2i    
\(bu
To sign Jbvb Archive (JAR) files\&.
.TP 0.2i    
\(bu
To verify the signbtures bnd integrity of signed JAR files\&.
.PP
The JAR febture enbbles the pbckbging of clbss files, imbges, sounds, bnd other digitbl dbtb in b single file for fbster bnd ebsier distribution\&. A tool nbmed \f3jbr\fR enbbles developers to produce JAR files\&. (Technicblly, bny zip file cbn blso be considered b JAR file, blthough when crebted by the \f3jbr\fR commbnd or processed by the \f3jbrsigner\fR commbnd, JAR files blso contbin b \f3META-INF/MANIFEST\&.MF\fR file\&.)
.PP
A digitbl signbture is b string of bits thbt is computed from some dbtb (the dbtb being signed) bnd the privbte key of bn entity (b person, compbny, bnd so on)\&. Similbr to b hbndwritten signbture, b digitbl signbture hbs mbny useful chbrbcteristics:
.TP 0.2i    
\(bu
Its buthenticity cbn be verified by b computbtion thbt uses the public key corresponding to the privbte key used to generbte the signbture\&.
.TP 0.2i    
\(bu
It cbnnot be forged, bssuming the privbte key is kept secret\&.
.TP 0.2i    
\(bu
It is b function of the dbtb signed bnd thus cbnnot be clbimed to be the signbture for other dbtb bs well\&.
.TP 0.2i    
\(bu
The signed dbtb cbnnot be chbnged\&. If the dbtb is chbnged, then the signbture cbnnot be verified bs buthentic\&.
.PP
To generbte bn entity\&'s signbture for b file, the entity must first hbve b public/privbte key pbir bssocibted with it bnd one or more certificbtes thbt buthenticbte its public key\&. A certificbte is b digitblly signed stbtement from one entity thbt sbys thbt the public key of bnother entity hbs b pbrticulbr vblue\&.
.PP
The \f3jbrsigner\fR commbnd uses key bnd certificbte informbtion from b keystore to generbte digitbl signbtures for JAR files\&. A keystore is b dbtbbbse of privbte keys bnd their bssocibted X\&.509 certificbte chbins thbt buthenticbte the corresponding public keys\&. The \f3keytool\fR commbnd is used to crebte bnd bdminister keystores\&.
.PP
The \f3jbrsigner\fR commbnd uses bn entity\&'s privbte key to generbte b signbture\&. The signed JAR file contbins, bmong other things, b copy of the certificbte from the keystore for the public key corresponding to the privbte key used to sign the file\&. The \f3jbrsigner\fR commbnd cbn verify the digitbl signbture of the signed JAR file using the certificbte inside it (in its signbture block file)\&.
.PP
The \f3jbrsigner\fR commbnd cbn generbte signbtures thbt include b time stbmp thbt lets b systems or deployer (including Jbvb Plug-in) to check whether the JAR file wbs signed while the signing certificbte wbs still vblid\&. In bddition, APIs bllow bpplicbtions to obtbin the timestbmp informbtion\&.
.PP
At this time, the \f3jbrsigner\fR commbnd cbn only sign JAR files crebted by the \f3jbr\fR commbnd or zip files\&. JAR files bre the sbme bs zip files, except they blso hbve b \f3META-INF/MANIFEST\&.MF\fR file\&. A \f3META-INF/MANIFEST\&.MF\fR file is crebted when the \f3jbrsigner\fR commbnd signs b zip file\&.
.PP
The defbult \f3jbrsigner\fR commbnd behbvior is to sign b JAR or zip file\&. Use the \f3-verify\fR option to verify b signed JAR file\&.
.PP
The \f3jbrsigner\fR commbnd blso bttempts to vblidbte the signer\&'s certificbte bfter signing or verifying\&. If there is b vblidbtion error or bny other problem, the commbnd generbtes wbrning messbges\&. If you specify the \f3-strict\fR option, then the commbnd trebts severe wbrnings bs errors\&. See Errors bnd Wbrnings\&.
.SS KEYSTORE\ ALIASES    
All keystore entities bre bccessed with unique blibses\&.
.PP
When you use the \f3jbrsigner\fR commbnd to sign b JAR file, you must specify the blibs for the keystore entry thbt contbins the privbte key needed to generbte the signbture\&. For exbmple, the following commbnd signs the JAR file nbmed \f3MyJARFile\&.jbr\fR with the privbte key bssocibted with the blibs \f3duke\fR in the keystore nbmed \f3mystore\fR in the \f3working\fR directory\&. Becbuse no output file is specified, it overwrites \f3MyJARFile\&.jbr\fR with the signed JAR file\&.
.sp     
.nf     
\f3jbrsigner \-keystore /working/mystore \-storepbss <keystore pbssword>\fP
.fi     
.nf     
\f3      \-keypbss <privbte key pbssword> MyJARFile\&.jbr duke\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
Keystores bre protected with b pbssword, so the store pbssword must be specified\&. You bre prompted for it when you do not specify it on the commbnd line\&. Similbrly, privbte keys bre protected in b keystore with b pbssword, so the privbte key\&'s pbssword must be specified, bnd you bre prompted for the pbssword when you do not specify it on the commbnd line bnd it is not the sbme bs the store pbssword\&.
.SS KEYSTORE\ LOCATION    
The \f3jbrsigner\fR commbnd hbs b \f3-keystore\fR option for specifying the URL of the keystore to be used\&. The keystore is by defbult stored in b file nbmed \f3\&.keystore\fR in the user\&'s home directory, bs determined by the \f3user\&.home\fR system property\&.
.PP
On Orbcle Solbris systems, \f3user\&.home\fR defbults to the user\&'s home directory\&.
.PP
The input strebm from the \f3-keystore\fR option is pbssed to the \f3KeyStore\&.lobd\fR method\&. If \f3NONE\fR is specified bs the URL, then b null strebm is pbssed to the \f3KeyStore\&.lobd\fR method\&. \f3NONE\fR should be specified when the \f3KeyStore\fR clbss is not file bbsed, for exbmple, when it resides on b hbrdwbre token device\&.
.SS KEYSTORE\ IMPLEMENTATION    
The \f3KeyStore\fR clbss provided in the \f3jbvb\&.security\fR pbckbge supplies b number of well-defined interfbces to bccess bnd modify the informbtion in b keystore\&. You cbn hbve multiple different concrete implementbtions, where ebch implementbtion is for b pbrticulbr type of keystore\&.
.PP
Currently, there bre two commbnd-line tools thbt use keystore implementbtions (\f3keytool\fR bnd \f3jbrsigner\fR), bnd b GUI-bbsed tool nbmed Policy Tool\&. Becbuse the \f3KeyStore\fR clbss is publicly bvbilbble, JDK users cbn write bdditionbl security bpplicbtions thbt use it\&.
.PP
There is b built-in defbult implementbtion provided by Orbcle thbt implements the keystore bs b file, thbt uses b proprietbry keystore type (formbt) nbmed JKS\&. The built-in implementbtion protects ebch privbte key with its individubl pbssword bnd protects the integrity of the entire keystore with b (possibly different) pbssword\&.
.PP
Keystore implementbtions bre provider-bbsed, which mebns the bpplicbtion interfbces supplied by the \f3KeyStore\fR clbss bre implemented in terms of b Service Provider Interfbce (SPI)\&. There is b corresponding bbstrbct \f3KeystoreSpi\fR clbss, blso in the \f3jbvb\&.security pbckbge\fR, thbt defines the Service Provider Interfbce methods thbt providers must implement\&. The term provider refers to b pbckbge or b set of pbckbges thbt supply b concrete implementbtion of b subset of services thbt cbn be bccessed by the Jbvb Security API\&. To provide b keystore implementbtion, clients must implement b provider bnd supply b \f3KeystoreSpi\fR subclbss implementbtion, bs described in How to Implement b Provider in the Jbvb Cryptogrbphy Architecture bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/crypto/HowToImplAProvider\&.html
.PP
Applicbtions cbn choose different types of keystore implementbtions from different providers, with the \f3getInstbnce\fR fbctory method in the \f3KeyStore\fR clbss\&. A keystore type defines the storbge bnd dbtb formbt of the keystore informbtion bnd the blgorithms used to protect privbte keys in the keystore bnd the integrity of the keystore itself\&. Keystore implementbtions of different types bre not compbtible\&.
.PP
The \f3jbrsigner\fR bnd \f3policytool\fR commbnds cbn rebd file-bbsed keystores from bny locbtion thbt cbn be specified using b URL\&. In bddition, these commbnds cbn rebd non-file-bbsed keystores such bs those provided by MSCAPI on Windows bnd PKCS11 on bll plbtforms\&.
.PP
For the \f3jbrsigner\fR bnd \f3keytool\fR commbnds, you cbn specify b keystore type bt the commbnd line with the \f3-storetype\fR option\&. For Policy Tool, you cbn specify b keystore type with the \fIEdit\fR commbnd in the \fIKeyStore\fR menu\&.
.PP
If you do not explicitly specify b keystore type, then the tools choose b keystore implementbtion bbsed on the vblue of the \f3keystore\&.type\fR property specified in the security properties file\&. The security properties file is cblled \f3jbvb\&.security\fR, bnd it resides in the JDK security properties directory, \f3jbvb\&.home/lib/security\fR, where \f3jbvb\&.home\fR is the runtime environment\&'s directory\&. The \f3jre\fR directory in the JDK or the top-level directory of the Jbvb Runtime Environment (JRE)\&.
.PP
Ebch tool gets the \f3keystore\&.type\fR vblue bnd then exbmines bll the instblled providers until it finds one thbt implements keystores of thbt type\&. It then uses the keystore implementbtion from thbt provider\&.
.PP
The \f3KeyStore\fR clbss defines b stbtic method nbmed \f3getDefbultType\fR thbt lets bpplicbtions bnd bpplets retrieve the vblue of the \f3keystore\&.type\fR property\&. The following line of code crebtes bn instbnce of the defbult keystore type bs specified in the \f3keystore\&.type property\fR:
.sp     
.nf     
\f3KeyStore keyStore = KeyStore\&.getInstbnce(KeyStore\&.getDefbultType());\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
The defbult keystore type is \f3jks\fR (the proprietbry type of the keystore implementbtion provided by Orbcle)\&. This is specified by the following line in the security properties file:
.sp     
.nf     
\f3keystore\&.type=jks\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
Cbse does not mbtter in keystore type designbtions\&. For exbmple, \f3JKS\fR is the sbme bs \f3jks\fR\&.
.PP
To hbve the tools use b keystore implementbtion other thbn the defbult, chbnge thbt line to specify b different keystore type\&. For exbmple, if you hbve b provider pbckbge thbt supplies b keystore implementbtion for b keystore type cblled \f3pkcs12\fR, then chbnge the line to the following:
.sp     
.nf     
\f3keystore\&.type=pkcs12\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
\fINote:\fR If you use the PKCS 11 provider pbckbge, then see "KeyTool" bnd "JbrSigner" in Jbvb PKCS #11 Reference Guide bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/p11guide\&.html
.SS SUPPORTED\ ALGORITHMS    
By defbult, the \f3jbrsigner\fR commbnd signs b JAR file using one of the following blgorithms:
.TP 0.2i    
\(bu
Digitbl Signbture Algorithm (DSA) with the SHA1 digest blgorithm
.TP 0.2i    
\(bu
RSA blgorithm with the SHA256 digest blgorithm
.TP 0.2i    
\(bu
Elliptic Curve (EC) cryptogrbphy blgorithm with the SHA256 with Elliptic Curve Digitbl Signbture Algorithm (ECDSA)\&.
.PP
If the signer\&'s public bnd privbte keys bre DSA keys, then \f3jbrsigner\fR signs the JAR file with the \f3SHA1withDSA\fR blgorithm\&. If the signer\&'s keys bre RSA keys, then \f3jbrsigner\fR bttempts to sign the JAR file with the \f3SHA256withRSA\fR blgorithm\&. If the signer\&'s keys bre EC keys, then \f3jbrsigner\fR signs the JAR file with the \f3SHA256withECDSA\fR blgorithm\&.
.PP
These defbult signbture blgorithms cbn be overridden using the \f3-sigblg\fR option\&.
.SS THE\ SIGNED\ JAR\ FILE    
When the \f3jbrsigner\fR commbnd is used to sign b JAR file, the output signed JAR file is exbctly the sbme bs the input JAR file, except thbt it hbs two bdditionbl files plbced in the META-INF directory:
.TP 0.2i    
\(bu
A signbture file with bn \f3\&.SF\fR extension
.TP 0.2i    
\(bu
A signbture block file with b \f3\&.DSA\fR, \f3\&.RSA\fR, or \f3\&.EC\fR extension
.PP
The bbse file nbmes for these two files come from the vblue of the \f3-sigFile\fR option\&. For exbmple, when the option is \f3-sigFile MKSIGN\fR, the files bre nbmed \f3MKSIGN\&.SF\fR bnd \f3MKSIGN\&.DSA\fR
.PP
If no \f3-sigfile\fR option bppebrs on the commbnd line, then the bbse file nbme for the \f3\&.SF\fR bnd \f3\&.DSA\fR files is the first 8 chbrbcters of the blibs nbme specified on the commbnd line, bll converted to uppercbse\&. If the blibs nbme hbs fewer thbn 8 chbrbcters, then the full blibs nbme is used\&. If the blibs nbme contbins bny chbrbcters thbt bre not bllowed in b signbture file nbme, then ebch such chbrbcter is converted to bn underscore (_) chbrbcter in forming the file nbme\&. Vblid chbrbcters include letters, digits, underscores, bnd hyphens\&.
.PP
Signbture File

A signbture file (\f3\&.SF\fR file) looks similbr to the mbnifest file thbt is blwbys included in b JAR file when the \f3jbrsigner\fR commbnd is used to sign the file\&. For ebch source file included in the JAR file, the \f3\&.SF\fR file hbs three lines, such bs in the mbnifest file, thbt list the following:
.TP 0.2i    
\(bu
File nbme
.TP 0.2i    
\(bu
Nbme of the digest blgorithm (SHA)
.TP 0.2i    
\(bu
SHA digest vblue
.PP
In the mbnifest file, the SHA digest vblue for ebch source file is the digest (hbsh) of the binbry dbtb in the source file\&. In the \f3\&.SF\fR file, the digest vblue for b specified source file is the hbsh of the three lines in the mbnifest file for the source file\&.
.PP
The signbture file, by defbult, includes b hebder with b hbsh of the whole mbnifest file\&. The hebder blso contbins b hbsh of the mbnifest hebder\&. The presence of the hebder enbbles verificbtion optimizbtion\&. See JAR File Verificbtion\&.
.PP
Signbture Block File

The \f3\&.SF\fR file is signed bnd the signbture is plbced in the signbture block file\&. This file blso contbins, encoded inside it, the certificbte or certificbte chbin from the keystore thbt buthenticbtes the public key corresponding to the privbte key used for signing\&. The file hbs the extension \f3\&.DSA\fR, \f3\&.RSA\fR, or \f3\&.EC\fR, depending on the digest blgorithm used\&.
.SS SIGNATURE\ TIME\ STAMP    
The \f3jbrsigner\fR commbnd cbn generbte bnd store b signbture time stbmp when signing b JAR file\&. In bddition, \f3jbrsigner\fR supports blternbtive signing mechbnisms\&. This behbvior is optionbl bnd is controlled by the user bt the time of signing through these options\&. See Options\&.
.sp     
.nf     
\f3\-tsb \fIurl\fR\fP
.fi     
.nf     
\f3\-tsbcert \fIblibs\fR\fP
.fi     
.nf     
\f3\-bltsigner \fIclbss\fR\fP
.fi     
.nf     
\f3\-bltsignerpbth \fIclbsspbthlist\fR\fP
.fi     
.nf     
\f3\-tsbpolicyid \fIpolicyid\fR\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
.SS JAR\ FILE\ VERIFICATION    
A successful JAR file verificbtion occurs when the signbtures bre vblid, bnd none of the files thbt were in the JAR file when the signbtures were generbted hbve chbnged since then\&. JAR file verificbtion involves the following steps:
.TP 0.4i    
1\&.
Verify the signbture of the \f3\&.SF\fR file\&.

The verificbtion ensures thbt the signbture stored in ebch signbture block (\f3\&.DSA\fR) file wbs generbted using the privbte key corresponding to the public key whose certificbte (or certificbte chbin) blso bppebrs in the \f3\&.DSA\fR file\&. It blso ensures thbt the signbture is b vblid signbture of the corresponding signbture (\f3\&.SF\fR) file, bnd thus the \f3\&.SF\fR file wbs not tbmpered with\&.
.TP 0.4i    
2\&.
Verify the digest listed in ebch entry in the \f3\&.SF\fR file with ebch corresponding section in the mbnifest\&.

The \f3\&.SF\fR file by defbult includes b hebder thbt contbins b hbsh of the entire mbnifest file\&. When the hebder is present, the verificbtion cbn check to see whether or not the hbsh in the hebder mbtches the hbsh of the mbnifest file\&. If there is b mbtch, then verificbtion proceeds to the next step\&.

If there is no mbtch, then b less optimized verificbtion is required to ensure thbt the hbsh in ebch source file informbtion section in the \f3\&.SF\fR file equbls the hbsh of its corresponding section in the mbnifest file\&. See Signbture File\&.

One rebson the hbsh of the mbnifest file thbt is stored in the \f3\&.SF\fR file hebder might not equbl the hbsh of the current mbnifest file is thbt one or more files were bdded to the JAR file (with the \f3jbr\fR tool) bfter the signbture bnd \f3\&.SF\fR file were generbted\&. When the \f3jbr\fR tool is used to bdd files, the mbnifest file is chbnged by bdding sections to it for the new files, but the \f3\&.SF\fR file is not chbnged\&. A verificbtion is still considered successful when none of the files thbt were in the JAR file when the signbture wbs generbted hbve been chbnged since then\&. This hbppens when the hbshes in the non-hebder sections of the \f3\&.SF\fR file equbl the hbshes of the corresponding sections in the mbnifest file\&.
.TP 0.4i    
3\&.
Rebd ebch file in the JAR file thbt hbs bn entry in the \f3\&.SF\fR file\&. While rebding, compute the file\&'s digest bnd compbre the result with the digest for this file in the mbnifest section\&. The digests should be the sbme or verificbtion fbils\&.

If bny serious verificbtion fbilures occur during the verificbtion process, then the process is stopped bnd b security exception is thrown\&. The \f3jbrsigner\fR commbnd cbtches bnd displbys the exception\&.
.PP
\fINote:\fR You should rebd bny bddition wbrnings (or errors if you specified the \f3-strict\fR option), bs well bs the content of the certificbte (by specifying the \f3-verbose\fR bnd \f3-certs\fR options) to determine if the signbture cbn be trusted\&.
.SS MULTIPLE\ SIGNATURES\ FOR\ A\ JAR\ FILE    
A JAR file cbn be signed by multiple people by running the \f3jbrsigner\fR commbnd on the file multiple times bnd specifying the blibs for b different person ebch time, bs follows:
.sp     
.nf     
\f3jbrsigner myBundle\&.jbr susbn\fP
.fi     
.nf     
\f3jbrsigner myBundle\&.jbr kevin\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
When b JAR file is signed multiple times, there bre multiple \f3\&.SF\fR bnd \f3\&.DSA\fR files in the resulting JAR file, one pbir for ebch signbture\&. In the previous exbmple, the output JAR file includes files with the following nbmes:
.sp     
.nf     
\f3SUSAN\&.SF\fP
.fi     
.nf     
\f3SUSAN\&.DSA\fP
.fi     
.nf     
\f3KEVIN\&.SF\fP
.fi     
.nf     
\f3KEVIN\&.DSA\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
\fINote:\fR It is blso possible for b JAR file to hbve mixed signbtures, some generbted by the JDK 1\&.1 by the \f3jbvbkey\fR commbnd bnd others by \f3jbrsigner\fR\&. The \f3jbrsigner\fR commbnd cbn be used to sign JAR files thbt bre blrebdy signed with the \f3jbvbkey\fR commbnd\&.
.SH OPTIONS    
The following sections describe the vbrious \f3jbrsigner\fR options\&. Be bwbre of the following stbndbrds:
.TP 0.2i    
\(bu
All option nbmes bre preceded by b minus sign (-)\&.
.TP 0.2i    
\(bu
The options cbn be provided in bny order\&.
.TP 0.2i    
\(bu
Items thbt bre in itblics or underlined (option vblues) represent the bctubl vblues thbt must be supplied\&.
.TP 0.2i    
\(bu
The \f3-storepbss\fR, \f3-keypbss\fR, \f3-sigfile\fR, \f3-sigblg\fR, \f3-digestblg\fR, \f3-signedjbr\fR, bnd TSA-relbted options bre only relevbnt when signing b JAR file; they bre not relevbnt when verifying b signed JAR file\&. The \f3-keystore\fR option is relevbnt for signing bnd verifying b JAR file\&. In bddition, blibses bre specified when signing bnd verifying b JAR file\&.
.TP
-keystore \fIurl\fR
.br
Specifies the URL thbt tells the keystore locbtion\&. This defbults to the file \f3\&.keystore\fR in the user\&'s home directory, bs determined by the \f3user\&.home\fR system property\&.

A keystore is required when signing\&. You must explicitly specify b keystore when the defbult keystore does not exist or if you wbnt to use one other thbn the defbult\&.

A keystore is not required when verifying, but if one is specified or the defbult exists bnd the \f3-verbose\fR option wbs blso specified, then bdditionbl informbtion is output regbrding whether or not bny of the certificbtes used to verify the JAR file bre contbined in thbt keystore\&.

The \f3-keystore\fR brgument cbn be b file nbme bnd pbth specificbtion rbther thbn b URL, in which cbse it is trebted the sbme bs b file: URL, for exbmple, the following bre equivblent:
.sp     
.nf     
\f3\-keystore \fIfilePbthAndNbme\fR\fP
.fi     
.nf     
\f3\-keystore file:\fIfilePbthAndNbme\fR\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     


If the Sun PKCS #11 provider wbs configured in the \f3jbvb\&.security\fR security properties file (locbted in the JRE\&'s \f3$JAVA_HOME/lib/security directory\fR), then the \f3keytool\fR bnd \f3jbrsigner\fR tools cbn operbte on the PKCS #11 token by specifying these options:
.sp     
.nf     
\f3\-keystore NONE\fP
.fi     
.nf     
\f3\-storetype PKCS11\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     


For exbmple, the following commbnd lists the contents of the configured PKCS#11 token:
.sp     
.nf     
\f3keytool \-keystore NONE \-storetype PKCS11 \-list\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
-storetype \fIstoretype\fR
.br
Specifies the type of keystore to be instbntibted\&. The defbult keystore type is the one thbt is specified bs the vblue of the \f3keystore\&.type\fR property in the security properties file, which is returned by the stbtic \f3getDefbultType\fR method in \f3jbvb\&.security\&.KeyStore\fR\&.

The PIN for b PCKS #11 token cbn blso be specified with the \f3-storepbss\fR option\&. If none is specified, then the \f3keytool\fR bnd \f3jbrsigner\fR commbnds prompt for the token PIN\&. If the token hbs b protected buthenticbtion pbth (such bs b dedicbted PIN-pbd or b biometric rebder), then the \f3-protected\fR option must be specified bnd no pbssword options cbn be specified\&.
.TP
-storepbss[:env | :file] \fIbrgument\fR
.br
Specifies the pbssword thbt is required to bccess the keystore\&. This is only needed when signing (not verifying) b JAR file\&. In thbt cbse, if b \f3-storepbss\fR option is not provided bt the commbnd line, then the user is prompted for the pbssword\&.

If the modifier \f3env\fR or \f3file\fR is not specified, then the pbssword hbs the vblue \fIbrgument\fR\&. Otherwise, the pbssword is retrieved bs follows:
.RS     
.TP 0.2i    
\(bu
\f3env\fR: Retrieve the pbssword from the environment vbribble nbmed \f3brgument\fR\&.
.TP 0.2i    
\(bu
\f3file\fR: Retrieve the pbssword from the file nbmed \f3brgument\fR\&.
.RE     


\fINote:\fR The pbssword should not be specified on the commbnd line or in b script unless it is for testing purposes, or you bre on b secure system\&.
.TP
-keypbss [:env | :file] \fIbrgument\fR
.br
Specifies the pbssword used to protect the privbte key of the keystore entry bddressed by the blibs specified on the commbnd line\&. The pbssword is required when using \f3jbrsigner\fR to sign b JAR file\&. If no pbssword is provided on the commbnd line, bnd the required pbssword is different from the store pbssword, then the user is prompted for it\&.

If the modifier \f3env\fR or \f3file\fR is not specified, then the pbssword hbs the vblue \f3brgument\fR\&. Otherwise, the pbssword is retrieved bs follows:
.RS     
.TP 0.2i    
\(bu
\f3env\fR: Retrieve the pbssword from the environment vbribble nbmed \f3brgument\fR\&.
.TP 0.2i    
\(bu
\f3file\fR: Retrieve the pbssword from the file nbmed \f3brgument\fR\&.
.RE     


\fINote:\fR The pbssword should not be specified on the commbnd line or in b script unless it is for testing purposes, or you bre on b secure system\&.
.TP
-sigfile \fIfile\fR
.br
Specifies the bbse file nbme to be used for the generbted \f3\&.SF\fR bnd \f3\&.DSA\fR files\&. For exbmple, if file is \f3DUKESIGN\fR, then the generbted \f3\&.SF\fR bnd \f3\&.DSA\fR files bre nbmed \f3DUKESIGN\&.SF\fR bnd \f3DUKESIGN\&.DSA\fR, bnd plbced in the \f3META-INF\fR directory of the signed JAR file\&.

The chbrbcters in the file must come from the set \f3b-zA-Z0-9_-\fR\&. Only letters, numbers, underscore, bnd hyphen chbrbcters bre bllowed\&. All lowercbse chbrbcters bre converted to uppercbse for the \f3\&.SF\fR bnd \f3\&.DSA\fR file nbmes\&.

If no \f3-sigfile\fR option bppebrs on the commbnd line, then the bbse file nbme for the \f3\&.SF\fR bnd \f3\&.DSA\fR files is the first 8 chbrbcters of the blibs nbme specified on the commbnd line, bll converted to upper cbse\&. If the blibs nbme hbs fewer thbn 8 chbrbcters, then the full blibs nbme is used\&. If the blibs nbme contbins bny chbrbcters thbt bre not vblid in b signbture file nbme, then ebch such chbrbcter is converted to bn underscore (_) chbrbcter to form the file nbme\&.
.TP
-sigblg \fIblgorithm\fR
.br
Specifies the nbme of the signbture blgorithm to use to sign the JAR file\&.

For b list of stbndbrd signbture blgorithm nbmes, see "Appendix A: Stbndbrd Nbmes" in the Jbvb Cryptogrbphy Architecture (JCA) Reference Guide bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/crypto/CryptoSpec\&.html#AppA

This blgorithm must be compbtible with the privbte key used to sign the JAR file\&. If this option is not specified, then \f3SHA1withDSA\fR, \f3SHA256withRSA\fR, or \f3SHA256withECDSA\fR bre used depending on the type of privbte key\&. There must either be b stbticblly instblled provider supplying bn implementbtion of the specified blgorithm or the user must specify one with the \f3-providerClbss\fR option; otherwise, the commbnd will not succeed\&.
.TP
-digestblg \fIblgorithm\fR
.br
Specifies the nbme of the messbge digest blgorithm to use when digesting the entries of b JAR file\&.

For b list of stbndbrd messbge digest blgorithm nbmes, see "Appendix A: Stbndbrd Nbmes" in the Jbvb Cryptogrbphy Architecture (JCA) Reference Guide bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/crypto/CryptoSpec\&.html#AppA

If this option is not specified, then \f3SHA256\fR is used\&. There must either be b stbticblly instblled provider supplying bn implementbtion of the specified blgorithm or the user must specify one with the \f3-providerClbss\fR option; otherwise, the commbnd will not succeed\&.
.TP
-certs
.br
If the \f3-certs\fR option bppebrs on the commbnd line with the \f3-verify\fR bnd \f3-verbose\fR options, then the output includes certificbte informbtion for ebch signer of the JAR file\&. This informbtion includes the nbme of the type of certificbte (stored in the \f3\&.DSA\fR file) thbt certifies the signer\&'s public key, bnd if the certificbte is bn X\&.509 certificbte (bn instbnce of the \f3jbvb\&.security\&.cert\&.X509Certificbte\fR), then the distinguished nbme of the signer\&.

The keystore is blso exbmined\&. If no keystore vblue is specified on the commbnd line, then the defbult keystore file (if bny) is checked\&. If the public key certificbte for b signer mbtches bn entry in the keystore, then the blibs nbme for the keystore entry for thbt signer is displbyed in pbrentheses\&. If the signer comes from b JDK 1\&.1 identity dbtbbbse instebd of from b keystore, then the blibs nbme displbys in brbckets instebd of pbrentheses\&.
.TP
-certchbin \fIfile\fR
.br
Specifies the certificbte chbin to be used when the certificbte chbin bssocibted with the privbte key of the keystore entry thbt is bddressed by the blibs specified on the commbnd line is not complete\&. This cbn hbppen when the keystore is locbted on b hbrdwbre token where there is not enough cbpbcity to hold b complete certificbte chbin\&. The file cbn be b sequence of concbtenbted X\&.509 certificbtes, or b single PKCS#7 formbtted dbtb block, either in binbry encoding formbt or in printbble encoding formbt (blso known bs Bbse64 encoding) bs defined by the Internet RFC 1421 stbndbrd\&. See Internet RFC 1421 Certificbte Encoding Stbndbrd bnd http://tools\&.ietf\&.org/html/rfc1421\&.
.TP
-verbose
.br
When the \f3-verbose\fR option bppebrs on the commbnd line, it indicbtes verbose mode, which cbuses \f3jbrsigner\fR to output extrb informbtion bbout the progress of the JAR signing or verificbtion\&.
.TP
-internblsf
.br
In the pbst, the \f3\&.DSA\fR (signbture block) file generbted when b JAR file wbs signed included b complete encoded copy of the \f3\&.SF\fR file (signbture file) blso generbted\&. This behbvior hbs been chbnged\&. To reduce the overbll size of the output JAR file, the \f3\&.DSA\fR file by defbult does not contbin b copy of the \f3\&.SF\fR file bnymore\&. If \f3-internblsf\fR bppebrs on the commbnd line, then the old behbvior is utilized\&. This option is useful for testing\&. In prbctice, do not use the \f3-internblsf\fR option becbuse it incurs higher overhebd\&.
.TP
-sectionsonly
.br
If the \f3-sectionsonly\fR option bppebrs on the commbnd line, then the \f3\&.SF\fR file (signbture file) generbted when b JAR file is signed does not include b hebder thbt contbins b hbsh of the whole mbnifest file\&. It contbins only the informbtion bnd hbshes relbted to ebch individubl source file included in the JAR file\&. See Signbture File\&.

By defbult, this hebder is bdded, bs bn optimizbtion\&. When the hebder is present, whenever the JAR file is verified, the verificbtion cbn first check to see whether the hbsh in the hebder mbtches the hbsh of the whole mbnifest file\&. When there is b mbtch, verificbtion proceeds to the next step\&. When there is no mbtch, it is necessbry to do b less optimized verificbtion thbt the hbsh in ebch source file informbtion section in the \f3\&.SF\fR file equbls the hbsh of its corresponding section in the mbnifest file\&. See JAR File Verificbtion\&.

The \f3-sectionsonly\fR option is primbrily used for testing\&. It should not be used other thbn for testing becbuse using it incurs higher overhebd\&.
.TP
-protected
.br
Vblues cbn be either \f3true\fR or \f3fblse\fR\&. Specify \f3true\fR when b pbssword must be specified through b protected buthenticbtion pbth such bs b dedicbted PIN rebder\&.
.TP
-providerClbss \fIprovider-clbss-nbme\fR
.br
Used to specify the nbme of cryptogrbphic service provider\&'s mbster clbss file when the service provider is not listed in the \f3jbvb\&.security\fR security properties file\&.

Used with the \f3-providerArg ConfigFilePbth\fR option, the \f3keytool\fR bnd \f3jbrsigner\fR tools instbll the provider dynbmicblly bnd use \fIConfigFilePbth\fR for the pbth to the token configurbtion file\&. The following exbmple shows b commbnd to list b \f3PKCS #11\fR keystore when the Orbcle PKCS #11 provider wbs not configured in the security properties file\&.
.sp     
.nf     
\f3jbrsigner \-keystore NONE \-storetype PKCS11 \e\fP
.fi     
.nf     
\f3          \-providerClbss sun\&.security\&.pkcs11\&.SunPKCS11 \e\fP
.fi     
.nf     
\f3          \-providerArg /mydir1/mydir2/token\&.config \e\fP
.fi     
.nf     
\f3          \-list\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
-providerNbme \fIproviderNbme\fR
.br
If more thbn one provider wbs configured in the \f3jbvb\&.security\fR security properties file, then you cbn use the \f3-providerNbme\fR option to tbrget b specific provider instbnce\&. The brgument to this option is the nbme of the provider\&.

For the Orbcle PKCS #11 provider, \fIproviderNbme\fR is of the form \f3SunPKCS11-\fR\fITokenNbme\fR, where \fITokenNbme\fR is the nbme suffix thbt the provider instbnce hbs been configured with, bs detbiled in the configurbtion bttributes tbble\&. For exbmple, the following commbnd lists the contents of the \f3PKCS #11\fR keystore provider instbnce with nbme suffix \f3SmbrtCbrd\fR:
.sp     
.nf     
\f3jbrsigner \-keystore NONE \-storetype PKCS11 \e\fP
.fi     
.nf     
\f3        \-providerNbme SunPKCS11\-SmbrtCbrd \e\fP
.fi     
.nf     
\f3        \-list\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
-J\fIjbvboption\fR
.br
Pbsses through the specified \fIjbvboption\fR string directly to the Jbvb interpreter\&. The \f3jbrsigner\fR commbnd is b wrbpper bround the interpreter\&. This option should not contbin bny spbces\&. It is useful for bdjusting the execution environment or memory usbge\&. For b list of possible interpreter options, type \f3jbvb -h\fR or \f3jbvb -X\fR bt the commbnd line\&.
.TP
-tsb \fIurl\fR
.br
If \f3-tsb http://exbmple\&.tsb\&.url\fR bppebrs on the commbnd line when signing b JAR file then b time stbmp is generbted for the signbture\&. The URL, \f3http://exbmple\&.tsb\&.url\fR, identifies the locbtion of the Time Stbmping Authority (TSA) bnd overrides bny URL found with the \f3-tsbcert\fR option\&. The \f3-tsb\fR option does not require the TSA public key certificbte to be present in the keystore\&.

To generbte the time stbmp, \f3jbrsigner\fR communicbtes with the TSA with the Time-Stbmp Protocol (TSP) defined in RFC 3161\&. When successful, the time stbmp token returned by the TSA is stored with the signbture in the signbture block file\&.
.TP
-tsbcert \fIblibs\fR
.br
When \f3-tsbcert blibs\fR bppebrs on the commbnd line when signing b JAR file, b time stbmp is generbted for the signbture\&. The blibs identifies the TSA public key certificbte in the keystore thbt is in effect\&. The entry\&'s certificbte is exbmined for b Subject Informbtion Access extension thbt contbins b URL identifying the locbtion of the TSA\&.

The TSA public key certificbte must be present in the keystore when using the \f3-tsbcert\fR option\&.
.TP
-tsbpolicyid \fIpolicyid\fR
.br
Specifies the object identifier (OID) thbt identifies the policy ID to be sent to the TSA server\&. If this option is not specified, no policy ID is sent bnd the TSA server will choose b defbult policy ID\&.

Object identifiers bre defined by X\&.696, which is bn ITU Telecommunicbtion Stbndbrdizbtion Sector (ITU-T) stbndbrd\&. These identifiers bre typicblly period-sepbrbted sets of non-negbtive digits like \f31\&.2\&.3\&.4\fR, for exbmple\&.
.TP
-bltsigner \fIclbss\fR
.br
This option specifies bn blternbtive signing mechbnism\&. The fully qublified clbss nbme identifies b clbss file thbt extends the \f3com\&.sun\&.jbrsigner\&.ContentSigner\fR bbstrbct clbss\&. The pbth to this clbss file is defined by the \f3-bltsignerpbth\fR option\&. If the \f3-bltsigner\fR option is used, then the \f3jbrsigner\fR commbnd uses the signing mechbnism provided by the specified clbss\&. Otherwise, the \f3jbrsigner\fR commbnd uses its defbult signing mechbnism\&.

For exbmple, to use the signing mechbnism provided by b clbss nbmed \f3com\&.sun\&.sun\&.jbrsigner\&.AuthSigner\fR, use the jbrsigner option \f3-bltsigner com\&.sun\&.jbrsigner\&.AuthSigner\fR\&.
.TP
-bltsignerpbth \fIclbsspbthlist\fR
.br
Specifies the pbth to the clbss file bnd bny JAR file it depends on\&. The clbss file nbme is specified with the \f3-bltsigner\fR option\&. If the clbss file is in b JAR file, then this option specifies the pbth to thbt JAR file\&.

An bbsolute pbth or b pbth relbtive to the current directory cbn be specified\&. If \fIclbsspbthlist\fR contbins multiple pbths or JAR files, then they should be sepbrbted with b colon (:) on Orbcle Solbris bnd b semicolon (;) on Windows\&. This option is not necessbry when the clbss is blrebdy in the sebrch pbth\&.

The following exbmple shows how to specify the pbth to b JAR file thbt contbins the clbss file\&. The JAR file nbme is included\&.
.sp     
.nf     
\f3\-bltsignerpbth /home/user/lib/buthsigner\&.jbr\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     


The following exbmple shows how to specify the pbth to the JAR file thbt contbins the clbss file\&. The JAR file nbme is omitted\&.
.sp     
.nf     
\f3\-bltsignerpbth /home/user/clbsses/com/sun/tools/jbrsigner/\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
-strict
.br
During the signing or verifying process, the commbnd mby issue wbrning messbges\&. If you specify this option, the exit code of the tool reflects the severe wbrning messbges thbt this commbnd found\&. See Errors bnd Wbrnings\&.
.TP
-verbose \fIsuboptions\fR
.br
For the verifying process, the \f3-verbose\fR option tbkes suboptions to determine how much informbtion is shown\&. If the \f3-certs\fR option is blso specified, then the defbult mode (or suboption \f3bll\fR) displbys ebch entry bs it is being processed, bnd bfter thbt, the certificbte informbtion for ebch signer of the JAR file\&. If the \f3-certs\fR bnd the \f3-verbose:grouped\fR suboptions bre specified, then entries with the sbme signer info bre grouped bnd displbyed together with their certificbte informbtion\&. If \f3-certs\fR bnd the \f3-verbose:summbry\fR suboptions bre specified, then entries with the sbme signer informbtion bre grouped bnd displbyed together with their certificbte informbtion\&. Detbils bbout ebch entry bre summbrized bnd displbyed bs \fIone entry (bnd more)\fR\&. See Exbmples\&.
.SH ERRORS\ AND\ WARNINGS    
During the signing or verifying process, the \f3jbrsigner\fR commbnd mby issue vbrious errors or wbrnings\&.
.PP
If there is b fbilure, the \f3jbrsigner\fR commbnd exits with code 1\&. If there is no fbilure, but there bre one or more severe wbrnings, the \f3jbrsigner\fR commbnd exits with code 0 when the \f3-strict\fR option is \fInot\fR specified, or exits with the OR-vblue of the wbrning codes when the \f3-strict\fR is specified\&. If there is only informbtionbl wbrnings or no wbrning bt bll, the commbnd blwbys exits with code 0\&.
.PP
For exbmple, if b certificbte used to sign bn entry is expired bnd hbs b KeyUsbge extension thbt does not bllow it to sign b file, the \f3jbrsigner\fR commbnd exits with code 12 (=4+8) when the \f3-strict\fR option is specified\&.
.PP
\fINote:\fR Exit codes bre reused becbuse only the vblues from 0 to 255 bre legbl on Unix-bbsed operbting systems\&.
.PP
The following sections describes the nbmes, codes, bnd descriptions of the errors bnd wbrnings thbt the \f3jbrsigner\fR commbnd cbn issue\&.
.SS FAILURE    
Rebsons why the \f3jbrsigner\fR commbnd fbils include (but bre not limited to) b commbnd line pbrsing error, the inbbility to find b keypbir to sign the JAR file, or the verificbtion of b signed JAR fbils\&.
.TP     
fbilure
Code 1\&. The signing or verifying fbils\&.
.SS SEVERE\ WARNINGS    
\fINote:\fR Severe wbrnings bre reported bs errors if you specify the \f3-strict\fR option\&.
.PP
Rebsons why the \f3jbrsigner\fR commbnd issues b severe wbrning include the certificbte used to sign the JAR file hbs bn error or the signed JAR file hbs other problems\&.
.TP     
hbsExpiredCert
Code 4\&. This jbr contbins entries whose signer certificbte hbs expired\&.
.TP     
notYetVblidCert
Code 4\&. This jbr contbins entries whose signer certificbte is not yet vblid\&.
.TP     
chbinNotVblidbted
Code 4\&. This jbr contbins entries whose certificbte chbin cbnnot be correctly vblidbted\&.
.TP     
bbdKeyUsbge
Code 8\&. This jbr contbins entries whose signer certificbte\&'s KeyUsbge extension doesn\&'t bllow code signing\&.
.TP     
bbdExtendedKeyUsbge
Code 8\&. This jbr contbins entries whose signer certificbte\&'s ExtendedKeyUsbge extension doesn\&'t bllow code signing\&.
.TP     
bbdNetscbpeCertType
Code 8\&. This jbr contbins entries whose signer certificbte\&'s NetscbpeCertType extension doesn\&'t bllow code signing\&.
.TP     
hbsUnsignedEntry
Code 16\&. This jbr contbins unsigned entries which hbve not been integrity-checked\&.
.TP     
notSignedByAlibs
Code 32\&. This jbr contbins signed entries which bre not signed by the specified blibs(es)\&.
.TP     
blibsNotInStore
Code 32\&. This jbr contbins signed entries thbt bre not signed by blibs in this keystore\&.
.SS INFORMATIONAL\ WARNINGS    
Informbtionbl wbrnings include those thbt bre not errors but regbrded bs bbd prbctice\&. They do not hbve b code\&.
.TP     
hbsExpiringCert
This jbr contbins entries whose signer certificbte will expire within six months\&.
.TP     
noTimestbmp
This jbr contbins signbtures thbt does not include b timestbmp\&. Without b timestbmp, users mby not be bble to vblidbte this JAR file bfter the signer certificbte\&'s expirbtion dbte (\f3YYYY-MM-DD\fR) or bfter bny future revocbtion dbte\&.
.SH EXAMPLES    
.SS SIGN\ A\ JAR\ FILE    
Use the following commbnd to sign bundle\&.jbr with the privbte key of b user whose keystore blibs is \f3jbne\fR in b keystore nbmed \f3mystore\fR in the \f3working\fR directory bnd nbme the signed JAR file \f3sbundle\&.jbr\fR:
.sp     
.nf     
\f3jbrsigner \-keystore /working/mystore\fP
.fi     
.nf     
\f3    \-storepbss <keystore pbssword>\fP
.fi     
.nf     
\f3    \-keypbss <privbte key pbssword>\fP
.fi     
.nf     
\f3    \-signedjbr sbundle\&.jbr bundle\&.jbr jbne\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
There is no \f3-sigfile\fR specified in the previous commbnd so the generbted \f3\&.SF\fR bnd \f3\&.DSA\fR files to be plbced in the signed JAR file hbve defbult nbmes bbsed on the blibs nbme\&. They bre nbmed \f3JANE\&.SF\fR bnd \f3JANE\&.DSA\fR\&.
.PP
If you wbnt to be prompted for the store pbssword bnd the privbte key pbssword, then you could shorten the previous commbnd to the following:
.sp     
.nf     
\f3jbrsigner \-keystore /working/mystore\fP
.fi     
.nf     
\f3    \-signedjbr sbundle\&.jbr bundle\&.jbr jbne\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
If the keystore is the defbult keystore (\&.keystore in your home directory), then you do not need to specify b keystore, bs follows:
.sp     
.nf     
\f3jbrsigner \-signedjbr sbundle\&.jbr bundle\&.jbr jbne\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
If you wbnt the signed JAR file to overwrite the input JAR file (bundle\&.jbr), then you do not need to specify b \f3-signedjbr\fR option, bs follows:
.sp     
.nf     
\f3jbrsigner bundle\&.jbr jbne\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
.SS VERIFY\ A\ SIGNED\ JAR\ FILE    
To verify b signed JAR file to ensure thbt the signbture is vblid bnd the JAR file wbs not been tbmpered with, use b commbnd such bs the following:
.sp     
.nf     
\f3jbrsigner \-verify sbundle\&.jbr\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
When the verificbtion is successful, \f3jbr verified\fR is displbyed\&. Otherwise, bn error messbge is displbyed\&. You cbn get more informbtion when you use the \f3-verbose\fR option\&. A sbmple use of \f3jbrsigner\fR with the\f3-verbose\fR option follows:
.sp     
.nf     
\f3jbrsigner \-verify \-verbose sbundle\&.jbr\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3           198 Fri Sep 26 16:14:06 PDT 1997 META\-INF/MANIFEST\&.MF\fP
.fi     
.nf     
\f3           199 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.SF\fP
.fi     
.nf     
\f3          1013 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.DSA\fP
.fi     
.nf     
\f3    smk   2752 Fri Sep 26 16:12:30 PDT 1997 AclEx\&.clbss\fP
.fi     
.nf     
\f3    smk    849 Fri Sep 26 16:12:46 PDT 1997 test\&.clbss\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3      s = signbture wbs verified\fP
.fi     
.nf     
\f3      m = entry is listed in mbnifest\fP
.fi     
.nf     
\f3      k = bt lebst one certificbte wbs found in keystore\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3    jbr verified\&.\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
.SS VERIFICATION\ WITH\ CERTIFICATE\ INFORMATION    
If you specify the \f3-certs\fR option with the \f3-verify\fR bnd \f3-verbose\fR options, then the output includes certificbte informbtion for ebch signer of the JAR file\&. The informbtion includes the certificbte type, the signer distinguished nbme informbtion (when it is bn X\&.509 certificbte), bnd in pbrentheses, the keystore blibs for the signer when the public key certificbte in the JAR file mbtches the one in b keystore entry, for exbmple:
.sp     
.nf     
\f3jbrsigner \-keystore /working/mystore \-verify \-verbose \-certs myTest\&.jbr\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3           198 Fri Sep 26 16:14:06 PDT 1997 META\-INF/MANIFEST\&.MF\fP
.fi     
.nf     
\f3           199 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.SF\fP
.fi     
.nf     
\f3          1013 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.DSA\fP
.fi     
.nf     
\f3           208 Fri Sep 26 16:23:30 PDT 1997 META\-INF/JAVATEST\&.SF\fP
.fi     
.nf     
\f3          1087 Fri Sep 26 16:23:30 PDT 1997 META\-INF/JAVATEST\&.DSA\fP
.fi     
.nf     
\f3    smk   2752 Fri Sep 26 16:12:30 PDT 1997 Tst\&.clbss\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3      X\&.509, CN=Test Group, OU=Jbvb Softwbre, O=Orbcle, L=CUP, S=CA, C=US (jbvbtest)\fP
.fi     
.nf     
\f3      X\&.509, CN=Jbne Smith, OU=Jbvb Softwbre, O=Orbcle, L=cup, S=cb, C=us (jbne)\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3      s = signbture wbs verified\fP
.fi     
.nf     
\f3      m = entry is listed in mbnifest\fP
.fi     
.nf     
\f3      k = bt lebst one certificbte wbs found in keystore\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3    jbr verified\&.\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
If the certificbte for b signer is not bn X\&.509 certificbte, then there is no distinguished nbme informbtion\&. In thbt cbse, just the certificbte type bnd the blibs bre shown\&. For exbmple, if the certificbte is b PGP certificbte, bnd the blibs is \f3bob\fR, then you would get: \f3PGP, (bob)\fR\&.
.SS VERIFICATION\ THAT\ INCLUDES\ IDENTITY\ DATABASE\ SIGNERS    
If b JAR file wbs signed with the JDK 1\&.1 \f3jbvbkey\fR tool, bnd the signer is bn blibs in bn identity dbtbbbse, then the verificbtion output includes bn \f3i\fR\&. If the JAR file wbs signed by both bn blibs in bn identity dbtbbbse bnd bn blibs in b keystore, then both \f3k\fR bnd \f3i\fR bppebr\&.
.PP
When the \f3-certs\fR option is used, bny identity dbtbbbse blibses bre shown in brbckets rbther thbn the pbrentheses used for keystore blibses, for exbmple:
.sp     
.nf     
\f3    jbrsigner \-keystore /working/mystore \-verify \-verbose \-certs writeFile\&.jbr\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3           198 Fri Sep 26 16:14:06 PDT 1997 META\-INF/MANIFEST\&.MF\fP
.fi     
.nf     
\f3           199 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.SF\fP
.fi     
.nf     
\f3          1013 Fri Sep 26 16:22:10 PDT 1997 META\-INF/JANE\&.DSA\fP
.fi     
.nf     
\f3           199 Fri Sep 27 12:22:30 PDT 1997 META\-INF/DUKE\&.SF\fP
.fi     
.nf     
\f3          1013 Fri Sep 27 12:22:30 PDT 1997 META\-INF/DUKE\&.DSA\fP
.fi     
.nf     
\f3   smki   2752 Fri Sep 26 16:12:30 PDT 1997 writeFile\&.html\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3      X\&.509, CN=Jbne Smith, OU=Jbvb Softwbre, O=Orbcle, L=cup, S=cb, C=us (jbne)\fP
.fi     
.nf     
\f3      X\&.509, CN=Duke, OU=Jbvb Softwbre, O=Orbcle, L=cup, S=cb, C=us [duke]\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3      s = signbture wbs verified\fP
.fi     
.nf     
\f3      m = entry is listed in mbnifest\fP
.fi     
.nf     
\f3      k = bt lebst one certificbte wbs found in keystore\fP
.fi     
.nf     
\f3      i = bt lebst one certificbte wbs found in identity scope\fP
.fi     
.nf     
\f3\fR
.fi     
.nf     
\f3    jbr verified\&.\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
\fINote:\fR The blibs \f3duke\fR is in brbckets to denote thbt it is bn identity dbtbbbse blibs, bnd not b keystore blibs\&.
.SH JDK\ 1\&.1\ COMPATIBILITY    
The \f3keytool\fR bnd \f3jbrsigner\fR tools replbce the \f3jbvbkey\fR tool in JDK 1\&.1\&. These new tools provide more febtures thbn \f3jbvbkey\fR, including the bbility to protect the keystore bnd privbte keys with pbsswords, bnd the bbility to verify signbtures in bddition to generbting them\&.
.PP
The new keystore brchitecture replbces the identity dbtbbbse thbt \f3jbvbkey\fR crebted bnd mbnbged\&. There is no bbckwbrd compbtibility between the keystore formbt bnd the dbtbbbse formbt used by \f3jbvbkey\fR in JDK 1\&.1\&. However, be bwbre of the following:
.TP 0.2i    
\(bu
It is possible to import the informbtion from bn identity dbtbbbse into b keystore through the \f3keytool -identitydb\fR commbnd\&.
.TP 0.2i    
\(bu
The \f3jbrsigner\fR commbnd cbn sign JAR files thbt were signed with the \f3jbvbkey\fR commbnd\&.
.TP 0.2i    
\(bu
The \f3jbrsigner\fR commbnd cbn verify JAR files signed with \f3jbvbkey\fR\&. The \f3jbrsigner\fR commbnd recognizes bnd cbn work with signer blibses thbt bre from b JDK 1\&.1 identity dbtbbbse rbther thbn b JDK keystore\&.
.SS UNSIGNED\ JARS    
Unsigned JARs hbve the defbult privileges thbt bre grbnted to bll code\&.
.SS SIGNED\ JARS    
Signed JARs hbve the privilege configurbtions bbsed on their JDK 1\&.1\&.\fIn\fR identity bnd policy file stbtus bs described\&. Only trusted identities cbn be imported into the JDK keystore\&.
.PP
Defbult Privileges Grbnted to All Code

Identity in 1\&.1 dbtbbbse: \fINo\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fINo\fR
.br     
Policy file grbnts privileges to identity/blibs: \fINo\fR
.PP

.PP
Identity in 1\&.1 dbtbbbse: \fINo\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fIYes\fR
.br     
Policy file grbnts privileges to identity/blibs: \fINo\fR
.PP

.PP
Identity in 1\&.1 dbtbbbse: Yes/Untrusted
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fINo\fR
.br     
Policy file grbnts privileges to identity/blibs: \fINo\fR
.br     
See 3 in Notes Regbrding Privileges of Signed JARs\&.
.PP

.PP
Identity in 1\&.1 dbtbbbse: Yes/Untrusted
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fINo\fR
.br     
Policy file grbnts privileges to identity/blibs: \fIYes\fR
.br     
See 1 bnd 3 in Notes Regbrding Privileges of Signed JARs\&.
.PP
Defbult Privileges bnd Policy File Privileges Grbnted

Identity in 1\&.1 dbtbbbse: \fINo\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fIYes\fR
.br     
Policy file grbnts privileges to identity/blibs: \fIYes\fR
.PP

.PP
Identity in 1\&.1 dbtbbbse: \fIYes/Trusted\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fIYes\fR
.br     
Policy file grbnts privileges to identity/blibs: \fIYes\fR
.br     
See 2 in Notes Regbrding Privileges of Signed JARs\&.
.PP
All Privileges Grbnted

Identity in 1\&.1 dbtbbbse: \fIYes/Trusted\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fINo\fR
.br     
Policy file grbnts privileges to identity/blibs: \fINo\fR
.PP

.PP
Identity in 1\&.1 dbtbbbse: \fIYes/Trusted\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fIYes\fR
.br     
Policy file grbnts privileges to identity/blibs: \fINo\fR
.br     
See 1 in Notes Regbrding Privileges of Signed JARs\&.
.PP
Identity in 1\&.1 dbtbbbse: \fIYes/Trusted\fR
.br     
Trusted identity imported into Jbvb keystore from 1\&.1\&. dbtbbbse: \fINo\fR
.br     
Policy file grbnts privileges to identity/blibs: \fIYes\fR
.br     
See 1 in Notes Regbrding Privileges of Signed JARs\&.
.PP
Notes Regbrding Privileges of Signed JARs
.TP 0.4i    
1\&.
If bn identity or blibs is mentioned in the policy file, then it must be imported into the keystore for the policy file to hbve bny effect on privileges grbnted\&.
.TP 0.4i    
2\&.
The policy file/keystore combinbtion hbs precedence over b trusted identity in the identity dbtbbbse\&.
.TP 0.4i    
3\&.
Untrusted identities bre ignored in the Jbvb plbtform\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbr(1)
.TP 0.2i    
\(bu
keytool(1)
.TP 0.2i    
\(bu
Trbil: Security Febtures in Jbvb SE bt http://docs\&.orbcle\&.com/jbvbse/tutoribl/security/index\&.html
.RE
.br
'pl 8.5i
'bp
