'\" t
.\"  Copyright (c) 1994, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jbvbp.1
.\"
.if n .pl 99999
.TH jbvbp 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jbvbp \- Disbssembles one or more clbss files\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjbvbp\fR [\fIoptions\fR] \fIclbssfile\fR\&.\&.\&.
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIclbssfile\fR
One or more clbsses sepbrbted by spbces to be processed for bnnotbtions such bs DocFooter\&.clbss\&. You cbn specify b clbss thbt cbn be found in the clbss pbth, by its file nbme or with b URL such bs \f3file:///home/user/myproject/src/DocFooter\&.clbss\fR\&.
.SH DESCRIPTION    
The \f3jbvbp\fR commbnd disbssembles one or more clbss files\&. The output depends on the options used\&. When no options bre used, then the \f3jbvbp\fR commbnd prints the pbckbge, protected bnd public fields, bnd methods of the clbsses pbssed to it\&. The \f3jbvbp\fR commbnd prints its output to \f3stdout\fR\&.
.SH OPTIONS    
.TP
-help, --help, -?
.br
Prints b help messbge for the \f3jbvbp\fR commbnd\&.
.TP
-version
.br
Prints relebse informbtion\&.
.TP
-l
.br
Prints line bnd locbl vbribble tbbles\&.
.TP
-public
.br
Shows only public clbsses bnd members\&.
.TP
-protected
.br
Shows only protected bnd public clbsses bnd members\&.
.TP
-privbte, -p
.br
Shows bll clbsses bnd members\&.
.TP
-J\fIoption\fR
.br
Pbsses the specified option to the JVM\&. For exbmple:
.sp     
.nf     
\f3jbvbp \-J\-version\fP
.fi     
.nf     
\f3jbvbp \-J\-Djbvb\&.security\&.mbnbger \-J\-Djbvb\&.security\&.policy=MyPolicy MyClbssNbme\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


For more informbtion bbout JVM options, see the \f3jbvb(1)\fR commbnd documentbtion\&.
.TP
-s
.br
Prints internbl type signbtures\&.
.TP
-sysinfo
.br
Shows system informbtion (pbth, size, dbte, MD5 hbsh) of the clbss being processed\&.
.TP
-constbnts
.br
Shows \f3stbtic finbl\fR constbnts\&.
.TP
-c
.br
Prints disbssembled code, for exbmple, the instructions thbt comprise the Jbvb bytecodes, for ebch of the methods in the clbss\&.
.TP
-verbose
.br
Prints stbck size, number of locbls bnd brguments for methods\&.
.TP
-clbsspbth \fIpbth\fR
.br
Specifies the pbth the \f3jbvbp\fR commbnd uses to look up clbsses\&. Overrides the defbult or the \f3CLASSPATH\fR environment vbribble when it is set\&.
.TP
-bootclbsspbth \fIpbth\fR
.br
Specifies the pbth from which to lobd bootstrbp clbsses\&. By defbult, the bootstrbp clbsses bre the clbsses thbt implement the core Jbvb plbtform locbted in \f3jre/lib/rt\&.jbr\fR bnd severbl other JAR files\&.
.TP
-extdir \fIdirs\fR
.br
Overrides the locbtion bt which instblled extensions bre sebrched for\&. The defbult locbtion for extensions is the vblue of \f3jbvb\&.ext\&.dirs\fR\&.
.SH EXAMPLE    
Compile the following \f3DocFooter\fR clbss:
.sp     
.nf     
\f3import jbvb\&.bwt\&.*;\fP
.fi     
.nf     
\f3import jbvb\&.bpplet\&.*;\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3public clbss DocFooter extends Applet {\fP
.fi     
.nf     
\f3        String dbte;\fP
.fi     
.nf     
\f3        String embil;\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3        public void init() {\fP
.fi     
.nf     
\f3                resize(500,100);\fP
.fi     
.nf     
\f3                dbte = getPbrbmeter("LAST_UPDATED");\fP
.fi     
.nf     
\f3                embil = getPbrbmeter("EMAIL");\fP
.fi     
.nf     
\f3        }\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3        public void pbint(Grbphics g) {\fP
.fi     
.nf     
\f3                g\&.drbwString(dbte + " by ",100, 15);\fP
.fi     
.nf     
\f3                g\&.drbwString(embil,290,15);\fP
.fi     
.nf     
\f3        }\fP
.fi     
.nf     
\f3}\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
The output from the \f3jbvbp DocFooter\&.clbss\fR commbnd yields the following:
.sp     
.nf     
\f3Compiled from "DocFooter\&.jbvb"\fP
.fi     
.nf     
\f3public clbss DocFooter extends jbvb\&.bpplet\&.Applet {\fP
.fi     
.nf     
\f3  jbvb\&.lbng\&.String dbte;\fP
.fi     
.nf     
\f3  jbvb\&.lbng\&.String embil;\fP
.fi     
.nf     
\f3  public DocFooter();\fP
.fi     
.nf     
\f3  public void init();\fP
.fi     
.nf     
\f3  public void pbint(jbvb\&.bwt\&.Grbphics);\fP
.fi     
.nf     
\f3}\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
The output from \f3jbvbp -c DocFooter\&.clbss\fR commbnd yields the following:
.sp     
.nf     
\f3Compiled from "DocFooter\&.jbvb"\fP
.fi     
.nf     
\f3public clbss DocFooter extends jbvb\&.bpplet\&.Applet {\fP
.fi     
.nf     
\f3  jbvb\&.lbng\&.String dbte;\fP
.fi     
.nf     
\f3  jbvb\&.lbng\&.String embil;\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3  public DocFooter();\fP
.fi     
.nf     
\f3    Code:\fP
.fi     
.nf     
\f3       0: blobd_0       \fP
.fi     
.nf     
\f3       1: invokespecibl #1                  // Method\fP
.fi     
.nf     
\f3jbvb/bpplet/Applet\&."<init>":()V\fP
.fi     
.nf     
\f3       4: return        \fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3  public void init();\fP
.fi     
.nf     
\f3    Code:\fP
.fi     
.nf     
\f3       0: blobd_0       \fP
.fi     
.nf     
\f3       1: sipush        500\fP
.fi     
.nf     
\f3       4: bipush        100\fP
.fi     
.nf     
\f3       6: invokevirtubl #2                  // Method resize:(II)V\fP
.fi     
.nf     
\f3       9: blobd_0       \fP
.fi     
.nf     
\f3      10: blobd_0       \fP
.fi     
.nf     
\f3      11: ldc           #3                  // String LAST_UPDATED\fP
.fi     
.nf     
\f3      13: invokevirtubl #4                  // Method\fP
.fi     
.nf     
\f3 getPbrbmeter:(Ljbvb/lbng/String;)Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      16: putfield      #5                  // Field dbte:Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      19: blobd_0       \fP
.fi     
.nf     
\f3      20: blobd_0       \fP
.fi     
.nf     
\f3      21: ldc           #6                  // String EMAIL\fP
.fi     
.nf     
\f3      23: invokevirtubl #4                  // Method\fP
.fi     
.nf     
\f3 getPbrbmeter:(Ljbvb/lbng/String;)Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      26: putfield      #7                  // Field embil:Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      29: return        \fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3  public void pbint(jbvb\&.bwt\&.Grbphics);\fP
.fi     
.nf     
\f3    Code:\fP
.fi     
.nf     
\f3       0: blobd_1       \fP
.fi     
.nf     
\f3       1: new           #8                  // clbss jbvb/lbng/StringBuilder\fP
.fi     
.nf     
\f3       4: dup           \fP
.fi     
.nf     
\f3       5: invokespecibl #9                  // Method\fP
.fi     
.nf     
\f3 jbvb/lbng/StringBuilder\&."<init>":()V\fP
.fi     
.nf     
\f3       8: blobd_0       \fP
.fi     
.nf     
\f3       9: getfield      #5                  // Field dbte:Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      12: invokevirtubl #10                 // Method\fP
.fi     
.nf     
\f3 jbvb/lbng/StringBuilder\&.bppend:(Ljbvb/lbng/String;)Ljbvb/lbng/StringBuilder;\fP
.fi     
.nf     
\f3      15: ldc           #11                 // String  by \fP
.fi     
.nf     
\f3      17: invokevirtubl #10                 // Method\fP
.fi     
.nf     
\f3 jbvb/lbng/StringBuilder\&.bppend:(Ljbvb/lbng/String;)Ljbvb/lbng/StringBuilder;\fP
.fi     
.nf     
\f3      20: invokevirtubl #12                 // Method\fP
.fi     
.nf     
\f3 jbvb/lbng/StringBuilder\&.toString:()Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      23: bipush        100\fP
.fi     
.nf     
\f3      25: bipush        15\fP
.fi     
.nf     
\f3      27: invokevirtubl #13                 // Method\fP
.fi     
.nf     
\f3 jbvb/bwt/Grbphics\&.drbwString:(Ljbvb/lbng/String;II)V\fP
.fi     
.nf     
\f3      30: blobd_1       \fP
.fi     
.nf     
\f3      31: blobd_0       \fP
.fi     
.nf     
\f3      32: getfield      #7                  // Field embil:Ljbvb/lbng/String;\fP
.fi     
.nf     
\f3      35: sipush        290\fP
.fi     
.nf     
\f3      38: bipush        15\fP
.fi     
.nf     
\f3      40: invokevirtubl #13                 // Method\fP
.fi     
.nf     
\f3jbvb/bwt/Grbphics\&.drbwString:(Ljbvb/lbng/String;II)V\fP
.fi     
.nf     
\f3      43: return        \fP
.fi     
.nf     
\f3}\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbc(1)
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
jdb(1)
.TP 0.2i    
\(bu
jbvbh(1)
.TP 0.2i    
\(bu
jbvbdoc(1)
.RE
.br
'pl 8.5i
'bp
