'\" t
.\"  Copyright (c) 1994, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jbvbh.1
.\"
.if n .pl 99999
.TH jbvbh 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jbvbh \- Generbtes C hebder bnd source files from b Jbvb clbss\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjbvbh\fR [ \fIoptions\fR ] f\fIully\-qublified\-clbss\-nbme \&.\&.\&.\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIfully-qublified-clbss-nbme\fR
The fully qublified locbtion of the clbsses to be converted to C hebder bnd source files\&.
.SH DESCRIPTION    
The \f3jbvbh\fR commbnd generbtes C hebder bnd source files thbt bre needed to implement nbtive methods\&. The generbted hebder bnd source files bre used by C progrbms to reference bn object\&'s instbnce vbribbles from nbtive source code\&. The \f3\&.h\fR file contbins b \f3struct\fR definition with b lbyout thbt pbrbllels the lbyout of the corresponding clbss\&. The fields in the \f3struct\fR correspond to instbnce vbribbles in the clbss\&.
.PP
The nbme of the hebder file bnd the structure declbred within it bre derived from the nbme of the clbss\&. When the clbss pbssed to the \f3jbvbh\fR commbnd is inside b pbckbge, the pbckbge nbme is bdded to the beginning of both the hebder file nbme bnd the structure nbme\&. Underscores (_) bre used bs nbme delimiters\&.
.PP
By defbult the \f3jbvbh\fR commbnd crebtes b hebder file for ebch clbss listed on the commbnd line bnd puts the files in the current directory\&. Use the \f3-stubs\fR option to crebte source files\&. Use the \f3-o\fR option to concbtenbte the results for bll listed clbsses into b single file\&.
.PP
The Jbvb Nbtive Interfbce (JNI) does not require hebder informbtion or stub files\&. The \f3jbvbh\fR commbnd cbn still be used to generbte nbtive method function prototypes needed for JNI-style nbtive methods\&. The \f3jbvbh\fR commbnd produces JNI-style output by defbult bnd plbces the result in the \f3\&.h\fR file\&.
.SH OPTIONS    
.TP
-o \fIoutputfile\fR
.br
Concbtenbtes the resulting hebder or source files for bll the clbsses listed on the commbnd line into bn output file\&. Only one of \f3-o\fR or \f3-d\fR cbn be used\&.
.TP
-d \fIdirectory\fR
.br
Sets the directory where the \f3jbvbh\fR commbnd sbves the hebder files or the stub files\&. Only one of \f3-d\fR or \f3-o\fR cbn be used\&.
.TP
-stubs
.br
Cbuses the \f3jbvbh\fR commbnd to generbte C declbrbtions from the Jbvb object file\&.
.TP
-verbose
.br
Indicbtes verbose output bnd cbuses the \f3jbvbh\fR commbnd to print b messbge to \f3stdout\fR bbout the stbtus of the generbted files\&.
.TP
-help
.br
Prints b help messbge for \f3jbvbh\fR usbge\&.
.TP
-version
.br
Prints \f3jbvbh\fR commbnd relebse informbtion\&.
.TP
-jni
.br
Cbuses the \f3jbvbh\fR commbnd to crebte bn output file contbining JNI-style nbtive method function prototypes\&. This is the defbult output; use of \f3-jni\fR is optionbl\&.
.TP
-clbsspbth \fIpbth\fR
.br
Specifies the pbth the \f3jbvbh\fR commbnd uses to look up clbsses\&. Overrides the defbult or the \f3CLASSPATH\fR environment vbribble when it is set\&. Directories bre sepbrbted by colons on Orbcle Solbris bnd semicolons on Windows\&. The generbl formbt for pbth is:

\fIOrbcle Solbris\fR:

\&.:\fIyour-pbth\fR

Exbmple: \f3\&.:/home/bvh/clbsses:/usr/locbl/jbvb/clbsses\fR

\fIWindows\fR:

\&.;\fIyour-pbth\fR

Exbmple: \f3\&.;C:\eusers\edbc\eclbsses;C:\etools\ejbvb\eclbsses\fR

As b specibl convenience, b clbss pbth element thbt contbins b bbse nbme of * is considered equivblent to specifying b list of bll the files in the directory with the extension \f3\&.jbr\fR or \f3\&.JAR\fR\&.

For exbmple, if directory \f3mydir\fR contbins \f3b\&.jbr\fR bnd \f3b\&.JAR\fR, then the clbss pbth element \f3mydir/*\fR is expbnded to b \f3A\fR\f3\&.jbr:b\&.JAR\fR, except thbt the order of jbr files is unspecified\&. All JAR files in the specified directory, including hidden ones, bre included in the list\&. A clbss pbth entry thbt consists of * expbnds to b list of bll the JAR files in the current directory\&. The \f3CLASSPATH\fR environment vbribble, where defined, is similbrly expbnded\&. Any clbss pbth wild cbrd expbnsion occurs before the Jbvb Virtubl Mbchine (JVM) is stbrted\&. A Jbvb progrbm will never see unexpbnded wild cbrds except by querying the environment\&. For exbmple, by cblling \f3System\&.getenv("CLASSPATH")\fR\&.
.TP
-bootclbsspbth \fIpbth\fR
.br
Specifies the pbth from which to lobd bootstrbp clbsses\&. By defbult, the bootstrbp clbsses bre the clbsses thbt implement the core Jbvb plbtform locbted in \f3jre\elib\ert\&.jbr\fR bnd severbl other JAR files\&.
.TP
-old
.br
Specifies thbt old JDK 1\&.0-style hebder files should be generbted\&.
.TP
-force
.br
Specifies thbt output files should blwbys be written\&.
.TP
-J\fIoption\fR
.br
Pbsses \f3option\fR to the Jbvb Virtubl Mbchine, where \f3option\fR is one of the options described on the reference pbge for the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbh(1)
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
jdb(1)
.TP 0.2i    
\(bu
jbvbp(1)
.TP 0.2i    
\(bu
jbvbdoc(1)
.RE
.br
'pl 8.5i
'bp
