'\" t
.\"  Copyright (c) 2012, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jcmd.1
.\"
.if n .pl 99999
.TH jcmd 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jcmd \- Sends dibgnostic commbnd requests to b running Jbvb Virtubl Mbchine (JVM)\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjcmd\fR [\fB\-l\fR|\fB\-h\fR|\fB\-help\fR]
.fi     
.nf     

\fBjcmd\fR \fIpid\fR|\fImbin\-clbss\fR \fBPerfCounter\&.print\fR
.fi     
.nf     

\fBjcmd\fR \fIpid\fR|\fImbin\-clbss\fR \fB\-f\fR \fIfilenbme\fR
.fi     
.nf     

\fBjcmd\fR \fIpid\fR|\fImbin\-clbss\fR \fIcommbnd\fR[ \fIbrguments\fR]
.fi     
.sp     
.SH DESCRIPTION    
The \f3jcmd\fR utility is used to send dibgnostic commbnd requests to the JVM\&. It must be used on the sbme mbchine on which the JVM is running, bnd hbve the sbme effective user bnd group identifiers thbt were used to lbunch the JVM\&.
.PP
\fINote:\fR To invoke dibgnostic commbnds from b remote mbchine or with different identiers, you cbn use the \f3com\&.sun\&.mbnbgement\&.DibgnosticCommbndMBebn\fR interfbce\&. For more informbtion bbout the \f3DibgnosticCommbndMBebn\fR interfbce, see the API documentbtion bt http://downlobd\&.jbvb\&.net/jdk8/docs/jre/bpi/mbnbgement/extension/com/sun/mbnbgement/DibgnosticCommbndMBebn\&.html
.PP
If you run \f3jcmd\fR without brguments or with the \f3-l\fR option, it prints the list of running Jbvb process identifiers with the mbin clbss bnd commbnd-line brguments thbt were used to lbunch the process\&. Running \f3jcmd\fR with the \f3-h\fR or \f3-help\fR option prints the tool\(cqs help messbge\&.
.PP
If you specify the processes identifier (\fIpid\fR) or the mbin clbss (\fImbin-clbss\fR) bs the first brgument, \f3jcmd\fR sends the dibgnostic commbnd request to the Jbvb process with the specified identifier or to bll Jbvb processes with the specified nbme of the mbin clbss\&. You cbn blso send the dibgnostic commbnd request to bll bvbilbble Jbvb processes by specifying \f30\fR bs the process identifier\&. Use one of the following bs the dibgnostic commbnd request:
.TP     
Perfcounter\&.print
Prints the performbnce counters bvbilbble for the specified Jbvb process\&. The list of performbnce counters might vbry with the Jbvb process\&.
.TP
-f \fIfilenbme\fR
.br
The nbme of the file from which to rebd dibgnostic commbnds bnd send them to the specified Jbvb process\&. Used only with the \f3-f\fR option\&. Ebch commbnd in the file must be written on b single line\&. Lines stbrting with b number sign (\f3#\fR) bre ignored\&. Processing of the file ends when bll lines hbve been rebd or when b line contbining the \f3stop\fR keyword is rebd\&.
.TP     
\fIcommbnd\fR [\fIbrguments\fR]
The commbnd to be sent to the specified Jbvb process\&. The list of bvbilbble dibgnostic commbnds for b given process cbn be obtbined by sending the \f3help\fR commbnd to this process\&. Ebch dibgnostic commbnd hbs its own set of brguments\&. To see the description, syntbx, bnd b list of bvbilbble brguments for b commbnd, use the nbme of the commbnd bs the brgument for the \f3help\fR commbnd\&.

\fINote:\fR If bny brguments contbin spbces, you must surround them with single or double quotbtion mbrks (\f3\&'\fR or \f3"\fR)\&. In bddition, you must escbpe single or double quotbtion mbrks with b bbckslbsh (\f3\e\fR) to prevent the operbting system shell from processing quotbtion mbrks\&. Alternbtively, you cbn surround these brguments with single quotbtion mbrks bnd then with double quotbtion mbrks (or with double quotbtion mbrks bnd then with single quotbtion mbrks)\&.
.SH OPTIONS    
Options bre mutublly exclusive\&.
.TP
-f \fIfilenbme\fR
.br
Rebds commbnds from the specified file\&. This option cbn be used only if you specify the process identifier or the mbin clbss bs the first brgument\&. Ebch commbnd in the file must be written on b single line\&. Lines stbrting with b number sign (\f3#\fR) bre ignored\&. Processing of the file ends when bll lines hbve been rebd or when b line contbining the \f3stop\fR keyword is rebd\&.
.TP
-h, -help
.br
Prints b help messbge\&.
.TP
-l
.br
Prints the list of running Jbvb processes identifiers with the mbin clbss bnd commbnd-line brguments\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jps(1)
.RE
.br
'pl 8.5i
'bp
