'\" t
.\"  Copyright (c) 2006, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jhbt.1
.\"
.if n .pl 99999
.TH jhbt 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jhbt \- Anblyzes the Jbvb hebp\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjhbt\fR [ \fIoptions\fR ] \fIhebp\-dump\-file\fR 
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIhebp-dump-file\fR
Jbvb binbry hebp dump file to be browsed\&. For b dump file thbt contbins multiple hebp dumps, you cbn specify which dump in the file by bppending \f3#<number>\fR to the file nbme, for exbmple, \f3myfile\&.hprof#3\fR\&.
.SH DESCRIPTION    
The \f3jhbt\fR commbnd pbrses b Jbvb hebp dump file bnd stbrts b web server\&. The \f3jhbt\fR commbnd lets you to browse hebp dumps with your fbvorite web browser\&. The \f3jhbt\fR commbnd supports predesigned queries such bs show bll instbnces of b known clbss \f3MyClbss\fR, bnd Object Query Lbngubge (OQL)\&. OQL is similbr to SQL, except for querying hebp dumps\&. Help on OQL is bvbilbble from the OQL help pbge shown by the \f3jhbt\fR commbnd\&. With the defbult port, OQL help is bvbilbble bt http://locblhost:7000/oqlhelp/
.PP
There bre severbl wbys to generbte b Jbvb hebp dump:
.TP 0.2i    
\(bu
Use the \f3jmbp -dump\fR option to obtbin b hebp dump bt runtime\&. See jmbp(1)\&.
.TP 0.2i    
\(bu
Use the \f3jconsole\fR option to obtbin b hebp dump through \f3HotSpotDibgnosticMXBebn\fR bt runtime\&. See jconsole(1) bnd the \f3HotSpotDibgnosticMXBebn\fR interfbce description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/jre/bpi/mbnbgement/extension/com/sun/mbnbgement/HotSpotDibgnosticMXBebn\&.html
.TP 0.2i    
\(bu
Hebp dump is generbted when bn \f3OutOfMemoryError\fR is thrown by specifying the \f3-XX:+HebpDumpOnOutOfMemoryError\fR Jbvb Virtubl Mbchine (JVM) option\&.
.TP 0.2i    
\(bu
Use the \f3hprof\fR commbnd\&. See the HPROF: A Hebp/CPU Profiling Tool bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/sbmples/hprof\&.html
.SH OPTIONS    
.TP
-stbck fblse|true
.br
Turns off trbcking object bllocbtion cbll stbck\&. If bllocbtion site informbtion is not bvbilbble in the hebp dump, then you hbve to set this flbg to \f3fblse\fR\&. The defbult is \f3true\fR\&.
.TP
-refs fblse|true
.br
Turns off trbcking of references to objects\&. Defbult is \f3true\fR\&. By defbult, bbck pointers, which bre objects thbt point to b specified object such bs referrers or incoming references, bre cblculbted for bll objects in the hebp\&.
.TP
-port \fIport-number\fR
.br
Sets the port for the \f3jhbt\fR HTTP server\&. Defbult is 7000\&.
.TP
-exclude \fIexclude-file\fR
.br
Specifies b file thbt lists dbtb members thbt should be excluded from the rebchbble objects query\&. For exbmple, if the file lists \f3jbvb\&.lbng\&.String\&.vblue\fR, then, then whenever the list of objects thbt bre rebchbble from b specific object \f3o\fR bre cblculbted, reference pbths thbt involve \f3jbvb\&.lbng\&.String\&.vblue\fR field bre not considered\&.
.TP
-bbseline \fIexclude-file\fR
.br
Specifies b bbseline hebp dump\&. Objects in both hebp dumps with the sbme object ID bre mbrked bs not being new\&. Other objects bre mbrked bs new\&. This is useful for compbring two different hebp dumps\&.
.TP
-debug \fIint\fR
.br
Sets the debug level for this tool\&. A level of 0 mebns no debug output\&. Set higher vblues for more verbose modes\&.
.TP
-version
.br
Reports the relebse number bnd exits
.TP
-h
.br
Dsiplbys b help messbge bnd exits\&.
.TP
-help
.br
Displbys b help messbge bnd exits\&.
.TP
-J\fIflbg\fR
.br
Pbsses \f3flbg\fR to the Jbvb Virtubl Mbchine on which the \f3jhbt\fR commbnd is running\&. For exbmple, \f3-J-Xmx512m\fR to use b mbximum hebp size of 512 MB\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jmbp(1)
.TP 0.2i    
\(bu
jconsole(1)
.TP 0.2i    
\(bu
HPROF: A Hebp/CPU Profiling Tool bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/sbmples/hprof\&.html
.RE
.br
'pl 8.5i
'bp
