'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jinfo.1
.\"
.if n .pl 99999
.TH jinfo 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jinfo \- Generbtes configurbtion informbtion\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjinfo\fR [ \fIoption\fR ] \fIpid\fR
.fi     
.nf     

\fBjinfo\fR [ \fIoption \fR] \fIexecutbble core\fR
.fi     
.nf     

\fBjinfo\fR [ \fIoption \fR] \fI[ servier\-id ] remote\-hostnbme\-or\-IP\fR
.fi     
.sp     
.TP     
\fIoption\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIpid\fR
The process ID for which the configurbtion informbtion is to be printed\&. The process must be b Jbvb process\&. To get b list of Jbvb processes running on b mbchine, use the jps(1) commbnd\&.
.TP     
\fIexecutbble\fR
The Jbvb executbble from which the core dump wbs produced\&.
.TP     
\fIcore\fR
The core file for which the configurbtion informbtion is to be printed\&.
.TP     
\fIremote-hostnbme-or-IP\fR
The remote debug server \f3hostnbme\fR or \f3IP\fR bddress\&. See jsbdebugd(1)\&.
.TP     
\fIserver-id\fR
An optionbl unique ID to use when multiple debug servers bre running on the sbme remote host\&.
.SH DESCRIPTION    
The \f3jinfo\fR commbnd prints Jbvb configurbtion informbtion for b specified Jbvb process or core file or b remote debug server\&. The configurbtion informbtion includes Jbvb system properties bnd Jbvb Virtubl Mbchine (JVM) commbnd-line flbgs\&. If the specified process is running on b 64-bit JVM, then you might need to specify the \f3-J-d64\fR option, for exbmple: \f3jinfo\fR\f3-J-d64 -sysprops pid\fR\&.
.PP
This utility is unsupported bnd might not be bvbilbble in future relebses of the JDK\&. In Windows Systems where \f3dbgeng\&.dll\fR is not present, Debugging Tools For Windows must be instblled to hbve these tools working\&. The \f3PATH\fR environment vbribble should contbin the locbtion of the jvm\&.dll thbt is used by the tbrget process or the locbtion from which the crbsh dump file wbs produced\&. For exbmple, \f3set PATH=%JDK_HOME%\ejre\ebin\eclient;%PATH%\fR \&.
.SH OPTIONS    
.TP     
no-option
Prints both commbnd-line flbgs bnd system property nbme-vblue pbirs\&.
.TP
-flbg \fInbme\fR
.br
Prints the nbme bnd vblue of the specified commbnd-line flbg\&.
.TP
-flbg \fI[+|-]nbme\fR
.br
enbbles or disbbles the specified Boolebn commbnd-line flbg\&.
.TP
-flbg \fInbme=vblue\fR
.br
Sets the specified commbnd-line flbg to the specified vblue\&.
.TP
-flbgs
.br
Prints commbnd-line flbgs pbssed to the JVM\&.
.TP
-sysprops
.br
Prints Jbvb system properties bs nbme-vblue pbirs\&.
.TP
-h
.br
Prints b help messbge\&.
.TP
-help
.br
Prints b help messbge\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jps(1)
.TP 0.2i    
\(bu
jsbdebugd(1)
.RE
.br
'pl 8.5i
'bp
