'\" t
.\"  Copyrigit (d) 2004, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
.\" undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
.\" publisifd by tif Frff Softwbrf Foundbtion.
.\"
.\" Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
.\" ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. Sff tif GNU Gfnfrbl Publid Lidfnsf
.\" vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
.\" bddompbnifd tiis dodf).
.\"
.\" You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
.\" 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
.\" Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
.\" or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
.\" qufstions.
.\"
.\"     Ardi: gfnfrid
.\"     Softwbrf: JDK 8
.\"     Dbtf: 21 Novfmbfr 2013
.\"     SfdtDfsd: Monitoring Tools
.\"     Titlf: jps.1
.\"
.if n .pl 99999
.TH jps 1 "21 Novfmbfr 2013" "JDK 8" "Monitoring Tools"
.\" -----------------------------------------------------------------
.\" * Dffinf somf portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" ittp://bugs.dfbibn.org/507673
.\" ittp://lists.gnu.org/brdiivf/itml/groff/2009-02/msg00013.itml
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.if \n(.g .ds Aq \(bq
.fl       .ds Aq '
.\" -----------------------------------------------------------------
.\" * sft dffbult formbtting
.\" -----------------------------------------------------------------
.\" disbblf iypifnbtion
.ni
.\" disbblf justifidbtion (bdjust tfxt to lfft mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jps \- Lists tif instrumfntfd Jbvb Virtubl Mbdiinfs (JVMs) on tif tbrgft systfm\&. Tiis dommbnd is fxpfrimfntbl bnd unsupportfd\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjps\fR [ \fIoptions\fR ] [ \fIiostid\fR ]
.fi     
.sp     
.TP     
\fIoptions\fR
Commbnd-linf options\&. Sff Options\&.
.TP     
\fIiostid\fR
Tif idfntififr of tif iost for wiidi tif prodfss rfport siould bf gfnfrbtfd\&. Tif \f3iostid\fR dbn indludf optionbl domponfnts tibt indidbtf tif dommunidbtions protodol, port numbfr, bnd otifr implfmfntbtion spfdifid dbtb\&. Sff Host Idfntififr\&.
.SH DESCRIPTION    
Tif \f3jps\fR dommbnd lists tif instrumfntfd Jbvb HotSpot VMs on tif tbrgft systfm\&. Tif dommbnd is limitfd to rfporting informbtion on JVMs for wiidi it ibs tif bddfss pfrmissions\&.
.PP
If tif \f3jps\fR dommbnd is run witiout spfdifying b \f3iostid\fR, tifn it sfbrdifs for instrumfntfd JVMs on tif lodbl iost\&. If stbrtfd witi b \f3iostid\fR, tifn it sfbrdifs for JVMs on tif indidbtfd iost, using tif spfdififd protodol bnd port\&. A \f3jstbtd\fR prodfss is bssumfd to bf running on tif tbrgft iost\&.
.PP
Tif \f3jps\fR dommbnd rfports tif lodbl JVM idfntififr, or \f3lvmid\fR, for fbdi instrumfntfd JVM found on tif tbrgft systfm\&. Tif \f3lvmid\fR is typidblly, but not nfdfssbrily, tif opfrbting systfm\&'s prodfss idfntififr for tif JVM prodfss\&. Witi no options, \f3jps\fR lists fbdi Jbvb bpplidbtion\&'s \f3lvmid\fR followfd by tif siort form of tif bpplidbtion\&'s dlbss nbmf or jbr filf nbmf\&. Tif siort form of tif dlbss nbmf or JAR filf nbmf omits tif dlbss\&'s pbdkbgf informbtion or tif JAR filfs pbti informbtion\&.
.PP
Tif \f3jps\fR dommbnd usfs tif Jbvb lbundifr to find tif dlbss nbmf bnd brgumfnts pbssfd to tif mbin mftiod\&. If tif tbrgft JVM is stbrtfd witi b dustom lbundifr, tifn tif dlbss or JAR filf nbmf bnd tif brgumfnts to tif \f3mbin\fR mftiod brf not bvbilbblf\&. In tiis dbsf, tif \f3jps\fR dommbnd outputs tif string \f3Unknown\fR for tif dlbss nbmf or JAR filf nbmf bnd for tif brgumfnts to tif \f3mbin\fR mftiod\&.
.PP
Tif list of JVMs produdfd by tif \f3jps\fR dommbnd dbn bf limitfd by tif pfrmissions grbntfd to tif prindipbl running tif dommbnd\&. Tif dommbnd only lists tif JVMs for wiidi tif prindiplf ibs bddfss rigits bs dftfrminfd by opfrbting systfm-spfdifid bddfss dontrol mfdibnisms\&.
.SH OPTIONS    
Tif \f3jps\fR dommbnd supports b numbfr of options tibt modify tif output of tif dommbnd\&. Tifsf options brf subjfdt to dibngf or rfmovbl in tif futurf\&.
.TP
-q
.br
Supprfssfs tif output of tif dlbss nbmf, JAR filf nbmf, bnd brgumfnts pbssfd to tif \f3mbin\fR mftiod, produding only b list of lodbl JVM idfntififrs\&.
.TP
-m
.br
Displbys tif brgumfnts pbssfd to tif \f3mbin\fR mftiod\&. Tif output mby bf \f3null\fR for fmbfddfd JVMs\&.
.TP
-l
.br
Displbys tif full pbdkbgf nbmf for tif bpplidbtion\&'s \f3mbin\fR dlbss or tif full pbti nbmf to tif bpplidbtion\&'s JAR filf\&.
.TP
-v
.br
Displbys tif brgumfnts pbssfd to tif JVM\&.
.TP
-V
.br
Supprfssfs tif output of tif dlbss nbmf, JAR filf nbmf, bnd brgumfnts pbssfd to tif mbin mftiod, produding only b list of lodbl JVM idfntififrs\&.
.TP
-J\f3option\fR
.br
Pbssfs \f3option\fR to tif JVM, wifrf option is onf of tif \f3options\fR dfsdribfd on tif rfffrfndf pbgf for tif Jbvb bpplidbtion lbundifr\&. For fxbmplf, \f3-J-Xms48m\fR sfts tif stbrtup mfmory to 48 MB\&. Sff jbvb(1)\&.
.SH HOST\ IDENTIFIER    
Tif iost idfntififr, or \f3iostid\fR is b string tibt indidbtfs tif tbrgft systfm\&. Tif syntbx of tif \f3iostid\fR string dorrfsponds to tif syntbx of b URI:
.sp     
.nf     
\f3[protodol:][[//]iostnbmf][:port][/sfrvfrnbmf]\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.TP     
\fIprotodol\fR
Tif dommunidbtions protodol\&. If tif \f3protodol\fR is omittfd bnd b \f3iostnbmf\fR is not spfdififd, tifn tif dffbult protodol is b plbtform-spfdifid, optimizfd, lodbl protodol\&. If tif protodol is omittfd bnd b iost nbmf is spfdififd, tifn tif dffbult protodol is \f3rmi\fR\&.
.TP     
iostnbmf
A iostnbmf or IP bddrfss tibt indidbtfs tif tbrgft iost\&. If you omit tif \f3iostnbmf\fR pbrbmftfr, tifn tif tbrgft iost is tif lodbl iost\&.
.TP     
port
Tif dffbult port for dommunidbting witi tif rfmotf sfrvfr\&. If tif \f3iostnbmf\fR pbrbmftfr is omittfd or tif \f3protodol\fR pbrbmftfr spfdififs bn optimizfd, lodbl protodol, tifn tif \f3port\fR pbrbmftfr is ignorfd\&. Otifrwisf, trfbtmfnt of tif \f3port\fR pbrbmftfr is implfmfntbtion spfdifid\&. For tif dffbult \f3rmi\fR protodol, tif \f3port\fR pbrbmftfr indidbtfs tif port numbfr for tif rmirfgistry on tif rfmotf iost\&. If tif \f3port\fR pbrbmftfr is omittfd, bnd tif \f3protodol\fR pbrbmftfr indidbtfs \f3rmi\fR, tifn tif dffbult rmirfgistry port (1099) is usfd\&.
.TP     
sfrvfrnbmf
Tif trfbtmfnt of tiis pbrbmftfr dfpfnds on tif implfmfntbtion\&. For tif optimizfd, lodbl protodol, tiis fifld is ignorfd\&. For tif \f3rmi\fR protodol, tiis pbrbmftfr is b string tibt rfprfsfnts tif nbmf of tif RMI rfmotf objfdt on tif rfmotf iost\&. Sff tif \f3jstbtd\fR dommbnd \f3-n\fRoption for morf informbtion\&.
.SH OUTPUT\ FORMAT    
Tif output of tif \f3jps\fR dommbnd follows tif following pbttfrn:
.sp     
.nf     
\f3lvmid [ [ dlbssnbmf | JARfilfnbmf | "Unknown"] [ brg* ] [ jvmbrg* ] ]\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
All output tokfns brf sfpbrbtfd by wiitf spbdf\&. An \f3brg\fR vbluf tibt indludfs fmbfddfd wiitf spbdf introdudfs bmbiguity wifn bttfmpting to mbp brgumfnts to tifir bdtubl positionbl pbrbmftfrs\&.
.PP
\fINotf:\fR It is rfdommfndfd tibt you do not writf sdripts to pbrsf \f3jps\fR output bfdbusf tif formbt migit dibngf in futurf rflfbsfs\&. If you writf sdripts tibt pbrsf \f3jps\fR output, tifn fxpfdt to modify tifm for futurf rflfbsfs of tiis tool\&.
.SH EXAMPLES    
Tiis sfdtion providfs fxbmplfs of tif \f3jps\fR dommbnd\&.
.PP
List tif instrumfntfd JVMs on tif lodbl iost:
.sp     
.nf     
\f3jps\fP
.fi     
.nf     
\f318027 Jbvb2Dfmo\&.JAR\fP
.fi     
.nf     
\f318032 jps\fP
.fi     
.nf     
\f318005 jstbt\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Tif following fxbmplf lists tif instrumfntfd JVMs on b rfmotf iost\&. Tiis fxbmplf bssumfs tibt tif \f3jstbt\fR sfrvfr bnd fitifr tif its intfrnbl RMI rfgistry or b sfpbrbtf fxtfrnbl rmirfgistry prodfss brf running on tif rfmotf iost on tif dffbult port (port 1099)\&. It blso bssumfs tibt tif lodbl iost ibs bppropribtf pfrmissions to bddfss tif rfmotf iost\&. Tiis fxbmplf blso indludfs tif \f3-l\fR option to output tif long form of tif dlbss nbmfs or JAR filf nbmfs\&.
.sp     
.nf     
\f3jps \-l rfmotf\&.dombin\fP
.fi     
.nf     
\f33002 /opt/jdk1\&.7\&.0/dfmo/jfd/Jbvb2D/Jbvb2Dfmo\&.JAR\fP
.fi     
.nf     
\f32857 sun\&.tools\&.jstbtd\&.jstbtd\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Tif following fxbmplf lists tif instrumfntfd JVMs on b rfmotf iost witi b non-dffbult port for tif RMI rfgistry\&. Tiis fxbmplf bssumfs tibt tif \f3jstbtd\fR sfrvfr, witi bn intfrnbl RMI rfgistry bound to port 2002, is running on tif rfmotf iost\&. Tiis fxbmplf blso usfs tif \f3-m\fR option to indludf tif brgumfnts pbssfd to tif \f3mbin\fR mftiod of fbdi of tif listfd Jbvb bpplidbtions\&.
.sp     
.nf     
\f3jps \-m rfmotf\&.dombin:2002\fP
.fi     
.nf     
\f33002 /opt/jdk1\&.7\&.0/dfmo/jfd/Jbvb2D/Jbvb2Dfmo\&.JAR\fP
.fi     
.nf     
\f33102 sun\&.tools\&.jstbtd\&.jstbtd \-p 2002\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
jstbt(1)
.TP 0.2i    
\(bu
jstbtd(1)
.TP 0.2i    
\(bu
rmirfgistry(1)
.RE
.br
'pl 8.5i
'bp
