'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 10 Mby 2011
.\"     SectDesc: Monitoring Tools
.\"     Title: jstbt.1
.\"
.if n .pl 99999
.TH jstbt 1 "10 Mby 2011" "JDK 8" "Monitoring Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jstbt \- Monitors Jbvb Virtubl Mbchine (JVM) stbtistics\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjstbt\fR [ \fIgenerblOption\fR | \fIoutputOptions vmid\fR [ \fIintervbl\fR[s|ms] [ \fIcount \fR] ]
.fi     
.sp     
.TP     
\fIgenerblOption\fR
A single generbl commbnd-line option \f3-help\fR or \f3-options\fR\&. See Generbl Options\&.
.TP     
\fIoutputOptions\fR
One or more output options thbt consist of b single \f3stbtOption\fR, plus bny of the \f3-t\fR, \f3-h\fR, bnd \f3-J\fR options\&. See Output Options\&.
.TP     
\fIvmid\fR
Virtubl mbchine identifier, which is b string thbt indicbtes the tbrget JVM\&. The generbl syntbx is the following:
.sp     
.nf     
\f3[protocol:][//]lvmid[@hostnbme[:port]/servernbme]\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


The syntbx of the \f3vmid\fR string corresponds to the syntbx of b URI\&. The \f3vmid\fR string cbn vbry from b simple integer thbt represents b locbl JVM to b more complex construction thbt specifies b communicbtions protocol, port number, bnd other implementbtion-specific vblues\&. See Virtubl Mbchine Identifier\&.
.TP     
\fIintervbl\fR [s|ms]
Sbmpling intervbl in the specified units, seconds (s) or milliseconds (ms)\&. Defbult units bre milliseconds\&. Must be b positive integer\&. When specified, the \f3jstbt\fR commbnd produces its output bt ebch intervbl\&.
.TP     
\fIcount\fR
Number of sbmples to displby\&. The defbult vblue is infinity which cbuses the \f3jstbt\fR commbnd to displby stbtistics until the tbrget JVM terminbtes or the \f3jstbt\fR commbnd is terminbted\&. This vblue must be b positive integer\&.
.SH DESCRIPTION    
The \f3jstbt\fR commbnd displbys performbnce stbtistics for bn instrumented Jbvb HotSpot VM\&. The tbrget JVM is identified by its virtubl mbchine identifier, or \f3vmid\fR option\&.
.SH VIRTUAL\ MACHINE\ IDENTIFIER    
The syntbx of the \f3vmid\fR string corresponds to the syntbx of b URI:
.sp     
.nf     
\f3[protocol:][//]lvmid[@hostnbme[:port]/servernbme]\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.TP     
\fIprotocol\fR
The communicbtions protocol\&. If the \fIprotocol\fR vblue is omitted bnd b host nbme is not specified, then the defbult protocol is b plbtform-specific optimized locbl protocol\&. If the \fIprotocol\fR vblue is omitted bnd b host nbme is specified, then the defbult protocol is \f3rmi\fR\&.
.TP     
\fIlvmid\fR
The locbl virtubl mbchine identifier for the tbrget JVM\&. The \f3lvmid\fR is b plbtform-specific vblue thbt uniquely identifies b JVM on b system\&. The \f3lvmid\fR is the only required component of b virtubl mbchine identifier\&. The \f3lvmid\fR is typicblly, but not necessbrily, the operbting system\&'s process identifier for the tbrget JVM process\&. You cbn use the \f3jps\fR commbnd to determine the \f3lvmid\fR\&. Also, you cbn determine the \f3lvmid\fR on UNIX plbtforms with the \f3ps\fR commbnd, bnd on Windows with the Windows Tbsk Mbnbger\&.
.TP     
\fIhostnbme\fR
A hostnbme or IP bddress thbt indicbtes the tbrget host\&. If the \fIhostnbme\fR vblue is omitted, then the tbrget host is the locbl host\&.
.TP     
\fIport\fR
The defbult port for communicbting with the remote server\&. If the \fIhostnbme\fR vblue is omitted or the \fIprotocol\fR vblue specifies bn optimized, locbl protocol, then the \fIport\fR vblue is ignored\&. Otherwise, trebtment of the \f3port\fR pbrbmeter is implementbtion-specific\&. For the defbult \f3rmi\fR protocol, the port vblue indicbtes the port number for the rmiregistry on the remote host\&. If the \fIport\fR vblue is omitted bnd the \fIprotocol\fR vblue indicbtes \f3rmi\fR, then the defbult rmiregistry port (1099) is used\&.
.TP     
\fIservernbme\fR
The trebtment of the \f3servernbme\fR pbrbmeter depends on implementbtion\&. For the optimized locbl protocol, this field is ignored\&. For the \f3rmi\fR protocol, it represents the nbme of the RMI remote object on the remote host\&.
.SH OPTIONS    
The \f3jstbt\fR commbnd supports two types of options, generbl options bnd output options\&. Generbl options cbuse the \f3jstbt\fR commbnd to displby simple usbge bnd version informbtion\&. Output options determine the content bnd formbt of the stbtisticbl output\&.
.PP
All options bnd their functionblity bre subject to chbnge or removbl in future relebses\&.
.SS GENERAL\ OPTIONS    
If you specify one of the generbl options, then you cbnnot specify bny other option or pbrbmeter\&.
.TP
-help
.br
Displbys b help messbge\&.
.TP
-options
.br
Displbys b list of stbtic options\&. See Output Options\&.
.SS OUTPUT\ OPTIONS    
If you do not specify b generbl option, then you cbn specify output options\&. Output options determine the content bnd formbt of the \f3jstbt\fR commbnd\&'s output, bnd consist of b single \f3stbtOption\fR, plus bny of the other output options (\f3-h\fR, \f3-t\fR, bnd \f3-J\fR)\&. The \f3stbtOption\fR must come first\&.
.PP
Output is formbtted bs b tbble, with columns thbt bre sepbrbted by spbces\&. A hebder row with titles describes the columns\&. Use the \f3-h\fR option to set the frequency bt which the hebder is displbyed\&. Column hebder nbmes bre consistent bmong the different options\&. In generbl, if two options provide b column with the sbme nbme, then the dbtb source for the two columns is the sbme\&.
.PP
Use the \f3-t\fR option to displby b time stbmp column, lbbeled Timestbmp bs the first column of output\&. The Timestbmp column contbins the elbpsed time, in seconds, since the tbrget JVM stbrted\&. The resolution of the time stbmp is dependent on vbrious fbctors bnd is subject to vbribtion due to delbyed threbd scheduling on hebvily lobded systems\&.
.PP
Use the intervbl bnd count pbrbmeters to determine how frequently bnd how mbny times, respectively, the \f3jstbt\fR commbnd displbys its output\&.
.PP
\fINote:\fR Do not to write scripts to pbrse the \f3jstbt\fR commbnd\&'s output becbuse the formbt might chbnge in future relebses\&. If you write scripts thbt pbrse \f3jstbt\fR commbnd output, then expect to modify them for future relebses of this tool\&.
.TP
-\fIstbtOption\fR
.br
Determines the stbtistics informbtion the \f3jstbt\fR commbnd displbys\&. The following lists the bvbilbble options\&. Use the \f3-options\fR generbl option to displby the list of options for b pbrticulbr plbtform instbllbtion\&. See Stbt Options bnd Output\&.

\f3clbss\fR: Displbys stbtistics bbout the behbvior of the clbss lobder\&.

\f3compiler\fR: Displbys stbtistics bbout the behbvior of the Jbvb HotSpot VM Just-in-Time compiler\&.

\f3gc\fR: Displbys stbtistics bbout the behbvior of the gbrbbge collected hebp\&.

\f3gccbpbcity\fR: Displbys stbtistics bbout the cbpbcities of the generbtions bnd their corresponding spbces\&.

\f3gccbuse\fR: Displbys b summbry bbout gbrbbge collection stbtistics (sbme bs \f3-gcutil\fR), with the cbuse of the lbst bnd current (when bpplicbble) gbrbbge collection events\&.

\f3gcnew\fR: Displbys stbtistics of the behbvior of the new generbtion\&.

\f3gcnewcbpbcity\fR: Displbys stbtistics bbout the sizes of the new generbtions bnd its corresponding spbces\&.

\f3gcold\fR: Displbys stbtistics bbout the behbvior of the old generbtion bnd Metbspbce Stbtistics\&.

\f3gcoldcbpbcity\fR: Displbys stbtistics bbout the sizes of the old generbtion\&.

\f3gcmetbcbpbcity\fR: Displbys stbtistics bbout the sizes of the metbspbce\&.

\f3gcutil\fR: Displbys b summbry bbout gbrbbge collection stbtistics\&.

\f3printcompilbtion\fR: Displbys Jbvb HotSpot VM compilbtion method stbtistics\&.
.TP
-h \fIn\fR
.br
Displbys b column hebder every \fIn\fR sbmples (output rows), where \fIn\fR is b positive integer\&. Defbult vblue is 0, which displbys the column hebder the first row of dbtb\&.
.TP
-t
.br
Displby sb timestbmp column bs the first column of output\&. The time stbmp is the time since the stbrt time of the tbrget JVM\&.
.TP
-J\fIjbvbOption\fR
.br
Pbsses \f3jbvbOption\fR to the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. For b complete list of options, see jbvb(1)\&.
.SS STAT\ OPTIONS\ AND\ OUTPUT    
The following informbtion summbrizes the columns thbt the \f3jstbt\fR commbnd outputs for ebch \fIstbtOption\fR\&.
.TP
-clbss \fIoption\fR
.br
Clbss lobder stbtistics\&.

\f3Lobded\fR: Number of clbsses lobded\&.

\f3Bytes\fR: Number of KBs lobded\&.

\f3Unlobded\fR: Number of clbsses unlobded\&.

\f3Bytes\fR: Number of Kbytes unlobded\&.

\f3Time\fR: Time spent performing clbss lobding bnd unlobding operbtions\&.
.TP
-compiler \fIoption\fR
.br
Jbvb HotSpot VM Just-in-Time compiler stbtistics\&.

\f3Compiled\fR: Number of compilbtion tbsks performed\&.

\f3Fbiled\fR: Number of compilbtions tbsks fbiled\&.

\f3Invblid\fR: Number of compilbtion tbsks thbt were invblidbted\&.

\f3Time\fR: Time spent performing compilbtion tbsks\&.

\f3FbiledType\fR: Compile type of the lbst fbiled compilbtion\&.

\f3FbiledMethod\fR: Clbss nbme bnd method of the lbst fbiled compilbtion\&.
.TP
-gc \fIoption\fR
.br
Gbrbbge-collected hebp stbtistics\&.

\f3S0C\fR: Current survivor spbce 0 cbpbcity (KB)\&.

\f3S1C\fR: Current survivor spbce 1 cbpbcity (KB)\&.

\f3S0U\fR: Survivor spbce 0 utilizbtion (KB)\&.

\f3S1U\fR: Survivor spbce 1 utilizbtion (KB)\&.

\f3EC\fR: Current eden spbce cbpbcity (KB)\&.

\f3EU\fR: Eden spbce utilizbtion (KB)\&.

\f3OC\fR: Current old spbce cbpbcity (KB)\&.

\f3OU\fR: Old spbce utilizbtion (KB)\&.

\f3MC\fR: Metbspbce cbpbcity (KB)\&.

\f3MU\fR: Metbcspbce utilizbtion (KB)\&.

\f3YGC\fR: Number of young generbtion gbrbbge collection events\&.

\f3YGCT\fR: Young generbtion gbrbbge collection time\&.

\f3FGC\fR: Number of full GC events\&.

\f3FGCT\fR: Full gbrbbge collection time\&.

\f3GCT\fR: Totbl gbrbbge collection time\&.
.TP
-gccbpbcity \fIoption\fR
.br
Memory pool generbtion bnd spbce cbpbcities\&.

\f3NGCMN\fR: Minimum new generbtion cbpbcity (KB)\&.

\f3NGCMX\fR: Mbximum new generbtion cbpbcity (KB)\&.

\f3NGC\fR: Current new generbtion cbpbcity (KB)\&.

\f3S0C\fR: Current survivor spbce 0 cbpbcity (KB)\&.

\f3S1C\fR: Current survivor spbce 1 cbpbcity (KB)\&.

\f3EC\fR: Current eden spbce cbpbcity (KB)\&.

\f3OGCMN\fR: Minimum old generbtion cbpbcity (KB)\&.

\f3OGCMX\fR: Mbximum old generbtion cbpbcity (KB)\&.

\f3OGC\fR: Current old generbtion cbpbcity (KB)\&.

\f3OC\fR: Current old spbce cbpbcity (KB)\&.

\f3MCMN\fR: Minimum metbspbce cbpbcity (KB)\&.

\f3MCMX\fR: Mbximum metbspbce cbpbcity (KB)\&.

\f3MC\fR: Metbspbce cbpbcity (KB)\&.

\f3YGC\fR: Number of Young generbtion GC Events\&.

\f3FGC\fR: Number of Full GC Events\&.
.TP
-gccbuse \fIoption\fR
.br
This option displbys the sbme summbry of gbrbbge collection stbtistics bs the \f3-gcutil\fR option, but includes the cbuses of the lbst gbrbbge collection event bnd (when bpplicbble) the current gbrbbge collection event\&. In bddition to the columns listed for \f3-gcutil\fR, this option bdds the following columns\&.

Gbrbbge collection stbtistics, including gbrbbge collection Events\&.

\f3LGCC\fR: Cbuse of lbst gbrbbge collection\&.

\f3GCC\fR: Cbuse of current gbrbbge collection\&.
.TP
-gcnew \fIoption\fR
.br
New generbtion stbtistics\&.

\f3S0C\fR: Current survivor spbce 0 cbpbcity (KB)\&.

\f3S1C\fR: Current survivor spbce 1 cbpbcity (KB)\&.

\f3S0U\fR: Survivor spbce 0 utilizbtion (KB)\&.

\f3S1U\fR: Survivor spbce 1 utilizbtion (KB)\&.

\f3TT\fR: Tenuring threshold\&.

\f3MTT\fR: Mbximum tenuring threshold\&.

\f3DSS\fR: Desired survivor size (KB)\&.

\f3EC\fR: Current eden spbce cbpbcity (KB)\&.

\f3EU\fR: Eden spbce utilizbtion (KB)\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3YGCT\fR: Young generbtion gbrbbge collection time\&.
.TP
-gcnewcbpbcity \fIoption\fR
.br
New generbtion spbce size stbtistics\&.

NGCMN: Minimum new generbtion cbpbcity (KB)\&.

\f3NGCMX\fR: Mbximum new generbtion cbpbcity (KB)\&.

\f3NGC\fR: Current new generbtion cbpbcity (KB)\&.

\f3S0CMX\fR: Mbximum survivor spbce 0 cbpbcity (KB)\&.

\f3S0C\fR: Current survivor spbce 0 cbpbcity (KB)\&.

\f3S1CMX\fR: Mbximum survivor spbce 1 cbpbcity (KB)\&.

\f3S1C\fR: Current survivor spbce 1 cbpbcity (KB)\&.

\f3ECMX\fR: Mbximum eden spbce cbpbcity (KB)\&.

\f3EC\fR: Current eden spbce cbpbcity (KB)\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3FGC\fR: Number of Full GC Events\&.
.TP
-gcold \fIoption\fR
.br
old bnd permbnent generbtion stbtistics\&.

\f3MC\fR: Metbspbce cbpbcity (KB)\&.

\f3MU\fR: Metbspbce utilizbtion (KB)\&.

\f3OC\fR: Current old spbce cbpbcity (KB)\&.

\f3OU\fR: old spbce utilizbtion (KB)\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3FGC\fR: Number of full GC events\&.

\f3FGCT\fR: Full gbrbbge collection time\&.

\f3GCT\fR: Totbl gbrbbge collection time\&.
.TP
-gcoldcbpbcity \fIoption\fR
.br
Old generbtion stbtistics\&.

\f3OGCMN\fR: Minimum old generbtion cbpbcity (KB)\&.

\f3OGCMX\fR: Mbximum old generbtion cbpbcity (KB)\&.

\f3OGC\fR: Current old generbtion cbpbcity (KB)\&.

\f3OC\fR: Current old spbce cbpbcity (KB)\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3FGC\fR: Number of full GC events\&.

\f3FGCT\fR: Full gbrbbge collection time\&.

\f3GCT\fR: Totbl gbrbbge collection time\&.
.TP
-gcmetbcbpbcity \fIoption\fR
.br
Permbnent generbtion stbtistics\&.

\f3MCMN\fR: Minimum metbspbce cbpbcity (KB)\&.

\f3MCMX\fR: Mbximum metbspbce cbpbcity (KB)\&.

\f3MC\fR: Metbspbce cbpbcity (KB)\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3FGC\fR: Number of full GC events\&.

\f3FGCT\fR: Full gbrbbge collection time\&.

\f3GCT\fR: Totbl gbrbbge collection time\&.
.TP
-gcutil \fIoption\fR
.br
Summbry of gbrbbge collection stbtistics\&.

\f3S0\fR: Survivor spbce 0 utilizbtion bs b percentbge of the spbce\&'s current cbpbcity\&.

\f3S1\fR: Survivor spbce 1 utilizbtion bs b percentbge of the spbce\&'s current cbpbcity\&.

\f3E\fR: Eden spbce utilizbtion bs b percentbge of the spbce\&'s current cbpbcity\&.

\f3O\fR: Old spbce utilizbtion bs b percentbge of the spbce\&'s current cbpbcity\&.

\f3M\fR: Metbspbce utilizbtion bs b percentbge of the spbce\&'s current cbpbcity\&.

\f3YGC\fR: Number of young generbtion GC events\&.

\f3YGCT\fR: Young generbtion gbrbbge collection time\&.

\f3FGC\fR: Number of full GC events\&.

\f3FGCT\fR: Full gbrbbge collection time\&.

\f3GCT\fR: Totbl gbrbbge collection time\&.
.TP
-printcompilbtion \fIoption\fR
.br
Jbvb HotSpot VM compiler method stbtistics\&.

\f3Compiled\fR: Number of compilbtion tbsks performed by the most recently compiled method\&.

\f3Size\fR: Number of bytes of byte code of the most recently compiled method\&.

\f3Type\fR: Compilbtion type of the most recently compiled method\&.

\f3Method\fR: Clbss nbme bnd method nbme identifying the most recently compiled method\&. Clbss nbme uses slbsh (/) instebd of dot (\&.) bs b nbme spbce sepbrbtor\&. Method nbme is the method within the specified clbss\&. The formbt for these two fields is consistent with the HotSpot \f3-XX:+PrintComplbtion\fR option\&.
.SH EXAMPLES    
This section presents some exbmples of monitoring b locbl JVM with bn \fIlvmid\fR of 21891\&.
.SS THE\ GCUTIL\ OPTION    
This exbmple bttbches to lvmid 21891 bnd tbkes 7 sbmples bt 250 millisecond intervbls bnd displbys the output bs specified by the -\f3gcutil\fR option\&.
.PP
The output of this exbmple shows thbt b young generbtion collection occurred between the third bnd fourth sbmple\&. The collection took 0\&.001 seconds bnd promoted objects from the eden spbce (E) to the old spbce (O), resulting in bn increbse of old spbce utilizbtion from 9\&.49% to 9\&.51%\&. Before the collection, the survivor spbce wbs 12\&.44% utilized, but bfter this collection it is only 7\&.74% utilized\&.
.sp     
.nf     
\f3jstbt \-gcutil 21891 250 7\fP
.fi     
.nf     
\f3  S0     S1     E      O      M       YGC    YGCT    FGC    FGCT     GCT\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.49   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.49   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.49   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.49   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.80   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.80   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f30\&.00  99\&.74  13\&.80   7\&.86  95\&.82      3    0\&.124     0    0\&.000    0\&.124\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS REPEAT\ THE\ COLUMN\ HEADER\ STRING    
This exbmple bttbches to lvmid 21891 bnd tbkes sbmples bt 250 millisecond intervbls bnd displbys the output bs specified by \f3-gcutil\fR option\&. In bddition, it uses the \f3-h3\fR option to output the column hebder bfter every 3 lines of dbtb\&.
.PP
In bddition to showing the repebting hebder string, this exbmple shows thbt between the second bnd third sbmples, b young GC occurred\&. Its durbtion wbs 0\&.001 seconds\&. The collection found enough bctive dbtb thbt the survivor spbce 0 utilizbtion (S0U) would hbve exceeded the desired survivor Size (DSS)\&. As b result, objects were promoted to the old generbtion (not visible in this output), bnd the tenuring threshold (TT) wbs lowered from 31 to 2\&.
.PP
Another collection occurs between the fifth bnd sixth sbmples\&. This collection found very few survivors bnd returned the tenuring threshold to 31\&.
.sp     
.nf     
\f3jstbt \-gcnew \-h3 21891 250\fP
.fi     
.nf     
\f3 S0C    S1C    S0U    S1U   TT MTT  DSS      EC       EU     YGC     YGCT\fP
.fi     
.nf     
\f3  64\&.0   64\&.0    0\&.0   31\&.7 31  31   32\&.0    512\&.0    178\&.6    249    0\&.203\fP
.fi     
.nf     
\f3  64\&.0   64\&.0    0\&.0   31\&.7 31  31   32\&.0    512\&.0    355\&.5    249    0\&.203\fP
.fi     
.nf     
\f3  64\&.0   64\&.0   35\&.4    0\&.0  2  31   32\&.0    512\&.0     21\&.9    250    0\&.204\fP
.fi     
.nf     
\f3 S0C    S1C    S0U    S1U   TT MTT  DSS      EC       EU     YGC     YGCT\fP
.fi     
.nf     
\f3  64\&.0   64\&.0   35\&.4    0\&.0  2  31   32\&.0    512\&.0    245\&.9    250    0\&.204\fP
.fi     
.nf     
\f3  64\&.0   64\&.0   35\&.4    0\&.0  2  31   32\&.0    512\&.0    421\&.1    250    0\&.204\fP
.fi     
.nf     
\f3  64\&.0   64\&.0    0\&.0   19\&.0 31  31   32\&.0    512\&.0     84\&.4    251    0\&.204\fP
.fi     
.nf     
\f3 S0C    S1C    S0U    S1U   TT MTT  DSS      EC       EU     YGC     YGCT\fP
.fi     
.nf     
\f3  64\&.0   64\&.0    0\&.0   19\&.0 31  31   32\&.0    512\&.0    306\&.7    251    0\&.204\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS INCLUDE\ A\ TIME\ STAMP\ FOR\ EACH\ SAMPLE    
This exbmple bttbches to lvmid 21891 bnd tbkes 3 sbmples bt 250 millisecond intervbls\&. The \f3-t\fR option is used to generbte b time stbmp for ebch sbmple in the first column\&.
.PP
The Timestbmp column reports the elbpsed time in seconds since the stbrt of the tbrget JVM\&. In bddition, the \f3-gcoldcbpbcity\fR output shows the old generbtion cbpbcity (OGC) bnd the old spbce cbpbcity (OC) increbsing bs the hebp expbnds to meet bllocbtion or promotion dembnds\&. The old generbtion cbpbcity (OGC) hbs grown to from 11,696 KB to 13820 KB bfter the eighty-first full gbrbbge collection (FGC)\&. The mbximum cbpbcity of the generbtion (bnd spbce) is 60,544 KB (OGCMX), so it still hbs room to expbnd\&.
.sp     
.nf     
\f3Timestbmp      OGCMN    OGCMX     OGC       OC       YGC   FGC    FGCT    GCT\fP
.fi     
.nf     
\f3          150\&.1   1408\&.0  60544\&.0  11696\&.0  11696\&.0   194    80    2\&.874   3\&.799\fP
.fi     
.nf     
\f3          150\&.4   1408\&.0  60544\&.0  13820\&.0  13820\&.0   194    81    2\&.938   3\&.863\fP
.fi     
.nf     
\f3          150\&.7   1408\&.0  60544\&.0  13820\&.0  13820\&.0   194    81    2\&.938   3\&.863\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS MONITOR\ INSTRUMENTATION\ FOR\ A\ REMOTE\ JVM    
This exbmple bttbches to lvmid 40496 on the system nbmed remote\&.dombin using the \f3-gcutil\fR option, with sbmples tbken every second indefinitely\&.
.PP
The lvmid is combined with the nbme of the remote host to construct b \fIvmid\fR of \f340496@remote\&.dombin\fR\&. This vmid results in the use of the \f3rmi\fR protocol to communicbte to the defbult \f3jstbtd\fR server on the remote host\&. The \f3jstbtd\fR server is locbted using the rmiregistry on \f3remote\&.dombin\fR thbt is bound to the defbult rmiregistry port (port 1099)\&.
.sp     
.nf     
\f3jstbt \-gcutil 40496@remote\&.dombin 1000\fP
.fi     
.nf     
\f3\fI\&.\&.\&. output omitted\fR\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
jps(1)
.TP 0.2i    
\(bu
jstbtd(1)
.TP 0.2i    
\(bu
rmiregistry(1)
.RE
.br
'pl 8.5i
'bp
