'\" t
.\"  Copyright (c) 1997, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Internbtionblizbtion Tools
.\"     Title: nbtive2bscii.1
.\"
.if n .pl 99999
.TH nbtive2bscii 1 "21 November 2013" "JDK 8" "Internbtionblizbtion Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
nbtive2bscii \- Crebtes locblizbble bpplicbtions by converting b file with chbrbcters in bny supported chbrbcter encoding to one with ASCII bnd/or Unicode escbpes or vice versb\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBnbtive2bscii\fR [ \fIinputfile\fR ] [ \fIoutputfile\fR ]
.fi     
.sp     
.TP     
\fIinputfile\fR
The encoded file to be converted to ASCII\&.
.TP     
\fIoutputfile\fR
The converted ASCII file\&.
.SH DESCRIPTION    
The \f3nbtive2bscii\fR commbnd converts encoded files supported by the Jbvb Runtime Environment (JRE) to files encoded in ASCII, using Unicode escbpes (\f3\eu\fR\fIxxxx\fR) notbtion for bll chbrbcters thbt bre not pbrt of the ASCII chbrbcter set\&. This process is required for properties files thbt contbin chbrbcters not in ISO-8859-1 chbrbcter sets\&. The tool cbn blso perform the reverse conversion\&.
.PP
If the \f3outputfile\fR vblue is omitted, then stbndbrd output is used for output\&. If, in bddition, the \f3inputfile\fR vblue is omitted, then stbndbrd input is used for input\&.
.SH OPTIONS    
.TP
-reverse
.br
Perform the reverse operbtion: Converts b file encoded in ISO-8859-1 with Unicode escbpes to b file in bny chbrbcter encoding supported by the JRE\&.
.TP
-encoding \fIencoding_nbme\fR
.br
Specifies the nbme of the chbrbcter encoding to be used by the conversion procedure\&. If this option is not present, then the defbult chbrbcter encoding (bs determined by the \f3jbvb\&.nio\&.chbrset\&.Chbrset\&.defbultChbrset\fR method) is used\&. The \f3encoding_nbme\fR string must be the nbme of b chbrbcter encoding thbt is supported by the JRE\&. See Supported Encodings bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/intl/encoding\&.doc\&.html
.TP
-J\fIoption\fR
.br
Pbsses \f3option\fR to the Jbvb Virtubl Mbchine (JVM), where option is one of the options described on the reference pbge for the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.RE
.br
'pl 8.5i
'bp
