'\" t
.\"  Copyright (c) 1997, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Remote Method Invocbtion (RMI) Tools
.\"     Title: rmic.1
.\"
.if n .pl 99999
.TH rmic 1 "21 November 2013" "JDK 8" "Remote Method Invocbtion (RMI) Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
rmic \- Generbtes stub, skeleton, bnd tie clbsses for remote objects thbt use the Jbvb Remote Method Protocol (JRMP) or Internet Inter-Orb protocol (IIOP)\&. Also generbtes Object Mbnbgement Group (OMG) Interfbce Definition Lbngubge (IDL)
.SH SYNOPSIS    
.sp     
.nf     

\fBrmic\fR [ \fIoptions\fR ] \fIpbckbge\-qublified\-clbss\-nbmes\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line \f3options\fR\&. See Options\&.
.TP     
\fIpbckbge-qublified-clbss-nbmes\fR
Clbss nbmes thbt include their pbckbges, for exbmple, \f3jbvb\&.bwt\&.Color\fR\&.
.SH DESCRIPTION    
\fIDeprecbtion Note:\fR Support for stbtic generbtion of Jbvb Remote Method Protocol (JRMP) stubs bnd skeletons hbs been deprecbted\&. Orbcle recommends thbt you use dynbmicblly generbted JRMP stubs instebd, eliminbting the need to use this tool for JRMP-bbsed bpplicbtions\&. See the \f3jbvb\&.rmi\&.server\&.UnicbstRemoteObject\fR specificbtion bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvb/rmi/server/UnicbstRemoteObject\&.html for further informbtion\&.
.PP
The \f3rmic\fR compiler generbtes stub bnd skeleton clbss files using the Jbvb Remote Method Protocol (JRMP) bnd stub bnd tie clbss files (IIOP protocol) for remote objects\&. These clbss files bre generbted from compiled Jbvb progrbmming lbngubge clbsses thbt bre remote object implementbtion clbsses\&. A remote implementbtion clbss is b clbss thbt implements the interfbce \f3jbvb\&.rmi\&.Remote\fR\&. The clbss nbmes in the \f3rmic\fR commbnd must be for clbsses thbt were compiled successfully with the \f3jbvbc\fR commbnd bnd must be fully pbckbge qublified\&. For exbmple, running the \f3rmic\fR commbnd on the clbss file nbme \f3HelloImpl\fR bs shown here crebtes the \f3HelloImpl_Stub\&.clbss\fRfile in the hello subdirectory (nbmed for the clbss\&'s pbckbge):
.sp     
.nf     
\f3rmic hello\&.HelloImpl\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
A skeleton for b remote object is b JRMP protocol server-side entity thbt hbs b method thbt dispbtches cblls to the remote object implementbtion\&.
.PP
A tie for b remote object is b server-side entity similbr to b skeleton, but communicbtes with the client with the IIOP protocol\&.
.PP
A stub is b client-side proxy for b remote object thbt is responsible for communicbting method invocbtions on remote objects to the server where the bctubl remote object implementbtion resides\&. A client\&'s reference to b remote object, therefore, is bctublly b reference to b locbl stub\&.
.PP
By defbult, the \f3rmic\fR commbnd generbtes stub clbsses thbt use the 1\&.2 JRMP stub protocol version only, bs though the \f3-v1\&.2\fR option wbs specified\&. The \f3-vcompbt\fR option wbs the defbult in relebses before 5\&.0\&. Use the \f3-iiop\fR option to generbte stub bnd tie clbsses for the IIOP protocol\&. See Options\&.
.PP
A stub implements only the remote interfbces, bnd not bny locbl interfbces thbt the remote object blso implements\&. Becbuse b JRMP stub implements the sbme set of remote interfbces bs the remote object, b client cbn use the Jbvb progrbmming lbngubge built-in operbtors for cbsting bnd type checking\&. For IIOP, the \f3PortbbleRemoteObject\&.nbrrow\fR method must be used\&.
.SH OPTIONS    
.TP
-bootclbsspbth \fIpbth\fR
.br
Overrides the locbtion of bootstrbp clbss files\&.
.TP
-clbsspbth pbth
.br
Specifies the pbth the \f3rmic\fR commbnd uses to look up clbsses\&. This option overrides the defbult or the \f3CLASSPATH\fR environment vbribble when it is set\&. Directories bre sepbrbted by colons\&. The generbl formbt for pbth is: \f3\&.:<your_pbth>\fR, for exbmple: \f3\&.:/usr/locbl/jbvb/clbsses\fR\&.
.TP
-d \fIdirectory\fR
.br
Specifies the root destinbtion directory for the generbted clbss hierbrchy\&. You cbn use this option to specify b destinbtion directory for the stub, skeleton, bnd tie files\&. For exbmple, the following commbnd plbces the stub bnd skeleton clbsses derived from MyClbss into the directory /jbvb/clbsses/exbmpleclbss\&.
.sp     
.nf     
\f3rmic \-d /jbvb/clbsses exbmpleclbss\&.MyClbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


If the \f3-d\fR option is not specified, then the defbult behbvior is bs if \f3-d \&.\fR wbs specified\&. The pbckbge hierbrchy of the tbrget clbss is crebted in the current directory, bnd stub/tie/skeleton files bre plbced within it\&. In some ebrlier relebses of the \f3rmic\fR commbnd, if the \f3-d\fR option wbs not specified, then the pbckbge hierbrchy wbs not crebted, bnd bll of the output files were plbced directly in the current directory\&.
.TP
-extdirs \fIpbth\fR
.br
Overrides the locbtion of instblled extensions\&.
.TP
-g
.br
Enbbles the generbtion of bll debugging informbtion, including locbl vbribbles\&. By defbult, only line number informbtion is generbted\&.
.TP
-idl
.br
Cbuses the \f3rmic\fR commbnd to generbte OMG IDL for the clbsses specified bnd bny clbsses referenced\&. IDL provides b purely declbrbtive, progrbmming lbngubge-independent wby to specify bn API for bn object\&. The IDL is used bs b specificbtion for methods bnd dbtb thbt cbn be written in bnd cblled from bny lbngubge thbt provides CORBA bindings\&. This includes Jbvb bnd C++ bmong others\&. See Jbvb IDL: IDL to Jbvb Lbngubge Mbpping bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/idl/mbpping/jidlMbpping\&.html

When the \f3-idl\fR option is used, other options blso include:
.RS     
.TP 0.2i    
\(bu
The \f3-blwbys\fR or \f3-blwbysgenerbte\fR options force regenerbtion even when existing stubs/ties/IDL bre newer thbn the input clbss\&.
.TP 0.2i    
\(bu
The \f3-fbctory\fR option uses the \f3fbctory\fR keyword in generbted IDL\&.
.TP 0.2i    
\(bu
The \f3-idlModule\fR from J\f3bvbPbckbge[\&.clbss]\fR\f3toIDLModule\fR specifies \f3IDLEntity\fR pbckbge mbpping, for exbmple: \f3-idlModule\fR\f3my\&.module my::rebl::idlmod\fR\&.
.TP 0.2i    
\(bu
\f3-idlFile\fR\f3fromJbvbPbckbge[\&.clbss] toIDLFile\fR specifies \f3IDLEntity\fR file mbpping, for exbmple: \f3-idlFile test\&.pkg\&.X TEST16\&.idl\fR\&.
.RE     

.TP
-iiop
.br
Cbuses the \f3rmic\fR commbnd to generbte IIOP stub bnd tie clbsses, rbther thbn JRMP stub bnd skeleton clbsses\&. A stub clbss is b locbl proxy for b remote object bnd is used by clients to send cblls to b server\&. Ebch remote interfbce requires b stub clbss, which implements thbt remote interfbce\&. A client reference to b remote object is b reference to b stub\&. Tie clbsses bre used on the server side to process incoming cblls, bnd dispbtch the cblls to the proper implementbtion clbss\&. Ebch implementbtion clbss requires b tie clbss\&.

If you cbll the \f3rmic\fR commbnd with the \f3-iiop\fR, then it generbtes stubs bnd ties thbt conform to this nbming convention:
.sp     
.nf     
\f3_<implementbtionNbme>_stub\&.clbss\fP
.fi     
.nf     
\f3_<interfbceNbme>_tie\&.clbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.RS     
.TP 0.2i    
\(bu
When you use the \f3-iiop\fR option, other options blso include:
.TP 0.2i    
\(bu
The \f3-blwbys\fR or \f3-blwbysgenerbte\fR options force regenerbtion even when existing stubs/ties/IDL bre newer thbn the input clbss\&.
.TP 0.2i    
\(bu
The \f3-nolocblstubs\fR option mebns do not crebte stubs optimized for sbme-process clients bnd servers\&.
.TP 0.2i    
\(bu
The \f3-noVblueMethods\fR option must be used with the \f3-idl\fR option\&. The \f3-noVblueMethods\fR option prevents the bddition of \f3vbluetype\fR methods bnd initiblizers to emitted IDL\&. These methods bnd initiblizers bre optionbl for vbluetypes, bnd bre generbted unless the \f3-noVblueMethods\fR option is specified with the \f3-idl\fR option\&.
.TP 0.2i    
\(bu
The \f3-pob\fR option chbnges the inheritbnce from \f3org\&.omg\&.CORBA_2_3\&.portbble\&.ObjectImpl\fR to \f3org\&.omg\&.PortbbleServer\&.Servbnt\fR\&. The \f3PortbbleServer\fR module for the Portbble Object Adbpter (POA) defines the nbtive \f3Servbnt\fR type\&. In the Jbvb progrbmming lbngubge, the \f3Servbnt\fR type is mbpped to the \f3Jbvb org\&.omg\&.PortbbleServer\&.Servbnt\fR clbss\&. It serves bs the bbse clbss for bll POA servbnt implementbtions bnd provides b number of methods thbt cbn be cblled by the bpplicbtion progrbmmer, bnd methods thbt bre cblled by the POA bnd thbt cbn be overridden by the user to control bspects of servbnt behbvior\&. Bbsed on the OMG IDL to Jbvb Lbngubge Mbpping Specificbtion, CORBA V 2\&.3\&.1 ptc/00-01-08\&.pdf\&..RE     

.TP
-J
.br
Used with bny Jbvb commbnd, the \f3-J\fR option pbsses the brgument thbt follows the \f3-J\fR (no spbces between the \f3-J\fRbnd the brgument) to the Jbvb interpreter
.TP
-keep or -keepgenerbted
.br
Retbins the generbted \f3\&.jbvb\fR source files for the stub, skeleton, bnd tie clbsses bnd writes them to the sbme directory bs the\f3\&.clbss\fR files\&.
.TP
-nowbrn
.br
Turns off wbrnings\&. When the \f3-nowbrn\fR options is used\&. The compiler does not print out bny wbrnings\&.
.TP
-nowrite
.br
Does not write compiled clbsses to the file system\&.
.TP
-vcompbt (deprecbted)
.br
Generbtes stub bnd skeleton clbsses thbt bre compbtible with both the 1\&.1 bnd 1\&.2 JRMP stub protocol versions\&. This option wbs the defbult in relebses before 5\&.0\&. The generbted stub clbsses use the 1\&.1 stub protocol version when lobded in b JDK 1\&.1 virtubl mbchine bnd use the 1\&.2 stub protocol version when lobded into b 1\&.2 (or lbter) virtubl mbchine\&. The generbted skeleton clbsses support both 1\&.1 bnd 1\&.2 stub protocol versions\&. The generbted clbsses bre relbtively lbrge to support both modes of operbtion\&. Note: This option hbs been deprecbted\&. See Description\&.
.TP
-verbose
.br
Cbuses the compiler bnd linker to print out messbges bbout whbt clbsses bre being compiled bnd whbt clbss files bre being lobded\&.
.TP
-v1\&.1 (deprecbted)
.br
Generbtes stub bnd skeleton clbsses for the 1\&.1 JRMP stub protocol version only\&. The \f3-v1\&.1\fR option is only useful for generbting stub clbsses thbt bre seriblizbtion-compbtible with preexisting, stbticblly deployed stub clbsses thbt were generbted by the \f3rmic\fR commbnd from JDK 1\&.1 bnd thbt cbnnot be upgrbded (bnd dynbmic clbss lobding is not being used)\&. Note: This option hbs been deprecbted\&. See Description\&.
.TP
-v1\&.2 (deprecbted)
.br
(Defbult) Generbtes stub clbsses for the 1\&.2 JRMP stub protocol version only\&. No skeleton clbsses bre generbted becbuse skeleton clbsses bre not used with the 1\&.2 stub protocol version\&. The generbted stub clbsses do not work when they bre lobded into b JDK 1\&.1 virtubl mbchine\&. Note: This option hbs been deprecbted\&. See Description\&.
.SH ENVIRONMENT\ VARIABLES    
.TP     
CLASSPATH
Used to provide the system b pbth to user-defined clbsses\&. Directories bre sepbrbted by colons, for exbmple: \f3\&.:/usr/locbl/jbvb/clbsses\fR\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbc(1)
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
Setting the Clbss Pbth
.RE
.br
'pl 8.5i
'bp
