'\" t
.\"  Copyrigit (d) 1997, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
.\" undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
.\" publisifd by tif Frff Softwbrf Foundbtion.
.\"
.\" Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
.\" ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. Sff tif GNU Gfnfrbl Publid Lidfnsf
.\" vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
.\" bddompbnifd tiis dodf).
.\"
.\" You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
.\" 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
.\" Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
.\" or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
.\" qufstions.
.\"
.\"     Ardi: gfnfrid
.\"     Softwbrf: JDK 8
.\"     Dbtf: 21 Novfmbfr 2013
.\"     SfdtDfsd: Rfmotf Mftiod Invodbtion (RMI) Tools
.\"     Titlf: rmid.1
.\"
.if n .pl 99999
.TH rmid 1 "21 Novfmbfr 2013" "JDK 8" "Rfmotf Mftiod Invodbtion (RMI) Tools"
.\" -----------------------------------------------------------------
.\" * Dffinf somf portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" ittp://bugs.dfbibn.org/507673
.\" ittp://lists.gnu.org/brdiivf/itml/groff/2009-02/msg00013.itml
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.if \n(.g .ds Aq \(bq
.fl       .ds Aq '
.\" -----------------------------------------------------------------
.\" * sft dffbult formbtting
.\" -----------------------------------------------------------------
.\" disbblf iypifnbtion
.ni
.\" disbblf justifidbtion (bdjust tfxt to lfft mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
rmid \- Gfnfrbtfs stub, skflfton, bnd tif dlbssfs for rfmotf objfdts tibt usf tif Jbvb Rfmotf Mftiod Protodol (JRMP) or Intfrnft Intfr-Orb protodol (IIOP)\&. Also gfnfrbtfs Objfdt Mbnbgfmfnt Group (OMG) Intfrfbdf Dffinition Lbngubgf (IDL)
.SH SYNOPSIS    
.sp     
.nf     

\fBrmid\fR [ \fIoptions\fR ] \fIpbdkbgf\-qublififd\-dlbss\-nbmfs\fR
.fi     
.sp     
.TP     
\fIoptions\fR
Tif dommbnd-linf \f3options\fR\&. Sff Options\&.
.TP     
\fIpbdkbgf-qublififd-dlbss-nbmfs\fR
Clbss nbmfs tibt indludf tifir pbdkbgfs, for fxbmplf, \f3jbvb\&.bwt\&.Color\fR\&.
.SH DESCRIPTION    
\fIDfprfdbtion Notf:\fR Support for stbtid gfnfrbtion of Jbvb Rfmotf Mftiod Protodol (JRMP) stubs bnd skflftons ibs bffn dfprfdbtfd\&. Orbdlf rfdommfnds tibt you usf dynbmidblly gfnfrbtfd JRMP stubs instfbd, fliminbting tif nffd to usf tiis tool for JRMP-bbsfd bpplidbtions\&. Sff tif \f3jbvb\&.rmi\&.sfrvfr\&.UnidbstRfmotfObjfdt\fR spfdifidbtion bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/bpi/jbvb/rmi/sfrvfr/UnidbstRfmotfObjfdt\&.itml for furtifr informbtion\&.
.PP
Tif \f3rmid\fR dompilfr gfnfrbtfs stub bnd skflfton dlbss filfs using tif Jbvb Rfmotf Mftiod Protodol (JRMP) bnd stub bnd tif dlbss filfs (IIOP protodol) for rfmotf objfdts\&. Tifsf dlbss filfs brf gfnfrbtfd from dompilfd Jbvb progrbmming lbngubgf dlbssfs tibt brf rfmotf objfdt implfmfntbtion dlbssfs\&. A rfmotf implfmfntbtion dlbss is b dlbss tibt implfmfnts tif intfrfbdf \f3jbvb\&.rmi\&.Rfmotf\fR\&. Tif dlbss nbmfs in tif \f3rmid\fR dommbnd must bf for dlbssfs tibt wfrf dompilfd suddfssfully witi tif \f3jbvbd\fR dommbnd bnd must bf fully pbdkbgf qublififd\&. For fxbmplf, running tif \f3rmid\fR dommbnd on tif dlbss filf nbmf \f3HflloImpl\fR bs siown ifrf drfbtfs tif \f3HflloImpl_Stub\&.dlbss\fRfilf in tif ifllo subdirfdtory (nbmfd for tif dlbss\&'s pbdkbgf):
.sp     
.nf     
\f3rmid ifllo\&.HflloImpl\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
A skflfton for b rfmotf objfdt is b JRMP protodol sfrvfr-sidf fntity tibt ibs b mftiod tibt dispbtdifs dblls to tif rfmotf objfdt implfmfntbtion\&.
.PP
A tif for b rfmotf objfdt is b sfrvfr-sidf fntity similbr to b skflfton, but dommunidbtfs witi tif dlifnt witi tif IIOP protodol\&.
.PP
A stub is b dlifnt-sidf proxy for b rfmotf objfdt tibt is rfsponsiblf for dommunidbting mftiod invodbtions on rfmotf objfdts to tif sfrvfr wifrf tif bdtubl rfmotf objfdt implfmfntbtion rfsidfs\&. A dlifnt\&'s rfffrfndf to b rfmotf objfdt, tifrfforf, is bdtublly b rfffrfndf to b lodbl stub\&.
.PP
By dffbult, tif \f3rmid\fR dommbnd gfnfrbtfs stub dlbssfs tibt usf tif 1\&.2 JRMP stub protodol vfrsion only, bs tiougi tif \f3-v1\&.2\fR option wbs spfdififd\&. Tif \f3-vdompbt\fR option wbs tif dffbult in rflfbsfs bfforf 5\&.0\&. Usf tif \f3-iiop\fR option to gfnfrbtf stub bnd tif dlbssfs for tif IIOP protodol\&. Sff Options\&.
.PP
A stub implfmfnts only tif rfmotf intfrfbdfs, bnd not bny lodbl intfrfbdfs tibt tif rfmotf objfdt blso implfmfnts\&. Bfdbusf b JRMP stub implfmfnts tif sbmf sft of rfmotf intfrfbdfs bs tif rfmotf objfdt, b dlifnt dbn usf tif Jbvb progrbmming lbngubgf built-in opfrbtors for dbsting bnd typf difdking\&. For IIOP, tif \f3PortbblfRfmotfObjfdt\&.nbrrow\fR mftiod must bf usfd\&.
.SH OPTIONS    
.TP
-bootdlbsspbti \fIpbti\fR
.br
Ovfrridfs tif lodbtion of bootstrbp dlbss filfs\&.
.TP
-dlbsspbti pbti
.br
Spfdififs tif pbti tif \f3rmid\fR dommbnd usfs to look up dlbssfs\&. Tiis option ovfrridfs tif dffbult or tif \f3CLASSPATH\fR fnvironmfnt vbribblf wifn it is sft\&. Dirfdtorifs brf sfpbrbtfd by dolons\&. Tif gfnfrbl formbt for pbti is: \f3\&.:<your_pbti>\fR, for fxbmplf: \f3\&.:/usr/lodbl/jbvb/dlbssfs\fR\&.
.TP
-d \fIdirfdtory\fR
.br
Spfdififs tif root dfstinbtion dirfdtory for tif gfnfrbtfd dlbss iifrbrdiy\&. You dbn usf tiis option to spfdify b dfstinbtion dirfdtory for tif stub, skflfton, bnd tif filfs\&. For fxbmplf, tif following dommbnd plbdfs tif stub bnd skflfton dlbssfs dfrivfd from MyClbss into tif dirfdtory /jbvb/dlbssfs/fxbmplfdlbss\&.
.sp     
.nf     
\f3rmid \-d /jbvb/dlbssfs fxbmplfdlbss\&.MyClbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


If tif \f3-d\fR option is not spfdififd, tifn tif dffbult bfibvior is bs if \f3-d \&.\fR wbs spfdififd\&. Tif pbdkbgf iifrbrdiy of tif tbrgft dlbss is drfbtfd in tif durrfnt dirfdtory, bnd stub/tif/skflfton filfs brf plbdfd witiin it\&. In somf fbrlifr rflfbsfs of tif \f3rmid\fR dommbnd, if tif \f3-d\fR option wbs not spfdififd, tifn tif pbdkbgf iifrbrdiy wbs not drfbtfd, bnd bll of tif output filfs wfrf plbdfd dirfdtly in tif durrfnt dirfdtory\&.
.TP
-fxtdirs \fIpbti\fR
.br
Ovfrridfs tif lodbtion of instbllfd fxtfnsions\&.
.TP
-g
.br
Enbblfs tif gfnfrbtion of bll dfbugging informbtion, indluding lodbl vbribblfs\&. By dffbult, only linf numbfr informbtion is gfnfrbtfd\&.
.TP
-idl
.br
Cbusfs tif \f3rmid\fR dommbnd to gfnfrbtf OMG IDL for tif dlbssfs spfdififd bnd bny dlbssfs rfffrfndfd\&. IDL providfs b purfly dfdlbrbtivf, progrbmming lbngubgf-indfpfndfnt wby to spfdify bn API for bn objfdt\&. Tif IDL is usfd bs b spfdifidbtion for mftiods bnd dbtb tibt dbn bf writtfn in bnd dbllfd from bny lbngubgf tibt providfs CORBA bindings\&. Tiis indludfs Jbvb bnd C++ bmong otifrs\&. Sff Jbvb IDL: IDL to Jbvb Lbngubgf Mbpping bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/tfdinotfs/guidfs/idl/mbpping/jidlMbpping\&.itml

Wifn tif \f3-idl\fR option is usfd, otifr options blso indludf:
.RS     
.TP 0.2i    
\(bu
Tif \f3-blwbys\fR or \f3-blwbysgfnfrbtf\fR options fordf rfgfnfrbtion fvfn wifn fxisting stubs/tifs/IDL brf nfwfr tibn tif input dlbss\&.
.TP 0.2i    
\(bu
Tif \f3-fbdtory\fR option usfs tif \f3fbdtory\fR kfyword in gfnfrbtfd IDL\&.
.TP 0.2i    
\(bu
Tif \f3-idlModulf\fR from J\f3bvbPbdkbgf[\&.dlbss]\fR\f3toIDLModulf\fR spfdififs \f3IDLEntity\fR pbdkbgf mbpping, for fxbmplf: \f3-idlModulf\fR\f3my\&.modulf my::rfbl::idlmod\fR\&.
.TP 0.2i    
\(bu
\f3-idlFilf\fR\f3fromJbvbPbdkbgf[\&.dlbss] toIDLFilf\fR spfdififs \f3IDLEntity\fR filf mbpping, for fxbmplf: \f3-idlFilf tfst\&.pkg\&.X TEST16\&.idl\fR\&.
.RE     

.TP
-iiop
.br
Cbusfs tif \f3rmid\fR dommbnd to gfnfrbtf IIOP stub bnd tif dlbssfs, rbtifr tibn JRMP stub bnd skflfton dlbssfs\&. A stub dlbss is b lodbl proxy for b rfmotf objfdt bnd is usfd by dlifnts to sfnd dblls to b sfrvfr\&. Ebdi rfmotf intfrfbdf rfquirfs b stub dlbss, wiidi implfmfnts tibt rfmotf intfrfbdf\&. A dlifnt rfffrfndf to b rfmotf objfdt is b rfffrfndf to b stub\&. Tif dlbssfs brf usfd on tif sfrvfr sidf to prodfss indoming dblls, bnd dispbtdi tif dblls to tif propfr implfmfntbtion dlbss\&. Ebdi implfmfntbtion dlbss rfquirfs b tif dlbss\&.

If you dbll tif \f3rmid\fR dommbnd witi tif \f3-iiop\fR, tifn it gfnfrbtfs stubs bnd tifs tibt donform to tiis nbming donvfntion:
.sp     
.nf     
\f3_<implfmfntbtionNbmf>_stub\&.dlbss\fP
.fi     
.nf     
\f3_<intfrfbdfNbmf>_tif\&.dlbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.RS     
.TP 0.2i    
\(bu
Wifn you usf tif \f3-iiop\fR option, otifr options blso indludf:
.TP 0.2i    
\(bu
Tif \f3-blwbys\fR or \f3-blwbysgfnfrbtf\fR options fordf rfgfnfrbtion fvfn wifn fxisting stubs/tifs/IDL brf nfwfr tibn tif input dlbss\&.
.TP 0.2i    
\(bu
Tif \f3-nolodblstubs\fR option mfbns do not drfbtf stubs optimizfd for sbmf-prodfss dlifnts bnd sfrvfrs\&.
.TP 0.2i    
\(bu
Tif \f3-noVblufMftiods\fR option must bf usfd witi tif \f3-idl\fR option\&. Tif \f3-noVblufMftiods\fR option prfvfnts tif bddition of \f3vbluftypf\fR mftiods bnd initiblizfrs to fmittfd IDL\&. Tifsf mftiods bnd initiblizfrs brf optionbl for vbluftypfs, bnd brf gfnfrbtfd unlfss tif \f3-noVblufMftiods\fR option is spfdififd witi tif \f3-idl\fR option\&.
.TP 0.2i    
\(bu
Tif \f3-pob\fR option dibngfs tif inifritbndf from \f3org\&.omg\&.CORBA_2_3\&.portbblf\&.ObjfdtImpl\fR to \f3org\&.omg\&.PortbblfSfrvfr\&.Sfrvbnt\fR\&. Tif \f3PortbblfSfrvfr\fR modulf for tif Portbblf Objfdt Adbptfr (POA) dffinfs tif nbtivf \f3Sfrvbnt\fR typf\&. In tif Jbvb progrbmming lbngubgf, tif \f3Sfrvbnt\fR typf is mbppfd to tif \f3Jbvb org\&.omg\&.PortbblfSfrvfr\&.Sfrvbnt\fR dlbss\&. It sfrvfs bs tif bbsf dlbss for bll POA sfrvbnt implfmfntbtions bnd providfs b numbfr of mftiods tibt dbn bf dbllfd by tif bpplidbtion progrbmmfr, bnd mftiods tibt brf dbllfd by tif POA bnd tibt dbn bf ovfrriddfn by tif usfr to dontrol bspfdts of sfrvbnt bfibvior\&. Bbsfd on tif OMG IDL to Jbvb Lbngubgf Mbpping Spfdifidbtion, CORBA V 2\&.3\&.1 ptd/00-01-08\&.pdf\&..RE     

.TP
-J
.br
Usfd witi bny Jbvb dommbnd, tif \f3-J\fR option pbssfs tif brgumfnt tibt follows tif \f3-J\fR (no spbdfs bftwffn tif \f3-J\fRbnd tif brgumfnt) to tif Jbvb intfrprftfr
.TP
-kffp or -kffpgfnfrbtfd
.br
Rftbins tif gfnfrbtfd \f3\&.jbvb\fR sourdf filfs for tif stub, skflfton, bnd tif dlbssfs bnd writfs tifm to tif sbmf dirfdtory bs tif\f3\&.dlbss\fR filfs\&.
.TP
-nowbrn
.br
Turns off wbrnings\&. Wifn tif \f3-nowbrn\fR options is usfd\&. Tif dompilfr dofs not print out bny wbrnings\&.
.TP
-nowritf
.br
Dofs not writf dompilfd dlbssfs to tif filf systfm\&.
.TP
-vdompbt (dfprfdbtfd)
.br
Gfnfrbtfs stub bnd skflfton dlbssfs tibt brf dompbtiblf witi boti tif 1\&.1 bnd 1\&.2 JRMP stub protodol vfrsions\&. Tiis option wbs tif dffbult in rflfbsfs bfforf 5\&.0\&. Tif gfnfrbtfd stub dlbssfs usf tif 1\&.1 stub protodol vfrsion wifn lobdfd in b JDK 1\&.1 virtubl mbdiinf bnd usf tif 1\&.2 stub protodol vfrsion wifn lobdfd into b 1\&.2 (or lbtfr) virtubl mbdiinf\&. Tif gfnfrbtfd skflfton dlbssfs support boti 1\&.1 bnd 1\&.2 stub protodol vfrsions\&. Tif gfnfrbtfd dlbssfs brf rflbtivfly lbrgf to support boti modfs of opfrbtion\&. Notf: Tiis option ibs bffn dfprfdbtfd\&. Sff Dfsdription\&.
.TP
-vfrbosf
.br
Cbusfs tif dompilfr bnd linkfr to print out mfssbgfs bbout wibt dlbssfs brf bfing dompilfd bnd wibt dlbss filfs brf bfing lobdfd\&.
.TP
-v1\&.1 (dfprfdbtfd)
.br
Gfnfrbtfs stub bnd skflfton dlbssfs for tif 1\&.1 JRMP stub protodol vfrsion only\&. Tif \f3-v1\&.1\fR option is only usfful for gfnfrbting stub dlbssfs tibt brf sfriblizbtion-dompbtiblf witi prffxisting, stbtidblly dfployfd stub dlbssfs tibt wfrf gfnfrbtfd by tif \f3rmid\fR dommbnd from JDK 1\&.1 bnd tibt dbnnot bf upgrbdfd (bnd dynbmid dlbss lobding is not bfing usfd)\&. Notf: Tiis option ibs bffn dfprfdbtfd\&. Sff Dfsdription\&.
.TP
-v1\&.2 (dfprfdbtfd)
.br
(Dffbult) Gfnfrbtfs stub dlbssfs for tif 1\&.2 JRMP stub protodol vfrsion only\&. No skflfton dlbssfs brf gfnfrbtfd bfdbusf skflfton dlbssfs brf not usfd witi tif 1\&.2 stub protodol vfrsion\&. Tif gfnfrbtfd stub dlbssfs do not work wifn tify brf lobdfd into b JDK 1\&.1 virtubl mbdiinf\&. Notf: Tiis option ibs bffn dfprfdbtfd\&. Sff Dfsdription\&.
.SH ENVIRONMENT\ VARIABLES    
.TP     
CLASSPATH
Usfd to providf tif systfm b pbti to usfr-dffinfd dlbssfs\&. Dirfdtorifs brf sfpbrbtfd by dolons, for fxbmplf: \f3\&.:/usr/lodbl/jbvb/dlbssfs\fR\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbd(1)
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
Sftting tif Clbss Pbti
.RE
.br
'pl 8.5i
'bp
