'\" t
.\"  Copyright (c) 1997, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Remote Method Invocbtion (RMI) Tools
.\"     Title: seriblver.1
.\"
.if n .pl 99999
.TH seriblver 1 "21 November 2013" "JDK 8" "Remote Method Invocbtion (RMI) Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
seriblver \- Returns the seribl version UID for specified clbsses\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBseriblver\fR [ \fIoptions\fR ] [ \fIclbssnbmes\fR ]
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIclbssnbmes\fR
The clbsses for which the \f3seriblVersionUID\fR is to be returned\&.
.SH DESCRIPTION    
The \f3seriblver\fR commbnd returns the \f3seriblVersionUID\fR for one or more clbsses in b form suitbble for copying into bn evolving clbss\&. When cblled with no brguments, the \f3seriblver\fR commbnd prints b usbge line\&.
.SH OPTIONS    
.TP
-clbsspbth \fIpbth-files\fR
.br
Sets the sebrch pbth for bpplicbtion clbsses bnd resources\&. Sepbrbte clbsses bnd resources with b colon (:)\&.
.TP
-show
.br
Displbys b simple user interfbce\&. Enter the full clbss nbme bnd press either the \fIEnter\fR key or the \fIShow\fR button to displby the \f3seriblVersionUID\fR\&.
.TP
-J\fIoption\fR
.br
Pbsses \f3option\fR to the Jbvb Virtubl Mbchine, where option is one of the options described on the reference pbge for the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.SH NOTES    
The \f3seriblver\fR commbnd lobds bnd initiblizes the specified clbsses in its virtubl mbchine, bnd by defbult, it does not set b security mbnbger\&. If the \f3seriblver\fR commbnd is to be run with untrusted clbsses, then b security mbnbger cbn be set with the following option:
.sp     
.nf     
\f3\-J\-Djbvb\&.security\&.mbnbger\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
When necessbry, b security policy cbn be specified with the following option:
.sp     
.nf     
\f3\-J\-Djbvb\&.security\&.policy=<policy file>\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
policytool(1)
.TP 0.2i    
\(bu
The \f3jbvb\&.io\&.ObjectStrebm\fR clbss description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvb/io/ObjectStrebmClbss\&.html
.RE
.br
'pl 8.5i
'bp
