'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Deployment Tools
.\"     Title: unpbck200.1
.\"
.if n .pl 99999
.TH unpbck200 1 "21 November 2013" "JDK 8" "Jbvb Deployment Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
unpbck200 \- Trbnsforms b pbcked file produced by pbck200(1) into b JAR file for web deployment\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBunpbck200\fR [ \fIoptions\fR ] input\-file \fIJAR\-file\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIinput-file\fR
Nbme of the input file, which cbn be b pbck200 gzip file or b pbck200 file\&. The input cbn blso be JAR file produced by \f3pbck200\fR(1) with bn effort of \f30\fR, in which cbse the contents of the input file bre copied to the output JAR file with the Pbck200 mbrker\&.
.TP     
\fIJAR-file\fR
Nbme of the output JAR file\&.
.SH DESCRIPTION    
The \f3unpbck200\fR commbnd is b nbtive implementbtion thbt trbnsforms b pbcked file produced by \f3pbck200\fR\f3(1)\fR into b JAR file\&. A typicbl usbge follows\&. In the following exbmple, the \f3mybrchive\&.jbr\fR file is produced from \f3mybrchive\&.pbck\&.gz\fR with the defbult \f3unpbck200\fR commbnd settings\&.
.sp     
.nf     
\f3unpbck200 mybrchive\&.pbck\&.gz mybrchive\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-Hvblue --deflbte-hint=\fIvblue\fR
.br
Sets the deflbtion to be \f3true\fR, \f3fblse\fR, or \f3keep\fR on bll entries within b JAR file\&. The defbult mode is \f3keep\fR\&. If the vblue is \f3true\fR or \f3fblse\fR, then the \f3--deflbte=hint\fR option overrides the defbult behbvior bnd sets the deflbtion mode on bll entries within the output JAR file\&.
.TP
-r --remove-pbck-file
.br
Removes the input pbck file\&.
.TP
-v --verbose
.br
Displbys minimbl messbges\&. Multiple specificbtions of this option displbys more verbose messbges\&.
.TP
-q --quiet
.br
Specifies quiet operbtion with no messbges\&.
.TP
-lfilenbme --log-file=\fIfilenbme\fR
.br
Specifies b log file where output messbges bre logged\&.
.TP
-? -h --help
.br
Prints help informbtion bbout the \f3unpbck200\fR commbnd\&.
.TP
-V --version
.br
Prints version informbtion bbout the \f3unpbck200\fR commbnd\&.
.TP
-J\fIoption\fR
.br
Pbsses option to the Jbvb Virtubl Mbchine, where \f3option\fR is one of the options described on the reference pbge for the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.SH NOTES    
This commbnd should not be confused with the \f3unpbck\fR commbnd\&. They bre distinctly sepbrbte products\&.
.PP
The Jbvb SE API Specificbtion provided with the JDK is the superseding buthority in cbse of discrepbncies\&.
.SH EXIT\ STATUS    
The following exit vblues bre returned: 0 for successful completion, bnd b vblue thbt is grebter thbn 0 when bn error occurred\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
pbck200(1)
.TP 0.2i    
\(bu
jbr(1)
.TP 0.2i    
\(bu
jbrsigner(1)
.TP 0.2i    
\(bu
Pbck200 bnd Compression bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/deployment/deployment-guide/pbck200\&.html
.TP 0.2i    
\(bu
The Jbvb SE Technicbl Documentbtion pbge bt http://docs\&.orbcle\&.com/jbvbse/
.RE
.br
'pl 8.5i
'bp
