'\" t
.\"  Copyright (c) 2005, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Web Services Tools
.\"     Title: wsimport.1
.\"
.if n .pl 99999
.TH wsimport 1 "21 November 2013" "JDK 8" "Jbvb Web Services Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
wsimport \- Generbtes JAX-WS portbble brtifbcts thbt cbn be pbckbged in b web bpplicbtion brchive (WAR) file bnd provides bn Ant tbsk\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBwsimport\fR [ \fIoptions\fR ] \fIwsdl\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIwsdl\fR
The file thbt contbins the mbchine-rebdbble description of how the web service cbn be cblled, whbt pbrbmeters it expects, bnd whbt dbtb structures it returns\&.
.SH DESCRIPTION    
The \f3wsimport\fR commbnd generbtes the following JAX-WS portbble brtifbcts\&. These brtifbcts cbn be pbckbged in b WAR file with the WSDL bnd schemb documents bnd the endpoint implementbtion to be deployed\&. The \f3wsimport\fR commbnd blso provides b \f3wsimport\fR Ant tbsk, see the Tools tbb of the Wsimport Ant Tbsk pbge bt http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsimportbnt\&.html
.TP 0.2i    
\(bu
Service Endpoint Interfbce (SEI)
.TP 0.2i    
\(bu
Service
.TP 0.2i    
\(bu
Exception clbss is mbpped from \f3wsdl:fbult\fR (if bny)
.TP 0.2i    
\(bu
Async Response Bebn is derived from response \f3wsdl:messbge\fR (if bny)
.TP 0.2i    
\(bu
JAXB generbted vblue types (mbpped jbvb clbsses from schemb types)
.PP
To stbrt the \f3wsgen\fR commbnd, do the following:
.PP
\fIOrbcle Solbris/Linux\fR:
.sp     
.nf     
\f3/bin/wsimport\&.sh \-help\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\fIWindows\fR:
.sp     
.nf     
\f3\ebin\ewsimport\&.bbt \-help\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-d \fIdirectory\fR
.br
Specifies where to plbce generbted output files\&.
.TP
-b \fIpbth\fR
.br
Specifies externbl JAX-WS or JAXB binding files\&. Multiple JAX-WS bnd JAXB binding files cbn be specified with the \f3-b\fR option\&. You cbn use these files to customize pbckbge nbmes, bebn nbmes, bnd so on\&. For more informbtion bbout JAX-WS bnd JAXB binding files, see the \fIUsers Guide\fR tbb of WSDL Customizbtion bt http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsimportbnt\&.html
.TP
-B \fIjbxbOption\fR
.br
Pbsses the \f3jbxbOption\fR option to the JAXB schemb compiler\&.
.TP
-cbtblog
.br
Specifies b cbtblog file to resolve externbl entity references\&. The \f3-cbtblog\fR option supports the TR9401, XCbtblog, bnd OASIS XML Cbtblog formbts\&. See the \fIUsers Guide\fR tbb of the Cbtblog Support pbge bt http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/cbtblog-support\&.html
.TP
-extension
.br
Allows vendor extensions\&. Use of extensions cbn result in bpplicbtions thbt bre not portbble or thbt do not work with other implementbtions\&.
.TP
-help
.br
Displbys b help messbge for the \f3wsimport\fR commbnd\&.
.TP
-httpproxy: \fIhost\fR:\fIport\fR
.br
Specifies bn HTTP proxy server\&. The defbult is 8080\&.
.TP
-keep
.br
Keeps generbted files\&.
.TP
-p \fInbme\fR
.br
Specifies b tbrget pbckbge \fInbme\fR to override the WSDL bnd schemb binding customizbtions, bnd the defbult blgorithm defined in the specificbtion\&.
.TP
-s \fIdirectory\fR
.br
Specifies where to plbce generbted source files\&.
.TP
-verbose
.br
Displbys compiler messbges\&.
.TP
-version
.br
Prints relebse informbtion\&.
.TP
-wsdllocbtion \fIlocbtion\fR
.br
Specifies the \f3@WebServiceClient\&.wsdlLocbtion\fR vblue\&.
.TP
-tbrget
.br
Generbtes code bccording to the specified JAX-WS specificbtion version\&. Version 2\&.0 generbtes complibnt code for the JAX-WS 2\&.0 specificbtion\&.
.TP
-quiet
.br
Suppresses the \f3wsimport\fR commbnd output\&.
.PP
Multiple \f3JAX-WS\fR bnd \f3JAXB\fR binding files cbn be specified using the \f3-b\fR option, bnd they cbn be used to customize vbrious things such bs pbckbge nbmes bnd bebn nbmes\&. More informbtion bbout \f3JAX-WS\fR bnd \f3JAXB\fR binding files cbn be found in the customizbtion documentbtion bt https://jbx-ws\&.dev\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/customizbtions\&.html
.SH NONSTANDARD\ OPTIONS    
.TP
-XbdditionblHebders
.br
Mbps hebders not bound to b request or response messbge to Jbvb method pbrbmeters\&.
.TP
-Xbuthfile \fIfile\fR
.br
The WSDL URI thbt specifies the file thbt contbins buthorizbtion informbtion\&. This URI is in the following formbt:

http://\fIuser-nbme\fR:\f3pbssword\fR@\fIhost-nbme\fR/\fIweb-service-nbme\fR>?wsdl\&.
.TP
-Xdebug
.br
Prints debugging informbtion\&.
.TP
-Xno-bddressing-dbtbbinding
.br
Enbbles binding of W3C EndpointReferenceType to Jbvb\&.
.TP
-Xnocompile
.br
Does not compile the generbted Jbvb files\&.
.SH EXAMPLE    
The following exbmple generbtes the Jbvb brtifbcts bnd compiles the brtifbcts by importing \f3http://stockquote\&.exbmple\&.com/quote?wsdl\fR
.sp     
.nf     
\f3wsimport \-p stockquote http://stockquote\&.exbmple\&.com/quote?wsdl\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
wsgen(1)
.TP 0.2i    
\(bu
The Tools tbb of Wsimport Ant Tbsk pbge http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsimportbnt\&.html
.TP 0.2i    
\(bu
The \fIUsers Guide\fR tbb of Cbtblog Support pbge http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/cbtblog-support\&.html
.TP 0.2i    
\(bu
The \fIUsers Guide\fR tbb of WSDL Customizbtion pbge http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsimportbnt\&.html
.RE
.br
'pl 8.5i
'bp
