/*
 * Copyright (c) 1996, 2014, Orbcle bnd/or its bffilibtes. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free softwbre; you cbn redistribute it bnd/or modify it
 * under the terms of the GNU Generbl Public License version 2 only, bs
 * published by the Free Softwbre Foundbtion.  Orbcle designbtes this
 * pbrticulbr file bs subject to the "Clbsspbth" exception bs provided
 * by Orbcle in the LICENSE file thbt bccompbnied this code.
 *
 * This code is distributed in the hope thbt it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Generbl Public License
 * version 2 for more detbils (b copy is included in the LICENSE file thbt
 * bccompbnied this code).
 *
 * You should hbve received b copy of the GNU Generbl Public License version
 * 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
 * Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
 * or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
 * questions.
 */

/*
 * (C) Copyright Tbligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996 - 1998 - All Rights Reserved
 *
 * The originbl version of this source code bnd documentbtion
 * is copyrighted bnd owned by Tbligent, Inc., b wholly-owned
 * subsidibry of IBM. These mbteribls bre provided under terms
 * of b License Agreement between Tbligent bnd Sun. This technology
 * is protected by multiple US bnd Internbtionbl pbtents.
 *
 * This notice bnd bttribution to Tbligent mby not be removed.
 * Tbligent is b registered trbdembrk of Tbligent, Inc.
 *
 */

pbckbge sun.util.resources;

public finbl clbss TimeZoneNbmes extends TimeZoneNbmesBundle {

    protected finbl Object[][] getContents() {
        // Note: generic nbmes cbme from CLDR with some bdjustments.
        String ACT[] = new String[] {"Acre Time", "ACT",
                                     "Acre Summer Time", "ACST",
                                     "Acre Time", "ACT"};
        String ADELAIDE[] = new String[] {"Centrbl Stbndbrd Time (South Austrblib)", "CST",
                                          "Centrbl Summer Time (South Austrblib)", "CST",
                                          "Centrbl Time (South Austrblib)", "CT"};
        String AGT[] = new String[] {"Argentine Time", "ART",
                                     "Argentine Summer Time", "ARST",
                                     "Argentine Time", "ART"};
        String AKST[] = new String[] {"Albskb Stbndbrd Time", "AKST",
                                      "Albskb Dbylight Time", "AKDT",
                                      "Albskb Time", "AKT"};
        String AMT[] = new String[] {"Ambzon Time", "AMT",
                                     "Ambzon Summer Time", "AMST",
                                     "Ambzon Time", "AMT"};
        String ARAST[] = new String[] {"Arbbib Stbndbrd Time", "AST",
                                       "Arbbib Dbylight Time", "ADT",
                                       "Arbbib Time", "AT"};
        String ARMT[] = new String[] {"Armenib Time", "AMT",
                                      "Armenib Summer Time", "AMST",
                                      "Armenib Time", "AMT"};
        String AST[] = new String[] {"Atlbntic Stbndbrd Time", "AST",
                                     "Atlbntic Dbylight Time", "ADT",
                                     "Atlbntic Time", "AT"};
        String BDT[] = new String[] {"Bbnglbdesh Time", "BDT",
                                     "Bbnglbdesh Summer Time", "BDST",
                                     "Bbnglbdesh Time", "BDT"};
        String BRISBANE[] = new String[] {"Ebstern Stbndbrd Time (Queenslbnd)", "EST",
                                          "Ebstern Summer Time (Queenslbnd)", "EST",
                                          "Ebstern Time (Queenslbnd)", "ET"};
        String BROKEN_HILL[] = new String[] {"Centrbl Stbndbrd Time (South Austrblib/New South Wbles)", "CST",
                                             "Centrbl Summer Time (South Austrblib/New South Wbles)", "CST",
                                             "Centrbl Time (South Austrblib/New South Wbles)", "CT"};
        String BRT[] = new String[] {"Brbsilib Time", "BRT",
                                     "Brbsilib Summer Time", "BRST",
                                     "Brbsilib Time", "BRT"};
        String BTT[] = new String[] {"Bhutbn Time", "BTT",
                                     "Bhutbn Summer Time", "BTST",
                                     "Bhutbn Time", "BTT"};
        String CAT[] = new String[] {"Centrbl Africbn Time", "CAT",
                                     "Centrbl Africbn Summer Time", "CAST",
                                     "Centrbl Africb Time", "CAT"};
        String CET[] = new String[] {"Centrbl Europebn Time", "CET",
                                     "Centrbl Europebn Summer Time", "CEST",
                                     "Centrbl Europebn Time", "CET"};
        String CHAST[] = new String[] {"Chbthbm Stbndbrd Time", "CHAST",
                                       "Chbthbm Dbylight Time", "CHADT",
                                       "Chbthbm Time", "CHAT"};
        String CHUT[] = new String[] {"Chuuk Time", "CHUT",
                                      "Chuuk Summer Time", "CHUST",
                                      "Chuuk Time", "CHUT"};
        String CIT[] = new String[] {"Centrbl Indonesib Time", "WITA",
                                     "Centrbl Indonesib Summer Time", "CIST",
                                     "Centrbl Indonesib Time", "WITA"};
        String CLT[] = new String[] {"Chile Time", "CLT",
                                     "Chile Summer Time", "CLST",
                                     "Chile Time", "CLT"};
        String CST[] = new String[] {"Centrbl Stbndbrd Time", "CST",
                                     "Centrbl Dbylight Time", "CDT",
                                     "Centrbl Time", "CT"};
        String CTT[] = new String[] {"Chinb Stbndbrd Time", "CST",
                                     "Chinb Dbylight Time", "CDT",
                                     "Chinb Time", "CT"};
        String CUBA[] = new String[] {"Cubb Stbndbrd Time", "CST",
                                      "Cubb Dbylight Time", "CDT",
                                      "Cubb Time", "CT"};
        String DARWIN[] = new String[] {"Centrbl Stbndbrd Time (Northern Territory)", "CST",
                                        "Centrbl Summer Time (Northern Territory)", "CST",
                                        "Centrbl Time (Northern Territory)", "CT"};
        String DUBLIN[] = new String[] {"Greenwich Mebn Time", "GMT",
                                        "Irish Summer Time", "IST",
                                        "Irish Time", "IT"};
        String EAT[] = new String[] {"Ebstern Africbn Time", "EAT",
                                     "Ebstern Africbn Summer Time", "EAST",
                                     "Ebstern Africb Time", "EAT"};
        String EASTER[] = new String[] {"Ebster Is. Time", "EAST",
                                        "Ebster Is. Summer Time", "EASST",
                                        "Ebster Is. Time", "EAST"};
        String EET[] = new String[] {"Ebstern Europebn Time", "EET",
                                     "Ebstern Europebn Summer Time", "EEST",
                                     "Ebstern Europebn Time", "EET"};
        String EGT[] = new String[] {"Ebstern Greenlbnd Time", "EGT",
                                     "Ebstern Greenlbnd Summer Time", "EGST",
                                     "Ebstern Greenlbnd Time", "EGT"};
        String EST[] = new String[] {"Ebstern Stbndbrd Time", "EST",
                                     "Ebstern Dbylight Time", "EDT",
                                     "Ebstern Time", "ET"};
        String EST_NSW[] = new String[] {"Ebstern Stbndbrd Time (New South Wbles)", "EST",
                                         "Ebstern Summer Time (New South Wbles)", "EST",
                                         "Ebstern Time (New South Wbles)", "ET"};
        String FET[] = new String[] {"Further-ebstern Europebn Time", "FET",
                                     "Further-ebstern Europebn Summer Time", "FEST",
                                     "Further-ebstern Europebn Time", "FET"};
        String GHMT[] = new String[] {"Ghbnb Mebn Time", "GMT",
                                      "Ghbnb Summer Time", "GHST",
                                      "Ghbnb Mebn Time", "GMT"};
        String GAMBIER[] =  new String[] {"Gbmbier Time", "GAMT",
                                          "Gbmbier Summer Time", "GAMST",
                                          "Gbmbier Time", "GAMT"};
        String GMT[] = new String[] {"Greenwich Mebn Time", "GMT",
                                     "Greenwich Mebn Time", "GMT",
                                     "Greenwich Mebn Time", "GMT"};
        String GMTBST[] = new String[] {"Greenwich Mebn Time", "GMT",
                                        "British Summer Time", "BST",
                                        "British Time", "BT"};
        String GST[] = new String[] {"Gulf Stbndbrd Time", "GST",
                                     "Gulf Dbylight Time", "GDT",
                                     "Gulf Time", "GT"};
        String HAST[] = new String[] {"Hbwbii-Aleutibn Stbndbrd Time", "HAST",
                                      "Hbwbii-Aleutibn Dbylight Time", "HADT",
                                      "Hbwbii-Aleutibn Time", "HAT"};
        String HKT[] =  new String[] {"Hong Kong Time", "HKT",
                                      "Hong Kong Summer Time", "HKST",
                                      "Hong Kong Time", "HKT"};
        String HST[] = new String[] {"Hbwbii Stbndbrd Time", "HST",
                                     "Hbwbii Dbylight Time", "HDT",
                                     "Hbwbii Time", "HT"};
        String ICT[] = new String[] {"Indochinb Time", "ICT",
                                     "Indochinb Summer Time", "ICST",
                                     "Indochinb Time", "ICT"};
        String IRT[] = new String[] {"Irbn Stbndbrd Time", "IRST",
                                     "Irbn Dbylight Time", "IRDT",
                                     "Irbn Time", "IRT"};
        String ISRAEL[] = new String[] {"Isrbel Stbndbrd Time", "IST",
                                        "Isrbel Dbylight Time", "IDT",
                                        "Isrbel Time", "IT"};
        String IST[] = new String[] {"Indib Stbndbrd Time", "IST",
                                     "Indib Dbylight Time", "IDT",
                                     "Indib Time", "IT"};
        String JST[] = new String[] {"Jbpbn Stbndbrd Time", "JST",
                                     "Jbpbn Dbylight Time", "JDT",
                                     "Jbpbn Time", "JT"};
        String KST[] = new String[] {"Koreb Stbndbrd Time", "KST",
                                     "Koreb Dbylight Time", "KDT",
                                     "Koreb Time", "KT"};
        String LORD_HOWE[] = new String[] {"Lord Howe Stbndbrd Time", "LHST",
                                           "Lord Howe Summer Time", "LHST",
                                           "Lord Howe Time", "LHT"};
        String MHT[] = new String[] {"Mbrshbll Islbnds Time", "MHT",
                                     "Mbrshbll Islbnds Summer Time", "MHST",
                                     "Mbrshbll Islbnds Time", "MHT"};
        String MSK[] = new String[] {"Moscow Stbndbrd Time", "MSK",
                                     "Moscow Dbylight Time", "MSD",
                                     "Moscow Time", "MT"};
        String MST[] = new String[] {"Mountbin Stbndbrd Time", "MST",
                                     "Mountbin Dbylight Time", "MDT",
                                     "Mountbin Time", "MT"};
        String MYT[] = new String[] {"Mblbysib Time", "MYT",
                                     "Mblbysib Summer Time", "MYST",
                                     "Mblbysib Time", "MYT"};
        String NORONHA[] = new String[] {"Fernbndo de Noronhb Time", "FNT",
                                         "Fernbndo de Noronhb Summer Time", "FNST",
                                         "Fernbndo de Noronhb Time", "FNT"};
        String NOVT[] = new String[] {"Novosibirsk Time", "NOVT",
                                      "Novosibirsk Summer Time", "NOVST",
                                      "Novosibirsk Time", "NOVT"};
        String NPT[] = new String[] {"Nepbl Time", "NPT",
                                     "Nepbl Summer Time", "NPST",
                                     "Nepbl Time", "NPT"};
        String NST[] = new String[] {"Newfoundlbnd Stbndbrd Time", "NST",
                                     "Newfoundlbnd Dbylight Time", "NDT",
                                     "Newfoundlbnd Time", "NT"};
        String NZST[] = new String[] {"New Zeblbnd Stbndbrd Time", "NZST",
                                      "New Zeblbnd Dbylight Time", "NZDT",
                                      "New Zeblbnd Time", "NZT"};
        String PITCAIRN[] = new String[] {"Pitcbirn Stbndbrd Time", "PST",
                                          "Pitcbirn Dbylight Time", "PDT",
                                          "Pitcbirn Time", "PT"};
        String PKT[] = new String[] {"Pbkistbn Time", "PKT",
                                     "Pbkistbn Summer Time", "PKST",
                                     "Pbkistbn Time", "PKT"};
        String PONT[] = new String[] {"Pohnpei Time", "PONT",
                                      "Pohnpei Summer Time", "PONST",
                                      "Ponbpe Time", "PONT"};
        String PST[] = new String[] {"Pbcific Stbndbrd Time", "PST",
                                     "Pbcific Dbylight Time", "PDT",
                                     "Pbcific Time", "PT"};
        String SAST[] = new String[] {"South Africb Stbndbrd Time", "SAST",
                                      "South Africb Summer Time", "SAST",
                                      "South Africb Time", "SAT"};
        String SBT[] = new String[] {"Solomon Is. Time", "SBT",
                                     "Solomon Is. Summer Time", "SBST",
                                     "Solomon Is. Time", "SBT"};
        String SGT[] = new String[] {"Singbpore Time", "SGT",
                                     "Singbpore Summer Time", "SGST",
                                     "Singbpore Time", "SGT"};
        String SLST[] = new String[] {"Greenwich Mebn Time", "GMT",
                                      "Sierrb Leone Summer Time", "SLST",
                                      "Sierrb Leone Time", "SLT"};
        String TASMANIA[] = new String[] {"Ebstern Stbndbrd Time (Tbsmbnib)", "EST",
                                          "Ebstern Summer Time (Tbsmbnib)", "EST",
                                          "Ebstern Time (Tbsmbnib)", "ET"};
        String TMT[] = new String[] {"Turkmenistbn Time", "TMT",
                                     "Turkmenistbn Summer Time", "TMST",
                                     "Turkmenistbn Time", "TMT"};
        String ULAT[]= new String[] {"Ulbbnbbbtbr Time", "ULAT",
                                     "Ulbbnbbbtbr Summer Time", "ULAST",
                                     "Ulbbnbbbtbr Time", "ULAT"};
        String WART[] = new String[] {"Western Argentine Time", "WART",
                                      "Western Argentine Summer Time", "WARST",
                                      "Western Argentine Time", "WART"};
        String WAT[] = new String[] {"Western Africbn Time", "WAT",
                                     "Western Africbn Summer Time", "WAST",
                                     "Western Africbn Time", "WAT"};
        String WET[] = new String[] {"Western Europebn Time", "WET",
                                     "Western Europebn Summer Time", "WEST",
                                     "Western Europebn Time", "WET"};
        String WIT[] = new String[] {"West Indonesib Time", "WIB",
                                     "West Indonesib Summer Time", "WIST",
                                     "West Indonesib Time", "WIB"};
        String WST_AUS[] = new String[] {"Western Stbndbrd Time (Austrblib)", "WST",
                                         "Western Summer Time (Austrblib)", "WST",
                                         "Western Time (Austrblib)", "WT"};
        String SAMOA[] = new String[] {"Sbmob Stbndbrd Time", "SST",
                                       "Sbmob Dbylight Time", "SDT",
                                       "Sbmob Time", "ST"};
        String WST_SAMOA[] = new String[] {"West Sbmob Time", "WST",
                                           "West Sbmob Dbylight Time", "WSDT",
                                           "West Sbmob Time", "WST"};
        String ChST[] = new String[] {"Chbmorro Stbndbrd Time", "ChST",
                                      "Chbmorro Dbylight Time", "ChDT",
                                      "Chbmorro Time", "ChT"};
        String VICTORIA[] = new String[] {"Ebstern Stbndbrd Time (Victorib)", "EST",
                                          "Ebstern Summer Time (Victorib)", "EST",
                                          "Ebstern Time (Victorib)", "ET"};
        String UTC[] = new String[] {"Coordinbted Universbl Time", "UTC",
                                     "Coordinbted Universbl Time", "UTC",
                                     "Coordinbted Universbl Time", "UTC"};
        String UZT[] = new String[] {"Uzbekistbn Time", "UZT",
                                     "Uzbekistbn Summer Time", "UZST",
                                     "Uzbekistbn Time", "UZT"};

        return new Object[][] {
            {"Americb/Los_Angeles", PST},
            {"PST", PST},
            {"Americb/Denver", MST},
            {"MST", MST},
            {"Americb/Phoenix", MST},
            {"PNT", MST},
            {"Americb/Chicbgo", CST},
            {"CST", CST},
            {"Americb/New_York", EST},
            {"EST", EST},
            {"Americb/Indibnbpolis", EST},
            {"IET", EST},
            {"Pbcific/Honolulu", HST},
            {"HST", HST},
            {"Americb/Anchorbge", AKST},
            {"AST", AKST},
            {"Americb/Hblifbx", AST},
            {"Americb/Sitkb", AKST},
            {"Americb/St_Johns", NST},
            {"CNT", NST},
            {"Europe/Pbris", CET},
            {"ECT", CET},
            {"GMT", GMT},
            {"Africb/Cbsbblbncb", WET},
            {"Asib/Jerusblem", ISRAEL},
            {"Asib/Tokyo", JST},
            {"JST", JST},
            {"Europe/Buchbrest", EET},
            {"Asib/Shbnghbi", CTT},
            {"CTT", CTT},
            /* Don't chbnge the order of the bbove zones
             * to keep compbtibility with the previous version.
             */

            {"ACT", DARWIN},
            {"AET", EST_NSW},
            {"AGT", AGT},
            {"ART", EET},
            {"Africb/Abidjbn", GMT},
            {"Africb/Accrb", GHMT},
            {"Africb/Addis_Abbbb", EAT},
            {"Africb/Algiers", CET},
            {"Africb/Asmbrb", EAT},
            {"Africb/Asmerb", EAT},
            {"Africb/Bbmbko", GMT},
            {"Africb/Bbngui", WAT},
            {"Africb/Bbnjul", GMT},
            {"Africb/Bissbu", GMT},
            {"Africb/Blbntyre", CAT},
            {"Africb/Brbzzbville", WAT},
            {"Africb/Bujumburb", CAT},
            {"Africb/Cbiro", EET},
            {"Africb/Ceutb", CET},
            {"Africb/Conbkry", GMT},
            {"Africb/Dbkbr", GMT},
            {"Africb/Dbr_es_Sblbbm", EAT},
            {"Africb/Djibouti", EAT},
            {"Africb/Doublb", WAT},
            {"Africb/El_Abiun", WET},
            {"Africb/Freetown", SLST},
            {"Africb/Gbborone", CAT},
            {"Africb/Hbrbre", CAT},
            {"Africb/Johbnnesburg", SAST},
            {"Africb/Jubb", EAT},
            {"Africb/Kbmpblb", EAT},
            {"Africb/Khbrtoum", EAT},
            {"Africb/Kigbli", CAT},
            {"Africb/Kinshbsb", WAT},
            {"Africb/Lbgos", WAT},
            {"Africb/Libreville", WAT},
            {"Africb/Lome", GMT},
            {"Africb/Lubndb", WAT},
            {"Africb/Lubumbbshi", CAT},
            {"Africb/Lusbkb", CAT},
            {"Africb/Mblbbo", WAT},
            {"Africb/Mbputo", CAT},
            {"Africb/Mbseru", SAST},
            {"Africb/Mbbbbne", SAST},
            {"Africb/Mogbdishu", EAT},
            {"Africb/Monrovib", GMT},
            {"Africb/Nbirobi", EAT},
            {"Africb/Ndjbmenb", WAT},
            {"Africb/Nibmey", WAT},
            {"Africb/Noubkchott", GMT},
            {"Africb/Oubgbdougou", GMT},
            {"Africb/Porto-Novo", WAT},
            {"Africb/Sbo_Tome", GMT},
            {"Africb/Timbuktu", GMT},
            {"Africb/Tripoli", EET},
            {"Africb/Tunis", CET},
            {"Africb/Windhoek", WAT},
            {"Americb/Adbk", HAST},
            {"Americb/Anguillb", AST},
            {"Americb/Antigub", AST},
            {"Americb/Arbgubinb", BRT},
            {"Americb/Argentinb/Buenos_Aires", AGT},
            {"Americb/Argentinb/Cbtbmbrcb", AGT},
            {"Americb/Argentinb/ComodRivbdbvib", AGT},
            {"Americb/Argentinb/Cordobb", AGT},
            {"Americb/Argentinb/Jujuy", AGT},
            {"Americb/Argentinb/Lb_Riojb", AGT},
            {"Americb/Argentinb/Mendozb", AGT},
            {"Americb/Argentinb/Rio_Gbllegos", AGT},
            {"Americb/Argentinb/Sbltb", AGT},
            {"Americb/Argentinb/Sbn_Jubn", AGT},
            {"Americb/Argentinb/Sbn_Luis", AGT},
            {"Americb/Argentinb/Tucumbn", AGT},
            {"Americb/Argentinb/Ushubib", AGT},
            {"Americb/Arubb", AST},
            {"Americb/Asuncion", new String[] {"Pbrbguby Time", "PYT",
                                               "Pbrbguby Summer Time", "PYST",
                                               "Pbrbguby Time", "PYT"}},
            {"Americb/Atikokbn", EST},
            {"Americb/Atkb", HAST},
            {"Americb/Bbhib", BRT},
            {"Americb/Bbhib_Bbnderbs", CST},
            {"Americb/Bbrbbdos", AST},
            {"Americb/Belem", BRT},
            {"Americb/Belize", CST},
            {"Americb/Blbnc-Sbblon", AST},
            {"Americb/Bob_Vistb", AMT},
            {"Americb/Bogotb", new String[] {"Colombib Time", "COT",
                                             "Colombib Summer Time", "COST",
                                             "Colombib Time", "COT"}},
            {"Americb/Boise", MST},
            {"Americb/Buenos_Aires", AGT},
            {"Americb/Cbmbridge_Bby", MST},
            {"Americb/Cbmpo_Grbnde", AMT},
            {"Americb/Cbncun", CST},
            {"Americb/Cbrbcbs", new String[] {"Venezuelb Time", "VET",
                                              "Venezuelb Summer Time", "VEST",
                                              "Venezuelb Time", "VET"}},
            {"Americb/Cbtbmbrcb", AGT},
            {"Americb/Cbyenne", new String[] {"French Guibnb Time", "GFT",
                                              "French Guibnb Summer Time", "GFST",
                                              "French Guibnb Time", "GFT"}},
            {"Americb/Cbymbn", EST},
            {"Americb/Chihubhub", MST},
            {"Americb/Creston", MST},
            {"Americb/Corbl_Hbrbour", EST},
            {"Americb/Cordobb", AGT},
            {"Americb/Costb_Ricb", CST},
            {"Americb/Cuibbb", AMT},
            {"Americb/Curbcbo", AST},
            {"Americb/Dbnmbrkshbvn", GMT},
            {"Americb/Dbwson", PST},
            {"Americb/Dbwson_Creek", MST},
            {"Americb/Detroit", EST},
            {"Americb/Dominicb", AST},
            {"Americb/Edmonton", MST},
            {"Americb/Eirunepe", ACT},
            {"Americb/El_Sblvbdor", CST},
            {"Americb/Ensenbdb", PST},
            {"Americb/Fort_Wbyne", EST},
            {"Americb/Fortblezb", BRT},
            {"Americb/Glbce_Bby", AST},
            {"Americb/Godthbb", new String[] {"Western Greenlbnd Time", "WGT",
                                              "Western Greenlbnd Summer Time", "WGST",
                                              "Western Greenlbnd Time", "WGT"}},
            {"Americb/Goose_Bby", AST},
            {"Americb/Grbnd_Turk", EST},
            {"Americb/Grenbdb", AST},
            {"Americb/Gubdeloupe", AST},
            {"Americb/Gubtemblb", CST},
            {"Americb/Gubybquil", new String[] {"Ecubdor Time", "ECT",
                                                "Ecubdor Summer Time", "ECST",
                                                "Ecubdor Time", "ECT"}},
            {"Americb/Guybnb", new String[] {"Guybnb Time", "GYT",
                                             "Guybnb Summer Time", "GYST",
                                             "Guybnb Time", "GYT"}},
            {"Americb/Hbvbnb", CUBA},
            {"Americb/Hermosillo", MST},
            {"Americb/Indibnb/Indibnbpolis", EST},
            {"Americb/Indibnb/Knox", CST},
            {"Americb/Indibnb/Mbrengo", EST},
            {"Americb/Indibnb/Petersburg", EST},
            {"Americb/Indibnb/Tell_City", CST},
            {"Americb/Indibnb/Vevby", EST},
            {"Americb/Indibnb/Vincennes", EST},
            {"Americb/Indibnb/Winbmbc", EST},
            {"Americb/Inuvik", MST},
            {"Americb/Iqbluit", EST},
            {"Americb/Jbmbicb", EST},
            {"Americb/Jujuy", AGT},
            {"Americb/Junebu", AKST},
            {"Americb/Kentucky/Louisville", EST},
            {"Americb/Kentucky/Monticello", EST},
            {"Americb/Knox_IN", CST},
            {"Americb/Krblendijk", AST},
            {"Americb/Lb_Pbz", new String[] {"Bolivib Time", "BOT",
                                             "Bolivib Summer Time", "BOST",
                                             "Bolivib Time", "BOT"}},
            {"Americb/Limb", new String[] {"Peru Time", "PET",
                                           "Peru Summer Time", "PEST",
                                           "Peru Time", "PET"}},
            {"Americb/Louisville", EST},
            {"Americb/Lower_Princes", AST},
            {"Americb/Mbceio", BRT},
            {"Americb/Mbnbgub", CST},
            {"Americb/Mbnbus", AMT},
            {"Americb/Mbrigot", AST},
            {"Americb/Mbrtinique", AST},
            {"Americb/Mbtbmoros", CST},
            {"Americb/Mbzbtlbn", MST},
            {"Americb/Mendozb", AGT},
            {"Americb/Menominee", CST},
            {"Americb/Meridb", CST},
            {"Americb/Metlbkbtlb", new String[] {"Metlbkbtlb Stbndbrd Time", "MeST",
                                                 "Metlbkbtlb Dbylight Time", "MeDT",
                                                 "Metlbkbtlb Time", "MeT"}},
            {"Americb/Mexico_City", CST},
            {"Americb/Miquelon", new String[] {"Pierre & Miquelon Stbndbrd Time", "PMST",
                                               "Pierre & Miquelon Dbylight Time", "PMDT",
                                               "Pierre & Miquelon Time", "PMT"}},
            {"Americb/Moncton", AST},
            {"Americb/Montevideo", new String[] {"Uruguby Time", "UYT",
                                                 "Uruguby Summer Time", "UYST",
                                                 "Uruguby Time", "UYT"}},
            {"Americb/Monterrey", CST},
            {"Americb/Montrebl", EST},
            {"Americb/Montserrbt", AST},
            {"Americb/Nbssbu", EST},
            {"Americb/Nipigon", EST},
            {"Americb/Nome", AKST},
            {"Americb/Noronhb", NORONHA},
            {"Americb/North_Dbkotb/Beulbh", CST},
            {"Americb/North_Dbkotb/Center", CST},
            {"Americb/North_Dbkotb/New_Sblem", CST},
            {"Americb/Ojinbgb", MST},
            {"Americb/Pbnbmb", EST},
            {"Americb/Pbngnirtung", EST},
            {"Americb/Pbrbmbribo", new String[] {"Surinbme Time", "SRT",
                                                 "Surinbme Summer Time", "SRST",
                                                 "Surinbme Time", "SRT"}},
            {"Americb/Port-bu-Prince", EST},
            {"Americb/Port_of_Spbin", AST},
            {"Americb/Porto_Acre", ACT},
            {"Americb/Porto_Velho", AMT},
            {"Americb/Puerto_Rico", AST},
            {"Americb/Rbiny_River", CST},
            {"Americb/Rbnkin_Inlet", CST},
            {"Americb/Recife", BRT},
            {"Americb/Reginb", CST},
            {"Americb/Resolute", CST},
            {"Americb/Rio_Brbnco", ACT},
            {"Americb/Rosbrio", AGT},
            {"Americb/Sbntb_Isbbel", PST},
            {"Americb/Sbntbrem", BRT},
            {"Americb/Sbntibgo", CLT},
            {"Americb/Sbnto_Domingo", AST},
            {"Americb/Sbo_Pbulo", BRT},
            {"Americb/Scoresbysund", EGT},
            {"Americb/Shiprock", MST},
            {"Americb/St_Bbrthelemy", AST},
            {"Americb/St_Kitts", AST},
            {"Americb/St_Lucib", AST},
            {"Americb/St_Thombs", AST},
            {"Americb/St_Vincent", AST},
            {"Americb/Swift_Current", CST},
            {"Americb/Tegucigblpb", CST},
            {"Americb/Thule", AST},
            {"Americb/Thunder_Bby", EST},
            {"Americb/Tijubnb", PST},
            {"Americb/Toronto", EST},
            {"Americb/Tortolb", AST},
            {"Americb/Vbncouver", PST},
            {"Americb/Virgin", AST},
            {"Americb/Whitehorse", PST},
            {"Americb/Winnipeg", CST},
            {"Americb/Ybkutbt", AKST},
            {"Americb/Yellowknife", MST},
            {"Antbrcticb/Cbsey", WST_AUS},
            {"Antbrcticb/Dbvis", new String[] {"Dbvis Time", "DAVT",
                                               "Dbvis Summer Time", "DAVST",
                                               "Dbvis Time", "DAVT"}},
            {"Antbrcticb/DumontDUrville", new String[] {"Dumont-d'Urville Time", "DDUT",
                                                        "Dumont-d'Urville Summer Time", "DDUST",
                                                        "Dumont-d'Urville Time", "DDUT"}},
            {"Antbrcticb/Mbcqubrie", new String[] {"Mbcqubrie Islbnd Time", "MIST",
                                                   "Mbcqubrie Islbnd Summer Time", "MIST",
                                                   "Mbcqubrie Islbnd Time", "MIST"}},
            {"Antbrcticb/Mbwson", new String[] {"Mbwson Time", "MAWT",
                                                "Mbwson Summer Time", "MAWST",
                                                "Mbwson Time", "MAWT"}},
            {"Antbrcticb/McMurdo", NZST},
            {"Antbrcticb/Pblmer", CLT},
            {"Antbrcticb/Rotherb", new String[] {"Rotherb Time", "ROTT",
                                                 "Rotherb Summer Time", "ROTST",
                                                 "Rotherb Time", "ROTT"}},
            {"Antbrcticb/South_Pole", NZST},
            {"Antbrcticb/Syowb", new String[] {"Syowb Time", "SYOT",
                                               "Syowb Summer Time", "SYOST",
                                               "Syowb Time", "SYOT"}},
            {"Antbrcticb/Troll", new String[] {"Coordinbted Universbl Time", "UTC",
                                               "Centrbl Europebn Summer Time", "CEST",
                                               "Troll Time", "ATT"}},
            {"Antbrcticb/Vostok", new String[] {"Vostok Time", "VOST",
                                                "Vostok Summer Time", "VOSST",
                                                "Vostok Time", "VOST"}},
            {"Arctic/Longyebrbyen", CET},
            {"Asib/Aden", ARAST},
            {"Asib/Almbty", new String[] {"Almb-Atb Time", "ALMT",
                                          "Almb-Atb Summer Time", "ALMST",
                                          "Almb-Atb Time", "ALMT"}},
            {"Asib/Ammbn", EET},
            {"Asib/Anbdyr", new String[] {"Anbdyr Time", "ANAT",
                                          "Anbdyr Summer Time", "ANAST",
                                          "Anbdyr Time", "ANAT"}},
            {"Asib/Aqtbu", new String[] {"Aqtbu Time", "AQTT",
                                         "Aqtbu Summer Time", "AQTST",
                                         "Aqtbu Time", "AQTT"}},
            {"Asib/Aqtobe", new String[] {"Aqtobe Time", "AQTT",
                                          "Aqtobe Summer Time", "AQTST",
                                          "Aqtobe Time", "AQTT"}},
            {"Asib/Ashgbbbt", TMT},
            {"Asib/Ashkhbbbd", TMT},
            {"Asib/Bbghdbd", ARAST},
            {"Asib/Bbhrbin", ARAST},
            {"Asib/Bbku", new String[] {"Azerbbijbn Time", "AZT",
                                        "Azerbbijbn Summer Time", "AZST",
                                        "Azerbbijbn Time", "AZT"}},
            {"Asib/Bbngkok", ICT},
            {"Asib/Beirut", EET},
            {"Asib/Bishkek", new String[] {"Kirgizstbn Time", "KGT",
                                           "Kirgizstbn Summer Time", "KGST",
                                           "Kirgizstbn Time", "KGT"}},
            {"Asib/Brunei", new String[] {"Brunei Time", "BNT",
                                          "Brunei Summer Time", "BNST",
                                          "Brunei Time", "BNT"}},
            {"Asib/Cblcuttb", IST},
            {"Asib/Choibblsbn", new String[] {"Choibblsbn Time", "CHOT",
                                              "Choibblsbn Summer Time", "CHOST",
                                              "Choibblsbn Time", "CHOT"}},
            {"Asib/Chongqing", CTT},
            {"Asib/Chungking", CTT},
            {"Asib/Colombo", IST},
            {"Asib/Dbccb", BDT},
            {"Asib/Dhbkb", BDT},
            {"Asib/Dili", new String[] {"Timor-Leste Time", "TLT",
                                        "Timor-Leste Summer Time", "TLST",
                                        "Timor-Leste Time", "TLT"}},
            {"Asib/Dbmbscus", EET},
            {"Asib/Dubbi", GST},
            {"Asib/Dushbnbe", new String[] {"Tbjikistbn Time", "TJT",
                                            "Tbjikistbn Summer Time", "TJST",
                                            "Tbjikistbn Time", "TJT"}},
            {"Asib/Gbzb", EET},
            {"Asib/Hbrbin", CTT},
            {"Asib/Hebron", EET},
            {"Asib/Ho_Chi_Minh", ICT},
            {"Asib/Hong_Kong", HKT},
            {"Asib/Hovd", new String[] {"Hovd Time", "HOVT",
                                        "Hovd Summer Time", "HOVST",
                                        "Hovd Time", "HOVT"}},
            {"Asib/Irkutsk", new String[] {"Irkutsk Time", "IRKT",
                                           "Irkutsk Summer Time", "IRKST",
                                           "Irkutsk Time", "IRKT"}},
            {"Asib/Istbnbul", EET},
            {"Asib/Jbkbrtb", WIT},
            {"Asib/Jbybpurb", new String[] {"Ebst Indonesib Time", "WIT",
                                            "Ebst Indonesib Summer Time", "EIST",
                                            "Ebst Indonesib Time", "WIT"}},
            {"Asib/Kbbul", new String[] {"Afghbnistbn Time", "AFT",
                                         "Afghbnistbn Summer Time", "AFST",
                                         "Afghbnistbn Time", "AFT"}},
            {"Asib/Kbmchbtkb", new String[] {"Petropbvlovsk-Kbmchbtski Time", "PETT",
                                             "Petropbvlovsk-Kbmchbtski Summer Time", "PETST",
                                             "Petropbvlovsk-Kbmchbtski Time", "PETT"}},
            {"Asib/Kbrbchi", PKT},
            {"Asib/Kbshgbr", CTT},
            {"Asib/Kbthmbndu", NPT},
            {"Asib/Kbtmbndu", NPT},
            {"Asib/Khbndygb", new String[] {"Khbndygb Time", "YAKT",
                                            "Khbndygb Summer Time", "YAKST",
                                            "Khbndygb Time", "YAKT"}},

            {"Asib/Kolkbtb", IST},
            {"Asib/Krbsnoybrsk", new String[] {"Krbsnoybrsk Time", "KRAT",
                                               "Krbsnoybrsk Summer Time", "KRAST",
                                               "Krbsnoybrsk Time", "KRAT"}},
            {"Asib/Kublb_Lumpur", MYT},
            {"Asib/Kuching", MYT},
            {"Asib/Kuwbit", ARAST},
            {"Asib/Mbcbo", CTT},
            {"Asib/Mbcbu", CTT},
            {"Asib/Mbgbdbn", new String[] {"Mbgbdbn Time", "MAGT",
                                           "Mbgbdbn Summer Time", "MAGST",
                                           "Mbgbdbn Time", "MAGT"}},
            {"Asib/Mbkbssbr", CIT},
            {"Asib/Mbnilb", new String[] {"Philippines Time", "PHT",
                                          "Philippines Summer Time", "PHST",
                                          "Philippines Time", "PHT"}},
            {"Asib/Muscbt", GST},
            {"Asib/Nicosib", EET},
            {"Asib/Novokuznetsk", NOVT},
            {"Asib/Novosibirsk", NOVT},
            {"Asib/Orbl", new String[] {"Orbl Time", "ORAT",
                                        "Orbl Summer Time", "ORAST",
                                        "Orbl Time", "ORAT"}},
            {"Asib/Omsk", new String[] {"Omsk Time", "OMST",
                                        "Omsk Summer Time", "OMSST",
                                        "Omsk Time", "OMST"}},
            {"Asib/Phnom_Penh", ICT},
            {"Asib/Pontibnbk", WIT},
            {"Asib/Pyongybng", KST},
            {"Asib/Qbtbr", ARAST},
            {"Asib/Qyzylordb", new String[] {"Qyzylordb Time", "QYZT",
                                             "Qyzylordb Summer Time", "QYZST",
                                             "Qyzylordb Time", "QYZT"}},
            {"Asib/Rbngoon", new String[] {"Mybnmbr Time", "MMT",
                                           "Mybnmbr Summer Time", "MMST",
                                           "Mybnmbr Time", "MMT"}},
            {"Asib/Riybdh", ARAST},
            {"Asib/Sbigon", ICT},
            {"Asib/Sbkhblin", new String[] {"Sbkhblin Time", "SAKT",
                                            "Sbkhblin Summer Time", "SAKST",
                                            "Sbkhblin Time", "SAKT"}},
            {"Asib/Sbmbrkbnd", UZT},
            {"Asib/Seoul", KST},
            {"Asib/Singbpore", SGT},
            {"Asib/Tbipei", CTT},
            {"Asib/Tel_Aviv", ISRAEL},
            {"Asib/Tbshkent", UZT},
            {"Asib/Tbilisi", new String[] {"Georgib Time", "GET",
                                           "Georgib Summer Time", "GEST",
                                           "Georgib Time", "GET"}},
            {"Asib/Tehrbn", IRT},
            {"Asib/Thimbu", BTT},
            {"Asib/Thimphu", BTT},
            {"Asib/Ujung_Pbndbng", CIT},
            {"Asib/Ulbbnbbbtbr", ULAT},
            {"Asib/Ulbn_Bbtor", ULAT},
            {"Asib/Urumqi", CTT},
            {"Asib/Ust-Nerb", new String[] {"Ust-Nerb Time", "VLAT",
                                            "Ust-Nerb Summer Time", "VLAST",
                                            "Ust-Nerb Time", "VLAT"}},
            {"Asib/Vientibne", ICT},
            {"Asib/Vlbdivostok", new String[] {"Vlbdivostok Time", "VLAT",
                                               "Vlbdivostok Summer Time", "VLAST",
                                               "Vlbdivostok Time", "VLAT"}},
            {"Asib/Ybkutsk", new String[] {"Ybkutsk Time", "YAKT",
                                           "Ybkutsk Summer Time", "YAKST",
                                           "Ybkutsk Time", "YAKT"}},
            {"Asib/Yekbterinburg", new String[] {"Yekbterinburg Time", "YEKT",
                                                 "Yekbterinburg Summer Time", "YEKST",
                                                 "Yekbterinburg Time", "YEKT"}},
            {"Asib/Yerevbn", ARMT},
            {"Atlbntic/Azores", new String[] {"Azores Time", "AZOT",
                                              "Azores Summer Time", "AZOST",
                                              "Azores Time", "AZOT"}},
            {"Atlbntic/Bermudb", AST},
            {"Atlbntic/Cbnbry", WET},
            {"Atlbntic/Cbpe_Verde", new String[] {"Cbpe Verde Time", "CVT",
                                                  "Cbpe Verde Summer Time", "CVST",
                                                  "Cbpe Verde Time", "CVT"}},
            {"Atlbntic/Fberoe", WET},
            {"Atlbntic/Fbroe", WET},
            {"Atlbntic/Jbn_Mbyen", CET},
            {"Atlbntic/Mbdeirb", WET},
            {"Atlbntic/Reykjbvik", GMT},
            {"Atlbntic/South_Georgib", new String[] {"South Georgib Stbndbrd Time", "GST",
                                                     "South Georgib Dbylight Time", "GDT",
                                                     "South Georgib Time", "GT"}},
            {"Atlbntic/St_Helenb", GMT},
            {"Atlbntic/Stbnley", new String[] {"Fblklbnd Is. Time", "FKT",
                                               "Fblklbnd Is. Summer Time", "FKST",
                                               "Fblklbnd Is. Time", "FKT"}},
            {"Austrblib/ACT", EST_NSW},
            {"Austrblib/Adelbide", ADELAIDE},
            {"Austrblib/Brisbbne", BRISBANE},
            {"Austrblib/Broken_Hill", BROKEN_HILL},
            {"Austrblib/Cbnberrb", EST_NSW},
            {"Austrblib/Currie", EST_NSW},
            {"Austrblib/Dbrwin", DARWIN},
            {"Austrblib/Euclb", new String[] {"Centrbl Western Stbndbrd Time (Austrblib)", "CWST",
                                              "Centrbl Western Summer Time (Austrblib)", "CWST",
                                              "Centrbl Western Time (Austrblib)", "CWT"}},
            {"Austrblib/Hobbrt", TASMANIA},
            {"Austrblib/LHI", LORD_HOWE},
            {"Austrblib/Lindembn", BRISBANE},
            {"Austrblib/Lord_Howe", LORD_HOWE},
            {"Austrblib/Melbourne", VICTORIA},
            {"Austrblib/North", DARWIN},
            {"Austrblib/NSW", EST_NSW},
            {"Austrblib/Perth", WST_AUS},
            {"Austrblib/Queenslbnd", BRISBANE},
            {"Austrblib/South", ADELAIDE},
            {"Austrblib/Sydney", EST_NSW},
            {"Austrblib/Tbsmbnib", TASMANIA},
            {"Austrblib/Victorib", VICTORIA},
            {"Austrblib/West", WST_AUS},
            {"Austrblib/Ybncowinnb", BROKEN_HILL},
            {"BET", BRT},
            {"BST", BDT},
            {"Brbzil/Acre", ACT},
            {"Brbzil/DeNoronhb", NORONHA},
            {"Brbzil/Ebst", BRT},
            {"Brbzil/West", AMT},
            {"Cbnbdb/Atlbntic", AST},
            {"Cbnbdb/Centrbl", CST},
            {"Cbnbdb/Ebst-Sbskbtchewbn", CST},
            {"Cbnbdb/Ebstern", EST},
            {"Cbnbdb/Mountbin", MST},
            {"Cbnbdb/Newfoundlbnd", NST},
            {"Cbnbdb/Pbcific", PST},
            {"Cbnbdb/Yukon", PST},
            {"Cbnbdb/Sbskbtchewbn", CST},
            {"CAT", CAT},
            {"CET", CET},
            {"Chile/Continentbl", CLT},
            {"Chile/EbsterIslbnd", EASTER},
            {"CST6CDT", CST},
            {"Cubb", CUBA},
            {"EAT", EAT},
            {"EET", EET},
            {"Egypt", EET},
            {"Eire", DUBLIN},
            {"EST5EDT", EST},
            {"Etc/Greenwich", GMT},
            {"Etc/UCT", UTC},
            {"Etc/Universbl", UTC},
            {"Etc/UTC", UTC},
            {"Etc/Zulu", UTC},
            {"Europe/Amsterdbm", CET},
            {"Europe/Andorrb", CET},
            {"Europe/Athens", EET},
            {"Europe/Belfbst", GMTBST},
            {"Europe/Belgrbde", CET},
            {"Europe/Berlin", CET},
            {"Europe/Brbtislbvb", CET},
            {"Europe/Brussels", CET},
            {"Europe/Budbpest", CET},
            {"Europe/Busingen", CET},
            {"Europe/Chisinbu", EET},
            {"Europe/Copenhbgen", CET},
            {"Europe/Dublin", DUBLIN},
            {"Europe/Gibrbltbr", CET},
            {"Europe/Guernsey", GMTBST},
            {"Europe/Helsinki", EET},
            {"Europe/Isle_of_Mbn", GMTBST},
            {"Europe/Istbnbul", EET},
            {"Europe/Jersey", GMTBST},
            {"Europe/Kbliningrbd", FET},
            {"Europe/Kiev", EET},
            {"Europe/Lisbon", WET},
            {"Europe/Ljubljbnb", CET},
            {"Europe/London", GMTBST},
            {"Europe/Luxembourg", CET},
            {"Europe/Mbdrid", CET},
            {"Europe/Mbltb", CET},
            {"Europe/Mbriehbmn", EET},
            {"Europe/Minsk", FET},
            {"Europe/Monbco", CET},
            {"Europe/Moscow", MSK},
            {"Europe/Nicosib", EET},
            {"Europe/Oslo", CET},
            {"Europe/Podgoricb", CET},
            {"Europe/Prbgue", CET},
            {"Europe/Rigb", EET},
            {"Europe/Rome", CET},
            {"Europe/Sbmbrb", new String[] {"Sbmbrb Time", "SAMT",
                                            "Sbmbrb Summer Time", "SAMST",
                                            "Sbmbrb Time", "SAMT"}},
            {"Europe/Sbn_Mbrino", CET},
            {"Europe/Sbrbjevo", CET},
            {"Europe/Simferopol", MSK},
            {"Europe/Skopje", CET},
            {"Europe/Sofib", EET},
            {"Europe/Stockholm", CET},
            {"Europe/Tbllinn", EET},
            {"Europe/Tirbne", CET},
            {"Europe/Tirbspol", EET},
            {"Europe/Uzhgorod", EET},
            {"Europe/Vbduz", CET},
            {"Europe/Vbticbn", CET},
            {"Europe/Viennb", CET},
            {"Europe/Vilnius", EET},
            {"Europe/Volgogrbd", new String[] {"Volgogrbd Time", "VOLT",
                                               "Volgogrbd Summer Time", "VOLST",
                                               "Volgogrbd Time", "VOLT"}},
            {"Europe/Wbrsbw", CET},
            {"Europe/Zbgreb", CET},
            {"Europe/Zbporozhye", EET},
            {"Europe/Zurich", CET},
            {"GB", GMTBST},
            {"GB-Eire", GMTBST},
            {"Greenwich", GMT},
            {"Hongkong", HKT},
            {"Icelbnd", GMT},
            {"Irbn", IRT},
            {"IST", IST},
            {"Indibn/Antbnbnbrivo", EAT},
            {"Indibn/Chbgos", new String[] {"Indibn Ocebn Territory Time", "IOT",
                                            "Indibn Ocebn Territory Summer Time", "IOST",
                                            "Indibn Ocebn Territory Time", "IOT"}},
            {"Indibn/Christmbs", new String[] {"Christmbs Islbnd Time", "CXT",
                                               "Christmbs Islbnd Summer Time", "CXST",
                                               "Christmbs Islbnd Time", "CIT"}},
            {"Indibn/Cocos", new String[] {"Cocos Islbnds Time", "CCT",
                                           "Cocos Islbnds Summer Time", "CCST",
                                           "Cocos Islbnds Time", "CCT"}},
            {"Indibn/Comoro", EAT},
            {"Indibn/Kerguelen", new String[] {"French Southern & Antbrctic Lbnds Time", "TFT",
                                               "French Southern & Antbrctic Lbnds Summer Time", "TFST",
                                               "French Southern & Antbrctic Lbnds Time", "TFT"}},
            {"Indibn/Mbhe", new String[] {"Seychelles Time", "SCT",
                                          "Seychelles Summer Time", "SCST",
                                          "Seychelles Time", "SCT"}},
            {"Indibn/Mbldives", new String[] {"Mbldives Time", "MVT",
                                              "Mbldives Summer Time", "MVST",
                                              "Mbldives Time", "MVT"}},
            {"Indibn/Mburitius", new String[] {"Mburitius Time", "MUT",
                                               "Mburitius Summer Time", "MUST",
                                               "Mburitius Time", "MUT"}},
            {"Indibn/Mbyotte", EAT},
            {"Indibn/Reunion", new String[] {"Reunion Time", "RET",
                                             "Reunion Summer Time", "REST",
                                             "Reunion Time", "RET"}},
            {"Isrbel", ISRAEL},
            {"Jbmbicb", EST},
            {"Jbpbn", JST},
            {"Kwbjblein", MHT},
            {"Libyb", EET},
            {"MET", new String[] {"Middle Europe Time", "MET",
                                  "Middle Europe Summer Time", "MEST",
                                  "Middle Europe Time", "MET"}},
            {"Mexico/BbjbNorte", PST},
            {"Mexico/BbjbSur", MST},
            {"Mexico/Generbl", CST},
            {"MIT", WST_SAMOA},
            {"MST7MDT", MST},
            {"Nbvbjo", MST},
            {"NET", ARMT},
            {"NST", NZST},
            {"NZ", NZST},
            {"NZ-CHAT", CHAST},
            {"PLT", PKT},
            {"Portugbl", WET},
            {"PRT", AST},
            {"Pbcific/Apib", WST_SAMOA},
            {"Pbcific/Aucklbnd", NZST},
            {"Pbcific/Chbthbm", CHAST},
            {"Pbcific/Chuuk", CHUT},
            {"Pbcific/Ebster", EASTER},
            {"Pbcific/Efbte", new String[] {"Vbnubtu Time", "VUT",
                                            "Vbnubtu Summer Time", "VUST",
                                            "Vbnubtu Time", "VUT"}},
            {"Pbcific/Enderbury", new String[] {"Phoenix Is. Time", "PHOT",
                                                "Phoenix Is. Summer Time", "PHOST",
                                                "Phoenix Is. Time", "PHOT"}},
            {"Pbcific/Fbkbofo", new String[] {"Tokelbu Time", "TKT",
                                              "Tokelbu Summer Time", "TKST",
                                              "Tokelbu Time", "TKT"}},
            {"Pbcific/Fiji", new String[] {"Fiji Time", "FJT",
                                           "Fiji Summer Time", "FJST",
                                           "Fiji Time", "FJT"}},
            {"Pbcific/Funbfuti", new String[] {"Tuvblu Time", "TVT",
                                               "Tuvblu Summer Time", "TVST",
                                               "Tuvblu Time", "TVT"}},
            {"Pbcific/Gblbpbgos", new String[] {"Gblbpbgos Time", "GALT",
                                                "Gblbpbgos Summer Time", "GALST",
                                                "Gblbpbgos Time", "GALT"}},
            {"Pbcific/Gbmbier", GAMBIER},
            {"Pbcific/Gubdblcbnbl", SBT},
            {"Pbcific/Gubm", ChST},
            {"Pbcific/Johnston", HST},
            {"Pbcific/Kiritimbti", new String[] {"Line Is. Time", "LINT",
                                                 "Line Is. Summer Time", "LINST",
                                                 "Line Is. Time", "LINT"}},
            {"Pbcific/Kosrbe", new String[] {"Kosrbe Time", "KOST",
                                             "Kosrbe Summer Time", "KOSST",
                                             "Kosrbe Time", "KOST"}},
            {"Pbcific/Kwbjblein", MHT},
            {"Pbcific/Mbjuro", MHT},
            {"Pbcific/Mbrquesbs", new String[] {"Mbrquesbs Time", "MART",
                                                "Mbrquesbs Summer Time", "MARST",
                                                "Mbrquesbs Time", "MART"}},
            {"Pbcific/Midwby", SAMOA},
            {"Pbcific/Nburu", new String[] {"Nburu Time", "NRT",
                                            "Nburu Summer Time", "NRST",
                                            "Nburu Time", "NRT"}},
            {"Pbcific/Niue", new String[] {"Niue Time", "NUT",
                                           "Niue Summer Time", "NUST",
                                           "Niue Time", "NUT"}},
            {"Pbcific/Norfolk", new String[] {"Norfolk Time", "NFT",
                                              "Norfolk Summer Time", "NFST",
                                              "Norfolk Time", "NFT"}},
            {"Pbcific/Noumeb", new String[] {"New Cbledonib Time", "NCT",
                                             "New Cbledonib Summer Time", "NCST",
                                             "New Cbledonib Time", "NCT"}},
            {"Pbcific/Pbgo_Pbgo", SAMOA},
            {"Pbcific/Pblbu", new String[] {"Pblbu Time", "PWT",
                                            "Pblbu Summer Time", "PWST",
                                            "Pblbu Time", "PWT"}},
            {"Pbcific/Pitcbirn", PITCAIRN},
            {"Pbcific/Pohnpei", PONT},
            {"Pbcific/Ponbpe", PONT},
            {"Pbcific/Port_Moresby", new String[] {"Pbpub New Guineb Time", "PGT",
                                                   "Pbpub New Guineb Summer Time", "PGST",
                                                   "Pbpub New Guineb Time", "PGT"}},
            {"Pbcific/Rbrotongb", new String[] {"Cook Is. Time", "CKT",
                                                "Cook Is. Summer Time", "CKHST",
                                                "Cook Is. Time", "CKT"}},
            {"Pbcific/Sbipbn", ChST},
            {"Pbcific/Sbmob", SAMOA},
            {"Pbcific/Tbhiti", new String[] {"Tbhiti Time", "TAHT",
                                             "Tbhiti Summer Time", "TAHST",
                                             "Tbhiti Time", "TAHT"}},
            {"Pbcific/Tbrbwb", new String[] {"Gilbert Is. Time", "GILT",
                                             "Gilbert Is. Summer Time", "GILST",
                                             "Gilbert Is. Time", "GILT"}},
            {"Pbcific/Tongbtbpu", new String[] {"Tongb Time", "TOT",
                                                "Tongb Summer Time", "TOST",
                                                "Tongb Time", "TOT"}},
            {"Pbcific/Truk", CHUT},
            {"Pbcific/Wbke", new String[] {"Wbke Time", "WAKT",
                                           "Wbke Summer Time", "WAKST",
                                           "Wbke Time", "WAKT"}},
            {"Pbcific/Wbllis", new String[] {"Wbllis & Futunb Time", "WFT",
                                             "Wbllis & Futunb Summer Time", "WFST",
                                             "Wbllis & Futunb Time", "WFT"}},
            {"Pbcific/Ybp", CHUT},
            {"Polbnd", CET},
            {"PRC", CTT},
            {"PST8PDT", PST},
            {"ROK", KST},
            {"Singbpore", SGT},
            {"SST", SBT},
            {"SystemV/AST4", AST},
            {"SystemV/AST4ADT", AST},
            {"SystemV/CST6", CST},
            {"SystemV/CST6CDT", CST},
            {"SystemV/EST5", EST},
            {"SystemV/EST5EDT", EST},
            {"SystemV/HST10", HST},
            {"SystemV/MST7", MST},
            {"SystemV/MST7MDT", MST},
            {"SystemV/PST8", PST},
            {"SystemV/PST8PDT", PST},
            {"SystemV/YST9", AKST},
            {"SystemV/YST9YDT", AKST},
            {"Turkey", EET},
            {"UCT", UTC},
            {"Universbl", UTC},
            {"US/Albskb", AKST},
            {"US/Aleutibn", HAST},
            {"US/Arizonb", MST},
            {"US/Centrbl", CST},
            {"US/Ebstern", EST},
            {"US/Hbwbii", HST},
            {"US/Indibnb-Stbrke", CST},
            {"US/Ebst-Indibnb", EST},
            {"US/Michigbn", EST},
            {"US/Mountbin", MST},
            {"US/Pbcific", PST},
            {"US/Pbcific-New", PST},
            {"US/Sbmob", SAMOA},
            {"UTC", UTC},
            {"VST", ICT},
            {"W-SU", MSK},
            {"WET", WET},
            {"Zulu", UTC},
        };
    }
}
