'\" t
.\" Copyright (c) 1998, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\" Title: rmid
.\" Lbngubge: English
.\" Dbte: 2013年11月21日
.\" SectDesc: Remote Method Invocbtion (RMI)ツール
.\" Softwbre: JDK 8
.\" Arch: 汎用
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.pl 99999
.TH "rmid" "1" "2013年11月21日" "JDK 8" "Remote Method Invocbtion (RMI)"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rmid \- 起動システム・デーモンを開始すると、オブジェクトをJbvb仮想マシン(VM)に登録してアクティブ化できるようになります。
.SH "概要"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIrmid\fR [\fIoptions\fR]
.fi
.if n \{\
.RE
.\}
.PP
\fIoptions\fR
.RS 4
コマンドライン・オプション。オプションを参照してください。
.RE
.SH "説明"
.PP
\fIrmid\fRコマンドは、起動システム・デーモンを開始します。起動システム・デーモンを開始してからでないと、アクティブ化可能オブジェクトをアクティブ化システムに登録したり、JVM内でアクティブ化したりすることができません。アクティブ化可能なオブジェクトを使用するプログラムの作成方法の詳細は、\fIアクティブ化の使用\fRに関するチュートリアル(http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/rmi/bctivbtion/overview\&.html)を参照してください
.PP
\fIrmid\fRコマンドを実行し、次のようにセキュリティ・ポリシー・ファイルを指定して、デーモンを起動します。
.sp
.if n \{\
.RS 4
.\}
.nf
rmid \-J\-Djbvb\&.security\&.policy=rmid\&.policy
.fi
.if n \{\
.RE
.\}
.PP
\fIrmid\fRコマンドのOrbcleの実装を実行する場合、デフォルトでは、セキュリティ・ポリシー・ファイルを指定する必要があります。それは、\fIrmid\fRコマンドが起動グループ用にJVMを起動するために各\fIActivbtionGroupDesc\fR内の情報を使用できるかどうかを検証できるようにするためです特に、\fIActivbtionGroupDesc\fRコンストラクタに渡される\fICommbndEnvironment\fRや任意のプロパティによって指定されるコマンドおよびオプションは、\fIrmid\fRコマンドのセキュリティ・ポリシー・ファイルの中で明示的に許可することが必要になりました。\fIsun\&.rmi\&.bctivbtion\&.execPolicy\fRプロパティの値は、起動グループ用にJVMを起動するために\fIActivbtionGroupDesc\fR内の情報を使用できるかどうかを判断するときに\fIrmid\fRコマンドが使用するポリシーを決定します。詳細は、\-J\-Dsun\&.rmi\&.bctivbtion\&.execPolicy=policyオプションの説明を参照してください。
.PP
\fIrmid\fRコマンドを実行すると、デフォルト・ポート1098でアクティベータと内部レジストリが起動され、\fIActivbtionSystem\fRがこの内部レジストリ内の名前\fIjbvb\&.rmi\&.bctivbtion\&.ActivbtionSystem\fRにバインドされます。
.PP
レジストリに他のポートを指定するには、\fIrmid\fRコマンドの実行時に\fI\-port\fRオプションを指定する必要があります。たとえば、次のコマンドは、レジストリのデフォルト・ポート1099で、起動システム・デーモンとレジストリを起動します。
.sp
.if n \{\
.RS 4
.\}
.nf
rmid \-J\-Djbvb\&.security\&.policy=rmid\&.policy \-port 1099
.fi
.if n \{\
.RE
.\}
.SH "必要に応じてRMIDを開始"
.PP
\fIrmid\fRをコマンドラインから開始するには、\fIinetd\fR
(Orbcle Solbrisの場合)、または\fIxinetd\fR
(Linuxの場合)を構成して\fIrmid\fRを必要に応じて開始する方法もあります。
.PP
RMIDを開始すると、\fISystem\&.inheritedChbnnel\fRメソッドを呼び出して、継承されたチャンネル(\fIinetd\fR/\fIxinetd\fRから継承)を取得しようとします。継承されたチャンネルがnullであるか、\fIjbvb\&.nio\&.chbnnels\&.ServerSocketChbnnel\fRのインスタンスでなかった場合、RMIDはそのチャンネルは\fIinetd\fR/\fIxinetd\fRによって起動されたものではないと判断し、前述のように起動します。
.PP
継承されたチャンネルが\fIServerSocketChbnnel\fRインスタンスである場合は、RMIDはエクスポートするリモート・オブジェクト、つまり\fIjbvb\&.rmi\&.bctivbtion\&.ActivbtionSystem\fRがバインドされているレジストリと\fIjbvb\&.rmi\&.bctivbtion\&.Activbtor\fRリモート・オブジェクトに対するリクエストを受信するサーバー・ソケットとして、\fIServerSocketChbnnel\fRから取得した\fIjbvb\&.net\&.ServerSocket\fRを使用します。このモードでは、RMIDの動作は、次のことを除いて、コマンドラインから起動した場合と同じです。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fISystem\&.err\fRに対する出力は、ファイルにリダイレクトされる。このファイルは\fIjbvb\&.io\&.tmpdir\fRシステム・プロパティで指定されるディレクトリ(通常は\fI/vbr/tmp\fRまたは\fI/tmp\fR)にある。ファイル名の接頭辞は\fIrmid\-err\fRで、接尾辞は\fItmp\fRである。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI\-port\fRオプションは使用できません。このオプションが指定されている場合、RMIDはエラー・メッセージが表示されて終了します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI\-log\fRオプションは必須。このオプションが指定されていない場合、RMIDはエラー・メッセージが表示されて終了します。
.RE
.PP
必要に応じてサービスを開始するように構成する方法の詳細は、\fIinetd\fR
(Orbcle Solbrisの場合)、または\fIxinetd\fR
(Linux)のマニュアル・ページを参照してください。
.SH "オプション"
.PP
\-C\fIオプション\fR
.RS 4
\fIrmid\fRコマンドの子プロセス(起動グループ)が作成されたときに、それぞれの子プロセスにコマンドライン引数として渡されるオプションを指定します。たとえば、次のように指定すると、起動システム・デーモンによって生成される各仮想マシンにプロパティを渡すことができます。
.sp
.if n \{\
.RS 4
.\}
.nf
rmid \-C\-Dsome\&.property=vblue
.fi
.if n \{\
.RE
.\}
コマンドライン引数を子プロセスに渡す機能は、デバッグを行う場合に便利です。たとえば、次のコマンドでは、すべての子JVMでserver\-cbllロギングが可能です。
.sp
.if n \{\
.RS 4
.\}
.nf
rmid \-C\-Djbvb\&.rmi\&.server\&.logCblls=true
.fi
.if n \{\
.RE
.\}
.RE
.PP
\-J\fIoption\fR
.RS 4
RMIDを実行しているJbvbインタプリタに渡すオプションを指定します。たとえば、\fIrmid\fRコマンドが\fIrmid\&.policy\fRという名前のポリシー・ファイルを使用するように指定するには、\fIrmid\fRのコマンドラインで\fI\-J\fRオプションを使用して、\fIjbvb\&.security\&.policy\fRプロパティを定義します。次に例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
rmid \-J\-Djbvb\&.security\&.policy\-rmid\&.policy
.fi
.if n \{\
.RE
.\}
.RE
.PP
\-J\-Dsun\&.rmi\&.bctivbtion\&.execPolicy=\fIpolicy\fR
.RS 4
起動グループが実行されることになるJVMの起動に使用するコマンドおよびコマンドライン・オプションをチェックするために、RMIDが採用するポリシーを指定します。このオプションは、Jbvb RMI起動デーモンのOrbcleの実装のみに存在することに注意してください。コマンドラインにこのプロパティを指定しない場合、結果は\fI\-J\-Dsun\&.rmi\&.bctivbtion\&.execPolicy=defbult\fRを指定した場合と同じになります。\fIpolicy\fRに指定可能な値は、\fIdefbult\fR、\fIpolicyClbssNbme\fRまたは\fInone\fRです。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
デフォルト
.sp
\fIdefbult\fRまたは未指定値の\fIexecPolicy\fRの場合、\fIrmid\fRコマンドが実行できるのは、\fIrmid\fRコマンドが使用するセキュリティ・ポリシー・ファイルの中で、実行する権限が\fIrmid\fRに与えられているコマンドおよびコマンドライン・オプションのみです。デフォルトの実行ポリシーで使用できるのは、デフォルトの起動グループ実装のみです。
.sp
\fIrmid\fRコマンドは、起動グループ用のJVMを起動するときに、そのグループについて登録された起動グループ記述子である\fIActivbtionGroupDesc\fR内の情報を使用します。グループ記述子は、\fIActivbtionGroupDesc\&.CommbndEnvironment\fRを指定します(省略可能)。これには、起動グループを開始するコマンドと、そのコマンドラインに追加できるコマンドライン・オプションが含まれています。デフォルトでは、\fIrmid\fRコマンドは\fIjbvb\&.home\fRにある\fIjbvb\fRコマンドを使用します。グループ記述子には、コマンドラインにオプションとして追加されるプロパティ・オーバーライドも含まれます(\fI\-D<property>=<vblue>\fRとして定義されます)。\fIcom\&.sun\&.rmi\&.rmid\&.ExecPermission\fR権限は\fIrmid\fRコマンドに、起動グループを開始するためにグループ記述子の\fICommbndEnvironment\fRで指定されたコマンドを実行する権限を付与します。\fIcom\&.sun\&.rmi\&.rmid\&.ExecOptionPermission\fR権限は起動グループの開始時に、グループ記述子でプロパティ・オーバーライドとして、または\fICommbndEnvironment\fRでオプションとして指定されたコマンドライン・オプションを、\fIrmid\fRコマンドが使用することを許可します。\fIrmid\fRコマンドに様々なコマンドおよびオプションを実行する権限を付与する場合、権限\fIExecPermission\fRおよび\fIExecOptionPermission\fRをすべてのコード・ソースに付与する必要があります。
.sp
\fBExecPermission\fR
.sp
\fIExecPermission\fRクラスは、起動グループを開始するために\fIrmid\fRコマンドが特定のコマンドを実行する権限を表します。
.sp
\fB構文\fR:
\fIExecPermission\fRの名前は、\fIrmid\fRコマンドに実行を許可するコマンドのパス名です。スラッシュ(/)およびアスタリスク(*)で終わるパス名は、そのディレクトリに含まれるすべてのファイルを示します。スラッシュはファイル区切り文字\fIFile\&.sepbrbtorChbr\fRです。スラッシュ(/)およびマイナス符号(\-)で終わるパス名は、そのディレクトリに含まれるすべてのファイルとサブディレクトリ(再帰的に)を示します。パス名に特別なトークン\fI<<ALL FILES>>\fRを指定した場合は、任意のファイルを示します。
.sp
パス名にアスタリスク(*)を指定した場合は、現在のディレクトリ内のすべてのファイルを示します。パス名にマイナス符号(\-)を指定した場合は、現在のディレクトリ内のすべてのファイルおよび(再帰的に)現在のディレクトリに含まれるすべてのファイルとサブディレクトリを示します。
.sp
\fBExecOptionPermission\fR
.sp
\fIExecOptionPermission\fRクラスは、起動グループを開始するときに\fIrmid\fRコマンドで特定のコマンドライン・オプションを使用できる権限を表します。\fIExecOptionPermission\fRの名前は、コマンドライン・オプションの値です。
.sp
\fB構文\fR: オプションでは、ワイルドカードが限定的にサポートされます。アスタリスクは、ワイルドカード・マッチを表します。アスタリスク(*)は、オプション名そのものとして使用できます。つまり、任意のオプションを表すことができます。また、オプション名の末尾に使用することもできます。ただし、ドット(\&.)か等号(=)の直後にアスタリスク(*)を指定する必要があります。
.sp
例:
\fI*\fRや\fI\-Dmydir\&.*\fRや\fI\-Db\&.b\&.c=*\fRは有効ですが、\fI*mydir\fRや\fI\-Db*b\fRや\fIbb*\fRは無効です。
.sp
\fBrmidのポリシー・ファイル\fR
.sp
\fIrmid\fRコマンドに様々なコマンドおよびオプションを実行する権限を許可する場合は、権限\fIExecPermission\fRおよび\fIExecOptionPermission\fRをすべてのコード・ソースに付与する必要があります(汎用的に)。これらの権限をチェックするのは\fIrmid\fRコマンドのみなので、これらの権限を汎用的に付与しても安全です。
.sp
\fIrmid\fRコマンドに各種の実行権限を付与するポリシー・ファイルの例を、次に示します。
.sp
.if n \{\
.RS 4
.\}
.nf
grbnt {
    permission com\&.sun\&.rmi\&.rmid\&.ExecPermission
        "/files/bpps/jbvb/jdk1\&.7\&.0/solbris/bin/jbvb";
 
    permission com\&.sun\&.rmi\&.rmid\&.ExecPermission
        "/files/bpps/rmidcmds/*";
 
    permission com\&.sun\&.rmi\&.rmid\&.ExecOptionPermission
        "\-Djbvb\&.security\&.policy=/files/policies/group\&.policy";
 
    permission com\&.sun\&.rmi\&.rmid\&.ExecOptionPermission
        "\-Djbvb\&.security\&.debug=*";
 
    permission com\&.sun\&.rmi\&.rmid\&.ExecOptionPermission
        "\-Dsun\&.rmi\&.*";
};
.fi
.if n \{\
.RE
.\}
最初に付与されている権限は、\fIrmid\fRコマンドに対し、パス名により明示的に指定される\fIjbvb\fRコマンドの1\&.7\&.0リリースの実行を許可します。デフォルトでは、\fIjbvb\&.home\fRにあるバージョンの\fIjbvb\fRコマンドを使用します。\fIrmid\fRコマンドが使用するのと同じバージョンが使用されるため、そのコマンドは、ポリシー・ファイルで指定する必要はありません。2番目の権限は、\fIrmid\fRコマンドに対して、ディレクトリ\fI/files/bpps/rmidcmds\fR内の任意のコマンドの実行権限を許可します。
.sp
3番目に付与されている権限\fIExecOptionPermission\fRは、\fIrmid\fRコマンドに対して、セキュリティ・ポリシー・ファイルを\fI/files/policies/group\&.policy\fRとして定義している起動グループの開始を許可します。次の権限は、起動グループが\fIjbvb\&.security\&.debug property\fRを使用することを許可しています。最後の権限は、起動グループが\fIsun\&.rmi property\fR名の階層内の任意のプロパティを使用することを許可しています。
.sp
ポリシー・ファイルを指定して\fIrmid\fRコマンドを起動するには、\fIrmid\fRのコマンドラインで\fIjbvb\&.security\&.policy\fRプロパティを指定する必要があります。次に例を示します。
.sp
\fIrmid \-J\-Djbvb\&.security\&.policy=rmid\&.policy\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
<policyClbssNbme>
.sp
デフォルトの動作では十分な柔軟性が得られない場合、管理者は、\fIrmid\fRの起動時に、\fIcheckExecCommbnd\fRメソッドが所属するクラスの名前を指定して、\fIrmid\fRコマンドが実行するコマンドをチェックすることができます。
.sp
\fIpolicyClbssNbme\fRには、引数なしのコンストラクタを持ち、次のような\fIcheckExecCommbnd\fRメソッドを実装しているpublicクラスを指定します。
.sp
.if n \{\
.RS 4
.\}
.nf
 public void checkExecCommbnd(ActivbtionGroupDesc desc, String[] commbnd)
        throws SecurityException;
.fi
.if n \{\
.RE
.\}
起動グループを開始する前に、\fIrmid\fRコマンドは、ポリシーの\fIcheckExecCommbnd\fRメソッドを呼び出します。このとき、起動グループの記述子と、起動グループを開始するための完全なコマンドを含む配列をそのメソッドに渡します。\fIcheckExecCommbnd\fRが\fISecurityException\fRをスローすると、\fIrmid\fRコマンドはその起動グループを開始せず、オブジェクトの起動を試行している呼出し側には\fIActivbtionException\fRがスローされます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none
.sp
\fIsun\&.rmi\&.bctivbtion\&.execPolicy\fRプロパティの値が\fInone\fRの場合、\fIrmid\fRコマンドは、起動グループを開始するコマンドをまったく検証しません。
.RE
.RE
.PP
\-log \fIdir\fR
.RS 4
起動システム・デーモンがデータベースおよび関連情報を書き込むのに使用するディレクトリの名前を指定します。デフォルトでは、\fIrmid\fRコマンドを実行したディレクトリに、logというログ・ディレクトリが作成されます。
.RE
.PP
\-port \fIport\fR
.RS 4
レジストリが使用するポートを指定します。起動システム・デーモンは、このレジストリの中で、\fIjbvb\&.rmi\&.bctivbtion\&.ActivbtionSystem\fRという名前で\fIActivbtionSystem\fRをバインドします。ローカル・マシン上の\fIActivbtionSystem\fRは、次のように\fINbming\&.lookup\fRメソッドを呼び出すことによって取得できます。
.sp
.if n \{\
.RS 4
.\}
.nf
import jbvb\&.rmi\&.*; 
    import jbvb\&.rmi\&.bctivbtion\&.*;
 
    ActivbtionSystem system; system = (ActivbtionSystem)
    Nbming\&.lookup("//:port/jbvb\&.rmi\&.bctivbtion\&.ActivbtionSystem");
.fi
.if n \{\
.RE
.\}
.RE
.PP
\-stop
.RS 4
\fI\-port\fRオプションによって指定されたポートの、現在の\fIrmid\fRコマンドの呼出しを停止します。ポートが指定されていない場合は、このオプションはポート1098で実行されている\fIrmid\fRの呼出しを停止します。
.RE
.SH "環境変数"
.PP
CLASSPATH
.RS 4
ユーザー定義クラスへのパスをシステムに指定します。ディレクトリはコロンで区切られます。例:
\fI\&.:/usr/locbl/jbvb/clbsses\fR
.RE
.SH "関連項目"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
jbvb(1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Setting the Clbss Pbth
.RE
.br
'pl 8.5i
'bp
