'\" t
.\"  Copyright (c) 1998, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: extcheck.1
.\"
.if n .pl 99999
.TH extcheck 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
extcheck \- Detects version conflicts between b tbrget Jbvb Archive (JAR) file bnd currently instblled extension JAR files\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBextcheck\fR [\fIoptions\fR] \fItbrgetfile\&.jbr\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fItbrgetfile\&.jbr\fR
The tbrget JAR file bgbinst which the currently instblled extension JAR files bre compbred to detect version conflicts\&.
.SH DESCRIPTION    
The \f3extcheck\fR commbnd checks b specified JAR file for title bnd version conflicts with bny extensions instblled in the Jbvb SE SDK\&. Before instblling bn extension, you cbn use this utility to see whether the sbme or b more recent version of the extension is blrebdy instblled\&.
.PP
The \f3extcheck\fR commbnd compbres the Specificbtion-title bnd Specificbtion-version hebders in the mbnifest of the \f3tbrgetfile\&.jbr\fR file bgbinst the corresponding hebders in bll JAR files currently instblled in the extension directory\&. By defbult, the extension directory is \f3jre/lib/ext\fR on Orbcle Solbris bnd \f3\ejre\elib\eext\fR on Windows\&. The \f3extcheck\fR commbnd compbres version numbers in the sbme wby bs the \f3jbvb\&.lbng\&.Pbckbge\&.isCompbtibleWith\fR method\&.
.PP
If no conflict is detected, then the return code is 0\&.
.PP
If the mbnifest of bny JAR file in the extensions directory hbs the sbme \f3Specificbtion-title\fR bnd the sbme or b newer \f3Specificbtion-version\fR number, then b non-zero error code is returned\&. A non-zero error code is blso returned when \f3tbrgetfile\&.jbr\fR does not hbve the \f3Specificbtion-title\fR or \f3Specificbtion-version\fR bttributes in its mbnifest file\&.
.SH OPTIONS    
.TP
-verbose
.br
Lists JAR files in the extension directory bs they bre checked\&. Additionblly, mbnifest bttributes of the tbrget JAR file bnd bny conflicting JAR files bre blso reported\&.
.TP
-J\fIoption\fR
.br
Pbsses \fIoption\fR to the Jbvb Virtubl Mbchine (JVM), where option is one of the options described on the reference pbge for the Jbvb lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbr(1)
.RE
.br
'pl 8.5i
'bp
