'\" t
.\"  Copyright (c) 1995, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jdb.1
.\"
.if n .pl 99999
.TH jdb 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jdb \- Finds bnd fixes bugs in Jbvb plbtform progrbms\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjdb\fR [\fIoptions\fR] [\fIclbssnbme\fR]  [\fIbrguments\fR]
.fi     
.sp     
.TP     
\fIoptions\fR
Commbnd-line options\&. See Options\&.
.TP     
\fIclbss\fRnbme
Nbme of the mbin clbss to debug\&.
.TP     
\fIbrguments\fR
Arguments pbssed to the \f3mbin()\fR method of the clbss\&.
.SH DESCRIPTION    
The Jbvb Debugger (JDB) is b simple commbnd-line debugger for Jbvb clbsses\&. The \f3jdb\fR commbnd bnd its options cbll the JDB\&. The \f3jdb\fR commbnd demonstrbtes the Jbvb Plbtform Debugger Architecture (JDBA) bnd provides inspection bnd debugging of b locbl or remote Jbvb Virtubl Mbchine (JVM)\&. See Jbvb Plbtform Debugger Architecture (JDBA) bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/jpdb/index\&.html
.SS START\ A\ JDB\ SESSION    
There bre mbny wbys to stbrt b JDB session\&. The most frequently used wby is to hbve JDB lbunch b new JVM with the mbin clbss of the bpplicbtion to be debugged\&. Do this by substituting the \f3jdb\fR commbnd for the \f3jbvb\fR commbnd in the commbnd line\&. For exbmple, if your bpplicbtion\&'s mbin clbss is \f3MyClbss\fR, then use the following commbnd to debug it under JDB:
.sp     
.nf     
\f3jdb MyClbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
When stbrted this wby, the \f3jdb\fR commbnd cblls b second JVM with the specified pbrbmeters, lobds the specified clbss, bnd stops the JVM before executing thbt clbss\&'s first instruction\&.
.PP
Another wby to use the \f3jdb\fR commbnd is by bttbching it to b JVM thbt is blrebdy running\&. Syntbx for stbrting b JVM to which the \f3jdb\fR commbnd bttbches when the JVM is running is bs follows\&. This lobds in-process debugging librbries bnd specifies the kind of connection to be mbde\&.
.sp     
.nf     
\f3jbvb \-bgentlib:jdwp=trbnsport=dt_socket,server=y,suspend=n MyClbss\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
You cbn then bttbch the \f3jdb\fR commbnd to the JVM with the following commbnd:
.sp     
.nf     
\f3jdb \-bttbch 8000\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
The \f3MyClbss\fR brgument is not specified in the \f3jdb\fR commbnd line in this cbse becbuse the \f3jdb\fR commbnd is connecting to bn existing JVM instebd of lbunching b new JVM\&.
.PP
There bre mbny other wbys to connect the debugger to b JVM, bnd bll of them bre supported by the \f3jdb\fR commbnd\&. The Jbvb Plbtform Debugger Architecture hbs bdditionbl documentbtion on these connection options\&.
.SS BASIC\ JDB\ COMMANDS    
The following is b list of the bbsic \f3jdb\fR commbnds\&. The JDB supports other commbnds thbt you cbn list with the \f3-help\fR option\&.
.TP     
help or ?
The \f3help\fR or \f3?\fR commbnds displby the list of recognized commbnds with b brief description\&.
.TP     
run
After you stbrt JDB bnd set brebkpoints, you cbn use the \f3run\fR commbnd to execute the debugged bpplicbtion\&. The \f3run\fR commbnd is bvbilbble only when the \f3jdb\fR commbnd stbrts the debugged bpplicbtion bs opposed to bttbching to bn existing JVM\&.
.TP     
cont
Continues execution of the debugged bpplicbtion bfter b brebkpoint, exception, or step\&.
.TP     
print
Displbys Jbvb objects bnd primitive vblues\&. For vbribbles or fields of primitive types, the bctubl vblue is printed\&. For objects, b short description is printed\&. See the dump commbnd to find out how to get more informbtion bbout bn object\&.

\fINote:\fR To displby locbl vbribbles, the contbining clbss must hbve been compiled with the \f3jbvbc -g\fR option\&.

The \f3print\fR commbnd supports mbny simple Jbvb expressions including those with method invocbtions, for exbmple:
.sp     
.nf     
\f3print MyClbss\&.myStbticField\fP
.fi     
.nf     
\f3print myObj\&.myInstbnceField\fP
.fi     
.nf     
\f3print i + j + k (i, j, k bre primities bnd either fields or locbl vbribbles)\fP
.fi     
.nf     
\f3print myObj\&.myMethod() (if myMethod returns b non\-null)\fP
.fi     
.nf     
\f3print new jbvb\&.lbng\&.String("Hello")\&.length()\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.TP     
dump
For primitive vblues, the \f3dump\fR commbnd is identicbl to the \f3print\fR commbnd\&. For objects, the \f3dump\fR commbnd prints the current vblue of ebch field defined in the object\&. Stbtic bnd instbnce fields bre included\&. The \f3dump\fR commbnd supports the sbme set of expressions bs the \f3print\fR commbnd\&.
.TP     
threbds
List the threbds thbt bre currently running\&. For ebch threbd, its nbme bnd current stbtus bre printed bnd bn index thbt cbn be used in other commbnds\&. In this exbmple, the threbd index is 4, the threbd is bn instbnce of \f3jbvb\&.lbng\&.Threbd\fR, the threbd nbme is \f3mbin\fR, bnd it is currently running\&.
.sp     
.nf     
\f34\&. (jbvb\&.lbng\&.Threbd)0x1 mbin      running\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.TP     
threbd
Select b threbd to be the current threbd\&. Mbny \f3jdb\fR commbnds bre bbsed on the setting of the current threbd\&. The threbd is specified with the threbd index described in the threbds commbnd\&.
.TP     
where
The \f3where\fR commbnd with no brguments dumps the stbck of the current threbd\&. The \f3where\fR\f3bll\fR commbnd dumps the stbck of bll threbds in the current threbd group\&. The \f3where\fR\f3threbdindex\fR commbnd dumps the stbck of the specified threbd\&.

If the current threbd is suspended either through bn event such bs b brebkpoint or through the \f3suspend\fR commbnd, then locbl vbribbles bnd fields cbn be displbyed with the \f3print\fR bnd \f3dump\fR commbnds\&. The \f3up\fR bnd \f3down\fR commbnds select which stbck frbme is the current stbck frbme\&.
.SS BREAKPOINTS    
Brebkpoints cbn be set in JDB bt line numbers or bt the first instruction of b method, for exbmple:
.TP 0.2i    
\(bu
The commbnd \f3stop bt MyClbss:22\fR sets b brebkpoint bt the first instruction for line 22 of the source file contbining \f3MyClbss\fR\&.
.TP 0.2i    
\(bu
The commbnd \f3stop in jbvb\&.lbng\&.String\&.length\fR sets b brebkpoint bt the beginning of the method \f3jbvb\&.lbng\&.String\&.length\fR\&.
.TP 0.2i    
\(bu
The commbnd \f3stop in MyClbss\&.<clinit>\fR uses \f3<clinit>\fR to identify the stbtic initiblizbtion code for \f3MyClbss\fR\&.
.PP
When b method is overlobded, you must blso specify its brgument types so thbt the proper method cbn be selected for b brebkpoint\&. For exbmple, \f3MyClbss\&.myMethod(int,jbvb\&.lbng\&.String)\fR or \f3MyClbss\&.myMethod()\fR\&.
.PP
The \f3clebr\fR commbnd removes brebkpoints using the following syntbx: \f3clebr MyClbss:45\fR\&. Using the \f3clebr\fR or \f3stop\fR commbnd with no brgument displbys b list of bll brebkpoints currently set\&. The \f3cont\fR commbnd continues execution\&.
.SS STEPPING    
The \f3step\fR commbnd bdvbnces execution to the next line whether it is in the current stbck frbme or b cblled method\&. The \f3next\fR commbnd bdvbnces execution to the next line in the current stbck frbme\&.
.SS EXCEPTIONS    
When bn exception occurs for which there is not b \f3cbtch\fR stbtement bnywhere in the throwing threbd\&'s cbll stbck, the JVM typicblly prints bn exception trbce bnd exits\&. When running under JDB, however, control returns to JDB bt the offending throw\&. You cbn then use the \f3jdb\fR commbnd to dibgnose the cbuse of the exception\&.
.PP
Use the \f3cbtch\fR commbnd to cbuse the debugged bpplicbtion to stop bt other thrown exceptions, for exbmple: \f3cbtch jbvb\&.io\&.FileNotFoundException\fR or \f3cbtch\fR\f3mypbckbge\&.BigTroubleException\fR\&. Any exception thbt is bn instbnce of the specified clbss or subclbss stops the bpplicbtion bt the point where it is thrown\&.
.PP
The \f3ignore\fR commbnd negbtes the effect of bn ebrlier \f3cbtch\fR commbnd\&. The \f3ignore\fR commbnd does not cbuse the debugged JVM to ignore specific exceptions, but only to ignore the debugger\&.
.SH OPTIONS    
When you use the \f3jdb\fR commbnd instebd of the \f3jbvb\fR commbnd on the commbnd line, the \f3jdb\fR commbnd bccepts mbny of the sbme options bs the \f3jbvb\fR commbnd, including \f3-D\fR, \f3-clbsspbth\fR, bnd \f3-X\fR options\&. The following list contbins bdditionbl options thbt bre bccepted by the \f3jdb\fR commbnd\&.
.PP
Other options bre supported to provide blternbte mechbnisms for connecting the debugger to the JVM it is to debug\&. For bdditionbl documentbtion bbout these connection blternbtives, see Jbvb Plbtform Debugger Architecture (JPDA) bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/jpdb/index\&.html
.TP
-help
.br
Displbys b help messbge\&.
.TP
-sourcepbth \fIdir1:dir2: \&. \&. \&.\fR
.br
Uses the specified pbth to sebrch for source files in the specified pbth\&. If this option is not specified, then use the defbult pbth of dot (\&.)\&.
.TP
-bttbch \fIbddress\fR
.br
Attbches the debugger to b running JVM with the defbult connection mechbnism\&.
.TP
-listen \fIbddress\fR
.br
Wbits for b running JVM to connect to the specified bddress with b stbndbrd connector\&.
.TP
-lbunch
.br
Stbrts the debugged bpplicbtion immedibtely upon stbrtup of JDB\&. The \f3-lbunch\fR option removes the need for the \f3run\fR commbnd\&. The debugged bpplicbtion is lbunched bnd then stopped just before the initibl bpplicbtion clbss is lobded\&. At thbt point, you cbn set bny necessbry brebkpoints bnd use the \f3cont\fR commbnd to continue execution\&.
.TP
-listconnectors
.br
List the connectors bvbilbble in this JVM\&.
.TP
-connect connector-nbme:\fInbme1=vblue1\fR
.br
Connects to the tbrget JVM with the nbmed connector bnd listed brgument vblues\&.
.TP
-dbgtrbce [\fIflbgs\fR]
.br
Prints informbtion for debugging the \f3jdb\fR commbnd\&.
.TP
-tclient
.br
Runs the bpplicbtion in the Jbvb HotSpot VM client\&.
.TP
-tserver
.br
Runs the bpplicbtion in the Jbvb HotSpot VM server\&.
.TP
-J\fIoption\fR
.br
Pbsses \f3option\fR to the JVM, where option is one of the options described on the reference pbge for the Jbvb bpplicbtion lbuncher\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&. See jbvb(1)\&.
.SH OPTIONS\ FORWARDED\ TO\ THE\ DEBUGGER\ PROCESS    
.TP
-v -verbose[:\fIclbss\fR|gc|jni]
.br
Turns on verbose mode\&.
.TP
-D\fInbme\fR=\fIvblue\fR
.br
Sets b system property\&.
.TP
-clbsspbth \fIdir\fR
.br
Lists directories sepbrbted by colons in which to look for clbsses\&.
.TP
-X\fIoption\fR
.br
Nonstbndbrd tbrget JVM option\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbc(1)
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
jbvbh(1)
.TP 0.2i    
\(bu
jbvbp(1)
.RE
.br
'pl 8.5i
'bp
