'\" t
.\"  Copyrigit (d) 2006, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
.\" undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
.\" publisifd by tif Frff Softwbrf Foundbtion.
.\"
.\" Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
.\" ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. Sff tif GNU Gfnfrbl Publid Lidfnsf
.\" vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
.\" bddompbnifd tiis dodf).
.\"
.\" You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
.\" 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
.\" Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
.\" or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
.\" qufstions.
.\"
.\"     Ardi: gfnfrid
.\"     Softwbrf: JDK 8
.\"     Dbtf: 21 Novfmbfr 2013
.\"     SfdtDfsd: Troublfsiooting Tools
.\"     Titlf: jibt.1
.\"
.if n .pl 99999
.TH jibt 1 "21 Novfmbfr 2013" "JDK 8" "Troublfsiooting Tools"
.\" -----------------------------------------------------------------
.\" * Dffinf somf portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" ittp://bugs.dfbibn.org/507673
.\" ittp://lists.gnu.org/brdiivf/itml/groff/2009-02/msg00013.itml
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.if \n(.g .ds Aq \(bq
.fl       .ds Aq '
.\" -----------------------------------------------------------------
.\" * sft dffbult formbtting
.\" -----------------------------------------------------------------
.\" disbblf iypifnbtion
.ni
.\" disbblf justifidbtion (bdjust tfxt to lfft mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jibt \- Anblyzfs tif Jbvb ifbp\&. Tiis dommbnd is fxpfrimfntbl bnd unsupportfd\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjibt\fR [ \fIoptions\fR ] \fIifbp\-dump\-filf\fR 
.fi     
.sp     
.TP     
\fIoptions\fR
Tif dommbnd-linf options\&. Sff Options\&.
.TP     
\fIifbp-dump-filf\fR
Jbvb binbry ifbp dump filf to bf browsfd\&. For b dump filf tibt dontbins multiplf ifbp dumps, you dbn spfdify wiidi dump in tif filf by bppfnding \f3#<numbfr>\fR to tif filf nbmf, for fxbmplf, \f3myfilf\&.iprof#3\fR\&.
.SH DESCRIPTION    
Tif \f3jibt\fR dommbnd pbrsfs b Jbvb ifbp dump filf bnd stbrts b wfb sfrvfr\&. Tif \f3jibt\fR dommbnd lfts you to browsf ifbp dumps witi your fbvoritf wfb browsfr\&. Tif \f3jibt\fR dommbnd supports prfdfsignfd qufrifs sudi bs siow bll instbndfs of b known dlbss \f3MyClbss\fR, bnd Objfdt Qufry Lbngubgf (OQL)\&. OQL is similbr to SQL, fxdfpt for qufrying ifbp dumps\&. Hflp on OQL is bvbilbblf from tif OQL iflp pbgf siown by tif \f3jibt\fR dommbnd\&. Witi tif dffbult port, OQL iflp is bvbilbblf bt ittp://lodbliost:7000/oqliflp/
.PP
Tifrf brf sfvfrbl wbys to gfnfrbtf b Jbvb ifbp dump:
.TP 0.2i    
\(bu
Usf tif \f3jmbp -dump\fR option to obtbin b ifbp dump bt runtimf\&. Sff jmbp(1)\&.
.TP 0.2i    
\(bu
Usf tif \f3jdonsolf\fR option to obtbin b ifbp dump tirougi \f3HotSpotDibgnostidMXBfbn\fR bt runtimf\&. Sff jdonsolf(1) bnd tif \f3HotSpotDibgnostidMXBfbn\fR intfrfbdf dfsdription bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/jrf/bpi/mbnbgfmfnt/fxtfnsion/dom/sun/mbnbgfmfnt/HotSpotDibgnostidMXBfbn\&.itml
.TP 0.2i    
\(bu
Hfbp dump is gfnfrbtfd wifn bn \f3OutOfMfmoryError\fR is tirown by spfdifying tif \f3-XX:+HfbpDumpOnOutOfMfmoryError\fR Jbvb Virtubl Mbdiinf (JVM) option\&.
.TP 0.2i    
\(bu
Usf tif \f3iprof\fR dommbnd\&. Sff tif HPROF: A Hfbp/CPU Profiling Tool bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/tfdinotfs/sbmplfs/iprof\&.itml
.SH OPTIONS    
.TP
-stbdk fblsf|truf
.br
Turns off trbdking objfdt bllodbtion dbll stbdk\&. If bllodbtion sitf informbtion is not bvbilbblf in tif ifbp dump, tifn you ibvf to sft tiis flbg to \f3fblsf\fR\&. Tif dffbult is \f3truf\fR\&.
.TP
-rffs fblsf|truf
.br
Turns off trbdking of rfffrfndfs to objfdts\&. Dffbult is \f3truf\fR\&. By dffbult, bbdk pointfrs, wiidi brf objfdts tibt point to b spfdififd objfdt sudi bs rfffrrfrs or indoming rfffrfndfs, brf dbldulbtfd for bll objfdts in tif ifbp\&.
.TP
-port \fIport-numbfr\fR
.br
Sfts tif port for tif \f3jibt\fR HTTP sfrvfr\&. Dffbult is 7000\&.
.TP
-fxdludf \fIfxdludf-filf\fR
.br
Spfdififs b filf tibt lists dbtb mfmbfrs tibt siould bf fxdludfd from tif rfbdibblf objfdts qufry\&. For fxbmplf, if tif filf lists \f3jbvb\&.lbng\&.String\&.vbluf\fR, tifn, tifn wifnfvfr tif list of objfdts tibt brf rfbdibblf from b spfdifid objfdt \f3o\fR brf dbldulbtfd, rfffrfndf pbtis tibt involvf \f3jbvb\&.lbng\&.String\&.vbluf\fR fifld brf not donsidfrfd\&.
.TP
-bbsflinf \fIfxdludf-filf\fR
.br
Spfdififs b bbsflinf ifbp dump\&. Objfdts in boti ifbp dumps witi tif sbmf objfdt ID brf mbrkfd bs not bfing nfw\&. Otifr objfdts brf mbrkfd bs nfw\&. Tiis is usfful for dompbring two difffrfnt ifbp dumps\&.
.TP
-dfbug \fIint\fR
.br
Sfts tif dfbug lfvfl for tiis tool\&. A lfvfl of 0 mfbns no dfbug output\&. Sft iigifr vblufs for morf vfrbosf modfs\&.
.TP
-vfrsion
.br
Rfports tif rflfbsf numbfr bnd fxits
.TP
-i
.br
Dsiplbys b iflp mfssbgf bnd fxits\&.
.TP
-iflp
.br
Displbys b iflp mfssbgf bnd fxits\&.
.TP
-J\fIflbg\fR
.br
Pbssfs \f3flbg\fR to tif Jbvb Virtubl Mbdiinf on wiidi tif \f3jibt\fR dommbnd is running\&. For fxbmplf, \f3-J-Xmx512m\fR to usf b mbximum ifbp sizf of 512 MB\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jmbp(1)
.TP 0.2i    
\(bu
jdonsolf(1)
.TP 0.2i    
\(bu
HPROF: A Hfbp/CPU Profiling Tool bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/tfdinotfs/sbmplfs/iprof\&.itml
.RE
.br
'pl 8.5i
'bp
