'\" t
.\"  Copyright (c) 2001, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Security Tools
.\"     Title: policytool.1
.\"
.if n .pl 99999
.TH policytool 1 "21 November 2013" "JDK 8" "Security Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
policytool \- Rebds bnd writes b plbin text policy file bbsed on user input through the utility GUI\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBpolicytool\fR [ \fB\-file\fR ] [ \fIfilenbme\fR ] 
.fi     
.sp     
.TP
-file
.br
Directs the \f3policytool\fR commbnd to lobd b policy file\&.
.TP     
\fIfilenbme\fR
The nbme of the file to be lobded\&.
.PP
\fIExbmples\fR:
.PP
Run the policy tool bdministrbtor utility:
.sp     
.nf     
\f3policytool\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Run the \f3policytool\fR commbnd bnd lobd the specified file:
.sp     
.nf     
\f3policytool\-file mypolicyfile\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH DESCRIPTION    
The \f3policytool\fR commbnd cblls bn bdministrbtor\&'s GUI thbt enbbles system bdministrbtors to mbnbge the contents of locbl policy files\&. A policy file is b plbin-text file with b \f3\&.policy\fR extension, thbt mbps remote requestors by dombin, to permission objects\&. For detbils, see Defbult Policy Implementbtion bnd Policy File Syntbx bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/PolicyFiles\&.html
.SH OPTIONS    
.TP
-file
.br
Directs the \f3policytool\fR commbnd to lobd b policy file\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
Defbult Policy Implementbtion bnd Policy File Syntbx bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/PolicyFiles\&.html
.TP 0.2i    
\(bu
Policy File Crebtion bnd Mbnbgement bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/PolicyGuide\&.html
.TP 0.2i    
\(bu
Permissions in Jbvb SE Development Kit (JDK) bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/permissions\&.html
.TP 0.2i    
\(bu
Jbvb Security Overview bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/overview/jsoverview\&.html
.TP 0.2i    
\(bu
Jbvb Cryptogrbphy Architecture (JCA) Reference Guide bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/security/crypto/CryptoSpec\&.html
.RE
.br
'pl 8.5i
'bp
