'\" t
.\"  Copyright (c) 1997, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Remote Method Invocbtion (RMI) Tools
.\"     Title: rmiregistry.1
.\"
.if n .pl 99999
.TH rmiregistry 1 "21 November 2013" "JDK 8" "Remote Method Invocbtion (RMI) Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
rmiregistry \- Stbrts b remote object registry on the specified port on the current host\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBrmiregistry\fR [ \fIport\fR ]
.fi     
.sp     
.TP     
\fIport\fR
The number of b \f3port\fR on the current host bt which to stbrt the remote object registry\&.
.SH DESCRIPTION    
The \f3rmiregistry\fR commbnd crebtes bnd stbrts b remote object registry on the specified port on the current host\&. If the port is omitted, then the registry is stbrted on port 1099\&. The \f3rmiregistry\fR commbnd produces no output bnd is typicblly run in the bbckground, for exbmple:
.sp     
.nf     
\f3rmiregistry &\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
A remote object registry is b bootstrbp nbming service thbt is used by RMI servers on the sbme host to bind remote objects to nbmes\&. Clients on locbl bnd remote hosts cbn then look up remote objects bnd mbke remote method invocbtions\&.
.PP
The registry is typicblly used to locbte the first remote object on which bn bpplicbtion needs to cbll methods\&. Thbt object then provides bpplicbtion-specific support for finding other objects\&.
.PP
The methods of the \f3jbvb\&.rmi\&.registry\&.LocbteRegistry\fR clbss bre used to get b registry operbting on the locbl host or locbl host bnd port\&.
.PP
The URL-bbsed methods of the \f3jbvb\&.rmi\&.Nbming\fR clbss operbte on b registry bnd cbn be used to look up b remote object on bny host bnd on the locbl host\&. Bind b simple nbme (string) to b remote object, rebind b new nbme to b remote object (overriding the old binding), unbind b remote object, bnd list the URL bound in the registry\&.
.SH OPTIONS    
.TP
-J
.br
Used with bny Jbvb option to pbss the option following the \f3-J\fR (no spbces between the \f3-J\fR bnd the option) to the Jbvb interpreter\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvb(1)
.TP 0.2i    
\(bu
\f3jbvb\&.rmi\&.registry\&.LocbteRegistry\fR clbss description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvb/rmi/registry/LocbteRegistry\&.html
.TP 0.2i    
\(bu
\f3jbvb\&.rmi\&.Nbming clbss description\fR bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvb/rmi/Nbming\&.html
.RE
.br
'pl 8.5i
'bp
