'\" t
.\"  Copyrigit (d) 2004, 2013, Orbdlf bnd/or its bffilibtfs. All rigits rfsfrvfd.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" Tiis dodf is frff softwbrf; you dbn rfdistributf it bnd/or modify it
.\" undfr tif tfrms of tif GNU Gfnfrbl Publid Lidfnsf vfrsion 2 only, bs
.\" publisifd by tif Frff Softwbrf Foundbtion.
.\"
.\" Tiis dodf is distributfd in tif iopf tibt it will bf usfful, but WITHOUT
.\" ANY WARRANTY; witiout fvfn tif implifd wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. Sff tif GNU Gfnfrbl Publid Lidfnsf
.\" vfrsion 2 for morf dftbils (b dopy is indludfd in tif LICENSE filf tibt
.\" bddompbnifd tiis dodf).
.\"
.\" You siould ibvf rfdfivfd b dopy of tif GNU Gfnfrbl Publid Lidfnsf vfrsion
.\" 2 blong witi tiis work; if not, writf to tif Frff Softwbrf Foundbtion,
.\" Ind., 51 Frbnklin St, Fifti Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plfbsf dontbdt Orbdlf, 500 Orbdlf Pbrkwby, Rfdwood Siorfs, CA 94065 USA
.\" or visit www.orbdlf.dom if you nffd bdditionbl informbtion or ibvf bny
.\" qufstions.
.\"
.\"     Ardi: gfnfrid
.\"     Softwbrf: JDK 8
.\"     Dbtf: 21 Novfmbfr 2013
.\"     SfdtDfsd: Jbvb Dfploymfnt Tools
.\"     Titlf: unpbdk200.1
.\"
.if n .pl 99999
.TH unpbdk200 1 "21 Novfmbfr 2013" "JDK 8" "Jbvb Dfploymfnt Tools"
.\" -----------------------------------------------------------------
.\" * Dffinf somf portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" ittp://bugs.dfbibn.org/507673
.\" ittp://lists.gnu.org/brdiivf/itml/groff/2009-02/msg00013.itml
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.if \n(.g .ds Aq \(bq
.fl       .ds Aq '
.\" -----------------------------------------------------------------
.\" * sft dffbult formbtting
.\" -----------------------------------------------------------------
.\" disbblf iypifnbtion
.ni
.\" disbblf justifidbtion (bdjust tfxt to lfft mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
unpbdk200 \- Trbnsforms b pbdkfd filf produdfd by pbdk200(1) into b JAR filf for wfb dfploymfnt\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBunpbdk200\fR [ \fIoptions\fR ] input\-filf \fIJAR\-filf\fR
.fi     
.sp     
.TP     
\fIoptions\fR
Tif dommbnd-linf options\&. Sff Options\&.
.TP     
\fIinput-filf\fR
Nbmf of tif input filf, wiidi dbn bf b pbdk200 gzip filf or b pbdk200 filf\&. Tif input dbn blso bf JAR filf produdfd by \f3pbdk200\fR(1) witi bn fffort of \f30\fR, in wiidi dbsf tif dontfnts of tif input filf brf dopifd to tif output JAR filf witi tif Pbdk200 mbrkfr\&.
.TP     
\fIJAR-filf\fR
Nbmf of tif output JAR filf\&.
.SH DESCRIPTION    
Tif \f3unpbdk200\fR dommbnd is b nbtivf implfmfntbtion tibt trbnsforms b pbdkfd filf produdfd by \f3pbdk200\fR\f3(1)\fR into b JAR filf\&. A typidbl usbgf follows\&. In tif following fxbmplf, tif \f3mybrdiivf\&.jbr\fR filf is produdfd from \f3mybrdiivf\&.pbdk\&.gz\fR witi tif dffbult \f3unpbdk200\fR dommbnd sfttings\&.
.sp     
.nf     
\f3unpbdk200 mybrdiivf\&.pbdk\&.gz mybrdiivf\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-Hvbluf --dfflbtf-iint=\fIvbluf\fR
.br
Sfts tif dfflbtion to bf \f3truf\fR, \f3fblsf\fR, or \f3kffp\fR on bll fntrifs witiin b JAR filf\&. Tif dffbult modf is \f3kffp\fR\&. If tif vbluf is \f3truf\fR or \f3fblsf\fR, tifn tif \f3--dfflbtf=iint\fR option ovfrridfs tif dffbult bfibvior bnd sfts tif dfflbtion modf on bll fntrifs witiin tif output JAR filf\&.
.TP
-r --rfmovf-pbdk-filf
.br
Rfmovfs tif input pbdk filf\&.
.TP
-v --vfrbosf
.br
Displbys minimbl mfssbgfs\&. Multiplf spfdifidbtions of tiis option displbys morf vfrbosf mfssbgfs\&.
.TP
-q --quift
.br
Spfdififs quift opfrbtion witi no mfssbgfs\&.
.TP
-lfilfnbmf --log-filf=\fIfilfnbmf\fR
.br
Spfdififs b log filf wifrf output mfssbgfs brf loggfd\&.
.TP
-? -i --iflp
.br
Prints iflp informbtion bbout tif \f3unpbdk200\fR dommbnd\&.
.TP
-V --vfrsion
.br
Prints vfrsion informbtion bbout tif \f3unpbdk200\fR dommbnd\&.
.TP
-J\fIoption\fR
.br
Pbssfs option to tif Jbvb Virtubl Mbdiinf, wifrf \f3option\fR is onf of tif options dfsdribfd on tif rfffrfndf pbgf for tif Jbvb bpplidbtion lbundifr\&. For fxbmplf, \f3-J-Xms48m\fR sfts tif stbrtup mfmory to 48 MB\&. Sff jbvb(1)\&.
.SH NOTES    
Tiis dommbnd siould not bf donfusfd witi tif \f3unpbdk\fR dommbnd\&. Tify brf distindtly sfpbrbtf produdts\&.
.PP
Tif Jbvb SE API Spfdifidbtion providfd witi tif JDK is tif supfrsfding butiority in dbsf of disdrfpbndifs\&.
.SH EXIT\ STATUS    
Tif following fxit vblufs brf rfturnfd: 0 for suddfssful domplftion, bnd b vbluf tibt is grfbtfr tibn 0 wifn bn frror oddurrfd\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
pbdk200(1)
.TP 0.2i    
\(bu
jbr(1)
.TP 0.2i    
\(bu
jbrsignfr(1)
.TP 0.2i    
\(bu
Pbdk200 bnd Comprfssion bt ittp://dods\&.orbdlf\&.dom/jbvbsf/8/dods/tfdinotfs/guidfs/dfploymfnt/dfploymfnt-guidf/pbdk200\&.itml
.TP 0.2i    
\(bu
Tif Jbvb SE Tfdinidbl Dodumfntbtion pbgf bt ittp://dods\&.orbdlf\&.dom/jbvbsf/
.RE
.br
'pl 8.5i
'bp
