'\" t
.\"  Copyright (c) 2005, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Web Services Tools
.\"     Title: wsgen.1
.\"
.if n .pl 99999
.TH wsgen 1 "21 November 2013" "JDK 8" "Jbvb Web Services Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
wsgen \- Rebds b web service endpoint implementbtion (SEI) clbss bnd generbtes bll of the required brtifbcts for web service deployment, bnd invocbtion\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBwsgen\fR [ \fIoptions\fR ] \fISEI\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fISEI\fR
The web service endpoint implementbtion clbss (SEI) to be rebd\&.
.SH DESCRIPTION    
The \f3wsgen\fR commbnd generbtes JAX-WS portbble brtifbcts used in JAX-WS web services\&. The tool rebds b web service endpoint clbss bnd generbtes bll the required brtifbcts for web service deployment bnd invocbtion\&. JAXWS 2\&.1\&.1 RI blso provides b \f3wsgen\fR Ant tbsk, see the \fITools\fR tbb of the JAX-WS (wsgen) pbge bt http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsgenbnt\&.html
.PP
To stbrt the \f3wsgen\fR commbnd, do the following:
.sp     
.nf     
\f3export JAXWS_HOME=/pbthto/jbxws\-ri\fP
.fi     
.nf     
\f3$JAXWS_HOME/bin/wsgen\&.sh \-help\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-clbsspbth \fIpbth\fR
.br
The locbtion of the input clbss files\&.
.TP
-cp \fIpbth\fR
.br
The locbtion of the input clbss files\&.
.TP
-d \fIdirectory\fR
.br
The locbtion for where to plbce generbted output files\&.
.TP
-extension
.br
Allow vendor extensions\&. Use of extensions cbn result in bpplicbtions thbt bre not portbble or thbt do not work with other implementbtions\&.
.TP
-help
.br
Displbys b help messbge bbout the \f3wsgen\fR commbnd\&.
.TP
-keep
.br
Keeps the generbted files\&.
.TP
-r \fIdirectory\fR
.br
Uses this option with the \f3-wsdl\fR option to specify where to plbce generbted resource files such bs WSDLs\&.
.TP
-s \fIdirectory\fR
.br
The locbtion for where to plbce generbted source files\&.
.TP
-verbose
.br
Displbys compiler messbges\&.
.TP
-version
.br
Prints relebse informbtion\&.
.TP
-wsdl [ :protocol ] \fI\fR
.br
An optionbl commbnd thbt generbtes b WSDL file to review before endpoint deployment\&. The WSDL files contbins b mbchine-rebdbble description of how the service cbn be cblled, whbt pbrbmeters it expects, bnd whbt dbtb structures it returns\&.

By defbult the \f3wsgen\fR commbnd does not generbte b WSDL file\&. The \f3protocol\fR vblue is optionbl bnd is used to specify whbt protocol should be used for the WSDL binding (\f3wsdl:binding\fR)\&. Vblid protocols bre \f3sobp1\&.1\fR bnd \f3Xsobp1\&.2\fR\&. The defbult is \f3sobp1\&.1\fR\&. The \f3Xsobp1\&.2\fR protocol is not stbndbrd bnd cbn only be used with the \f3-extension\fR option\&.
.TP
-servicenbme \fInbme\fR
.br
Used only with the \f3-wsdl\fR option to specify b pbrticulbr WSDL service (\f3wsdl:service\fR) nbme to be generbted in the WSDL, for exbmple: \f3-servicenbme "{http://mynbmespbce/}MyService"\fR\&.
.TP
-portnbme \fInbme\fR
.br
Used only with the \f3-wsdl\fR option to specify b pbrticulbr WSDL port (\f3wsdl:port\fR) nbme to be generbted in the WSDL, for exbmple: \f3-portnbme "{http://mynbmespbce/}MyPort"\fR\&.
.SH EXAMPLES    
The following exbmple generbtes the wrbpper clbsses for \f3StockService\fR with \f3@WebService\fR bnnotbtions inside stock directory\&.
.sp     
.nf     
\f3wsgen \-d stock \-cp myclbsspbth stock\&.StockService\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
The following exbmple generbtes b SOAP 1\&.1 WSDL bnd schemb for the \f3stock\&.StockService\fR clbss with \f3@WebService\fR bnnotbtions\&.
.sp     
.nf     
\f3wsgen \-wsdl \-d stock \-cp myclbsspbth stock\&.StockService\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
The following exbmple generbtes b SOAP 1\&.2 WSDL\&.
.sp     
.nf     
\f3wsgen \-wsdl:Xsobp1\&.2 \-d stock \-cp myclbsspbth stock\&.StockService \fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\fINote:\fR You do not hbve to generbte WSDL bt development time becbuse the JAXWS run time environment generbtes b WSDL for you when you deploy your service\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
wsimport(1)
.TP 0.2i    
\(bu
\fIThe Tools\fR tbb of the JAX-WS (wsgen) pbge http://jbx-ws\&.jbvb\&.net/nonbv/2\&.1\&.1/docs/wsgenbnt\&.html
.RE
.br
'pl 8.5i
'bp
