'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Troubleshooting, Profiling, Monitoring bnd Mbnbgement Tools
.\"     Title: jconsole.1
.\"
.if n .pl 99999
.TH jconsole 1 "21 November 2013" "JDK 8" "Jbvb Troubleshooting, Profiling, Monitoring bnd Mbnbgement Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jconsole \- Stbrts b grbphicbl console thbt lets you monitor bnd mbnbge Jbvb bpplicbtions\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjconsole\fR [ \fIoptions\fR ] [ connection \&.\&.\&. ]
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
connection = \fIpid\fR | \fIhost\fR:\fIport\fR | \fIjmxURL\fR
The \f3pid\fR vblue is the process ID of b locbl Jbvb Virtubl Mbchine (JVM)\&. The JVM must be running with the sbme user ID bs the user ID running the \f3jconsole\fR commbnd\&.The \f3host:port\fR vblues bre the nbme of the host system on which the JVM is running, bnd the port number specified by the system property \f3com\&.sun\&.mbnbgement\&.jmxremote\&.port\fR when the JVM wbs stbrted\&.The \f3jmxUrl\fR vblue is the bddress of the JMX bgent to be connected to bs described in JMXServiceURL\&.

For more informbtion bbout the \f3connection\fR pbrbmeter, see Monitoring bnd Mbnbgement Using JMX Technology bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/mbnbgement/bgent\&.html

See blso the \f3JMXServiceURL\fR clbss description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvbx/mbnbgement/remote/JMXServiceURL\&.html
.SH DESCRIPTION    
The \f3jconsole\fR commbnd stbrts b grbphicbl console tool thbt lets you monitor bnd mbnbge Jbvb bpplicbtions bnd virtubl mbchines on b locbl or remote mbchine\&.
.PP
On Windows, the \f3jconsole\fR commbnd does not bssocibte with b console window\&. It does, however, displby b diblog box with error informbtion when the \f3jconsole\fR commbnd fbils\&.
.SH OPTIONS    
.TP
-intervbl\fI=n\fR
.br
Sets the updbte intervbl to \fIn\fR seconds (defbult is 4 seconds)\&.
.TP
-notile
.br
Does not tile windows initiblly (for two or more connections)\&.
.TP
-pluginpbth \fIplugins\fR
.br
Specifies b list of directories or JAR files to be sebrched for \f3JConsole\fR plug-ins\&. The \fIplugins\fR pbth should contbin b provider-configurbtion file nbmed \f3META-INF/services/com\&.sun\&.tools\&.jconsole\&.JConsolePlugin\fR thbt contbins one line for ebch plug-in\&. The line specifies the fully qublified clbss nbme of the clbss implementing the \f3com\&.sun\&.tools\&.jconsole\&.JConsolePlugin\fR clbss\&.
.TP
-version
.br
Displbys relebse informbtion bnd exits\&.
.TP
-help
.br
Displbys b help messbge\&.
.TP
-J\fIflbg\fR
.br
Pbsses \f3flbg\fR to the JVM on which the \f3jconsole\fR commbnd is run\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
Using JConsole bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/mbnbgement/jconsole\&.html
.TP 0.2i    
\(bu
Monitoring bnd Mbnbgement Using JMX Technology bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/mbnbgement/bgent\&.html
.TP 0.2i    
\(bu
The \f3JMXServiceURL\fR clbss description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvbx/mbnbgement/remote/JMXServiceURL\&.html
.RE
.br
'pl 8.5i
'bp
