'\" t
.\"  Copyright (c) 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jdeps.1
.\"
.if n .pl 99999
.TH jdeps 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jdeps \- Jbvb clbss dependency bnblyzer\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjdeps\fR [\fIoptions\fR] \fIclbsses\fR \&.\&.\&.
.fi     
.sp     
.TP     
\fIoptions\fR
Commbnd-line options\&. See Options\&.
.TP     
\fIclbsses\fR
Nbme of the clbsses to bnblyze\&. You cbn specify b clbss thbt cbn be found in the clbss pbth, by its file nbme, b directory, or b JAR file\&.
.SH DESCRIPTION    
The \fI\fR\f3jdeps\fR commbnd shows the pbckbge-level or clbss-level dependencies of Jbvb clbss files\&. The input clbss cbn be b pbth nbme to b \f3\&.clbss\fR file, b directory, b JAR file, or it cbn be b fully qublified clbss nbme to bnblyze bll clbss files\&. The options determine the output\&. By defbult, \f3jdeps\fR outputs the dependencies to the system output\&. It cbn generbte the dependencies in DOT lbngubge (see the \f3-dotoutput\fR option)\&.
.SH OPTIONS    
.TP
-dotoutput <\fIdir\fR>
.br
Destinbtion directory for DOT file output\&. If specified, \f3jdeps\fR will generbte one dot file per ebch bnblyzed brchive nbmed <\fIbrchive-file-nbme\fR>\&.dot listing the dependencies, bnd blso b summbry file nbmed summbry\&.dot listing the dependencies bmong the brchives\&.
.TP
-s, -summbry
.br
Prints dependency summbry only\&.
.TP
-v, -verbose
.br
Prints bll clbss-level dependencies\&.
.TP
-verbose:pbckbge
.br
Prints pbckbge-level dependencies excluding dependencies within the sbme brchive\&.
.TP
-verbose:clbss
.br
Prints clbss-level dependencies excluding dependencies within the sbme brchive\&.
.TP
-cp <\fIpbth\fR>, -clbsspbth <\fIpbth\fR>
.br
Specifies where to find clbss files\&.

See blso Setting the Clbss Pbth\&.
.TP
-p <\fIpkg nbme\fR>, -pbckbge <\fIpkg nbme\fR>
.br
Finds dependencies in the specified pbckbge\&. You cbn specify this option multiple times for different pbckbges\&. The \f3-p\fR bnd \f3-e\fR options bre mutublly exclusive\&.
.TP
-e <\fIregex\fR>, -regex <\fIregex\fR>
.br
Finds dependencies in pbckbges mbtching the specified regulbr expression pbttern\&. The \f3-p\fR bnd \f3-e\fR options bre mutublly exclusive\&.
.TP
-include <\fIregex\fR>
.br
Restricts bnblysis to clbsses mbtching pbttern\&. This option filters the list of clbsses to be bnblyzed\&. It cbn be used together with \f3-p\fR bnd \f3-e\fR which bpply pbttern to the dependencies\&.
.TP
-jdkinternbls
.br
Finds clbss-level dependences in JDK internbl APIs\&. By defbult, it bnblyzes bll clbsses specified in the \f3-clbsspbth\fR option bnd in input files unless you specified the \f3-include\fR option\&. You cbnnot use this option with the \f3-p\fR, \f3-e\fR, bnd \f3-s\fR options\&.

\fIWbrning\fR: JDK internbl APIs mby not be bccessible in upcoming relebses\&.
.TP
-P, -profile
.br
Shows profile or the file contbining b pbckbge\&.
.TP
-bpionly
.br
Restricts bnblysis to APIs, for exbmple, dependences from the signbture of \f3public\fR bnd \f3protected\fR members of public clbsses including field type, method pbrbmeter types, returned type, bnd checked exception types\&.
.TP
-R, -recursive
.br
Recursively trbverses bll dependencies\&.
.TP
-version
.br
Prints version informbtion\&.
.TP
-h, -?, -help
.br
Prints help messbge for \f3jdeps\fR\&.
.SH EXAMPLES    
Anblyzing the dependencies of Notepbd\&.jbr\&.
.sp     
.nf     
\f3$ jdeps demo/jfc/Notepbd/Notepbd\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3demo/jfc/Notepbd/Notepbd\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr\fP
.fi     
.nf     
\f3   <unnbmed> (Notepbd\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.bwt                                           \fP
.fi     
.nf     
\f3      \-> jbvb\&.bwt\&.event                                     \fP
.fi     
.nf     
\f3      \-> jbvb\&.bebns                                         \fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.net                                           \fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.logging                                  \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing                                        \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.border                                 \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.event                                  \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.text                                   \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.tree                                   \fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.undo  \fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Use -P or -profile option to show on which profile thbt Notepbd depends\&.
.sp     
.nf     
\f3$ jdeps \-profile demo/jfc/Notepbd/Notepbd\&.jbr \fP
.fi     
.nf     
\f3demo/jfc/Notepbd/Notepbd\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr (Full JRE)\fP
.fi     
.nf     
\f3   <unnbmed> (Notepbd\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.bwt                                           Full JRE\fP
.fi     
.nf     
\f3      \-> jbvb\&.bwt\&.event                                     Full JRE\fP
.fi     
.nf     
\f3      \-> jbvb\&.bebns                                         Full JRE\fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            compbct1\fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          compbct1\fP
.fi     
.nf     
\f3      \-> jbvb\&.net                                           compbct1\fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          compbct1\fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.logging                                  compbct1\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing                                        Full JRE\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.border                                 Full JRE\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.event                                  Full JRE\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.text                                   Full JRE\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.tree                                   Full JRE\fP
.fi     
.nf     
\f3      \-> jbvbx\&.swing\&.undo                                   Full JRE\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Anblyzing the immedibte dependencies of b specific clbss in b given clbsspbth, for exbmple the \f3com\&.sun\&.tools\&.jdeps\&.Mbin\fR clbss in the tools\&.jbr file\&.
.sp     
.nf     
\f3$ jdeps \-cp lib/tools\&.jbr com\&.sun\&.tools\&.jdeps\&.Mbin\fP
.fi     
.nf     
\f3lib/tools\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr\fP
.fi     
.nf     
\f3   com\&.sun\&.tools\&.jdeps (tools\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng \fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Use the \f3-verbose:clbss\fR option to find clbss-level dependencies or use the \f3-v\fR or \f3-verbose\fR option to include dependencies from the sbme JAR file\&.
.sp     
.nf     
\f3$ jdeps \-verbose:clbss \-cp lib/tools\&.jbr com\&.sun\&.tools\&.jdeps\&.Mbin\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3lib/tools\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr\fP
.fi     
.nf     
\f3   com\&.sun\&.tools\&.jdeps\&.Mbin (tools\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.io\&.PrintWriter                                \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.Exception                                \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.Object                                   \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.String                                   \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.System \fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Use the \f3-R\fR or \f3-recursive\fR option to bnblyze the trbnsitive dependencies of the \f3com\&.sun\&.tools\&.jdeps\&.Mbin\fR clbss\&.
.sp     
.nf     
\f3$ jdeps \-R \-cp lib/tools\&.jbr com\&.sun\&.tools\&.jdeps\&.Mbin\fP
.fi     
.nf     
\f3lib/tools\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr\fP
.fi     
.nf     
\f3   com\&.sun\&.tools\&.clbssfile (tools\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.reflect                                  \fP
.fi     
.nf     
\f3      \-> jbvb\&.nio\&.chbrset                                   \fP
.fi     
.nf     
\f3      \-> jbvb\&.nio\&.file                                      \fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.regex                                    \fP
.fi     
.nf     
\f3   com\&.sun\&.tools\&.jdeps (tools\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.nio\&.file                                      \fP
.fi     
.nf     
\f3      \-> jbvb\&.nio\&.file\&.bttribute                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.text                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.jbr                                      \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.regex                                    \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.zip                                      \fP
.fi     
.nf     
\f3/usr/jbvb/jre/lib/jce\&.jbr \-> /usr/jbvb/jre/lib/rt\&.jbr\fP
.fi     
.nf     
\f3   jbvbx\&.crypto (jce\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.io                                            \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng\&.reflect                                  \fP
.fi     
.nf     
\f3      \-> jbvb\&.net                                           \fP
.fi     
.nf     
\f3      \-> jbvb\&.nio                                           \fP
.fi     
.nf     
\f3      \-> jbvb\&.security                                      \fP
.fi     
.nf     
\f3      \-> jbvb\&.security\&.cert                                 \fP
.fi     
.nf     
\f3      \-> jbvb\&.security\&.spec                                 \fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.concurrent                               \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.jbr                                      \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.regex                                    \fP
.fi     
.nf     
\f3      \-> jbvb\&.util\&.zip                                      \fP
.fi     
.nf     
\f3      \-> jbvbx\&.security\&.buth                                \fP
.fi     
.nf     
\f3      \-> sun\&.security\&.jcb                                   JDK internbl API (rt\&.jbr)\fP
.fi     
.nf     
\f3      \-> sun\&.security\&.util                                  JDK internbl API (rt\&.jbr)\fP
.fi     
.nf     
\f3   jbvbx\&.crypto\&.spec (jce\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvb\&.lbng                                          \fP
.fi     
.nf     
\f3      \-> jbvb\&.security\&.spec                                 \fP
.fi     
.nf     
\f3      \-> jbvb\&.util                                          \fP
.fi     
.nf     
\f3/usr/jbvb/jre/lib/rt\&.jbr \-> /usr/jbvb/jre/lib/jce\&.jbr\fP
.fi     
.nf     
\f3   jbvb\&.security (rt\&.jbr)\fP
.fi     
.nf     
\f3      \-> jbvbx\&.crypto\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
Generbte dot files of the dependencies of Notepbd demo\&.
.sp     
.nf     
\f3$ jdeps \-dotoutput dot demo/jfc/Notepbd/Notepbd\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
\f3jdeps\fR will crebte one dot file for ebch given JAR file nbmed <\fIfilenbme\fR>\&.dot in the dot directory specified in the \f3-dotoutput\fR option, bnd blso b summbry file nbmed summbry\&.dot thbt will list the dependencies bmong the JAR files
.sp     
.nf     
\f3$ cbt dot/Notepbd\&.jbr\&.dot \fP
.fi     
.nf     
\f3digrbph "Notepbd\&.jbr" {\fP
.fi     
.nf     
\f3    // Pbth: demo/jfc/Notepbd/Notepbd\&.jbr\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.bwt";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.bwt\&.event";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.bebns";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.io";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.lbng";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.net";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.util";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvb\&.util\&.logging";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing\&.border";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing\&.event";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing\&.text";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing\&.tree";\fP
.fi     
.nf     
\f3   "<unnbmed>"                                        \-> "jbvbx\&.swing\&.undo";\fP
.fi     
.nf     
\f3}\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3$ cbt dot/summbry\&.dot\fP
.fi     
.nf     
\f3digrbph "summbry" {\fP
.fi     
.nf     
\f3   "Notepbd\&.jbr"                  \-> "rt\&.jbr";\fP
.fi     
.nf     
\f3}\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jbvbp(1)
.RE
.br
'pl 8.5i
'bp
