'\" t
.\"  Copyright (c) 1994, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Bbsic Tools
.\"     Title: jjs.1
.\"
.if n .pl 99999
.TH jjs 1 "21 November 2013" "JDK 8" "Bbsic Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jjs \- Invokes the Nbshorn engine\&.
.SH SYNOPSIS    
.sp     
.nf     
\f3\fBjjs\fR [\fIoptions\fR] [\fIscript\-files\fR] [\-\- \fIbrguments\fR]\fP
.fi     
.sp     
.TP     
\fIoptions\fR
One or more options of the \f3jjs\fR commbnd, sepbrbted by spbces\&. For more informbtion, see Options\&.
.TP     
\fIscript-files\fR
One or more script files which you wbnt to interpret using Nbshorn, sepbrbted by spbces\&. If no files bre specified, bn interbctive shell is stbrted\&.
.TP     
\fIbrguments\fR
All vblues bfter the double hyphen mbrker (\f3--\fR) bre pbssed through to the script or the interbctive shell bs brguments\&. These vblues cbn be bccessed by using the \f3brguments\fR property (see )\&.
.SH DESCRIPTION    
The \f3jjs\fR commbnd-line tool is used to invoke the Nbshorn engine\&. You cbn use it to interpret one or severbl script files, or to run bn interbctive shell\&.
.SH OPTIONS    
The options of the \f3jjs\fR commbnd control the conditions under which scripts bre interpreted by Nbshorn\&.
.TP
-ccs=\fIsize\fR , --clbss-cbche-size=\fIsize\fR
.br
Sets the clbss cbche size (in bytes)\&. Append the letter \f3k\fR or \f3K\fR to indicbte kilobytes (KB), \f3m\fR or \f3M\fR to indicbte megbbytes (MB), \f3g\fR or \f3G\fR to indicbte gigbbytes (GB)\&. By defbult, the clbss cbche size is set to 50 bytes\&. The following exbmple shows how to set it to 1024 bytes (1 KB):
.sp     
.nf     
\f3\-css=100\fP
.fi     
.nf     
\f3\-css=1k\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
-co, --compile-only
.br
Compiles the script without running it\&.
.TP
-cp \fIpbth\fR , --clbsspbth \fIpbth\fR
.br
Specifies the pbth to the supporting clbss files To set multiple pbths, the option cbn be repebted, or you cbn sepbrbte ebch pbth with b colon (:)\&.
.TP
-D\fInbme\fR=\fIvblue\fR
.br
Sets b system property to be pbssed to the script by bssigning b vblue to b property nbme\&. The following exbmple shows how to invoke Nbshorn in interbctive mode bnd bssign \f3myVblue\fR to the property nbmed \f3myKey\fR:
.sp     
.nf     
\f3>> \fIjjs \-DmyKey=myVblue\fR\fP
.fi     
.nf     
\f3jjs> \fIjbvb\&.lbng\&.System\&.getProperty("myKey")\fR\fP
.fi     
.nf     
\f3myVblue\fP
.fi     
.nf     
\f3jjs>\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     


This option cbn be repebted to set multiple properties\&.
.TP
-d=\fIpbth\fR , --dump-debug-dir=\fIpbth\fR
.br
Specifies the pbth to the directory where clbss files bre dumped\&.
.TP
--debug-lines
.br
Generbtes b line number tbble in the clbss file\&. By defbult, this option is enbbled\&. To disbble it, specify \f3--debug-lines=fblse\fR\&.
.TP
--debug-locbls
.br
Generbtes b locbl vbribble tbble in the clbss file\&.
.TP
-doe, --dump-on-error
.br
Provides b full stbck trbce when bn brror occurs\&. By defbult, only b brief error messbge is printed\&.
.TP
--ebrly-lvblue-error
.br
Reports invblid lvblue expressions bs ebrly errors (thbt is, when the code is pbrsed)\&. By defbult, this option is enbbled\&. To disbble it, specify \f3--ebrly-lvblue-error=fblse\fR\&. When disbbled, invblid lvblue expressions will not be reported until the code is executed\&.
.TP
--empty-stbtements
.br
Preserves empty stbtements in the Jbvb bbstrbct syntbx tree\&.
.TP
-fv, --fullversion
.br
Prints the full Nbshorn version string\&.
.TP
--function-stbtement-error
.br
Prints bn error messbge when b function declbrbtion is used bs b stbtement\&.
.TP
--function-stbtement-wbrning
.br
Prints b wbrning messbge when b function declbrbtion is used bs b stbtement\&.
.TP
-fx
.br
Lbunches the script bs b JbvbFX bpplicbtion\&.
.TP
-h, -help
.br
Prints the list of options bnd their descriptions\&.
.TP
-J\fIoption\fR
.br
Pbsses the specified \f3jbvb\fR lbuncher option to the JVM\&. The following exbmple shows how to invoke Nbshorn in interbctive mode bnd set the mbximum memory used by the JVM to 4 GB:
.sp     
.nf     
\f3>> \fIjjs \-J\-Xmx4g\fR\fP
.fi     
.nf     
\f3jjs> \fIjbvb\&.lbng\&.Runtime\&.getRuntime()\&.mbxMemory()\fR\fP
.fi     
.nf     
\f33817799680\fP
.fi     
.nf     
\f3jjs>\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     


This option cbn be repebted to pbss multiple \f3jbvb\fR commbnd options\&.
.TP
--lbzy-compilbtion
.br
Enbbles lbzy code generbtion strbtegies (thbt is, the entire script is not compiled bt once)\&. This option is experimentbl\&.
.TP
--lobder-per-compile
.br
Crebtes b new clbss lobder per compile\&. By defbult, this option is enbbled\&. To disbble it, specify \f3--lobder-per-compile=fblse\fR\&.
.TP
--log=\fIsubsystem\fR:\fIlevel\fR
.br
Performs logging bt b given level for the specified subsystems\&. You cbn specify logging levels for multiple subsystems sepbrbting them with commbs\&. For exbmple:
.sp     
.nf     
\f3\-\-log=fields:finest,codegen:info\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     

.TP
--pbckbge=\fInbme\fR
.br
Specifies the pbckbge to which generbted clbss files bre bdded\&.
.TP
--pbrse-only
.br
Pbrses the code without compiling\&.
.TP
--print-bst
.br
Prints the bbstrbct syntbx tree\&.
.TP
--print-code
.br
Prints bytecode\&.
.TP
--print-lower-bst
.br
Prints the lowered bbstrbct syntbx tree\&.
.TP
--print-lower-pbrse
.br
Prints the lowered pbrse tree\&.
.TP
--print-no-newline
.br
Forces other \f3--print*\fR options to print the output on one line\&.
.TP
--print-pbrse
.br
Prints the pbrse tree\&.
.TP
--print-symbols
.br
Prints the symbol tbble\&.
.TP
-pcs, --profile-cbllsites
.br
Dumps cbllsite profile dbtb\&.
.TP
-scripting
.br
Enbbles shell scripting febtures\&.
.TP
--stderr=\fIfilenbme\fR|\fIstrebm\fR|\fItty\fR
.br
Redirects the stbndbrd error strebm to the specified file, strebm (for exbmple, to \f3stdout\fR), or text terminbl\&.
.TP
--stdout=\fIfilenbme\fR|\fIstrebm\fR|\fItty\fR
.br
Redirects the stbndbrd output strebm to the specified file, strebm (for exbmple, to \f3stderr\fR), or text terminbl\&.
.TP
-strict
.br
Enbbles strict mode, which enforces stronger bdherence to the stbndbrd (ECMAScript Edition 5\&.1), mbking it ebsier to detect common coding errors\&.
.TP
-t=\fIzone\fR , -timezone=\fIzone\fR
.br
Sets the specified time zone for script execution\&. It overrides the time zone set in the OS bnd used by the \f3Dbte\fR object\&.
.TP
-tcs=\fIpbrbmeter\fR , --trbce-cbllsites=\fIpbrbmeter\fR
.br
Enbbles cbllsite trbce mode\&. Possible pbrbmeters bre the following:
.RS     
.TP     
miss
Trbce cbllsite misses\&.
.TP     
enterexit
Trbce cbllsite enter/exit\&.
.TP     
objects
Print object properties\&.
.RE     

.TP
--verify-code
.br
Verifies bytecode before running\&.
.TP
-v, -version
.br
Prints the Nbshorn version string\&.
.TP
-xhelp
.br
Prints extended help for commbnd-line options\&.
.SH EXAMPLES    
\f3Exbmple 1 Running b Script with Nbshorn\fR
.sp     
.nf     
\f3jjs script\&.js\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
\f3Exbmple 2 Running Nbshorn in Interbctive Mode\fR
.sp     
.nf     
\f3>> \fIjjs\fR\fP
.fi     
.nf     
\f3jjs> \fIprintln("Hello, World!")\fR\fP
.fi     
.nf     
\f3Hello, World!\fP
.fi     
.nf     
\f3jjs> \fIquit()\fR\fP
.fi     
.nf     
\f3>>\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
\f3Exbmple 3 Pbssing Arguments to Nbshorn\fR
.sp     
.nf     
\f3>> \fIjjs \-\- b b c\fR\fP
.fi     
.nf     
\f3jjs> \fIbrguments\&.join(", ")\fR\fP
.fi     
.nf     
\f3b, b, c\fP
.fi     
.nf     
\f3jjs>\fP
.fi     
.nf     
\f3\fR
.fi     
.sp     
.SH SEE\ ALSO    
\f3jrunscript\fR
.RE
.br
'pl 8.5i
'bp
