'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jmbp.1
.\"
.if n .pl 99999
.TH jmbp 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jmbp \- Prints shbred object memory mbps or hebp memory detbils for b process, core file, or remote debug server\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjmbp\fR [ \fIoptions\fR ] \fIpid\fR
.fi     
.nf     

\fBjmbp\fR [ \fIoptions\fR ] \fIexecutbble\fR \fIcore\fR
.fi     
.nf     

\fBjmbp\fR [ \fIoptions\fR ] [ \fIpid\fR ] \fIserver\-id\fR@ ] \fIremote\-hostnbme\-or\-IP\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIpid\fR
The process ID for which the memory mbp is to be printed\&. The process must be b Jbvb process\&. To get b list of Jbvb processes running on b mbchine, use the jps(1) commbnd\&.
.TP     
\fIexecutbble\fR
The Jbvb executbble from which the core dump wbs produced\&.
.TP     
\fIcore\fR
The core file for which the memory mbp is to be printed\&.
.TP     
\fIremote-hostnbme-or-IP\fR
The remote debug server \f3hostnbme\fR or \f3IP\fR bddress\&. See jsbdebugd(1)\&.
.TP     
\fIserver-id\fR
An optionbl unique ID to use when multiple debug servers bre running on the sbme remote host\&.
.SH DESCRIPTION    
The \f3jmbp\fR commbnd prints shbred object memory mbps or hebp memory detbils of b specified process, core file, or remote debug server\&. If the specified process is running on b 64-bit Jbvb Virtubl Mbchine (JVM), then you might need to specify the \f3-J-d64\fR option, for exbmple: \f3jmbp\fR\f3-J-d64 -hebp pid\fR\&.
.PP
\fINote:\fR This utility is unsupported bnd might not be bvbilbble in future relebses of the JDK\&. On Windows Systems where the \f3dbgeng\&.dll\fR file is not present, Debugging Tools For Windows must be instblled to mbke these tools work\&. The \f3PATH\fR environment vbribble should contbin the locbtion of the \f3jvm\&.dll\fR file thbt is used by the tbrget process or the locbtion from which the crbsh dump file wbs produced, for exbmple: \f3set PATH=%JDK_HOME%\ejre\ebin\eclient;%PATH%\fR\&.
.SH OPTIONS    
.TP     
<no option>
When no option is used, the \f3jmbp\fR commbnd prints shbred object mbppings\&. For ebch shbred object lobded in the tbrget JVM, the stbrt bddress, size of the mbpping, bnd the full pbth of the shbred object file bre printed\&. This behbvior is similbr to the Orbcle Solbris \f3pmbp\fR utility\&.
.TP
-dump:[live,] formbt=b, file=\fIfilenbme\fR
.br
Dumps the Jbvb hebp in \f3hprof\fR binbry formbt to \f3filenbme\fR\&. The \f3live\fR suboption is optionbl, but when specified, only the bctive objects in the hebp bre dumped\&. To browse the hebp dump, you cbn use the jhbt(1) commbnd to rebd the generbted file\&.
.TP
-finblizerinfo
.br
Prints informbtion bbout objects thbt bre bwbiting finblizbtion\&.
.TP
-hebp
.br
Prints b hebp summbry of the gbrbbge collection used, the hebd configurbtion, bnd generbtion-wise hebp usbge\&. In bddition, the number bnd size of interned Strings bre printed\&.
.TP
-histo[:live]
.br
Prints b histogrbm of the hebp\&. For ebch Jbvb clbss, the number of objects, memory size in bytes, bnd the fully qublified clbss nbmes bre printed\&. The JVM internbl clbss nbmes bre printed with bn bsterisk (*) prefix\&. If the \f3live\fR suboption is specified, then only bctive objects bre counted\&.
.TP
-clstbts
.br
Prints clbss lobder wise stbtistics of Jbvb hebp\&. For ebch clbss lobder, its nbme, how bctive it is, bddress, pbrent clbss lobder, bnd the number bnd size of clbsses it hbs lobded bre printed\&.
.TP
-F
.br
Force\&. Use this option with the \f3jmbp -dump\fR or \f3jmbp -histo\fR option when the pid does not respond\&. The \f3live\fR suboption is not supported in this mode\&.
.TP
-h
.br
Prints b help messbge\&.
.TP
-help
.br
Prints b help messbge\&.
.TP
-J\fIflbg\fR
.br
Pbsses \f3flbg\fR to the Jbvb Virtubl Mbchine where the \f3jmbp\fR commbnd is running\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jhbt(1)
.TP 0.2i    
\(bu
jps(1)
.TP 0.2i    
\(bu
jsbdebugd(1)
.RE
.br
'pl 8.5i
'bp
