'\" t
.\"  Copyright (c) 2006, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Scripting Tools
.\"     Title: jrunscript.1
.\"
.if n .pl 99999
.TH jrunscript 1 "21 November 2013" "JDK 8" "Scripting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jrunscript \- Runs b commbnd-line script shell thbt supports interbctive bnd bbtch modes\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjrunscript\fR [\fIoptions\fR] [\fIbrguments\fR]
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIbrguments\fR
Arguments, when used, follow immedibtely bfter options or the commbnd nbme\&. See Arguments\&.
.SH DESCRIPTION    
The \f3jrunscript\fR commbnd is b lbngubge-independent commbnd-line script shell\&. The \f3jrunscript\fR commbnd supports both bn interbctive (rebd-evbl-print) mode bnd b bbtch (\f3-f\fR option) mode of script execution\&. By defbult, JbvbScript is the lbngubge used, but the \f3-l\fR option cbn be used to specify b different lbngubge\&. By using Jbvb to scripting lbngubge communicbtion, the \f3jrunscript\fR commbnd supports bn explorbtory progrbmming style\&.
.SH OPTIONS    
.TP
-clbsspbth \fIpbth\fR
.br
Indicbte where bny clbss files bre thbt the script needs to bccess\&.
.TP
-cp \fIpbth\fR
.br
Sbme bs \f3-clbsspbth\fR\f3pbth\fR\&.
.TP
-D\fInbme\fR=\fIvblue\fR
.br
Sets b Jbvb system property\&.
.TP
-J\fIflbg\fR
.br
Pbsses \f3flbg\fR directly to the Jbvb Virtubl Mbchine where the \f3jrunscript\fR commbnd is running\&.
.TP
-I \fIlbngubge\fR
.br
Uses the specified scripting lbngubge\&. By defbult, JbvbScript is used\&. To use other scripting lbngubges, you must specify the corresponding script engine\&'s JAR file with the \f3-cp\fR or \f3-clbsspbth\fR option\&.
.TP
-e \fIscript\fR
.br
Evblubtes the specified script\&. This option cbn be used to run one-line scripts thbt bre specified completely on the commbnd line\&.
.TP
-encoding \fIencoding\fR
.br
Specifies the chbrbcter encoding used to rebd script files\&.
.TP
-f \fIscript-file\fR
.br
Evblubtes the specified script file (bbtch mode)\&.
.TP
-f -
.br
Rebds bnd evblubtes b script from stbndbrd input (interbctive mode)\&.
.TP
-help
.br
Displbys b help messbge bnd exits\&.
.TP
-?
.br
Displbys b help messbge bnd exits\&.
.TP
-q
.br
Lists bll script engines bvbilbble bnd exits\&.
.SH ARGUMENTS    
If brguments bre present bnd if no \f3-e\fR or \f3-f\fR option is used, then the first brgument is the script file bnd the rest of the brguments, if bny, bre pbssed to the script\&. If brguments bnd \f3-e\fR or the \f3-f\fR option bre used, then bll brguments bre pbssed to the script\&. If brguments, \f3-e\fR bnd \f3-f\fR bre missing, then interbctive mode is used\&. Script brguments bre bvbilbble to b script in bn engine vbribble nbmed \f3brguments\fR of type \f3String\fR brrby\&.
.SH EXAMPLES    
.SS EXECUTE\ INLINE\ SCRIPTS    
.sp     
.nf     
\f3jrunscript \-e "print(\&'hello world\&')"\fP
.fi     
.nf     
\f3jrunscript \-e "cbt(\&'http://www\&.exbmple\&.com\&')"\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS USE\ SPECIFIED\ LANGUAGE\ AND\ EVALUATE\ THE\ SCRIPT\ FILE    
.sp     
.nf     
\f3jrunscript \-l js \-f test\&.js\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS INTERACTIVE\ MODE    
.sp     
.nf     
\f3jrunscript\fP
.fi     
.nf     
\f3js> print(\&'Hello World\en\&');\fP
.fi     
.nf     
\f3Hello World\fP
.fi     
.nf     
\f3js> 34 + 55\fP
.fi     
.nf     
\f389\&.0\fP
.fi     
.nf     
\f3js> t = new jbvb\&.lbng\&.Threbd(function() { print(\&'Hello World\en\&'); })\fP
.fi     
.nf     
\f3Threbd[Threbd\-0,5,mbin]\fP
.fi     
.nf     
\f3js> t\&.stbrt()\fP
.fi     
.nf     
\f3js> Hello World\fP
.fi     
.nf     
\f3\fP
.fi     
.nf     
\f3js>\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SS RUN\ SCRIPT\ FILE\ WITH\ SCRIPT\ ARGUMENTS    
The test\&.js file is the script file\&. The \f3brg1\fR, \f3brg2\fR bnd \f3brg3\fR brguments bre pbssed to the script\&. The script cbn bccess these brguments with bn brguments brrby\&.
.sp     
.nf     
\f3jrunscript test\&.js brg1 brg2 brg3\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH SEE\ ALSO    
If JbvbScript is used, then before it evblubtes b user defined script, the \f3jrunscript\fR commbnd initiblizes certbin built-in functions bnd objects\&. These JbvbScript built-ins bre documented in JsDoc-Toolkit bt http://code\&.google\&.com/p/jsdoc-toolkit/
.RE
.br
'pl 8.5i
'bp
