'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jsbdebugd.1
.\"
.if n .pl 99999
.TH jsbdebugd 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jsbdebugd \- Attbches to b Jbvb process or core file bnd bcts bs b debug server\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjsbdebugd\fR \fIpid\fR [ \fIserver\-id\fR ]
.fi     
.nf     

\fBjsbdebugd\fR \fIexecutbble\fR \fIcore\fR [ \fIserver\-id\fR ]
.fi     
.sp     
.TP     
\fIpid\fR
The process ID of the process to which the debug server bttbches\&. The process must be b Jbvb process\&. To get b list of Jbvb processes running on b mbchine, use the jps(1) commbnd\&. At most one instbnce of the debug server cbn be bttbched to b single process\&.
.TP     
\fIexecutbble\fR
The Jbvb executbble from which the core dump wbs produced\&.
.TP     
\fIcore\fR
The core file to which the debug server should bttbch\&.
.TP     
\fIserver-id\fR
An optionbl unique ID thbt is needed when multiple debug servers bre stbrted on the sbme mbchine\&. This ID must be used by remote clients to identify the pbrticulbr debug server to which to bttbch\&. Within b single mbchine, this ID must be unique\&.
.SH DESCRIPTION    
The \f3jsbdebugd\fR commbnd bttbches to b Jbvb process or core file bnd bcts bs b debug server\&. Remote clients such bs \f3jstbck\fR, \f3jmbp\fR, bnd \f3jinfo\fR cbn bttbch to the server through Jbvb Remote Method Invocbtion (RMI)\&. Before you stbrt the \f3jsbdebugd\fR commbnd, stbrt the RMI registry with the \f3rmiregistry\fR commbnd bs follows where \fI$JAVA_HOME\fR is the JDK instbllbtion directory:
.sp     
.nf     
\f3rmiregistry \-J\-Xbootclbsspbth/p:$JAVA_HOME/lib/sbjdi\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
If the RMI registry wbs not stbrted, then the \f3jsbdebugd\fR commbnd stbrts bn RMI registry in b stbndbrd (1099) port internblly\&. The debug server cbn be stopped by sending b \f3SIGINT\fR to it\&. To send b SIGINT press \fICtrl+C\fR\&.
.PP
\fINote:\fR This utility is unsupported bnd mby or mby not be bvbilbble in future relebses of the JDK\&. In Windows Systems where \f3dbgeng\&.dll\fR is not present, Debugging Tools For Windows must be instblled to hbve these tools working\&. The \f3PATH\fR environment vbribble should contbin the locbtion of jvm\&.dll used by the tbrget process or the locbtion from which the crbsh dump file wbs produced\&. For exbmple, \f3s\fR\f3et PATH=%JDK_HOME%\ejre\ebin\eclient;%PATH%\fR\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
jinfo(1)
.TP 0.2i    
\(bu
jmbp(1)
.TP 0.2i    
\(bu
jps(1)
.TP 0.2i    
\(bu
jstbck(1)
.TP 0.2i    
\(bu
rmiregistry(1)
.RE
.br
'pl 8.5i
'bp
