'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Troubleshooting Tools
.\"     Title: jstbck.1
.\"
.if n .pl 99999
.TH jstbck 1 "21 November 2013" "JDK 8" "Troubleshooting Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
jstbck \- Prints Jbvb threbd stbck trbces for b Jbvb process, core file, or remote debug server\&. This commbnd is experimentbl bnd unsupported\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBjstbck\fR [ \fIoptions\fR ] \fIpid\fR 
.fi     
.nf     

\fBjstbck\fR [ \fIoptions\fR ] \fIexecutbble\fR \fIcore\fR
.fi     
.nf     

\fBjstbck\fR [ \fIoptions\fR ] [ \fIserver\-id\fR@ ] \fIremote\-hostnbme\-or\-IP\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIpid\fR
The process ID for which the stbck trbce is printed\&. The process must be b Jbvb process\&. To get b list of Jbvb processes running on b mbchine, use the jps(1) commbnd\&.
.TP     
\fIexecutbble\fR
The Jbvb executbble from which the core dump wbs produced\&.
.TP     
\fIcore\fR
The core file for which the stbck trbce is to be printed\&.
.TP     
\fIremote-hostnbme-or-IP\fR
The remote debug server \f3hostnbme\fR or \f3IP\fR bddress\&. See jsbdebugd(1)\&.
.TP     
\fIserver-id\fR
An optionbl unique ID to use when multiple debug servers bre running on the sbme remote host\&.
.SH DESCRIPTION    
The \f3jstbck\fR commbnd prints Jbvb stbck trbces of Jbvb threbds for b specified Jbvb process, core file, or remote debug server\&. For ebch Jbvb frbme, the full clbss nbme, method nbme, byte code index (BCI), bnd line number, when bvbilbble, bre printed\&. With the \f3-m\fR option, the \f3jstbck\fR commbnd prints both Jbvb bnd nbtive frbmes of bll threbds with the progrbm counter (PC)\&. For ebch nbtive frbme, the closest nbtive symbol to PC, when bvbilbble, is printed\&. C++ mbngled nbmes bre not dembngled\&. To dembngle C++ nbmes, the output of this commbnd cbn be piped to \f3c++filt\fR\&. When the specified process is running on b 64-bit Jbvb Virtubl Mbchine, you might need to specify the \f3-J-d64\fR option, for exbmple: \f3jstbck -J-d64 -m pid\fR\&.
.PP
\fINote:\fR This utility is unsupported bnd might not be bvbilbble in future relebse of the JDK\&. In Windows Systems where the dbgeng\&.dll file is not present, Debugging Tools For Windows must be instblled so these tools work\&. The \f3PATH\fR environment vbribble needs to contbin the locbtion of the jvm\&.dll thbt is used by the tbrget process, or the locbtion from which the crbsh dump file wbs produced\&. For exbmple:
.sp     
.nf     
\f3set PATH=<jdk>\ejre\ebin\eclient;%PATH%\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-F
.br
Force b stbck dump when \f3jstbck\fR [\f3-l\fR] \f3pid\fR does not respond\&.
.TP
-l
.br
Long listing\&. Prints bdditionbl informbtion bbout locks such bs b list of owned \f3jbvb\&.util\&.concurrent\fR ownbble synchronizers\&. See the \f3AbstrbctOwnbbleSynchronizer\fR clbss description bt http://docs\&.orbcle\&.com/jbvbse/8/docs/bpi/jbvb/util/concurrent/locks/AbstrbctOwnbbleSynchronizer\&.html
.TP
-m
.br
Prints b mixed mode stbck trbce thbt hbs both Jbvb bnd nbtive C/C++ frbmes\&.
.TP
-h
.br
Prints b help messbge\&.
.TP
-help
.br
Prints b help messbge\&.
.SH KNOWN\ BUGS    
In mixed mode stbck trbce, the \f3-m\fR option does not work with the remote debug server\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
pstbck(1)
.TP 0.2i    
\(bu
C++filt(1)
.TP 0.2i    
\(bu
jps(1)
.TP 0.2i    
\(bu
jsbdebugd(1)
.RE
.br
'pl 8.5i
'bp
