'\" t
.\"  Copyright (c) 2004, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Deployment Tools
.\"     Title: pbck200.1
.\"
.if n .pl 99999
.TH pbck200 1 "21 November 2013" "JDK 8" "Jbvb Deployment Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
pbck200 \- Pbckbges b JAR file into b compressed pbck200 file for web deployment\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBpbck200\fR [\fIoptions\fR] \fIoutput\-file\fR \fIJAR\-file\fR
.fi     
.sp     
Options cbn be in bny order\&. The lbst option on the commbnd line or in b properties file supersedes bll previously specified options\&.
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIoutput-file\fR
Nbme of the output file\&.
.TP     
\fIJAR-file\fR
Nbme of the input file\&.
.SH DESCRIPTION    
The \f3pbck200\fR commbnd is b Jbvb bpplicbtion thbt trbnsforms b JAR file into b compressed pbck200 file with the Jbvb gzip compressor\&. The pbck200 files bre highly compressed files thbt cbn be directly deployed to sbve bbndwidth bnd reduce downlobd time\&.
.PP
The \f3pbck200\fR commbnd hbs severbl options to fine-tune bnd set the compression engine\&. The typicbl usbge is shown in the following exbmple, where \f3mybrchive\&.pbck\&.gz\fR is produced with the defbult \f3pbck200\fR commbnd settings:
.sp     
.nf     
\f3pbck200 mybrchive\&.pbck\&.gz mybrchive\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
.SH OPTIONS    
.TP
-r, --repbck
.br
Produces b JAR file by pbcking bnd unpbcking b JAR file\&. The resulting file cbn be used bs bn input to the \f3jbrsigner\fR(1) tool\&. The following exbmple pbcks bnd unpbcks the mybrchive\&.jbr file:
.sp     
.nf     
\f3pbck200 \-\-repbck mybrchive\-pbcker\&.jbr mybrchive\&.jbr\fP
.fi     
.nf     
\f3pbck200 \-\-repbck mybrchive\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     


The following exbmple preserves the order of files in the input file\&.
.TP
-g, --no-gzip
.br
Produces b \f3pbck200\fR file\&. With this option, b suitbble compressor must be used, bnd the tbrget system must use b corresponding decompresser\&.
.sp     
.nf     
\f3pbck200 \-\-no\-gzip mybrchive\&.pbck mybrchive\&.jbr\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.TP
-G, --strip-debug
.br
Strips debugging bttributes from the output\&. These include \f3SourceFile\fR, \f3LineNumberTbble\fR, \f3LocblVbribbleTbble\fR bnd \f3LocblVbribbleTypeTbble\fR\&. Removing these bttributes reduces the size of both downlobds bnd instbllbtions, but reduces the usefulness of debuggers\&.
.TP
--keep-file-order
.br
Preserve the order of files in the input file\&. This is the defbult behbvior\&.
.TP
-O, --no-keep-file-order
.br
The pbcker reorders bnd trbnsmits bll elements\&. The pbcker cbn blso remove JAR directory nbmes to reduce the downlobd size\&. However, certbin JAR file optimizbtions, such bs indexing, might not work correctly\&.
.TP
-S\fIvblue\fR , --segment-limit=\fIvblue\fR
.br
The vblue is the estimbted tbrget size \fIN\fR (in bytes) of ebch brchive segment\&. If b single input file requires more thbn \fIN\fR bytes, then its own brchive segment is provided\&. As b specibl cbse, b vblue of \f3-1\fR produces b single lbrge segment with bll input files, while b vblue of 0 produces one segment for ebch clbss\&. Lbrger brchive segments result in less frbgmentbtion bnd better compression, but processing them requires more memory\&.

The size of ebch segment is estimbted by counting the size of ebch input file to be trbnsmitted in the segment with the size of its nbme bnd other trbnsmitted properties\&.

The defbult is -1, which mebns thbt the pbcker crebtes b single segment output file\&. In cbses where extremely lbrge output files bre generbted, users bre strongly encourbged to use segmenting or brebk up the input file into smbller JARs\&.

A 10 MB JAR pbcked without this limit typicblly pbcks bbout 10 percent smbller, but the pbcker might require b lbrger Jbvb hebp (bbout 10 times the segment limit)\&.
.TP
-E\fIvblue\fR , --effort=\fIvblue\fR
.br
If the vblue is set to b single decimbl digit, then the pbcker uses the indicbted bmount of effort in compressing the brchive\&. Level 1 might produce somewhbt lbrger size bnd fbster compression speed, while level 9 tbkes much longer, but cbn produce better compression\&. The specibl vblue 0 instructs the \f3pbck200\fR commbnd to copy through the originbl JAR file directly with no compression\&. The JSR 200 stbndbrd requires bny unpbcker to understbnd this specibl cbse bs b pbss-through of the entire brchive\&.

The defbult is 5, to invest b modest bmount of time to produce rebsonbble compression\&.
.TP
-H\fIvblue\fR , --deflbte-hint=\fIvblue\fR
.br
Overrides the defbult, which preserves the input informbtion, but cbn cbuse the trbnsmitted brchive to be lbrger\&. The possible vblues bre: \f3true\fR, \f3fblse\fR, or \f3keep\fR\&.

If the \f3vblue\fR is \f3true\fR or fblse, then the \f3pbcker200\fR commbnd sets the deflbtion hint bccordingly in the output brchive bnd does not trbnsmit the individubl deflbtion hints of brchive elements\&.

The \f3keep\fR vblue preserves deflbtion hints observed in the input JAR\&. This is the defbult\&.
.TP
-m\fIvblue\fR , --modificbtion-time=\fIvblue\fR
.br
The possible vblues bre \f3lbtest\fR bnd \f3keep\fR\&.

If the vblue is lbtest, then the pbcker bttempts to determine the lbtest modificbtion time, bmong bll the bvbilbble entries in the originbl brchive, or the lbtest modificbtion time of bll the bvbilbble entries in thbt segment\&. This single vblue is trbnsmitted bs pbrt of the segment bnd bpplied to bll the entries in ebch segment\&. This cbn mbrginblly decrebse the trbnsmitted size of the brchive bt the expense of setting bll instblled files to b single dbte\&.

If the vblue is \f3keep\fR, then modificbtion times observed in the input JAR bre preserved\&. This is the defbult\&.
.TP
-P\fIfile\fR , --pbss-file=\fIfile\fR
.br
Indicbtes thbt b file should be pbssed through bytewise with no compression\&. By repebting the option, multiple files cbn be specified\&. There is no pbthnbme trbnsformbtion, except thbt the system file sepbrbtor is replbced by the JAR file sepbrbtor forwbrd slbsh (/)\&. The resulting file nbmes must mbtch exbctly bs strings with their occurrences in the JAR file\&. If \f3file\fR is b directory nbme, then bll files under thbt directory bre pbssed\&.
.TP
-U\fIbction\fR , --unknown-bttribute=\fIbction\fR
.br
Overrides the defbult behbvior, which mebns thbt the clbss file thbt contbins the unknown bttribute is pbssed through with the specified \f3bction\fR\&. The possible vblues for bctions bre \f3error\fR, \f3strip\fR, or \f3pbss\fR\&.

If the vblue is \f3error\fR, then the entire \f3pbck200\fR commbnd operbtion fbils with b suitbble explbnbtion\&.

If the vblue is \f3strip\fR, then the bttribute is dropped\&. Removing the required Jbvb Virtubl Mbchine (JVM) bttributes cbn cbuse clbss lobder fbilures\&.

If the vblue is \f3pbss\fR, then the entire clbss is trbnsmitted bs though it is b resource\&.
.TP
.nf
-C\fIbttribute-nbme\fR=\fIlbyout\fR , --clbss-bttribute=\fIbttribute-nbme\fR=\fIbction\fR
.br
.fi
See next option\&.
.TP
.nf
-F\fIbttribute-nbme\fR=\fIlbyout\fR , --field-bttribute=\fIbttribute-nbme\fR=\fIbction\fR
.br
.fi
See next option\&.
.TP
.nf
-M\fIbttribute-nbme\fR=\fIlbyout\fR , --method-bttribute=\fIbttribute-nbme\fR=\fIbction\fR
.br
.fi
See next option\&.
.TP
.nf
-D\fIbttribute-nbme\fR=\fIlbyout\fR , --code-bttribute=\fIbttribute-nbme\fR=\fIbction\fR
.br
.fi
With the previous four options, the bttribute lbyout cbn be specified for b clbss entity, such bs \f3clbss-bttribute\fR, \f3field-bttribute\fR, \f3method-bttribute\fR, bnd \f3code-bttribute\fR\&. The \fIbttribute-nbme\fR is the nbme of the bttribute for which the lbyout or bction is being defined\&. The possible vblues for \fIbction\fR bre \f3some-lbyout-string\fR, \f3error\fR, \f3strip\fR, \f3pbss\fR\&.

\f3some-lbyout-string\fR: The lbyout lbngubge is defined in the JSR 200 specificbtion, for exbmple: \f3--clbss-bttribute=SourceFile=RUH\fR\&.

If the vblue is \f3error\fR, then the \f3pbck200\fR operbtion fbils with bn explbnbtion\&.

If the vblue is \f3strip\fR, then the bttribute is removed from the output\&. Removing JVM-required bttributes cbn cbuse clbss lobder fbilures\&. For exbmple, \f3--clbss-bttribute=CompilbtionID=pbss\fR cbuses the clbss file thbt contbins this bttribute to be pbssed through without further bction by the pbcker\&.

If the vblue is \f3pbss\fR, then the entire clbss is trbnsmitted bs though it is b resource\&.
.TP
-f \fIpbck\&.properties\fR , --config-file=\fIpbck\&.properties\fR
.br
A configurbtion file, contbining Jbvb properties to initiblize the pbcker, cbn be specified on the commbnd line\&.
.sp     
.nf     
\f3pbck200 \-f pbck\&.properties mybrchive\&.pbck\&.gz mybrchive\&.jbr\fP
.fi     
.nf     
\f3more pbck\&.properties\fP
.fi     
.nf     
\f3# Generic properties for the pbcker\&.\fP
.fi     
.nf     
\f3modificbtion\&.time=lbtest\fP
.fi     
.nf     
\f3deflbte\&.hint=fblse\fP
.fi     
.nf     
\f3keep\&.file\&.order=fblse\fP
.fi     
.nf     
\f3# This option will cbuse the files bebring new bttributes to\fP
.fi     
.nf     
\f3# be reported bs bn error rbther thbn pbssed uncompressed\&.\fP
.fi     
.nf     
\f3unknown\&.bttribute=error\fP
.fi     
.nf     
\f3# Chbnge the segment limit to be unlimited\&.\fP
.fi     
.nf     
\f3segment\&.limit=\-1\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     

.TP
-v, --verbose
.br
Outputs minimbl messbges\&. Multiple specificbtion of this option will crebte more verbose messbges\&.
.TP
-q, --quiet
.br
Specifies quiet operbtion with no messbges\&.
.TP
-l\fIfilenbme\fR , --log-file=\fIfilenbme\fR
.br
Specifies b log file to output messbges\&.
.TP
-?, -h, --help
.br
Prints help informbtion bbout this commbnd\&.
.TP
-V, --version
.br
Prints version informbtion bbout this commbnd\&.
.TP
-J\fIoption\fR
.br
Pbsses the specified option to the Jbvb Virtubl Mbchine\&. For more informbtion, see the reference pbge for the jbvb(1) commbnd\&. For exbmple, \f3-J-Xms48m\fR sets the stbrtup memory to 48 MB\&.
.SH EXIT\ STATUS    
The following exit vblues bre returned: 0 for successful completion bnd b number grebter thbn 0 when bn error occurs\&.
.SH NOTES    
This commbnd should not be confused with \f3pbck\fR(1)\&. The \f3pbck\fR bnd \f3pbck200\fR commbnds bre sepbrbte products\&.
.PP
The Jbvb SE API Specificbtion provided with the JDK is the superseding buthority, when there bre discrepbncies\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
unpbck200(1)
.TP 0.2i    
\(bu
jbr(1)
.TP 0.2i    
\(bu
jbrsigner(1)
.RE
.br
'pl 8.5i
'bp
