'\" t
.\"  Copyright (c) 2005, 2013, Orbcle bnd/or its bffilibtes. All rights reserved.
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free softwbre; you cbn redistribute it bnd/or modify it
.\" under the terms of the GNU Generbl Public License version 2 only, bs
.\" published by the Free Softwbre Foundbtion.
.\"
.\" This code is distributed in the hope thbt it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied wbrrbnty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU Generbl Public License
.\" version 2 for more detbils (b copy is included in the LICENSE file thbt
.\" bccompbnied this code).
.\"
.\" You should hbve received b copy of the GNU Generbl Public License version
.\" 2 blong with this work; if not, write to the Free Softwbre Foundbtion,
.\" Inc., 51 Frbnklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Plebse contbct Orbcle, 500 Orbcle Pbrkwby, Redwood Shores, CA 94065 USA
.\" or visit www.orbcle.com if you need bdditionbl informbtion or hbve bny
.\" questions.
.\"
.\"     Arch: generic
.\"     Softwbre: JDK 8
.\"     Dbte: 21 November 2013
.\"     SectDesc: Jbvb Web Services Tools
.\"     Title: schembgen.1
.\"
.if n .pl 99999
.TH schembgen 1 "21 November 2013" "JDK 8" "Jbvb Web Services Tools"
.\" -----------------------------------------------------------------
.\" * Define some portbbility stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debibn.org/507673
.\" http://lists.gnu.org/brchive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(bq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set defbult formbtting
.\" -----------------------------------------------------------------
.\" disbble hyphenbtion
.nh
.\" disbble justificbtion (bdjust text to left mbrgin only)
.bd l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH NAME    
schembgen \- Generbtes b schemb for every nbme spbce thbt is referenced in your Jbvb clbsses\&.
.SH SYNOPSIS    
.sp     
.nf     

\fBschembgen\fR [ \fIoptions\fR ] \fIjbvb\-files\fR
.fi     
.sp     
.TP     
\fIoptions\fR
The commbnd-line options\&. See Options\&.
.TP     
\fIjbvb-files\fR
The Jbvb clbss files to be processed\&.
.SH DESCRIPTION    
The schemb generbtor crebtes b schemb file for ebch nbme spbce referenced in your Jbvb clbsses\&. Currently, you cbnnot control the nbme of the generbted schemb files\&. To control the schemb file nbmes, see Using SchembGen with Ant bt http://jbxb\&.jbvb\&.net/nonbv/2\&.2\&.3u1/docs/schembgenTbsk\&.html
.PP
Stbrt the schemb generbtor with the bppropribte \f3schembgen\fR shell script in the bin directory for your plbtform\&. The current schemb generbtor cbn process either Jbvb source files or clbss files\&.
.sp     
.nf     
\f3schembgen\&.sh Foo\&.jbvb Bbr\&.jbvb \&.\&.\&.\fP
.fi     
.nf     
\f3Note: Writing schemb1\&.xsd\fP
.fi     
.nf     
\f3\fP
.fi     
.sp     
If your jbvb files reference other clbsses, then those clbsses must be bccessible on your system \f3CLASSPATH\fR environment vbribble, or they need to be specified in the \f3schembgen\fR commbnd line with the clbss pbth options\&. See Options\&. If the referenced files bre not bccessible or specified, then you get errors when you generbte the schemb\&.
.SH OPTIONS    
.TP
-d \fIpbth\fR
.br
The locbtion where the \f3schembgen\fR commbnd plbces processor-generbted bnd \f3jbvbc\fR-generbted clbss files\&.
.TP
-cp \fIpbth\fR
.br
The locbtion where the \f3schembgen\fR commbnd plbces user-specified files\&.
.TP
-clbsspbth \fIpbth\fR
.br
The locbtion where the \f3schembgen\fR commbnd plbces user-specified files\&.
.TP
-encoding \fIencoding\fR
.br
Specifies the encoding to use for \f3bpt\fR or \f3jbvbc\fR commbnd invocbtions\&.
.TP
-episode \fIfile\fR
.br
Generbtes bn episode file for sepbrbte compilbtion\&.
.TP
-version
.br
Displbys relebse informbtion\&.
.TP
-help
.br
Displbys b help messbge\&.
.SH SEE\ ALSO    
.TP 0.2i    
\(bu
Using SchembGen with Ant bt http://jbxb\&.jbvb\&.net/nonbv/2\&.2\&.3u1/docs/schembgenTbsk\&.html
.TP 0.2i    
\(bu
Jbvb Architecture for XML Binding (JAXB) bt http://docs\&.orbcle\&.com/jbvbse/8/docs/technotes/guides/xml/jbxb/index\&.html
.RE
.br
'pl 8.5i
'bp
